-- ============================================================================
-- The M5 cleanup batch — pgTAP 112 (task L.D3.14; migration 164; PROGRESS
-- D428 — F467, F468(b), F489 discharged; D420 / D413 / D425; spec §10 /
-- standing rule (g), §11.2, §13.1, §11.4 / §23.4 v2.16.73).
--
-- Numbering: reserved and measured (164 / 112). OWN FIXTURE: users 9112…,
-- leagues b112…, teams c112…, action ids a112…, players r-*, NFL teams P*.
-- Every instant is passed explicitly (the TimeProvider rule); internals are
-- called as postgres with the actor JWT claims set.
--
--   §A  form: the three replaced bodies (PLAIN, search_path empty, closed to
--       anon / authenticated, one overload each), D137 in the database (each
--       live body with 164 reversed = its newest definer FILE TEXT — the
--       stored literals pgTAP 105 A6 pins), 164 as written, the call counts,
--       and the neighbours untouched.
--   §B  F468(b): the kept-start judgment counts a lineup record only when it
--       is a REAL, passed kickoff of the week and his team game is not
--       postponed — side by side with the pre-164 body (pg_temp.kept_pre164,
--       the live body with 164 reversed): a stale postponed / flexed record
--       no longer keeps him; the fall-through arms still do.
--   §C  F467: the roster override receipt (bypassed[], drop / add lock
--       documents) names the PLAYED lock — side by side with the pre-164
--       body — and nothing but the receipt changes (the rosters, lineups and
--       pool it writes are identical under both bodies).
--   §D  F467: the lineup override receipt (locked_players_moved, the
--       per_player_kickoff_lock and ir_lock_timing bypasses) names the
--       PLAYED lock — and the lineup row it writes is identical under both
--       bodies (receipt only).
--   §R  F489: the re-score door is retired — nobody but its owner may run
--       it, the service role is refused with the real 42501, and the
--       function, its ledger, its comment and the lock exit it serves stay.
--
-- BREAK PROBES (the PR body; measured), each injected right after
-- pg_temp.un164 inside this transaction (the ROLLBACK ends it):
--   (1) lineup_kept_starter_internal back to 154 (un164 on the live body) ⇒
--       B2 B3 B4 B5 B6 red;
--   (2) commish_roster_override_internal back to 153 ⇒ A4 A5 C1 C2 C3 red;
--   (3) commish_edit_lineup_internal back to 154 ⇒ A4 A5 D1 D2 red;
--   (4) GRANT EXECUTE on the door to service_role ⇒ R1 R4 red.
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(30);

-- L.D3.14 (migration 164): pg_temp.un164 reverses 164 substitutions in the
-- three bodies it replaced (an identity on every other body). Generated by
-- derive_164.py from the same pairs the migration was derived with.
create function pg_temp.un164(p_src text) returns text language sql as $un164$
  select replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(p_src,
    E'  ELSIF public.lineup_record_kicked_off_internal(p_season, p_week, p_player_id, v_rec_at, p_at) THEN   -- 164 / F468(b): a REAL, passed kickoff of the week and his team\'s game not postponed (157\'s guard — the locks\' own judgment)\n',
    E'  ELSIF v_rec_at IS NOT NULL AND v_rec_at <= p_at THEN\n'),
    E'      v_lose_lock := public.pool_game_lock_player_internal(p_league_id, v_league.season, v_current, v_lose_player, p_at);   -- 164 / F467: the receipt judges the lock per player (played this week), as 157\'s writers do\n',
    E'      v_lose_lock := public.pool_game_lock_any_internal(v_league.season, v_current, v_lose_p.team, p_at);\n'),
    E'      v_gain_lock := public.pool_game_lock_player_internal(p_league_id, v_league.season, v_current, v_gain_player, p_at);   -- 164 / F467: the receipt judges the lock per player (played this week), as 157\'s writers do\n',
    E'      v_gain_lock := public.pool_game_lock_any_internal(v_league.season, v_current, v_gain_p.team, p_at);\n'),
    E'  v_lock_kick   JSONB := \'{}\'::jsonb;   -- 164 / F467: the RECEIPT\'s datum for p_week, per PLAYER (157\'s lineup_player_kickoff_internal)\n  v_lock_kick_cur JSONB := \'{}\'::jsonb; -- 164 / F467: the same for the CURRENT week (the IR timing receipt)\n',
    E''),
    E'    -- 164 / F467: what the RECEIPT says is judged per PLAYER — his current\n    -- NFL team\'s kickoff, or the kickoff he PLAYED in this week (157) — so\n    -- a player the NFL released or traded after he played is named as\n    -- moved past the lock. Receipt only: v_kick (the stored record,\n    -- locked_at, the bye flags) is unchanged, and nothing here refuses.\n    SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, p_week, v_e ->> \'player_id\', p_at);\n    v_lock_kick := v_lock_kick || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n',
    E''),
    E'      SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, v_current, v_e ->> \'player_id\', p_at);   -- 164 / F467\n      v_lock_kick_cur := v_lock_kick_cur || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n        \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n',
    E''),
    E'  v_lock_kick := v_lock_kick || v_gone_kick;   -- 164 / F467: (4b)\'s kept starters, as v_kick\n',
    E''),
    E'    v_lock_kick_cur := v_lock_kick;   -- 164 / F467\n',
    E''),
    E'  --     164 / F467: judged by v_lock_kick — per PLAYER, the lock a manager\n  --     faces since 157 — so the record names every player a manager\n  --     could not have moved.\n',
    E''),
    E'v_lock_kick_cur -> v_pid',
    E'v_kick_cur -> v_pid'),
    E'v_lock_kick -> v_pid',
    E'v_kick -> v_pid')
$un164$;

-- The pre-164 bodies, side by side with the live ones: each live definition
-- with 164 reversed, renamed into pg_temp. Nothing live is replaced.
do $pre$
begin
  execute replace(pg_temp.un164(pg_get_functiondef('public.lineup_kept_starter_internal(integer, integer, text, text, jsonb, timestamptz)'::regprocedure)),
                  'FUNCTION public.lineup_kept_starter_internal(', 'FUNCTION pg_temp.kept_pre164(');
  execute replace(pg_temp.un164(pg_get_functiondef('public.commish_roster_override_internal(uuid, uuid, text, text, text, uuid, uuid, uuid, timestamptz, text, text)'::regprocedure)),
                  'FUNCTION public.commish_roster_override_internal(', 'FUNCTION pg_temp.roster_pre164(');
  execute replace(pg_temp.un164(pg_get_functiondef('public.commish_edit_lineup_internal(uuid, uuid, integer, jsonb, uuid, timestamptz, text)'::regprocedure)),
                  'FUNCTION public.commish_edit_lineup_internal(', 'FUNCTION pg_temp.edit_pre164(');
end
$pre$;

-- ---------------------------------------------------------------------------
-- A. Form pins, D137 in the database, the neighbours untouched
-- ---------------------------------------------------------------------------
select is(
  (select string_agg(format('%s:%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE'),
                            has_function_privilege('authenticated', p.oid, 'EXECUTE')), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('lineup_kept_starter_internal', 'commish_roster_override_internal', 'commish_edit_lineup_internal')),
  'commish_edit_lineup_internal:f:search_path="":f:f commish_roster_override_internal:f:search_path="":f:f lineup_kept_starter_internal:f:search_path="":f:f',
  'A1 the three replaced bodies: one overload each (signatures unchanged), PLAIN, search_path empty, closed to anon and authenticated');
select ok(
  not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
    where n.nspname = 'public' and a.privilege_type = 'EXECUTE' and a.grantee = 0
      and p.proname in ('lineup_kept_starter_internal', 'commish_roster_override_internal', 'commish_edit_lineup_internal', 'admin_rescore_final_week')),
  'A2 PUBLIC holds EXECUTE on none of the four (REVOKEs restated)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un164(p.prosrc)), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('lineup_kept_starter_internal', 'commish_roster_override_internal', 'commish_edit_lineup_internal')),
  'commish_edit_lineup_internal=60662cff534f641b2674201b999681c8 commish_roster_override_internal=32972a1a5183c748be5a90c8ffdad7f1 lineup_kept_starter_internal=3266056c8506911d20ef8f96fd76cbb3',
  'A3 D137: each live body with 164 reversed is its NEWEST definer FILE TEXT (154:1057 / 153:971 / 154:179 — the stored md5 literals pgTAP 105 A6 pinned before 164)');
select is(
  (select string_agg(p.proname || '=' || md5(p.prosrc), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('lineup_kept_starter_internal', 'commish_roster_override_internal', 'commish_edit_lineup_internal')),
  'commish_edit_lineup_internal=9bcdc00d2a66ad830883de3fca723cdb commish_roster_override_internal=a078d3e98fd386bdf4d77c587f87523e lineup_kept_starter_internal=3f60bb975e57719c0be2de7f4ccdbb12',
  'A4 the three live prosrc md5s — 164 as written (stored literals)');
select is(
  (select string_agg(p.proname || ':' || (length(p.prosrc) - length(replace(p.prosrc, 'public.pool_game_lock_any_internal(', ''))) / length('public.pool_game_lock_any_internal(')
                     || '/' || (length(p.prosrc) - length(replace(p.prosrc, 'public.pool_game_lock_player_internal(', ''))) / length('public.pool_game_lock_player_internal(')
                     || '/' || (length(p.prosrc) - length(replace(p.prosrc, 'public.lineup_player_kickoff_internal(', ''))) / length('public.lineup_player_kickoff_internal(')
                     || '/' || (length(p.prosrc) - length(replace(p.prosrc, 'public.lineup_record_kicked_off_internal(', ''))) / length('public.lineup_record_kicked_off_internal('),
                     ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('lineup_kept_starter_internal', 'commish_roster_override_internal', 'commish_edit_lineup_internal')),
  'commish_edit_lineup_internal:0/0/2/0 commish_roster_override_internal:0/2/0/0 lineup_kept_starter_internal:0/0/0/1',
  'A5 the receipts read the PLAYED lock and the kept-start judgment the guard (calls: team lock / per-player lock / per-player datum / real-kickoff guard)');
select is(
  (select string_agg(p.proname || '=' || md5(p.prosrc), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('lineup_record_kicked_off_internal', 'lineup_played_internal', 'lineup_player_kickoff_internal',
                                                 'lineup_played_lock_internal', 'pool_game_lock_player_internal', 'set_lineup_internal',
                                                 'lineup_autopilot_internal', 'commish_edit_lineup', 'commish_force_add_drop', 'commish_move_player')),
  'commish_edit_lineup=876d323ce50e0b305a29046a8fee0515 commish_force_add_drop=aa519b828303f9e9318349242174b099 commish_move_player=ec4ac48d6c6cd9daa4ba0ab7c6e45a11 lineup_autopilot_internal=544d32c67abd3f3243ff1bfa568360ad lineup_played_internal=aa79ff77ba714b19b6740c60202d8476 lineup_played_lock_internal=cfee6bd961f1dae36991bb4ffbfc19b4 lineup_player_kickoff_internal=b14949f7f54de384bac2a49efdfd494d lineup_record_kicked_off_internal=9c54a4f3fb38bad956d6386d7748b777 pool_game_lock_player_internal=402cae9eb3c781f6b0c82c44178e4851 set_lineup_internal=ca3307414057469da7ed5c0af0b29fe6',
  'A6 UNTOUCHED (stored literals): the five 157 helpers, the kept-start readers set_lineup and autopilot (157 as written — 105 A5), and the three DEFINER doors');

-- ---------------------------------------------------------------------------
-- FIXTURE — the 105 calendar shape (2026 seeds; only the stamps rewritten):
-- WEEK 6 — PA @ PZ Thu 10-16 00:15Z (played), PB @ PY Sun 10-18 17:00Z; PF @
-- PG FLEXED from Sun 10-18 13:00Z to 10-19 00:20Z; PD @ PE POSTPONED from Fri
-- 10-17 00:15Z to 10-27 00:15Z; PH @ PI POSTPONED from Thu 10-16 00:15Z (the
-- instant it shared with PA @ PZ) to 10-27 01:00Z. The week last game ends
-- Tue 10-20 03:30Z (its lock release). SUN = 10-18 16:00Z: after Thursday,
-- before Sunday. AFTER = 10-20 12:00Z: past the release.
-- ---------------------------------------------------------------------------
update nfl_weeks w
set last_game_ends_at = case when w.week <= 5 then w.starts_at + interval '6 days'
                             when w.week = 6 then '2026-10-20 03:30:00+00'::timestamptz end,
    first_kickoff_at = null
where w.season = 2026;
delete from nfl_games where season = 2026;
insert into nfl_games (id, season, week, home_team, away_team, kickoff_at)
select 'r-dummy-' || w.week, 2026, w.week, 'KC', 'BUF', w.starts_at + interval '1 day' from nfl_weeks w where w.season = 2026 and w.week <= 14 and w.week <> 6;
insert into nfl_games (id, season, week, home_team, away_team, kickoff_at, status) values
 ('r-g6a', 2026, 6, 'PA', 'PZ', '2026-10-16 00:15:00+00', 'final'),
 ('r-g6b', 2026, 6, 'PB', 'PY', '2026-10-18 17:00:00+00', 'scheduled'),
 ('r-g6f', 2026, 6, 'PF', 'PG', '2026-10-19 00:20:00+00', 'scheduled'),
 ('r-g6c', 2026, 6, 'PD', 'PE', '2026-10-27 00:15:00+00', 'postponed'),
 ('r-g6d', 2026, 6, 'PH', 'PI', '2026-10-27 01:00:00+00', 'postponed');

insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000', ('91120000-0000-4000-8000-00000000000' || i)::uuid,
  'authenticated', 'authenticated', 'pgtap-mc' || i || '@fieldscout.local', 'x', now(),
  '{"provider": "email", "providers": ["email"]}', json_build_object('username', 'mc_user' || i)::jsonb, now(), now()
from generate_series(1, 4) i;

insert into leagues (id, owner_id, name, season, status, team_count, regular_season_weeks, playoff_teams, playoff_start_week,
                     scoring_system_id, scoring_rules_snapshot, lineup_lock, waiver_type, faab_budget, trade_review,
                     settings, roster_settings)
values ('b1120000-0000-4000-8000-000000000001', '91120000-0000-4000-8000-000000000001', 'pgtap-mc-L', 2026, 'in_season', 12, 14, 0, 15,
        (select id from scoring_systems where is_template and name = 'ESPN Standard'),
        (select rules from scoring_systems where is_template and name = 'ESPN Standard'),
        'per_player_kickoff', 'none_fcfs', 100, 'none', '{}'::jsonb,
        '{"starting_slots": [{"key": "qb", "label": "QB", "eligible": ["QB"], "count": 2}], "bench": 3, "ir_slots": [{"key": "ir", "label": "IR", "type": "standard", "eligible_designations": ["OUT", "IR"]}], "swap_spots": 0}'::jsonb);

insert into teams (id, owner_id, name, league_id, status) values
 ('c1120000-0000-4000-8000-000000000001', '91120000-0000-4000-8000-000000000001', 'MC Commish', 'b1120000-0000-4000-8000-000000000001', 'active'),
 ('c1120000-0000-4000-8000-000000000002', '91120000-0000-4000-8000-000000000002', 'MC Two',     'b1120000-0000-4000-8000-000000000001', 'active'),
 ('c1120000-0000-4000-8000-000000000003', '91120000-0000-4000-8000-000000000003', 'MC Three',   'b1120000-0000-4000-8000-000000000001', 'active'),
 ('c1120000-0000-4000-8000-000000000004', '91120000-0000-4000-8000-000000000004', 'MC Echo',    'b1120000-0000-4000-8000-000000000001', 'active');
insert into league_members (league_id, user_id, team_id, role, is_placeholder, faab_balance)
select t.league_id, t.owner_id, t.id,
       case when t.owner_id = '91120000-0000-4000-8000-000000000001' then 'commissioner' else 'manager' end, false, 100
from teams t where t.id::text like 'c1120000-%';

insert into league_weeks (league_id, season, week)
select 'b1120000-0000-4000-8000-000000000001', 2026, w from generate_series(1, 14) w;
update league_weeks set status = 'live'              where league_id = 'b1120000-0000-4000-8000-000000000001' and week <= 6;
update league_weeks set status = 'correction_window' where league_id = 'b1120000-0000-4000-8000-000000000001' and week <= 5;
update league_weeks set status = 'final'             where league_id = 'b1120000-0000-4000-8000-000000000001' and week <= 5;

-- Everyone is on the team his note says at the Thursday kickoff; the NFL
-- moves (a trade to PB, a release to no team) are applied after the game.
insert into players (id, full_name, position, team, status) values
 ('r-b1', 'MC B1 (released)', 'QB', 'PA', 'Active'),   ('r-b2', 'MC B2 (PD, stale Fri record)', 'QB', 'PD', 'Active'),
 ('r-b3', 'MC B3 (PF, flexed record)', 'QB', 'PF', 'Active'), ('r-b4', 'MC B4 (PH, postponed team)', 'QB', 'PH', 'Active'),
 ('r-b5', 'MC B5 (PD, stat line)', 'QB', 'PD', 'Active'), ('r-b6', 'MC B6 (PD, week closed)', 'QB', 'PD', 'Active'),
 ('r-b7', 'MC B7 (PB, no record)', 'QB', 'PB', 'Active'),
 ('r-c1', 'MC C1 (Thu, released)', 'QB', 'PA', 'Active'), ('r-c2', 'MC C2 (Thu, traded)', 'QB', 'PA', 'Active'),
 ('r-c3', 'MC C3 (Thu, released FA)', 'QB', 'PA', 'Active'), ('r-c4', 'MC C4 (Sun)', 'QB', 'PB', 'Active'),
 ('r-c5', 'MC C5 (Thu, still PA)', 'QB', 'PA', 'Active'),
 ('r-e1', 'MC E1 (Thu, released)', 'QB', 'PA', 'Active'), ('r-e2', 'MC E2 (Sun)', 'QB', 'PB', 'Active'),
 ('r-e3', 'MC E3 (Sun)', 'QB', 'PB', 'Active'), ('r-e4', 'MC E4 (Thu, traded)', 'QB', 'PA', 'Active'),
 ('r-e5', 'MC E5 (Thu, released, out)', 'QB', 'PA', 'Out');

insert into league_rosters (league_id, team_id, player_id, slot_key) values
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000002', 'r-c1', 'bn'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000002', 'r-c2', 'qb'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000002', 'r-c4', 'bn'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000002', 'r-c5', 'bn'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004', 'r-e1', 'qb'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004', 'r-e2', 'bn'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004', 'r-e3', 'bn'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004', 'r-e4', 'qb'),
 ('b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004', 'r-e5', 'bn');
insert into league_player_pool (league_id, player_id, state)
select 'b1120000-0000-4000-8000-000000000001', r.player_id, 'rostered' from league_rosters r where r.league_id = 'b1120000-0000-4000-8000-000000000001';
insert into league_player_pool (league_id, player_id, state) values ('b1120000-0000-4000-8000-000000000001', 'r-c3', 'free_agent');

-- Week-6 lineups in 114 shape; each starter carries the kickoff the writer
-- that seated him recorded (Thursday for the Thursday starters).
insert into team_lineups (team_id, season, week, slot_map, starters, bench) values
 ('c1120000-0000-4000-8000-000000000002', 2026, 6, '{"qb:0": "r-c2"}'::jsonb,
  '[{"slot": "qb:0", "player_id": "r-c2", "kickoff_at": "2026-10-16T00:15:00+00:00", "flags": []}, {"slot": "qb:1", "player_id": null, "kickoff_at": null, "flags": ["empty"]}]'::jsonb,
  '["r-c1", "r-c4", "r-c5"]'::jsonb),
 ('c1120000-0000-4000-8000-000000000004', 2026, 6, '{"qb:0": "r-e1", "qb:1": "r-e4"}'::jsonb,
  '[{"slot": "qb:0", "player_id": "r-e1", "kickoff_at": "2026-10-16T00:15:00+00:00", "flags": []}, {"slot": "qb:1", "player_id": "r-e4", "kickoff_at": "2026-10-16T00:15:00+00:00", "flags": []}]'::jsonb,
  '["r-e2", "r-e3", "r-e5"]'::jsonb);

-- THE THURSDAY STAT LINES (he played): C1, C3, E1, E5, and B5 (whose line
-- names no game). C2 and E4 have NONE — their lineup record alone says so.
insert into player_stats (player_id, season, week, stat_type, game_id, updated_at)
select p, 2026, 6, 'weekly', case when p = 'r-b5' then null else 'r-g6a' end, '2026-10-16 03:30:00+00'
from unnest(array['r-c1', 'r-c3', 'r-e1', 'r-e5', 'r-b5']) p;

-- THE NFL MOVES, after the Thursday game.
update players set team = null where id in ('r-b1', 'r-c1', 'r-c3', 'r-e1', 'r-e5');
update players set team = 'PB' where id in ('r-c2', 'r-e4');

-- Post-reset race guard (067): today and tomorrow realtime.messages partitions.
do $part$
declare
  d date;
  part_name text;
begin
  foreach d in array array[current_date, current_date + 1] loop
    part_name := 'messages_' || to_char(d, 'YYYY_MM_DD');
    if not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                   where n.nspname = 'realtime' and c.relname = part_name) then
      execute format('create table realtime.%I partition of realtime.messages for values from (%L) to (%L)',
                     part_name, d::timestamp, (d + 1)::timestamp);
    end if;
  end loop;
end
$part$;

-- A TRIAL runs one statement in a subtransaction that is then rolled back,
-- and returns its document and the league state it left (rosters, lineups,
-- pool) — so the live body and the pre-164 body start from the SAME state.
create function pg_temp.state() returns jsonb language sql as $$
  select jsonb_build_object(
    'rosters', (select jsonb_agg(jsonb_build_array(r.team_id, r.player_id, r.slot_key, r.acquisition_type, r.ir_placed_week, r.ir_lock_until_week) order by r.team_id, r.player_id)
                from league_rosters r where r.league_id = 'b1120000-0000-4000-8000-000000000001'),
    'lineups', (select jsonb_agg(jsonb_build_array(tl.team_id, tl.week, tl.slot_map, tl.starters, tl.bench, tl.locked_at, tl.edited_by_commish) order by tl.team_id, tl.week)
                from team_lineups tl join teams t on t.id = tl.team_id where t.league_id = 'b1120000-0000-4000-8000-000000000001'),
    'pool',    (select jsonb_agg(jsonb_build_array(pp.player_id, pp.state) order by pp.player_id)
                from league_player_pool pp where pp.league_id = 'b1120000-0000-4000-8000-000000000001'));
$$;
create function pg_temp.trial(p_sql text) returns jsonb language plpgsql as $$
declare
  v_doc   jsonb;
  v_state jsonb;
begin
  begin
    execute p_sql into v_doc;
    v_state := pg_temp.state();
    raise exception 'trial rolled back' using errcode = 'FST01';
  exception when sqlstate 'FST01' then
    null;
  end;
  return jsonb_build_object('doc', v_doc, 'state', v_state);
exception when others then
  return jsonb_build_object('error', sqlerrm, 'sqlstate', sqlstate);
end $$;
create temp table r112 (tag text primary key, r jsonb not null);
select set_config('request.jwt.claims', json_build_object('sub', '91120000-0000-4000-8000-000000000001', 'role', 'authenticated')::text, true);

-- ---------------------------------------------------------------------------
-- B. F468(b) — the kept-start judgment and the locks agree on a record
-- ---------------------------------------------------------------------------
create function pg_temp.kept(p_fn text, p_pid text, p_rec text, p_at timestamptz) returns text language plpgsql as $$
declare
  v_r record;
  v_starters jsonb := jsonb_build_array(jsonb_build_object('slot', 'qb:0', 'player_id', p_pid, 'kickoff_at', p_rec));
begin
  execute format('select * from %s(2026, 6, $1, %L, $2, $3)', p_fn, 'qb:0') into v_r using p_pid, v_starters, p_at;
  return format('%s:%s:%s', v_r.kept::text, v_r.why, v_r.datum_arm);
end $$;
create function pg_temp.kept_both(p_pid text, p_rec text, p_at timestamptz) returns text language sql as $$
  select 'live ' || pg_temp.kept('public.lineup_kept_starter_internal', p_pid, p_rec, p_at)
      || ' | pre164 ' || pg_temp.kept('pg_temp.kept_pre164', p_pid, p_rec, p_at)
$$;

select is(pg_temp.kept_both('r-b1', '2026-10-16T00:15:00+00:00', '2026-10-18 16:00:00+00'),
  'live true:kicked_off:lineup_record | pre164 true:kicked_off:lineup_record',
  'B1 a record at a REAL passed kickoff (PA at PZ, Thursday), the player since released: kept by the record, as before');
select is(pg_temp.kept_both('r-b2', '2026-10-17T00:15:00+00:00', '2026-10-18 16:00:00+00'),
  'live false:not_played:nfl_games | pre164 true:kicked_off:lineup_record',
  'B2 a STALE record — his game (PD at PE) was POSTPONED from that instant and no game kicks off there now: no longer kept (154 kept him, the locks did not)');
select is(pg_temp.kept_both('r-b3', '2026-10-18T13:00:00+00:00', '2026-10-18 16:00:00+00'),
  'live false:not_played:nfl_games | pre164 true:kicked_off:lineup_record',
  'B3 a record at the instant his game was FLEXED away from (E42): no longer kept');
select is(pg_temp.kept_both('r-b4', '2026-10-16T00:15:00+00:00', '2026-10-18 16:00:00+00'),
  'live false:not_played:nfl_games | pre164 true:kicked_off:lineup_record',
  'B4 a record at a real kickoff instant (Thursday) that his OWN game shared before it was POSTPONED (E43, the postponed-team guard): no longer kept');
select is(pg_temp.kept_both('r-b5', '2026-10-17T00:15:00+00:00', '2026-10-18 16:00:00+00'),
  'live true:stat_line:stat_line | pre164 true:kicked_off:lineup_record',
  'B5 a stale record with a STAT LINE for the week: the fall-through keeps him by the stat line (arm iii)');
select is(pg_temp.kept_both('r-b6', '2026-10-17T00:15:00+00:00', '2026-10-20 12:00:00+00'),
  'live true:week_closed:nfl_games | pre164 true:kicked_off:lineup_record',
  'B6 a stale record after the week lock release, his game still to come: the fall-through keeps him as a closed week (arm iv, D412(5))');
select is(pg_temp.kept_both('r-b7', null, '2026-10-18 16:00:00+00'),
  'live false:not_played:nfl_games | pre164 false:not_played:nfl_games',
  'B7 CONTROL: no record, his game ahead — not kept, under both bodies');

-- ---------------------------------------------------------------------------
-- C. F467 — the roster override receipt names the PLAYED lock
-- ---------------------------------------------------------------------------
create function pg_temp.roster_sql(p_fn text, p_team text, p_add text, p_drop text, p_player text, p_from text, p_to text, p_verb text, p_act int)
returns text language sql as $$
  select format('select %s(%L, %L::uuid, %L, %L, %L, %L::uuid, %L::uuid, %L::uuid, %L::timestamptz, null, %L)',
                p_fn, 'b1120000-0000-4000-8000-000000000001', p_team, p_add, p_drop, p_player, p_from, p_to,
                'a1120000-0000-4000-8000-' || lpad(p_act::text, 12, '0'), '2026-10-18 16:00:00+00', p_verb)
$$;
insert into r112 (tag, r)
select c.tag || ':' || f.side,
       pg_temp.trial(pg_temp.roster_sql(f.fn, c.team, c.a, c.d, c.p, c.fr, c.tt, c.verb, c.act))
from (values ('live', 'public.commish_roster_override_internal'), ('pre', 'pg_temp.roster_pre164')) f(side, fn)
cross join (values
  ('c1', 'c1120000-0000-4000-8000-000000000002', null,   'r-c1', null,   null, null, 'commish_force_add_drop', 1),
  ('c2', null, null, null, 'r-c2', 'c1120000-0000-4000-8000-000000000002', 'c1120000-0000-4000-8000-000000000003', 'commish_move_player', 2),
  ('c3', 'c1120000-0000-4000-8000-000000000003', 'r-c3', null,   null,   null, null, 'commish_force_add_drop', 3),
  ('c4', 'c1120000-0000-4000-8000-000000000002', null,   'r-c4', null,   null, null, 'commish_force_add_drop', 4),
  ('c5', 'c1120000-0000-4000-8000-000000000002', null,   'r-c5', null,   null, null, 'commish_force_add_drop', 5)
) c(tag, team, a, d, p, fr, tt, verb, act);
create function pg_temp.rc(p_tag text) returns text language sql as $$
  select format('live %s %s %s | pre164 %s',
                coalesce((select r -> 'doc' -> 'bypassed' from r112 where tag = p_tag || ':live')::text, (select r ->> 'error' from r112 where tag = p_tag || ':live')),
                coalesce((select r -> 'doc' -> 'drop_game_lock' ->> 'datum_arm' from r112 where tag = p_tag || ':live'), 'none'),
                coalesce((select r -> 'doc' -> 'add_game_lock' ->> 'datum_arm' from r112 where tag = p_tag || ':live'), 'none'),
                coalesce((select r -> 'doc' -> 'bypassed' from r112 where tag = p_tag || ':pre')::text, (select r ->> 'error' from r112 where tag = p_tag || ':pre')))
$$;

select is(pg_temp.rc('c1'), 'live ["e32_drop_lock:r-c1"] stat_line none | pre164 []',
  'C1 a force-DROP of a player who played Thursday and was then RELEASED: the receipt names the drop lock he walked past (his stat line) — before 164 it named nothing');
select is(pg_temp.rc('c2'), 'live ["e32_drop_lock:r-c2"] lineup_record none | pre164 []',
  'C2 a MOVE of a player who played Thursday and was then TRADED to a Sunday team: the receipt names the lock (the lineup record)');
select is(pg_temp.rc('c3'), 'live ["e32_add_lock:r-c3"] none stat_line | pre164 []',
  'C3 a force-ADD of a free agent who played Thursday and was then released: the receipt names the add lock');
select is(pg_temp.rc('c4'), 'live [] nfl_games none | pre164 []',
  'C4 CONTROL: a player whose game is still ahead and who has not played — no lock is named, under both bodies (bypassed[] names measured locks, never a constant)');
select is(pg_temp.rc('c5'), 'live ["e32_drop_lock:r-c5"] nfl_games none | pre164 ["e32_drop_lock:r-c5"]',
  'C5 the TEAM lock is named as before (still on PA, whose game kicked off Thursday)');
select is(
  (select string_agg(tag, ',' order by tag) from r112 r where tag like 'c_:live'
     and r -> 'state' = (select p.r -> 'state' from r112 p where p.tag = replace(r.tag, ':live', ':pre'))
     and r -> 'state' is not null and r ? 'doc'),
  'c1:live,c2:live,c3:live,c4:live,c5:live',
  'C6 RECEIPT ONLY: every override landed (the commissioner is not bound) and left the rosters, lineups and pool EXACTLY as the pre-164 body does');
select is(
  (select string_agg(x.tag || '=' || x.n, ' ' order by x.tag)
   from (select tag, (select count(*) from jsonb_array_elements(r -> 'state' -> 'rosters') e where e ->> 1 in ('r-c1', 'r-c2', 'r-c3', 'r-c4', 'r-c5')
                                                                                                   and e ->> 0 = 'c1120000-0000-4000-8000-000000000002') as n
         from r112 where tag like 'c_:live') x),
  'c1:live=3 c2:live=3 c3:live=4 c4:live=3 c5:live=3',
  'C7 …and each did what was asked: MC Two keeps 3 of its 4 after a drop or a move away, all 4 when the add went to MC Three');

-- ---------------------------------------------------------------------------
-- D. F467 — the lineup override receipt names the PLAYED lock
--    MC Echo, week 6, at SUN: bench E One (played Thu, released), move E Four
--    (played Thu, traded to PB) from qb:1 to qb:0, start E Two (Sunday, not
--    played) at qb:1, put E Five (played Thu, released, OUT) on IR.
-- ---------------------------------------------------------------------------
insert into r112 (tag, r)
select 'd:' || f.side,
       pg_temp.trial(format('select %s(%L, %L, 6, %L::jsonb, %L::uuid, %L::timestamptz, null)', f.fn,
                            'b1120000-0000-4000-8000-000000000001', 'c1120000-0000-4000-8000-000000000004',
                            '{"qb:0": "r-e4", "qb:1": "r-e2", "ir:0": "r-e5"}', 'a1120000-0000-4000-8000-000000000011', '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre164')) f(side, fn);
create function pg_temp.moved(p_side text) returns text language sql as $$
  select coalesce((select string_agg(format('%s %s->%s %s', m ->> 'player_id', m ->> 'from', coalesce(m ->> 'to', 'bench'), m ->> 'datum_arm'), ', ' order by m ->> 'player_id')
                   from r112, jsonb_array_elements(r -> 'doc' -> 'locked_players_moved') m where tag = 'd:' || p_side),
                  (select coalesce(r ->> 'error', 'none') from r112 where tag = 'd:' || p_side))
$$;
select is('live ' || pg_temp.moved('live') || ' | pre164 ' || pg_temp.moved('pre'),
  'live r-e1 qb:0->bench lineup_record, r-e4 qb:1->qb:0 lineup_record | pre164 none',
  'D1 locked_players_moved names the two players who PLAYED Thursday and were since released / traded (the lineup record) — before 164 it named neither; E Two (not played) is not named');
select is(
  (select format('live %s | pre164 %s', (select r -> 'doc' -> 'bypassed' from r112 where tag = 'd:live'), (select r -> 'doc' -> 'bypassed' from r112 where tag = 'd:pre'))),
  'live ["per_player_kickoff_lock", "ir_lock_timing:r-e5"] | pre164 []',
  'D2 the bypasses: the per-player kickoff lock and the IR timing lock for E Five (who played Thursday) are named — before 164, neither');
select ok(
  (select r -> 'state' from r112 where tag = 'd:live') = (select r -> 'state' from r112 where tag = 'd:pre')
  and (select r -> 'state' -> 'lineups' from r112 where tag = 'd:live') is not null,
  'D3 RECEIPT ONLY: the lineup row (slot map, starters with their kickoff records, bench, locked_at) and the IR placement are EXACTLY what the pre-164 body writes');
select is(
  (select format('%s | %s', r -> 'doc' -> 'slot_map', (select string_agg(coalesce(s ->> 'player_id', '-') || '@' || coalesce(s ->> 'kickoff_at', '-'), ',' order by o)
                                                        from jsonb_array_elements(r -> 'doc' -> 'starters') with ordinality x(s, o)))
   from r112 where tag = 'd:live'),
  '{"ir:0": "r-e5", "qb:0": "r-e4", "qb:1": "r-e2"} | r-e4@2026-10-18T17:00:00+00:00,r-e2@2026-10-18T17:00:00+00:00',
  'D4 …and it is the edit that was asked: E Four at qb:0, E Two at qb:1, E Five on IR — each record still from his CURRENT team (F497 names that for a follow-up)');

-- ---------------------------------------------------------------------------
-- R. F489 — the re-score door is retired
-- ---------------------------------------------------------------------------
select is(
  (select format('%s:%s:%s:%s', has_function_privilege('service_role', p.oid, 'EXECUTE')::text, has_function_privilege('authenticated', p.oid, 'EXECUTE')::text,
                 has_function_privilege('anon', p.oid, 'EXECUTE')::text, p.proacl::text)
   from pg_proc p where p.oid = 'public.admin_rescore_final_week(uuid, integer, jsonb, text, text, uuid, uuid, boolean)'::regprocedure),
  'false:false:false:{postgres=X/postgres}',
  'R1 RETIRED: the service role no longer holds EXECUTE on admin_rescore_final_week (nor anon, nor authenticated) — only its owner');
select is(
  (select format('%s:%s:%s', md5(p.prosrc), p.prosecdef::text, array_to_string(p.proconfig, ','))
   from pg_proc p where p.oid = 'public.admin_rescore_final_week(uuid, integer, jsonb, text, text, uuid, uuid, boolean)'::regprocedure),
  'e604714a034578b8e56c4398621a3921:true:search_path=""',
  'R2 …the function itself is KEPT, byte for byte as 161 wrote it (a stored literal), still DEFINER with search_path empty — re-granting it is one migration');
select is(
  (select format('%s:%s:%s', c.relrowsecurity::text, (select count(*) from pg_policies where tablename = 'admin_rescore_actions'),
                 md5((select prosrc from pg_proc where proname = 'league_week_player_points_lock')))
   from pg_class c where c.oid = 'public.admin_rescore_actions'::regclass),
  'true:0:bc1ac0492d7b05c75aa212d7e9e0d990',
  'R3 …its replay ledger is kept (RLS on, zero policies) and so is the lock exit it served (161, a stored literal)');
set local role service_role;
select set_config('request.jwt.claims', '{"role": "service_role"}', true);
select throws_ok(
  $$ select public.admin_rescore_final_week(null, null, null, null, null, null, null, true) $$,
  '42501', 'permission denied for function admin_rescore_final_week',
  'R4 the service role calling the door is refused by the database (the real 42501 the CLI names), before a line of it runs');
reset role;
select set_config('request.jwt.claims', json_build_object('sub', '91120000-0000-4000-8000-000000000001', 'role', 'authenticated')::text, true);
select ok(
  obj_description('public.admin_rescore_final_week(uuid, integer, jsonb, text, text, uuid, uuid, boolean)'::regprocedure, 'pg_proc')
    like 'RETIRED by migration 164 (M5 L.D3.14; PROGRESS F489, D428; spec §11.4 v2.16.73): used once, 2026-09-29, then retired%',
  'R5 its comment says it is retired, when, and why');
select is(
  (select count(*)::int from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname <> 'admin_rescore_final_week' and p.prosrc like '%admin_rescore_final_week(%')
  + (select count(*)::int from cron.job j where j.command like '%admin_rescore_final_week%'),
  0,
  'R6 nothing in the database calls it: no other function body and no cron job names it');

select * from finish();
rollback;
