-- ============================================================================
-- The commissioner lineup editor stores the kickoff record per PLAYER —
-- pgTAP 113 (task L.D2.19; migration 165; PROGRESS D429 — F497 discharged;
-- D420 / D428 / D413 / D354; spec §11.2 (the one-start bullet: the lineup
-- record of his kickoff is kept), §7.3.6, §10 / standing rule (g)).
--
-- Numbering: reserved and measured (165 / 113). OWN FIXTURE: users 9113…,
-- league b113…, teams c113…, action ids a113…, players s-* / u-*, NFL teams
-- Q*. Every instant is passed explicitly (the TimeProvider rule); internals
-- are called as postgres with the actor JWT claims set.
--
--   §A  form: the two replaced bodies (PLAIN, search_path empty, closed to
--       anon / authenticated, one overload each), D137 in the database (each
--       live body with 165 reversed = its newest definer FILE TEXT, stored
--       literals), 165 as written, the call counts, un165 an identity on
--       every other body, the neighbours untouched, the helper comment.
--   §B  F497, the current week: a commissioner edit that KEEPS a starter
--       who played Thursday and was then released (s-rel — the r-e1 shape)
--       or traded to a Sunday team (s-trd — the r-e4 shape) stores the
--       Thursday record, keeps locked_at on Thursday and flags no bye —
--       side by side with the pre-165 body (pg_temp.edit_pre165, the live
--       body with 165 reversed); under allow_illegal_lineups = false the
--       re-save lands (164 refused it: a timing read binding the
--       commissioner); the record survives the tick; and the played lock
--       still holds each of them for his manager afterwards (164 let the
--       manager bench both).
--   §P  a RETROACTIVE fix to a closed past week keeps a since-released
--       starter record (164 blanked it, and refused under the setting).
--   §C  the receipts are 164s (the fold): locked_players_moved and every
--       bypass identical to the pre-165 body, current and past week; the
--       rows differ only in the records (slot map, bench, IR, rosters equal).
--   §D  lineup_carry_internal: identical at week open (before any kickoff);
--       a mid-week carry (the tick D354 materialize) records a played,
--       since-released starter by his stat line, not as a bye.
--   §E  controls: a player whose game is still ahead, and a flexed game
--       (E42), read the same under both bodies; a player released BEFORE he
--       played is still a bye — refused under the setting by both (validity
--       binds the commissioner).
--
-- BREAK PROBES (the PR body; measured), each injected right after the
-- pre-165 bodies are created, inside this transaction (the ROLLBACK ends it):
--   (1) commish_edit_lineup_internal back to 164 (un165 on the live body) ⇒
--       A4 A5 B1 B2 B5 B6 B7 P1 P2 C3 E2 red (13 / 24 green; pgTAP 112
--       with the same probe ⇒ D4 red);
--   (2) lineup_carry_internal back to 116 ⇒ A4 A5 D2 red;
--   (3) only the p_week read of the editor back to the team read ⇒ A3 A4
--       A5 B1 B2 B5 B6 B7 P1 P2 C1 C3 E2 red — C1 too (the receipt reads
--       v_kick since the fold), while C2 (the current-week map that feeds
--       the IR timing receipt) stays green.
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(24);

-- L.E1.31 (migration 170 — additive, the R992 shape): pg_temp.un170 reverses
-- 170's ONE hunk in each of commish_edit_lineup_internal,
-- commish_roster_override_internal and commish_rename_team_internal (D451 —
-- acting_as_team_id on the override twins) and is an identity on every other
-- body (pgTAP 118 A5). Generated by derive_170.py from the same pairs the
-- migration was derived with; applied INNERMOST below.
create function pg_temp.un170(p_src text) returns text language sql as $un170$
  select replace(replace(replace(p_src,
    -- commish_edit_lineup_internal
    E'        \'score_stale_reason\',  v_stale_why),\n      -- 170/L.E1.31 (D451) — acting_as_team_id = THE TEAM. The commissioner\n      -- set this team\'s lineup: a manager\'s act done for the team (§10.3:711\n      -- "set when the commissioner acts on behalf of any team, most commonly\n      -- an orphaned one"). set_lineup\'s commissioner arm has written the same\n      -- action_type with it since 169; one action_type, one shape.\n      p_team_id);\n    IF v_audit_id IS NULL THEN',
    E'        \'score_stale_reason\',  v_stale_why),\n      NULL);\n    IF v_audit_id IS NULL THEN'),
    -- commish_roster_override_internal
    E'        \'score_stale_reason\',  v_stale_why),\n      -- 170/L.E1.31 (D451) — acting_as_team_id = THE TEAM on the force\n      -- add / drop arm: the commissioner made this team\'s roster move, the\n      -- act roster_add_drop gives its manager (§10.3:711; TD16 — the manager\n      -- verb\'s commissioner door is this override, standing rule (h)). A MOVE\n      -- acts on two teams and for neither: NULL, both ride in\n      -- affected_team_ids (D353).\n      CASE WHEN v_is_move THEN NULL ELSE p_team_id END);\n    IF v_audit_id IS NULL THEN',
    E'        \'score_stale_reason\',  v_stale_why),\n      NULL);\n    IF v_audit_id IS NULL THEN'),
    -- commish_rename_team_internal
    E'        \'frozen_receipts_for_this_team\', v_frozen),\n      -- 170/L.E1.31 (D451) — acting_as_team_id = THE TEAM: the commissioner\n      -- renamed it, the act rename_own_team gives its manager (§10.3:711;\n      -- TD16 — the manager verb\'s commissioner door is this override).\n      p_team_id);\n    IF v_audit_id IS NULL THEN',
    E'        \'frozen_receipts_for_this_team\', v_frozen),\n      NULL);\n    IF v_audit_id IS NULL THEN')
$un170$;

-- L.E1.30 (migration 169 — additive, the R992 shape): pg_temp.un169 reverses
-- 169's ONE hunk in set_lineup_internal (F514 — the commissioner arm's
-- receipt) and is an identity on every other body (pgTAP 117 A3 / A5).
-- Generated by derive_169.py from the same pair the migration was derived
-- with; applied INNERMOST below.
create function pg_temp.un169(p_src text) returns text language sql as $un169$
  select replace(p_src,
    E'      INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)\n      VALUES (p_league_id, auth.uid(), v_message, \'league\', TRUE);\n      -- 169/L.E1.30 (F514) — THE RECEIPT: a commissioner setting a team he\n      -- does not manage is a commissioner action (D363(2)) — one row per\n      -- changed lineup, the team acted for in acting_as_team_id (§10.3). The\n      -- no-op re-save wrote nothing above; a manager\'s own save (the\n      -- commissioner\'s own team included) is not this arm.\n      PERFORM public.draft_commish_receipt_internal(\n        p_league_id, FALSE, \'set_lineup\', \'edit_lineup\', \'team\', p_team_id::text, v_reason,\n        jsonb_build_object(\'slot_map\', v_stored),\n        jsonb_build_object(\'slot_map\', v_canon)\n          || CASE WHEN jsonb_array_length(v_ir_placed) + jsonb_array_length(v_ir_removed) > 0\n                  THEN jsonb_build_object(\'ir_moves\', jsonb_build_object(\'placed\', v_ir_placed, \'removed\', v_ir_removed))\n                  ELSE \'{}\'::jsonb END,\n        jsonb_build_object(\'week\', p_week, \'current_week\', v_current, \'season\', v_league.season,\n                           \'week_status\', v_lw.status, \'team_name\', v_team.name, \'action_id\', p_action_id),\n        p_team_id);\n    END IF;\n',
    E'      INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)\n      VALUES (p_league_id, auth.uid(), v_message, \'league\', TRUE);\n    END IF;\n')
$un169$;

-- L.D2.20 (migration 166 — additive, the R992 shape): pg_temp.un166 reverses
-- 166's substitutions in the two bodies it replaced (commish_edit_lineup_
-- internal, lineup_player_kickoff_internal) and is an identity on every
-- other body (pgTAP 114 A3 / A5). Generated by derive_166.py from the same
-- pairs the migration was derived with; applied INNERMOST below.
create function pg_temp.un166(p_src text) returns text language sql as $un166$
  select replace(replace(replace(p_src,
    E'      -- §7.3.6 allow_illegal_lineups = FALSE. KEPT (see WHAT IS NOT LIFTED).\n      -- 166 / F500: R739\'s exemption, carried exactly as set_lineup_internal\n      -- step (10) has it (157): a STORED starter whose own game has kicked\n      -- off (his per-player datum, step (6)) and who stays at his stored key\n      -- is not blocked — his game is under way or over, so keeping him where\n      -- he stands is the week as it happened, not a submit. 123 dropped the\n      -- clause as meaningless for a verb with no lock; without it a starter\n      -- who played Thursday and was put on IR before Sunday refused every\n      -- commissioner fix to that week unless he benched him (changing the\n      -- score) — a save the manager may make: a TIMING refusal of the\n      -- commissioner (standing rule (g)). Putting a bye / OUT player at any\n      -- key he is not stored at (moving him, or starting one from the\n      -- bench) is still refused by name, as it is for the manager. The\n      -- stored-occupant test is spelled NULL-SAFE here: set_lineup\'s `=`\n      -- yields NULL for a key that was empty, which cannot reach its gate\n      -- (step (7b) refuses a kicked-off player entering a slot first) but\n      -- would reach this one (no lock) and let a moved OUT starter through.\n      -- The kept-start clause below (154 / F441) is spelled the same way\n      -- (F503): its `=` let a kept OFF-ROSTER starter, now OUT, be moved\n      -- into an empty key without the refusal.\n      IF NOT v_allow AND jsonb_array_length(v_pflags) > 0\n         AND NOT ((v_kick -> v_pid ->> \'kickoff_at\') IS NOT NULL\n                  AND (v_kick -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at\n                  AND (v_stored ->> v_key) IS NOT DISTINCT FROM v_pid)   -- 166 / F500: R739, as set_lineup (null-safe)\n         AND NOT (v_gone_kick ? v_pid AND (v_stored ->> v_key) IS NOT DISTINCT FROM v_pid) THEN   -- 154 / F441: a kept start where it stands is the week\'s record, not a submit (166 / F503: null-safe too — an empty key must not exempt a moved kept start)\n',
    E'      -- §7.3.6 allow_illegal_lineups = FALSE. KEPT (see WHAT IS NOT LIFTED).\n      -- 114\'s R739 clause is dropped from the predicate rather than carried:\n      -- it exempts "the stored player\'s own game has kicked off and he is the\n      -- stored occupant", i.e. "not the manager\'s to change" — and for a verb\n      -- with no lock there is no such thing, so carrying it would be a clause\n      -- that means nothing. The gate is therefore the plain one.\n      IF NOT v_allow AND jsonb_array_length(v_pflags) > 0\n         AND NOT (v_gone_kick ? v_pid AND (v_stored ->> v_key) = v_pid) THEN   -- 154 / F441: a kept start where it stands is the week\'s record, not a submit\n'),
    E'  v_k    RECORD;\n  v_p    RECORD;\n  v_stat TIMESTAMPTZ;   -- 166 / F501\nBEGIN\n',
    E'  v_k    RECORD;\n  v_p    RECORD;\nBEGIN\n'),
    E'      RETURN NEXT;\n      RETURN;\n    END IF;\n  ELSE\n    -- 166 / F501: his current team\'s kickoff HAS passed. When he PLAYED\n    -- earlier this week in another game — the NFL traded him after it to a\n    -- team that has also kicked off since — the datum is the game he played\n    -- in, never his new team\'s later one: an earlier start this league\n    -- recorded for a real, passed kickoff of the week (lineup_played_\n    -- internal (ii), guarded by lineup_record_kicked_off_internal), else his\n    -- stat line\'s game (a real, passed kickoff of the week, not postponed).\n    -- Both instants have passed, so every lock reads the same; only the\n    -- record (and locked_at, and the instant a refusal names) stays on the\n    -- game he played. A stat line that names no game carries no instant he\n    -- played at (157\'s fallback there is the week\'s first kickoff) and\n    -- never displaces his team\'s kickoff.\n    SELECT * INTO v_p FROM public.lineup_played_internal(p_league_id, p_season, p_week, p_player_id, p_at);\n    IF v_p.played AND v_p.datum_arm = \'lineup_record\' AND v_p.kickoff_at < v_k.kickoff_at THEN\n      kickoff_at := v_p.kickoff_at; datum_arm := v_p.datum_arm; on_bye := FALSE;\n      RETURN NEXT;\n      RETURN;\n    END IF;\n    SELECT min(g.kickoff_at) INTO v_stat\n    FROM public.player_stats ps\n    JOIN public.nfl_games g ON g.id = ps.game_id\n    WHERE ps.player_id = p_player_id AND ps.season = p_season AND ps.week = p_week\n      AND g.season = p_season AND g.week = p_week\n      AND g.status IS DISTINCT FROM \'postponed\'\n      AND g.kickoff_at <= p_at;\n    IF v_stat < v_k.kickoff_at THEN\n      kickoff_at := v_stat; datum_arm := \'stat_line\'; on_bye := FALSE;\n      RETURN NEXT;\n      RETURN;\n    END IF;\n  END IF;\n  kickoff_at := v_k.kickoff_at; datum_arm := v_k.datum_arm; on_bye := v_k.on_bye;\n',
    E'      RETURN NEXT;\n      RETURN;\n    END IF;\n  END IF;\n  kickoff_at := v_k.kickoff_at; datum_arm := v_k.datum_arm; on_bye := v_k.on_bye;\n')
$un166$;

-- pg_temp.un165 reverses 165's substitutions in the two bodies it replaced
-- (commish_edit_lineup_internal, lineup_carry_internal) — an identity on
-- every other body (A6). Generated by derive_165.py from the same pairs the
-- migration was derived with (one per unified hunk).
create function pg_temp.un165(p_src text) returns text language sql as $un165$
  select replace(replace(replace(replace(replace(replace(replace(p_src,
    E'  v_p           JSONB;\n  v_seen        JSONB := \'{}\'::jsonb;\n  v_by_pid      JSONB := \'{}\'::jsonb;   -- player_id → roster element\n  v_kick        JSONB := \'{}\'::jsonb;   -- player_id → {kickoff_at, datum_arm, on_bye} for p_week (165 / F497: per PLAYER — 157\'s lineup_player_kickoff_internal; 164\'s receipt map folded in)\n  v_kick_cur    JSONB := \'{}\'::jsonb;   -- the same for the CURRENT week (IR moves)\n  v_window      RECORD;\n  v_window_cur  RECORD;\n  v_k           RECORD;\n',
    E'  v_p           JSONB;\n  v_seen        JSONB := \'{}\'::jsonb;\n  v_by_pid      JSONB := \'{}\'::jsonb;   -- player_id → roster element\n  v_kick        JSONB := \'{}\'::jsonb;   -- player_id → {kickoff_at, datum_arm, on_bye} for p_week\n  v_kick_cur    JSONB := \'{}\'::jsonb;   -- the same for the CURRENT week (IR moves)\n  v_lock_kick   JSONB := \'{}\'::jsonb;   -- 164 / F467: the RECEIPT\'s datum for p_week, per PLAYER (157\'s lineup_player_kickoff_internal)\n  v_lock_kick_cur JSONB := \'{}\'::jsonb; -- 164 / F467: the same for the CURRENT week (the IR timing receipt)\n  v_window      RECORD;\n  v_window_cur  RECORD;\n  v_k           RECORD;\n'),
    E'  --     114:424-442. Still needed in full even though the lock is lifted:\n  --     v_kick feeds locked_at, starters[].kickoff_at and the bye flag.\n  SELECT * INTO v_window FROM public.schedule_window_internal(v_league.season, p_week, p_at);\n  -- 165 / F497: each player\'s kickoff is judged per PLAYER, exactly as\n  -- set_lineup has recorded it since 157 (lineup_player_kickoff_internal —\n  -- his current NFL team\'s game, or, when that is still ahead or he has no\n  -- team, the kickoff he PLAYED in this week: a start this league recorded\n  -- for a real, passed kickoff, or his stat line). A player the NFL released\n  -- or traded after he played keeps his kickoff record, his place in\n  -- locked_at and no bye flag through a commissioner edit (164 read his\n  -- current team here: NULL + "bye" for a release, the new team\'s later\n  -- game for a trade). The receipt reads the same map (164\'s parallel\n  -- v_lock_kick / v_lock_kick_cur, folded in). Nothing here refuses.\n  FOR v_e IN SELECT * FROM jsonb_array_elements(v_roster) LOOP\n    SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, p_week, v_e ->> \'player_id\', p_at);   -- 165 / F497\n    v_kick := v_kick || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n    IF v_current <> p_week THEN\n      SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, v_current, v_e ->> \'player_id\', p_at);   -- 165 / F497\n      v_kick_cur := v_kick_cur || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n        \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n    END IF;\n  END LOOP;\n  v_kick := v_kick || v_gone_kick;   -- 154 / F441: (4b)\'s kept, since-unrostered starters\n  IF v_current = p_week THEN\n    v_kick_cur := v_kick;\n    v_window_cur := v_window;\n  ELSE\n    SELECT * INTO v_window_cur FROM public.schedule_window_internal(v_league.season, v_current, p_at);\n',
    E'  --     114:424-442. Still needed in full even though the lock is lifted:\n  --     v_kick feeds locked_at, starters[].kickoff_at and the bye flag.\n  SELECT * INTO v_window FROM public.schedule_window_internal(v_league.season, p_week, p_at);\n  FOR v_e IN SELECT * FROM jsonb_array_elements(v_roster) LOOP\n    SELECT * INTO v_k FROM public.lineup_kickoff_internal(v_league.season, p_week, v_e ->> \'nfl_team\', p_at);\n    v_kick := v_kick || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n    -- 164 / F467: what the RECEIPT says is judged per PLAYER — his current\n    -- NFL team\'s kickoff, or the kickoff he PLAYED in this week (157) — so\n    -- a player the NFL released or traded after he played is named as\n    -- moved past the lock. Receipt only: v_kick (the stored record,\n    -- locked_at, the bye flags) is unchanged, and nothing here refuses.\n    SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, p_week, v_e ->> \'player_id\', p_at);\n    v_lock_kick := v_lock_kick || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n    IF v_current <> p_week THEN\n      SELECT * INTO v_k FROM public.lineup_kickoff_internal(v_league.season, v_current, v_e ->> \'nfl_team\', p_at);\n      v_kick_cur := v_kick_cur || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n        \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n      SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, v_league.season, v_current, v_e ->> \'player_id\', p_at);   -- 164 / F467\n      v_lock_kick_cur := v_lock_kick_cur || jsonb_build_object(v_e ->> \'player_id\', jsonb_build_object(\n        \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n    END IF;\n  END LOOP;\n  v_kick := v_kick || v_gone_kick;   -- 154 / F441: (4b)\'s kept, since-unrostered starters\n  v_lock_kick := v_lock_kick || v_gone_kick;   -- 164 / F467: (4b)\'s kept starters, as v_kick\n  IF v_current = p_week THEN\n    v_kick_cur := v_kick;\n    v_lock_kick_cur := v_lock_kick;   -- 164 / F467\n    v_window_cur := v_window;\n  ELSE\n    SELECT * INTO v_window_cur FROM public.schedule_window_internal(v_league.season, v_current, p_at);\n'),
    E'  --     moved whose game had already kicked off is named, and rides into the\n  --     audit row\'s metadata so the league can see exactly what the override\n  --     did that a manager could not have.\n  --     164 / F467: judged per PLAYER — the lock a manager faces since 157 —\n  --     so the record names every player a manager could not have moved\n  --     (165 / F497: that datum is v_kick itself now; 164\'s parallel map\n  --     is folded into it).\n  FOR v_key, v_val IN SELECT * FROM jsonb_each(v_stored) LOOP\n    v_pid := v_val #>> \'{}\';\n    CONTINUE WHEN NOT (v_by_pid ? v_pid);\n    CONTINUE WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(v_ir_spots) s WHERE s ->> \'key\' = v_key);\n    IF (((v_kick -> v_pid ->> \'kickoff_at\') IS NOT NULL\n         AND (v_kick -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at)\n        OR v_gone_kick ? v_pid)   -- 154 / F441: a kept off-roster starter moved or removed is recorded too\n       AND (p_slot_map ->> v_key) IS DISTINCT FROM v_pid THEN\n      v_moved_lock := v_moved_lock || jsonb_build_object(\n        \'player_id\', v_pid, \'name\', v_by_pid -> v_pid ->> \'name\',\n        \'from\', v_key, \'to\', v_seen ->> v_pid,\n        \'kickoff_at\', v_kick -> v_pid ->> \'kickoff_at\',\n        \'datum_arm\', v_kick -> v_pid ->> \'datum_arm\');\n    END IF;\n  END LOOP;\n  FOR v_key, v_val IN SELECT * FROM jsonb_each(p_slot_map) LOOP\n    v_pid := v_val #>> \'{}\';\n    CONTINUE WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(v_ir_spots) s WHERE s ->> \'key\' = v_key);\n    IF (v_kick -> v_pid ->> \'kickoff_at\') IS NOT NULL\n       AND (v_kick -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at\n       AND (v_stored ->> v_key) IS DISTINCT FROM v_pid\n       AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v_moved_lock) m WHERE m ->> \'player_id\' = v_pid) THEN\n      v_moved_lock := v_moved_lock || jsonb_build_object(\n',
    E'  --     moved whose game had already kicked off is named, and rides into the\n  --     audit row\'s metadata so the league can see exactly what the override\n  --     did that a manager could not have.\n  --     164 / F467: judged by v_lock_kick — per PLAYER, the lock a manager\n  --     faces since 157 — so the record names every player a manager\n  --     could not have moved.\n  FOR v_key, v_val IN SELECT * FROM jsonb_each(v_stored) LOOP\n    v_pid := v_val #>> \'{}\';\n    CONTINUE WHEN NOT (v_by_pid ? v_pid);\n    CONTINUE WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(v_ir_spots) s WHERE s ->> \'key\' = v_key);\n    IF (((v_lock_kick -> v_pid ->> \'kickoff_at\') IS NOT NULL\n         AND (v_lock_kick -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at)\n        OR v_gone_kick ? v_pid)   -- 154 / F441: a kept off-roster starter moved or removed is recorded too\n       AND (p_slot_map ->> v_key) IS DISTINCT FROM v_pid THEN\n      v_moved_lock := v_moved_lock || jsonb_build_object(\n        \'player_id\', v_pid, \'name\', v_by_pid -> v_pid ->> \'name\',\n        \'from\', v_key, \'to\', v_seen ->> v_pid,\n        \'kickoff_at\', v_lock_kick -> v_pid ->> \'kickoff_at\',\n        \'datum_arm\', v_lock_kick -> v_pid ->> \'datum_arm\');\n    END IF;\n  END LOOP;\n  FOR v_key, v_val IN SELECT * FROM jsonb_each(p_slot_map) LOOP\n    v_pid := v_val #>> \'{}\';\n    CONTINUE WHEN EXISTS (SELECT 1 FROM jsonb_array_elements(v_ir_spots) s WHERE s ->> \'key\' = v_key);\n    IF (v_lock_kick -> v_pid ->> \'kickoff_at\') IS NOT NULL\n       AND (v_lock_kick -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at\n       AND (v_stored ->> v_key) IS DISTINCT FROM v_pid\n       AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v_moved_lock) m WHERE m ->> \'player_id\' = v_pid) THEN\n      v_moved_lock := v_moved_lock || jsonb_build_object(\n'),
    E'        -- misled, in the permanent record of what the override did.)\n        \'from\', (SELECT e.key FROM jsonb_each(v_stored) e WHERE e.value #>> \'{}\' = v_pid LIMIT 1),\n        \'to\', v_key,\n        \'kickoff_at\', v_kick -> v_pid ->> \'kickoff_at\',\n        \'datum_arm\', v_kick -> v_pid ->> \'datum_arm\');\n    END IF;\n  END LOOP;\n  IF jsonb_array_length(v_moved_lock) > 0 THEN\n',
    E'        -- misled, in the permanent record of what the override did.)\n        \'from\', (SELECT e.key FROM jsonb_each(v_stored) e WHERE e.value #>> \'{}\' = v_pid LIMIT 1),\n        \'to\', v_key,\n        \'kickoff_at\', v_lock_kick -> v_pid ->> \'kickoff_at\',\n        \'datum_arm\', v_lock_kick -> v_pid ->> \'datum_arm\');\n    END IF;\n  END LOOP;\n  IF jsonb_array_length(v_moved_lock) > 0 THEN\n'),
    E'          (SELECT string_agg(x #>> \'{}\', \', \') FROM jsonb_array_elements(v_spot -> \'designations\') x)\n          USING ERRCODE = \'P0001\';\n      END IF;\n      IF (v_kick_cur -> v_pid ->> \'kickoff_at\') IS NOT NULL\n         AND (v_kick_cur -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at THEN\n        v_bypassed := v_bypassed || to_jsonb((\'ir_lock_timing:\' || v_pid)::text);\n      END IF;\n      v_ir_placed := v_ir_placed || jsonb_build_object(\n',
    E'          (SELECT string_agg(x #>> \'{}\', \', \') FROM jsonb_array_elements(v_spot -> \'designations\') x)\n          USING ERRCODE = \'P0001\';\n      END IF;\n      IF (v_lock_kick_cur -> v_pid ->> \'kickoff_at\') IS NOT NULL\n         AND (v_lock_kick_cur -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at THEN\n        v_bypassed := v_bypassed || to_jsonb((\'ir_lock_timing:\' || v_pid)::text);\n      END IF;\n      v_ir_placed := v_ir_placed || jsonb_build_object(\n'),
    E'    IF (v_e ->> \'ir_lock_until_week\') IS NOT NULL AND v_current < (v_e ->> \'ir_lock_until_week\')::int THEN\n      v_bypassed := v_bypassed || to_jsonb((\'ir_restricted_stint:\' || v_pid)::text);\n    END IF;\n    IF (v_kick_cur -> v_pid ->> \'kickoff_at\') IS NOT NULL\n       AND (v_kick_cur -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at THEN\n      v_bypassed := v_bypassed || to_jsonb((\'ir_lock_timing:\' || v_pid)::text);\n    END IF;\n    v_ir_removed := v_ir_removed || jsonb_build_object(\'player_id\', v_pid, \'spot\', v_e ->> \'slot_key\');\n',
    E'    IF (v_e ->> \'ir_lock_until_week\') IS NOT NULL AND v_current < (v_e ->> \'ir_lock_until_week\')::int THEN\n      v_bypassed := v_bypassed || to_jsonb((\'ir_restricted_stint:\' || v_pid)::text);\n    END IF;\n    IF (v_lock_kick_cur -> v_pid ->> \'kickoff_at\') IS NOT NULL\n       AND (v_lock_kick_cur -> v_pid ->> \'kickoff_at\')::timestamptz <= p_at THEN\n      v_bypassed := v_bypassed || to_jsonb((\'ir_lock_timing:\' || v_pid)::text);\n    END IF;\n    v_ir_removed := v_ir_removed || jsonb_build_object(\'player_id\', v_pid, \'spot\', v_e ->> \'slot_key\');\n'),
    E'\n  -- Per-starter kickoff at the injected instant (112\'s datum, E42/§23.3).\n  FOREACH v_pid IN ARRAY v_started LOOP\n    SELECT * INTO v_k FROM public.lineup_player_kickoff_internal(p_league_id, p_season, p_week, v_pid, p_at);   -- 165 / F497: per PLAYER (157), as set_lineup records it — a player who played and was since released / traded keeps his kickoff (D354: a carry can run after a kickoff)\n    v_kick := v_kick || jsonb_build_object(v_pid, jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n  END LOOP;\n',
    E'\n  -- Per-starter kickoff at the injected instant (112\'s datum, E42/§23.3).\n  FOREACH v_pid IN ARRAY v_started LOOP\n    SELECT * INTO v_k FROM public.lineup_kickoff_internal(p_season, p_week, v_by_pid -> v_pid ->> \'nfl_team\', p_at);\n    v_kick := v_kick || jsonb_build_object(v_pid, jsonb_build_object(\n      \'kickoff_at\', v_k.kickoff_at, \'datum_arm\', v_k.datum_arm, \'on_bye\', v_k.on_bye));\n  END LOOP;\n')
$un165$;


-- The pre-165 bodies, side by side with the live ones: each live definition
-- with 165 reversed, renamed into pg_temp. Nothing live is replaced.
do $pre$
begin
  execute replace(pg_temp.un165(pg_temp.un166(pg_get_functiondef('public.commish_edit_lineup_internal(uuid, uuid, integer, jsonb, uuid, timestamptz, text)'::regprocedure))),
                  'FUNCTION public.commish_edit_lineup_internal(', 'FUNCTION pg_temp.edit_pre165(');
  execute replace(pg_temp.un165(pg_get_functiondef('public.lineup_carry_internal(uuid, uuid, integer, integer, timestamptz)'::regprocedure)),
                  'FUNCTION public.lineup_carry_internal(', 'FUNCTION pg_temp.carry_pre165(');
end
$pre$;

-- ---------------------------------------------------------------------------
-- A. Form pins, D137 in the database, the neighbours untouched
-- ---------------------------------------------------------------------------
select is(
  (select string_agg(format('%s:%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE'),
                            has_function_privilege('authenticated', p.oid, 'EXECUTE')), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('commish_edit_lineup_internal', 'lineup_carry_internal')),
  'commish_edit_lineup_internal:f:search_path="":f:f lineup_carry_internal:f:search_path="":f:f',
  'A1 the two replaced bodies: one overload each (signatures unchanged), PLAIN, search_path empty, closed to anon and authenticated');
select ok(
  not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
    where n.nspname = 'public' and a.privilege_type = 'EXECUTE' and a.grantee = 0
      and p.proname in ('commish_edit_lineup_internal', 'lineup_carry_internal')),
  'A2 PUBLIC holds EXECUTE on neither (REVOKEs restated)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un165(pg_temp.un166(pg_temp.un170(p.prosrc)))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('commish_edit_lineup_internal', 'lineup_carry_internal')),
  'commish_edit_lineup_internal=9bcdc00d2a66ad830883de3fca723cdb lineup_carry_internal=e38a18c80dde298b3ca69af93b77dac9',
  'A3 D137: each live body with 165 reversed is its NEWEST definer FILE TEXT (164:1223 / 116:369 — the stored md5 literals pgTAP 112 A4 and 086 A8 pinned before 165)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un166(pg_temp.un170(p.prosrc))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('commish_edit_lineup_internal', 'lineup_carry_internal')),
  'commish_edit_lineup_internal=95d0b4652636948b4499d1e27c3b5d93 lineup_carry_internal=53f4b5d29a2d881e27e07ff27a0fec4c',
  'A4 the two live prosrc md5s — 165 as written (stored literals; 166 reversed innermost — pgTAP 114 A4 pins the editor as 166 wrote it)');
select is(
  (select string_agg(p.proname || ':' || (length(p.prosrc) - length(replace(p.prosrc, 'public.lineup_kickoff_internal(', ''))) / length('public.lineup_kickoff_internal(')
                     || '/' || (length(p.prosrc) - length(replace(p.prosrc, 'public.lineup_player_kickoff_internal(', ''))) / length('public.lineup_player_kickoff_internal(')
                     || '/' || (select count(*) from regexp_matches(p.prosrc, 'v_lock_kick(_cur)? *(:=|->)', 'g')),
                     ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('commish_edit_lineup_internal', 'lineup_carry_internal')),
  'commish_edit_lineup_internal:0/2/0 lineup_carry_internal:0/1/0',
  'A5 both read the per-player datum and never the team datum; the parallel receipt map is folded away (calls: team datum / per-player datum / reads or writes of v_lock_kick or v_lock_kick_cur)');
select is(
  (select count(*)::int from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname not in ('commish_edit_lineup_internal', 'lineup_carry_internal')
     and pg_temp.un165(p.prosrc) <> p.prosrc),
  0,
  'A6 un165 is an identity on every other body in the schema — so the older suites that apply it innermost pin exactly what they pinned (additive, R992)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un166(pg_temp.un169(p.prosrc))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('set_lineup_internal', 'lineup_autopilot_internal', 'lineup_lock_tick', 'lineup_player_kickoff_internal',
                                                 'lineup_played_internal', 'lineup_record_kicked_off_internal', 'lineup_kept_starter_internal',
                                                 'lineup_kickoff_internal', 'commish_edit_lineup', 'league_week_advance', 'team_lineups_one_start_per_week')),
  'commish_edit_lineup=876d323ce50e0b305a29046a8fee0515 league_week_advance=1ea76a893bada31b54ebe1a82f004625 lineup_autopilot_internal=544d32c67abd3f3243ff1bfa568360ad lineup_kept_starter_internal=3f60bb975e57719c0be2de7f4ccdbb12 lineup_kickoff_internal=80b9c63efa3cb5bbef7b79863e9801a7 lineup_lock_tick=bcc10f9a40e99f7a1cf83e1c94f813f0 lineup_played_internal=aa79ff77ba714b19b6740c60202d8476 lineup_player_kickoff_internal=b14949f7f54de384bac2a49efdfd494d lineup_record_kicked_off_internal=9c54a4f3fb38bad956d6386d7748b777 set_lineup_internal=ca3307414057469da7ed5c0af0b29fe6 team_lineups_one_start_per_week=a1fb72fc17941cda5f7ddc0d15226b74',
  'A7 UNTOUCHED (stored literals): set_lineup, autopilot and the tick (157), the played-lock helpers, the kept-start judgment (164), the team datum, the DEFINER door, the week advance and the one-start trigger (166 reversed innermost: 166 replaced the per-player datum, F501)');
select ok(
  obj_description('public.lineup_player_kickoff_internal(uuid, integer, integer, text, timestamptz)'::regprocedure, 'pg_proc')
    like '%since migration 165 (L.D2.19 — F497) by commish_edit_lineup_internal step (6) and lineup_carry_internal%',
  'A8 the per-player datum comment names its new readers (restated by 165)');

-- ---------------------------------------------------------------------------
-- FIXTURE — the 105 / 112 calendar shape (2026 seeds; only the stamps
-- rewritten): WEEK 6 — QA @ QZ Thu 10-16 00:15Z (played, final), QB @ QY Sun
-- 10-18 17:00Z; QF @ QG FLEXED from Sun 10-18 13:00Z to 10-19 00:20Z. Every
-- other week: KC @ BUF one day after its start (week 5: Thu 10-08 04:00Z).
-- SUN = 10-18 16:00Z: after Thursday, before Sunday.
-- ---------------------------------------------------------------------------
update nfl_weeks w
set last_game_ends_at = case when w.week <= 5 then w.starts_at + interval '6 days'
                             when w.week = 6 then '2026-10-20 03:30:00+00'::timestamptz end,
    first_kickoff_at = null
where w.season = 2026;
delete from nfl_games where season = 2026;
insert into nfl_games (id, season, week, home_team, away_team, kickoff_at, status)
select 's-dummy-' || w.week, 2026, w.week, 'KC', 'BUF', w.starts_at + interval '1 day', case when w.week <= 5 then 'final' else 'scheduled' end
from nfl_weeks w where w.season = 2026 and w.week <= 14 and w.week <> 6;
insert into nfl_games (id, season, week, home_team, away_team, kickoff_at, status) values
 ('s-g6a', 2026, 6, 'QA', 'QZ', '2026-10-16 00:15:00+00', 'final'),
 ('s-g6b', 2026, 6, 'QB', 'QY', '2026-10-18 17:00:00+00', 'scheduled'),
 ('s-g6f', 2026, 6, 'QF', 'QG', '2026-10-19 00:20:00+00', 'scheduled');

insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000', ('91130000-0000-4000-8000-00000000000' || i)::uuid,
  'authenticated', 'authenticated', 'pgtap-ek' || i || '@fieldscout.local', 'x', now(),
  '{"provider": "email", "providers": ["email"]}', json_build_object('username', 'ek_user' || i)::jsonb, now(), now()
from generate_series(1, 3) i;

insert into leagues (id, owner_id, name, season, status, team_count, regular_season_weeks, playoff_teams, playoff_start_week,
                     scoring_system_id, scoring_rules_snapshot, lineup_lock, waiver_type, faab_budget, trade_review,
                     settings, roster_settings)
values ('b1130000-0000-4000-8000-000000000001', '91130000-0000-4000-8000-000000000001', 'pgtap-ek-L', 2026, 'in_season', 12, 14, 0, 15,
        (select id from scoring_systems where is_template and name = 'ESPN Standard'),
        (select rules from scoring_systems where is_template and name = 'ESPN Standard'),
        'per_player_kickoff', 'none_fcfs', 100, 'none', '{}'::jsonb,
        '{"starting_slots": [{"key": "qb", "label": "QB", "eligible": ["QB"], "count": 4}], "bench": 8, "ir_slots": [{"key": "ir", "label": "IR", "type": "standard", "eligible_designations": ["OUT", "IR"]}], "swap_spots": 0}'::jsonb);

insert into teams (id, owner_id, name, league_id, status) values
 ('c1130000-0000-4000-8000-000000000001', '91130000-0000-4000-8000-000000000001', 'EK Commish', 'b1130000-0000-4000-8000-000000000001', 'active'),
 ('c1130000-0000-4000-8000-000000000002', '91130000-0000-4000-8000-000000000002', 'EK Tango',   'b1130000-0000-4000-8000-000000000001', 'active'),
 ('c1130000-0000-4000-8000-000000000003', '91130000-0000-4000-8000-000000000003', 'EK Uniform', 'b1130000-0000-4000-8000-000000000001', 'active');
insert into league_members (league_id, user_id, team_id, role, is_placeholder, faab_balance)
select t.league_id, t.owner_id, t.id,
       case when t.owner_id = '91130000-0000-4000-8000-000000000001' then 'commissioner' else 'manager' end, false, 100
from teams t where t.id::text like 'c1130000-%';

insert into league_weeks (league_id, season, week)
select 'b1130000-0000-4000-8000-000000000001', 2026, w from generate_series(1, 14) w;
update league_weeks set status = 'live'              where league_id = 'b1130000-0000-4000-8000-000000000001' and week <= 6;
update league_weeks set status = 'correction_window' where league_id = 'b1130000-0000-4000-8000-000000000001' and week <= 5;
update league_weeks set status = 'final'             where league_id = 'b1130000-0000-4000-8000-000000000001' and week <= 5;

-- Everyone is on the team his note says at the Thursday kickoff; the NFL
-- moves (a trade to QB, releases to no team) are applied after the game.
insert into players (id, full_name, position, team, status) values
 ('s-rel',  'EK Rel (Thu, released)',          'QB', 'QA', 'Active'),
 ('s-trd',  'EK Trd (Thu, traded)',            'QB', 'QA', 'Active'),
 ('s-flx',  'EK Flx (flexed game)',            'QB', 'QF', 'Active'),
 ('s-sun1', 'EK Sun1',                         'QB', 'QB', 'Active'),
 ('s-sun2', 'EK Sun2',                         'QB', 'QB', 'Active'),
 ('s-out',  'EK Out (Thu, released, out)',     'QB', 'QA', 'Out'),
 ('s-past', 'EK Past (week 5, released)',      'QB', 'KC', 'Active'),
 ('s-kc',   'EK KC',                           'QB', 'KC', 'Active'),
 ('s-cut',  'EK Cut (released, never played)', 'QB', null, 'Active'),
 ('u-rel',  'EK URel (Thu, released)',         'QB', 'QA', 'Active'),
 ('u-sun',  'EK USun',                         'QB', 'QB', 'Active');

insert into league_rosters (league_id, team_id, player_id, slot_key)
select 'b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000002', p, case when p in ('s-rel', 's-trd', 's-flx') then 'qb' else 'bn' end
from unnest(array['s-rel', 's-trd', 's-flx', 's-sun1', 's-sun2', 's-out', 's-past', 's-kc', 's-cut']) p;
insert into league_rosters (league_id, team_id, player_id, slot_key) values
 ('b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000003', 'u-rel', 'qb'),
 ('b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000003', 'u-sun', 'bn');
insert into league_player_pool (league_id, player_id, state)
select 'b1130000-0000-4000-8000-000000000001', r.player_id, 'rostered' from league_rosters r where r.league_id = 'b1130000-0000-4000-8000-000000000001';

-- Lineups in 114 shape; each starter carries the kickoff the writer that
-- seated him recorded (Thursday for the Thursday starters; the flexed game
-- old 13:00 instant for EK Flx; the week-5 game for EK Past).
insert into team_lineups (team_id, season, week, slot_map, starters, bench, locked_at) values
 ('c1130000-0000-4000-8000-000000000002', 2026, 6, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx"}'::jsonb,
  '[{"slot": "qb:0", "slot_key": "qb", "label": "QB", "player_id": "s-rel", "position": "QB", "kickoff_at": "2026-10-16T00:15:00+00:00", "flags": []},
    {"slot": "qb:1", "slot_key": "qb", "label": "QB", "player_id": "s-trd", "position": "QB", "kickoff_at": "2026-10-16T00:15:00+00:00", "flags": []},
    {"slot": "qb:2", "slot_key": "qb", "label": "QB", "player_id": "s-flx", "position": "QB", "kickoff_at": "2026-10-18T13:00:00+00:00", "flags": []},
    {"slot": "qb:3", "slot_key": "qb", "label": "QB", "player_id": null, "position": null, "kickoff_at": null, "flags": ["empty"]}]'::jsonb,
  '["s-cut", "s-kc", "s-out", "s-past", "s-sun1", "s-sun2"]'::jsonb, '2026-10-16 00:15:00+00'),
 ('c1130000-0000-4000-8000-000000000002', 2026, 5, '{"qb:0": "s-past"}'::jsonb,
  '[{"slot": "qb:0", "slot_key": "qb", "label": "QB", "player_id": "s-past", "position": "QB", "kickoff_at": "2026-10-08T04:00:00+00:00", "flags": []},
    {"slot": "qb:1", "slot_key": "qb", "label": "QB", "player_id": null, "position": null, "kickoff_at": null, "flags": ["empty"]},
    {"slot": "qb:2", "slot_key": "qb", "label": "QB", "player_id": null, "position": null, "kickoff_at": null, "flags": ["empty"]},
    {"slot": "qb:3", "slot_key": "qb", "label": "QB", "player_id": null, "position": null, "kickoff_at": null, "flags": ["empty"]}]'::jsonb,
  '["s-cut", "s-flx", "s-kc", "s-out", "s-rel", "s-sun1", "s-sun2", "s-trd"]'::jsonb, '2026-10-08 04:00:00+00'),
 ('c1130000-0000-4000-8000-000000000003', 2026, 5, '{"qb:0": "u-rel"}'::jsonb,
  '[{"slot": "qb:0", "slot_key": "qb", "label": "QB", "player_id": "u-rel", "position": "QB", "kickoff_at": null, "flags": ["bye"]}]'::jsonb,
  '["u-sun"]'::jsonb, null);

-- THE THURSDAY STAT LINES (he played): EK Out and EK URel only. EK Rel and
-- EK Trd have NONE — the lineup record alone says they played.
insert into player_stats (player_id, season, week, stat_type, game_id, updated_at)
select p, 2026, 6, 'weekly', 's-g6a', '2026-10-16 03:30:00+00'
from unnest(array['s-out', 'u-rel']) p;

-- THE NFL MOVES, after the games.
update players set team = null where id in ('s-rel', 's-out', 's-past', 'u-rel');
update players set team = 'QB' where id = 's-trd';

-- Post-reset race guard (067): today and tomorrow realtime.messages partitions.
do $part$
declare
  d date;
  part_name text;
begin
  foreach d in array array[current_date, current_date + 1] loop
    part_name := 'messages_' || to_char(d, 'YYYY_MM_DD');
    if not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                   where n.nspname = 'realtime' and c.relname = part_name) then
      execute format('create table realtime.%I partition of realtime.messages for values from (%L) to (%L)',
                     part_name, d::timestamp, (d + 1)::timestamp);
    end if;
  end loop;
end
$part$;

-- A TRIAL runs one statement in a subtransaction that is then rolled back,
-- and returns its document and the league state it left — so the live body
-- and the pre-165 body start from the SAME state.
create function pg_temp.state() returns jsonb language sql as $$
  select jsonb_build_object(
    'rosters', (select jsonb_agg(jsonb_build_array(r.team_id, r.player_id, r.slot_key, r.ir_placed_week, r.ir_lock_until_week) order by r.team_id, r.player_id)
                from league_rosters r where r.league_id = 'b1130000-0000-4000-8000-000000000001'),
    'lineups', (select jsonb_agg(jsonb_build_object('team', tl.team_id, 'week', tl.week, 'slot_map', tl.slot_map, 'starters', tl.starters,
                                                    'bench', tl.bench, 'locked_at', tl.locked_at) order by tl.team_id, tl.week)
                from team_lineups tl join teams t on t.id = tl.team_id where t.league_id = 'b1130000-0000-4000-8000-000000000001'));
$$;
create function pg_temp.trial(p_sql text) returns jsonb language plpgsql as $$
declare
  v_doc   jsonb;
  v_state jsonb;
begin
  begin
    execute p_sql into v_doc;
    v_state := pg_temp.state();
    raise exception 'trial rolled back' using errcode = 'FST01';
  exception when sqlstate 'FST01' then
    null;
  end;
  return jsonb_build_object('doc', v_doc, 'state', v_state);
exception when others then
  return jsonb_build_object('error', sqlerrm, 'sqlstate', sqlstate);
end $$;
create temp table r113 (tag text primary key, r jsonb not null);
create function pg_temp.as_commish() returns void language sql as $$
  select set_config('request.jwt.claims', json_build_object('sub', '91130000-0000-4000-8000-000000000001', 'role', 'authenticated')::text, true);
$$;
select pg_temp.as_commish();

-- One commissioner edit of week p_week (EK Tango) through p_fn at p_at.
create function pg_temp.edit_sql(p_fn text, p_week int, p_map text, p_act int, p_at text) returns text language sql as $$
  select format('select %s(%L::uuid, %L::uuid, %s, %L::jsonb, %L::uuid, %L::timestamptz, null)', p_fn,
                'b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000002', p_week, p_map,
                'a1130000-0000-4000-8000-' || lpad(p_act::text, 12, '0'), p_at)
$$;
-- The edit, then (p_then) the tick one minute later, or the MANAGER setting
-- his lineup five minutes later — the outcome returned beside the edit.
create function pg_temp.edit_then(p_fn text, p_map text, p_then text, p_mgr_map text) returns jsonb language plpgsql as $$
declare
  v_doc jsonb;
  v_out text;
begin
  execute pg_temp.edit_sql(p_fn, 6, p_map, 21, '2026-10-18 16:00:00+00') into v_doc;
  if p_then = 'tick' then
    perform set_config('request.jwt.claims', '', true);
    perform public.lineup_lock_tick('2026-10-18 16:01:00+00', 'b1130000-0000-4000-8000-000000000001');
    v_out := 'ticked';
  else
    perform set_config('request.jwt.claims', json_build_object('sub', '91130000-0000-4000-8000-000000000002', 'role', 'authenticated')::text, true);
    begin
      perform public.set_lineup_internal('b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000002', 6,
                                         p_mgr_map::jsonb, 'a1130000-0000-4000-8000-000000000022', '2026-10-18 16:05:00+00', null);
      v_out := 'accepted';
    exception when others then
      v_out := sqlerrm;
    end;
  end if;
  perform pg_temp.as_commish();
  return jsonb_build_object('edit', v_doc, 'then', v_out);
end $$;

-- Renders a lineup row of the state: player@kickoff[flags],… | locked_at.
create function pg_temp.row_of(p_r jsonb, p_team text, p_week int) returns text language sql as $$
  select (select string_agg(coalesce(s ->> 'player_id', '-') || '@' || coalesce(s ->> 'kickoff_at', '-') || coalesce(s ->> 'flags', ''), ',' order by o)
          from jsonb_array_elements(l -> 'starters') with ordinality x(s, o)
          where s ->> 'player_id' is not null)
         || ' | locked_at ' || coalesce(l ->> 'locked_at', '-')
  from jsonb_array_elements(p_r -> 'state' -> 'lineups') l
  where l ->> 'team' = p_team and (l ->> 'week')::int = p_week
$$;
create function pg_temp.outcome(p_tag text) returns text language sql as $$
  select coalesce((select 'refused: ' || (r ->> 'error') from r113 where tag = p_tag and r ? 'error'),
                  (select 'landed' from r113 where tag = p_tag and r ? 'doc'), 'missing')
$$;

-- ---------------------------------------------------------------------------
-- B. F497 — a commissioner edit that KEEPS the played starters in place
--    (fills the empty qb:3 with EK Sun1): EK Rel (played Thursday, released,
--    no stat line) at qb:0, EK Trd (played Thursday, traded to a Sunday
--    team, no stat line) at qb:1, EK Flx (flexed game) at qb:2.
-- ---------------------------------------------------------------------------
update leagues set settings = '{"allow_illegal_lineups": false}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';
insert into r113 (tag, r)
select 'b1:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 6, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}', 11, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is('live ' || pg_temp.outcome('b1:live') || ' | pre165 ' || pg_temp.outcome('b1:pre'),
  'live landed | pre165 refused: commish_edit_lineup: EK Rel (Thu, released) is on bye for week 6 and allow_illegal_lineups is off — slot "qb:0" is blocked at submit (§7.3.6); bench him, start someone who plays, or turn the setting on',
  'B1 allow_illegal_lineups OFF: a re-save that keeps a starter who played Thursday and was then released where he stands LANDS — before 165 his current team (none) read as a bye and the commissioner was refused (a timing read binding him)');

update leagues set settings = '{}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';
insert into r113 (tag, r)
select 'b2:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 6, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}', 12, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is(
  (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 6) from r113 where tag = 'b2:live'),
  's-rel@2026-10-16T00:15:00+00:00[],s-trd@2026-10-16T00:15:00+00:00[],s-flx@2026-10-19T00:20:00+00:00[],s-sun1@2026-10-18T17:00:00+00:00[] | locked_at 2026-10-16T00:15:00+00:00',
  'B2 the stored record: EK Rel (released) and EK Trd (traded to a Sunday team) keep the Thursday kickoff they PLAYED in, no bye flag, locked_at stays Thursday');
select is(
  (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 6) from r113 where tag = 'b2:pre'),
  's-rel@-["bye"],s-trd@2026-10-18T17:00:00+00:00[],s-flx@2026-10-19T00:20:00+00:00[],s-sun1@2026-10-18T17:00:00+00:00[] | locked_at 2026-10-18T17:00:00+00:00',
  'B3 …where the pre-165 body wrote the r-e1 shape (released: no record, a bye flag) and the r-e4 shape (traded: his new team Sunday kickoff) and moved locked_at to Sunday');
select is(
  (select format('live %s %s | pre165 %s %s', l.r -> 'doc' -> 'locked_players_moved', l.r -> 'doc' -> 'bypassed', p.r -> 'doc' -> 'locked_players_moved', p.r -> 'doc' -> 'bypassed')
   from r113 l, r113 p where l.tag = 'b2:live' and p.tag = 'b2:pre'),
  'live [] [] | pre165 [] []',
  'B4 nobody was moved: the two played starters stayed where they stand, so the receipt names no lock walked past — under both bodies');

insert into r113 (tag, r)
select 'b5:' || f.side,
       pg_temp.trial(format('select pg_temp.edit_then(%L, %L, %L, null)', f.fn, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}', 'tick'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is(
  (select format('live %s || pre165 %s',
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 6) from r113 where tag = 'b5:live'),
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 6) from r113 where tag = 'b5:pre'))),
  'live s-rel@2026-10-16T00:15:00+00:00[],s-trd@2026-10-16T00:15:00+00:00[],s-flx@2026-10-19T00:20:00+00:00[],s-sun1@2026-10-18T17:00:00+00:00[] | locked_at 2026-10-16T00:15:00+00:00'
  || ' || pre165 s-rel@-["bye"],s-trd@2026-10-18T17:00:00+00:00[],s-flx@2026-10-19T00:20:00+00:00[],s-sun1@2026-10-18T17:00:00+00:00[] | locked_at 2026-10-18T17:00:00+00:00',
  'B5 the tick one minute later KEEPS the Thursday records the edit stored (157: a passed real kickoff stays) — and cannot restore the ones the pre-165 body erased');

insert into r113 (tag, r)
select 'b6:' || f.side,
       pg_temp.trial(format('select pg_temp.edit_then(%L, %L, %L, %L)', f.fn, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}', 'manager',
                            '{"qb:0": "s-sun2", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is(
  (select format('live %s | pre165 %s', l.r -> 'doc' ->> 'then', p.r -> 'doc' ->> 'then') from r113 l, r113 p where l.tag = 'b6:live' and p.tag = 'b6:pre'),
  'live set_lineup: slot qb:0 is locked — EK Rel (Thu, released) kicked off at 2026-10-16T00:15:00+00:00 (lineup_record) and a locked slot''s player never moves (§11.2, lineup_lock = per_player_kickoff); every other unlocked slot stays editable | pre165 accepted',
  'B6 THE PLAYED LOCK SURVIVES THE EDIT (r-e1 shape): afterwards his manager cannot bench EK Rel — the lineup record says he played — where after the pre-165 edit the manager benched him in the week he played');
insert into r113 (tag, r)
select 'b7:' || f.side,
       pg_temp.trial(format('select pg_temp.edit_then(%L, %L, %L, %L)', f.fn, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-sun1"}', 'manager',
                            '{"qb:0": "s-rel", "qb:1": "s-sun2", "qb:2": "s-flx", "qb:3": "s-sun1"}'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is(
  (select format('live %s | pre165 %s', l.r -> 'doc' ->> 'then', p.r -> 'doc' ->> 'then') from r113 l, r113 p where l.tag = 'b7:live' and p.tag = 'b7:pre'),
  'live set_lineup: slot qb:1 is locked — EK Trd (Thu, traded) kicked off at 2026-10-16T00:15:00+00:00 (lineup_record) and a locked slot''s player never moves (§11.2, lineup_lock = per_player_kickoff); every other unlocked slot stays editable | pre165 accepted',
  'B7 …and the r-e4 shape: EK Trd (traded to a Sunday team) stays locked for his manager after the edit; after the pre-165 edit his record read Sunday and the manager benched him');

-- ---------------------------------------------------------------------------
-- P. A retroactive fix to a CLOSED past week (week 5, final): EK Past
--    started week 5 for KC and has since been released.
-- ---------------------------------------------------------------------------
update leagues set settings = '{"allow_illegal_lineups": false}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';
insert into r113 (tag, r)
select 'p1:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 5, '{"qb:0": "s-past", "qb:1": "s-kc"}', 13, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is('live ' || pg_temp.outcome('p1:live') || ' | pre165 ' || pg_temp.outcome('p1:pre'),
  'live landed | pre165 refused: commish_edit_lineup: EK Past (week 5, released) is on bye for week 5 and allow_illegal_lineups is off — slot "qb:0" is blocked at submit (§7.3.6); bench him, start someone who plays, or turn the setting on',
  'P1 allow_illegal_lineups OFF: a retroactive week-5 fix that keeps a since-released starter LANDS — before 165 his current team read as a bye and refused it');
update leagues set settings = '{}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';
insert into r113 (tag, r)
select 'p2:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 5, '{"qb:0": "s-past", "qb:1": "s-kc", "ir:0": "s-out"}', 14, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is(
  (select format('live %s || pre165 %s',
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 5) from r113 where tag = 'p2:live'),
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 5) from r113 where tag = 'p2:pre'))),
  'live s-past@2026-10-08T04:00:00+00:00[],s-kc@2026-10-08T04:00:00+00:00[] | locked_at 2026-10-08T04:00:00+00:00'
  || ' || pre165 s-past@-["bye"],s-kc@2026-10-08T04:00:00+00:00[] | locked_at 2026-10-08T04:00:00+00:00',
  'P2 …and the week-5 record of EK Past stays the kickoff he played in (the lineup record), where the pre-165 body erased it and flagged him bye');

-- ---------------------------------------------------------------------------
-- C. The receipts are 164s (the fold) — and only the records differ
-- ---------------------------------------------------------------------------
insert into r113 (tag, r)
select 'c1:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 6, '{"qb:0": "s-trd", "qb:1": "s-sun1", "qb:2": "s-flx", "ir:0": "s-out"}', 15, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
create function pg_temp.receipt(p_tag text) returns text language sql as $$
  select coalesce((select string_agg(format('%s %s->%s %s', m ->> 'player_id', m ->> 'from', coalesce(m ->> 'to', 'bench'), m ->> 'datum_arm'), ', ' order by m ->> 'player_id')
                   from r113, jsonb_array_elements(r -> 'doc' -> 'locked_players_moved') m where tag = p_tag), 'none')
         || ' ' || coalesce((select (r -> 'doc' -> 'bypassed')::text from r113 where tag = p_tag), (select r ->> 'error' from r113 where tag = p_tag))
$$;
select is('live ' || pg_temp.receipt('c1:live') || ' | pre165 ' || pg_temp.receipt('c1:pre'),
  'live s-rel qb:0->bench lineup_record, s-trd qb:1->qb:0 lineup_record ["per_player_kickoff_lock", "ir_lock_timing:s-out"] | pre165 s-rel qb:0->bench lineup_record, s-trd qb:1->qb:0 lineup_record ["per_player_kickoff_lock", "ir_lock_timing:s-out"]',
  'C1 the commissioner can still move played starters (he stands outside the lock): benching EK Rel and moving EK Trd are recorded exactly as 164 recorded them, and the IR timing lock for EK Out is named — one map now, the same receipt');
select is('live ' || pg_temp.receipt('p2:live') || ' | pre165 ' || pg_temp.receipt('p2:pre'),
  'live s-kc ->qb:1 nfl_games ["past_week", "closed_week:final", "per_player_kickoff_lock", "ir_lock_timing:s-out"] | pre165 s-kc ->qb:1 nfl_games ["past_week", "closed_week:final", "per_player_kickoff_lock", "ir_lock_timing:s-out"]',
  'C2 …and on a PAST week (the current-week map v_kick_cur feeds the IR timing receipt): the same receipt under both bodies');
select is(
  (select string_agg(x.tag || '=' || (x.a = x.b)::text, ' ' order by x.tag)
   from (select l.tag, l.r -> 'state' #- '{lineups}' as a, p.r -> 'state' #- '{lineups}' as b from r113 l join r113 p on p.tag = replace(l.tag, ':live', ':pre')
         where l.tag in ('b2:live', 'p2:live', 'c1:live')) x)
  || ' | ' ||
  (select string_agg(x.tag || '=' || (x.a = x.b)::text, ' ' order by x.tag)
   from (select l.tag,
                (select jsonb_agg(e - 'starters' - 'locked_at' order by e ->> 'team', e ->> 'week') from jsonb_array_elements(l.r -> 'state' -> 'lineups') e) as a,
                (select jsonb_agg(e - 'starters' - 'locked_at' order by e ->> 'team', e ->> 'week') from jsonb_array_elements(p.r -> 'state' -> 'lineups') e) as b
         from r113 l join r113 p on p.tag = replace(l.tag, ':live', ':pre') where l.tag in ('b2:live', 'p2:live', 'c1:live')) x)
  || ' | ' ||
  (select string_agg(x.tag || '=' || (x.a = x.b)::text, ' ' order by x.tag)
   from (select l.tag, l.r -> 'state' -> 'lineups' as a, p.r -> 'state' -> 'lineups' as b from r113 l join r113 p on p.tag = replace(l.tag, ':live', ':pre')
         where l.tag in ('b2:live', 'p2:live', 'c1:live')) x),
  'b2:live=true c1:live=true p2:live=true | b2:live=true c1:live=true p2:live=true | b2:live=false c1:live=false p2:live=false',
  'C3 ONLY THE RECORDS CHANGED: the rosters (IR placements included), and every lineup slot map and bench, are what the pre-165 body writes; the lineups differ only in starters[] records and locked_at');

-- ---------------------------------------------------------------------------
-- D. lineup_carry_internal — identical at week open; per player mid-week
-- ---------------------------------------------------------------------------
insert into r113 (tag, r)
select 'd1:' || f.side,
       pg_temp.trial(format('select %s(%L::uuid, %L::uuid, 2026, 7, %L::timestamptz)', f.fn,
                            'b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000002', '2026-10-21 04:00:00+00'))
from (values ('live', 'public.lineup_carry_internal'), ('pre', 'pg_temp.carry_pre165')) f(side, fn);
select ok(
  (select l.r = p.r from r113 l, r113 p where l.tag = 'd1:live' and p.tag = 'd1:pre')
  and (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000002', 7) from r113 where tag = 'd1:live') is not null
  and (select r -> 'doc' ->> 'carried_from_week' from r113 where tag = 'd1:live') = '6',
  'D1 the carry at WEEK OPEN (week 7, before any kickoff of the week): the row it writes and its document are identical under both bodies (the played arm cannot fire before a kickoff)');
insert into r113 (tag, r)
select 'd2:' || f.side,
       pg_temp.trial(format('select %s(%L::uuid, %L::uuid, 2026, 6, %L::timestamptz)', f.fn,
                            'b1130000-0000-4000-8000-000000000001', 'c1130000-0000-4000-8000-000000000003', '2026-10-18 16:00:00+00'))
from (values ('live', 'public.lineup_carry_internal'), ('pre', 'pg_temp.carry_pre165')) f(side, fn);
select is(
  (select format('live %s || pre165 %s',
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000003', 6) from r113 where tag = 'd2:live'),
                 (select pg_temp.row_of(r, 'c1130000-0000-4000-8000-000000000003', 6) from r113 where tag = 'd2:pre'))),
  'live u-rel@2026-10-16T00:15:00+00:00[] | locked_at 2026-10-16T00:15:00+00:00 || pre165 u-rel@-["bye"] | locked_at -',
  'D2 a MID-WEEK carry (the tick materializing a seat, D354): EK URel, who played Thursday (stat line) and was then released, is carried with the Thursday kickoff he played in — the pre-165 carry recorded him as a bye with no lock instant');

-- ---------------------------------------------------------------------------
-- E. Controls
-- ---------------------------------------------------------------------------
select is(
  (select format('%s | %s',
     (select string_agg(s ->> 'player_id' || '@' || (s ->> 'kickoff_at'), ',' order by s ->> 'player_id')
      from r113, jsonb_array_elements(r -> 'doc' -> 'starters') s where tag = 'b2:live' and s ->> 'player_id' in ('s-sun1', 's-flx')),
     (select string_agg(s ->> 'player_id' || '@' || (s ->> 'kickoff_at'), ',' order by s ->> 'player_id')
      from r113, jsonb_array_elements(r -> 'doc' -> 'starters') s where tag = 'b2:pre' and s ->> 'player_id' in ('s-sun1', 's-flx')))),
  's-flx@2026-10-19T00:20:00+00:00,s-sun1@2026-10-18T17:00:00+00:00 | s-flx@2026-10-19T00:20:00+00:00,s-sun1@2026-10-18T17:00:00+00:00',
  'E1 CONTROL: a player whose game is still ahead (EK Sun1) reads his team kickoff, and a FLEXED game still moves the record from its old 13:00 instant (E42) — the same under both bodies');
update leagues set settings = '{"allow_illegal_lineups": false}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';
insert into r113 (tag, r)
select 'e2:' || f.side,
       pg_temp.trial(pg_temp.edit_sql(f.fn, 6, '{"qb:0": "s-rel", "qb:1": "s-trd", "qb:2": "s-flx", "qb:3": "s-cut"}', 16, '2026-10-18 16:00:00+00'))
from (values ('live', 'public.commish_edit_lineup_internal'), ('pre', 'pg_temp.edit_pre165')) f(side, fn);
select is('live ' || pg_temp.outcome('e2:live') || ' | pre165 ' || split_part(pg_temp.outcome('e2:pre'), ' is on bye', 1),
  'live refused: commish_edit_lineup: EK Cut (released, never played) is on bye for week 6 and allow_illegal_lineups is off — slot "qb:3" is blocked at submit (§7.3.6); bench him, start someone who plays, or turn the setting on | pre165 refused: commish_edit_lineup: EK Rel (Thu, released)',
  'E2 CONTROL: a player released BEFORE he played is still a bye — starting him with the setting off is refused by name (a validity rule, it binds the commissioner); the pre-165 body refused this map earlier, at EK Rel');
update leagues set settings = '{}'::jsonb where id = 'b1130000-0000-4000-8000-000000000001';

select * from finish();
rollback;
