-- ============================================================================
-- 116 — receipts for the draft-room controls (migration 168; M6 L.E1.29;
--       F40, F45; spec §8.7, §10.3, §12.12; PROGRESS D441, D336, D449)
-- ============================================================================
-- What this file proves, per verb (the task's four cells), over REAL calls:
--   change   ⇒ exactly ONE commissioner_actions row (actor, type, target,
--              before / after pinned as stored literals where they carry the
--              pick, the price, the clock, the order, the budget);
--   no-op    ⇒ none (the verb's own early return, a replay, or the seam's
--              by-value detection — the same timer / order / pick again);
--   mock     ⇒ none (a league-attached mock the commissioner launched, and a
--              standalone one), whether the verb runs on it or refuses it;
--   manager  ⇒ 42501, unchanged, and nothing written.
-- Plus: F45 (a start names its placeholder seats), the system paths (the
-- tick's create / start write none), the reason normalised and never
-- refused, the chat posts unchanged, D137 in the database (pg_temp.un168
-- reverses 168 to each newest definer's file text), and the held lock on
-- draft_undo / draft_force_pick re-measured (< 50 ms, §8.3; the 060 K shape).
--
-- Worlds (all fabricated or started inside this rolled-back transaction):
--   LS b116…01  snake, REAL draft_create + draft_start by u1; u2 manages t2;
--               t3–t7 placeholder rows (user NULL), t8 NO member row
--   LA b116…02  auction, fabricated live in the NOMINATING phase; u1 t1, u2 t2;
--               one won pick (t3, $7)
--   LT b116…03  snake, scheduled — the tick path (p_require_commish FALSE)
--   LH b116…04  snake, fabricated live — the held-lock re-measure
--   M  e116…05  a live snake MOCK in LS launched by u1 (league-attached)
--   S  e116…06  a live STANDALONE mock (league NULL) launched by u4
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(121);

-- pg_temp.un168 — 168's substitutions reversed (generated by derive_168.py
-- with the migration; each replacement text is unique to its body, so the
-- order does not matter). Applied to a live prosrc it yields the source.
create function pg_temp.un168(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$    v_posted := TRUE;
  END IF;

  -- 168/L.E1.29 (F40) — THE RECEIPT, on the commissioner path only (a
  -- manager — the commissioner included — toggling his OWN seat is not an
  -- override). The re-set-the-current-value no-op returned above; v_seat is
  -- the row as read (the UPDATE returns nothing into it).
  IF NOT v_is_self THEN
    PERFORM public.draft_commish_receipt_internal(
      p_league_id, FALSE, 'set_team_autodraft', 'set_autodraft', 'team',
      p_team_id::text, p_reason,
      jsonb_build_object('autodraft', COALESCE(v_seat.is_autodraft, FALSE)),
      jsonb_build_object('autodraft', p_on),
      jsonb_build_object(
        'draft_id', v_draft.id,
        'team_name', (SELECT t.name FROM public.teams t WHERE t.id = p_team_id),
        'affected_team_ids', jsonb_build_array(p_team_id)),
      p_team_id);
  END IF;
$r$, $o$    v_posted := TRUE;
  END IF;
$o$);  -- set_team_autodraft
  s := replace(s, $r$  RETURNING * INTO v_draft;

  -- 168/L.E1.29 (F40) — THE RECEIPT, on the commissioner's create only (the
  -- tick and draft_start's create-if-absent pass FALSE — no receipt; a start
  -- writes its own). The existing-draft no-op returned above.
  IF p_require_commish THEN
    PERFORM public.draft_commish_receipt_internal(
      p_league_id, v_draft.is_mock, 'draft_create', 'draft_create', 'draft',
      v_draft.id::text, NULL,
      NULL,
      jsonb_build_object('status', v_draft.status, 'draft_type', v_draft.draft_type,
                         'total_rounds', v_draft.total_rounds),
      jsonb_build_object('draft_id', v_draft.id));
  END IF;

  RETURN jsonb_build_object('draft', to_jsonb(v_draft), 'created', TRUE);$r$, $o$  RETURNING * INTO v_draft;

  RETURN jsonb_build_object('draft', to_jsonb(v_draft), 'created', TRUE);$o$);  -- draft_create_internal
  s := replace(s, $r$  UPDATE public.leagues
  SET status = 'drafting', updated_at = now()
  WHERE id = p_league_id;

  -- 168/L.E1.29 (F40, F45) — THE RECEIPT, on the commissioner's start only
  -- (the tick's auto-start is a system act: no actor, no row — §10.3). It
  -- NAMES the seats that start with no manager (they autopick, D93) — the
  -- D339 predicate: no league_members row for the team with a user. `before`
  -- is 'scheduled' because the check above refuses anything else; the
  -- double-click no-op returned above.
  IF p_require_commish THEN
    PERFORM public.draft_commish_receipt_internal(
      p_league_id, v_draft.is_mock, 'draft_start', 'draft_start', 'draft',
      v_draft.id::text, NULL,
      jsonb_build_object('status', 'scheduled'),
      jsonb_build_object(
        'status', v_draft.status, 'draft_type', v_draft.draft_type,
        'draft_order', v_draft.draft_order, 'nomination_order', v_draft.nomination_order,
        'placeholder_team_ids', (SELECT COALESCE(jsonb_agg(t.id ORDER BY t.id), '[]'::jsonb)
         FROM public.teams t
         WHERE t.league_id = p_league_id AND t.status <> 'retired'
           AND NOT EXISTS (SELECT 1 FROM public.league_members m
                           WHERE m.team_id = t.id AND m.user_id IS NOT NULL))),
      jsonb_build_object(
        'draft_id', v_draft.id, 'season', v_league.season,
        'affected_team_ids', (SELECT COALESCE(jsonb_agg(t.id ORDER BY t.id), '[]'::jsonb)
         FROM public.teams t
         WHERE t.league_id = p_league_id AND t.status <> 'retired'
           AND NOT EXISTS (SELECT 1 FROM public.league_members m
                           WHERE m.team_id = t.id AND m.user_id IS NOT NULL))));
  END IF;

  RETURN jsonb_build_object('draft', to_jsonb(v_draft), 'started', TRUE);$r$, $o$  UPDATE public.leagues
  SET status = 'drafting', updated_at = now()
  WHERE id = p_league_id;

  RETURN jsonb_build_object('draft', to_jsonb(v_draft), 'started', TRUE);$o$);  -- draft_start_internal
  s := replace(s, $r$  GET DIAGNOSTICS v_faab_reseeded = ROW_COUNT;

  -- 168/L.E1.29 (F40) — THE RECEIPT (a reset always returns a started draft
  -- to scheduled — an unstarted one is refused above).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_reset', 'draft_reset', 'draft',
    p_draft_id::text, p_reason, v_before,
    jsonb_build_object('status', v_draft.status,
                       'current_pick_number', v_draft.current_pick_number),
    jsonb_build_object(
      'draft_id', p_draft_id, 'picks_cleared', v_undone,
      'faab_reseeded_seats', v_faab_reseeded));

  RETURN jsonb_build_object($r$, $o$  GET DIAGNOSTICS v_faab_reseeded = ROW_COUNT;

  RETURN jsonb_build_object($o$);  -- draft_reset
  s := replace(s, $r$  -- 168/L.E1.29 (F40): the board as it stands, for the receipt.
  v_before := jsonb_build_object('status', v_draft.status,
                                 'current_pick_number', v_draft.current_pick_number);

  -- Soft-undo every live pick (§12.4 audit trail; pool return is the
  -- partial index).
$r$, $o$  -- Soft-undo every live pick (§12.4 audit trail; pool return is the
  -- partial index).
$o$);  -- draft_reset
  s := replace(s, $r$  v_faab_reseeded INTEGER;  -- 147 / F412
  v_before JSONB;           -- 168/L.E1.29: the board before the reset
BEGIN$r$, $o$  v_faab_reseeded INTEGER;  -- 147 / F412
BEGIN$o$);  -- draft_reset
  s := replace(s, $r$                       || ' void, no money moved).'
                  ELSE '' END,
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT (ending always changes the status — a
  -- complete draft is refused above).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_end', 'draft_end', 'draft',
    p_draft_id::text, p_reason, v_before,
    jsonb_build_object('status', v_draft.status),
    jsonb_build_object(
      'draft_id', p_draft_id, 'rostered', v_filled,
      'unfilled_slots', v_unfilled, 'voided_bids', v_voided));
$r$, $o$                       || ' void, no money moved).'
                  ELSE '' END,
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_end
  s := replace(s, $r$  -- 168/L.E1.29 (F40): the status as it stands, for the receipt.
  v_before := jsonb_build_object('status', v_draft.status);

  v_voided := public.draft_void_nomination_internal(p_draft_id);

  -- (3b)$r$, $o$  v_voided := public.draft_void_nomination_internal(p_draft_id);

  -- (3b)$o$);  -- draft_end
  s := replace(s, $r$  v_filled   INTEGER;
  v_before   JSONB;  -- 168/L.E1.29: the board's status before the end
BEGIN$r$, $o$  v_filled   INTEGER;
BEGIN$o$);  -- draft_end
  s := replace(s, $r$          || ' nominates again when the draft resumes.',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT: the nomination that came off the block
  -- (the no-nomination call is refused above).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_cancel_nomination', 'draft_cancel_nomination', 'draft',
    p_draft_id::text, p_reason,
    jsonb_build_object('nomination', jsonb_build_object(
      'player_id', v_player, 'high_bid', v_high_bid,
      'team_id', v_draft.on_clock_team_id)),
    jsonb_build_object('nomination', NULL::jsonb),
    jsonb_build_object(
      'draft_id', p_draft_id, 'nomination_seq', v_draft.current_pick_number,
      'voided_bids', v_voided,
      'affected_team_ids', jsonb_build_array(v_draft.on_clock_team_id)));
$r$, $o$          || ' nominates again when the draft resumes.',
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_cancel_nomination
  s := replace(s, $r$    (p_draft_id, v_draft.league_id, p_team_id, p_delta, v_after, p_action_id, v_result);

  -- 168/L.E1.29 (F40) — THE RECEIPT: the team's budget adjustment before and
  -- after (a zero delta is refused above; a replay returned above).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_adjust_budget', 'draft_adjust_budget', 'team',
    p_team_id::text, p_reason,
    jsonb_build_object('budget_adjustment', v_before),
    jsonb_build_object('budget_adjustment', v_after),
    jsonb_build_object(
      'draft_id', p_draft_id, 'team_name', v_team_name, 'delta', p_delta,
      'remaining', v_remaining, 'open_slots', v_open, 'max_bid', v_max_bid,
      'action_id', p_action_id,
      'affected_team_ids', jsonb_build_array(p_team_id)));
$r$, $o$    (p_draft_id, v_draft.league_id, p_team_id, p_delta, v_after, p_action_id, v_result);
$o$);  -- draft_adjust_budget
  s := replace(s, $r$          || ' (now $' || v_remaining || ' for ' || v_open || ' open spots).',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT: the won pick and its price, live before,
  -- reversed after (v_pick is the row as read — the UPDATE above returns
  -- nothing into it).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_reverse_won_bid', 'draft_reverse_bid', 'draft_pick',
    p_pick_id::text, p_reason,
    jsonb_build_object('pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
                       'player_id', v_pick.player_id, 'price', v_pick.price,
                       'undone', v_pick.is_undone),
    jsonb_build_object('pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
                       'player_id', v_pick.player_id, 'price', v_pick.price,
                       'undone', TRUE),
    jsonb_build_object(
      'draft_id', p_draft_id, 'refunded', v_pick.price,
      'remaining', v_remaining, 'open_slots', v_open,
      'affected_team_ids', jsonb_build_array(v_pick.team_id)));
$r$, $o$          || ' (now $' || v_remaining || ' for ' || v_open || ' open spots).',
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_reverse_won_bid
  s := replace(s, $r$                 || ' — remaining picks follow the new order.'
          END,
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT; the same order again is a no-op, and a
  -- mock (the launcher's own order edit) writes none — both in the seam.
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_set_order', 'draft_set_order', 'draft',
    p_draft_id::text, p_reason, v_before, jsonb_build_object(
    'draft_order', v_draft.draft_order, 'nomination_order', v_draft.nomination_order,
    'on_clock_team_id', v_draft.on_clock_team_id),
    jsonb_build_object('draft_id', p_draft_id));
$r$, $o$                 || ' — remaining picks follow the new order.'
          END,
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_set_order
  s := replace(s, $r$            || ' — the rotation follows the new order from the next nomination.',
            'draft:' || p_draft_id::text, TRUE);

    -- 168/L.E1.29 (F40) — THE RECEIPT; the same order again is a no-op, and a
    -- mock (the launcher's own order edit) writes none — both in the seam.
    PERFORM public.draft_commish_receipt_internal(
      v_draft.league_id, v_draft.is_mock, 'draft_set_order', 'draft_set_order', 'draft',
      p_draft_id::text, p_reason, v_before, jsonb_build_object(
      'draft_order', v_draft.draft_order, 'nomination_order', v_draft.nomination_order,
      'on_clock_team_id', v_draft.on_clock_team_id),
      jsonb_build_object('draft_id', p_draft_id));
$r$, $o$            || ' — the rotation follows the new order from the next nomination.',
            'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_set_order
  s := replace(s, $r$  v_new_order := to_jsonb(p_order);
  -- 168/L.E1.29 (F40): the order as it stands, for the receipt.
  v_before := jsonb_build_object(
    'draft_order', v_draft.draft_order, 'nomination_order', v_draft.nomination_order,
    'on_clock_team_id', v_draft.on_clock_team_id);
$r$, $o$  v_new_order := to_jsonb(p_order);
$o$);  -- draft_set_order
  s := replace(s, $r$  v_new_onclock UUID;
  v_before     JSONB;  -- 168/L.E1.29: the order before the edit
BEGIN$r$, $o$  v_new_onclock UUID;
BEGIN$o$);  -- draft_set_order
  s := replace(s, $r$          || ': ' || v_player_name || '.',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT: the pick the commissioner made for the
  -- team on the clock (a replay returned above and writes none).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_force_pick', 'draft_force_pick', 'draft_pick',
    v_result->'pick'->>'id', p_reason,
    jsonb_build_object('pick_number', v_draft.current_pick_number,
                       'team_id', v_draft.on_clock_team_id, 'player_id', NULL::text),
    jsonb_build_object('pick_number', v_result->'pick'->'pick_number',
                       'team_id', v_result->'pick'->'team_id', 'player_id', p_player_id),
    jsonb_build_object(
      'draft_id', p_draft_id, 'for_team_id', v_draft.on_clock_team_id,
      'affected_team_ids', jsonb_build_array(v_draft.on_clock_team_id)));

  RETURN v_result;$r$, $o$          || ': ' || v_player_name || '.',
          'draft:' || p_draft_id::text, TRUE);

  RETURN v_result;$o$);  -- draft_force_pick
  s := replace(s, $r$      PERFORM public.draft_award_nomination_internal(p_draft_id);
      SELECT d.* INTO v_draft FROM public.drafts d WHERE d.id = p_draft_id;
    END IF;

    -- 168/L.E1.29 (F40) — THE RECEIPT: the nomination the commissioner made
    -- for the team on the clock. `before` is no nomination because the phase
    -- check above refuses a live one; a replay returned above and writes none.
    PERFORM public.draft_commish_receipt_internal(
      v_draft.league_id, v_draft.is_mock, 'draft_force_pick', 'draft_force_pick', 'draft',
      p_draft_id::text, p_reason,
      jsonb_build_object('nomination_seq', v_bid.nomination_seq, 'nomination', NULL::jsonb),
      jsonb_build_object('nomination_seq', v_bid.nomination_seq,
                         'nomination', jsonb_build_object(
                           'player_id', p_player_id, 'team_id', v_bid.team_id,
                           'opening_bid', v_nom_floor)),
      jsonb_build_object(
        'draft_id', p_draft_id, 'uncontested', v_uncontested,
        'for_team_id', v_bid.team_id,
        'affected_team_ids', jsonb_build_array(v_bid.team_id)));
$r$, $o$      PERFORM public.draft_award_nomination_internal(p_draft_id);
      SELECT d.* INTO v_draft FROM public.drafts d WHERE d.id = p_draft_id;
    END IF;
$o$);  -- draft_force_pick
  s := replace(s, $r$                  THEN ' at $' || v_price_in ELSE '' END || '.',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT (a move always changes the team — the
  -- same-team call is refused above).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_move_player', 'draft_move_player', 'draft_pick',
    v_pick.id::text, p_reason, v_before, jsonb_build_object(
    'pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
    'player_id', v_pick.player_id, 'price', v_pick.price),
    jsonb_build_object(
      'draft_id', p_draft_id,
      'affected_team_ids', jsonb_build_array(p_from_team, p_to_team)));
$r$, $o$                  THEN ' at $' || v_price_in ELSE '' END || '.',
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_move_player
  s := replace(s, $r$  -- 168/L.E1.29 (F40): the pick as it stands, for the receipt.
  v_before := jsonb_build_object(
    'pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
    'player_id', v_pick.player_id, 'price', v_pick.price);

  UPDATE public.draft_picks
  SET team_id = p_to_team,
$r$, $o$  UPDATE public.draft_picks
  SET team_id = p_to_team,
$o$);  -- draft_move_player
  s := replace(s, $r$  v_max_bid      INTEGER;
  v_before       JSONB;  -- 168/L.E1.29: the pick before the move
BEGIN$r$, $o$  v_max_bid      INTEGER;
BEGIN$o$);  -- draft_move_player
  s := replace(s, $r$  VALUES (v_draft.league_id, auth.uid(), v_msg,
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT; an edit that leaves team, player and
  -- price as they were is a no-op (detected by value — the post stands).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_reassign_pick', 'draft_reassign', 'draft_pick',
    p_pick_id::text, p_reason, v_before, jsonb_build_object(
    'pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
    'player_id', v_pick.player_id, 'price', v_pick.price),
    jsonb_build_object(
      'draft_id', p_draft_id,
      'affected_team_ids', CASE WHEN v_old_team = v_pick.team_id
                                THEN jsonb_build_array(v_pick.team_id)
                                ELSE jsonb_build_array(v_old_team, v_pick.team_id) END));
$r$, $o$  VALUES (v_draft.league_id, auth.uid(), v_msg,
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_reassign_pick
  s := replace(s, $r$  -- 168/L.E1.29 (F40): the pick as it stands, for the receipt.
  v_before := jsonb_build_object(
    'pick_number', v_pick.pick_number, 'team_id', v_pick.team_id,
    'player_id', v_pick.player_id, 'price', v_pick.price);

  UPDATE public.draft_picks
  SET team_id   = v_new_team,
$r$, $o$  UPDATE public.draft_picks
  SET team_id   = v_new_team,
$o$);  -- draft_reassign_pick
  s := replace(s, $r$  v_max_bid       INTEGER;
  v_before        JSONB;  -- 168/L.E1.29: the pick before the edit
BEGIN$r$, $o$  v_max_bid       INTEGER;
BEGIN$o$);  -- draft_reassign_pick
  s := replace(s, $r$          END || v_nom_note,
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT (an undo always reverts >= 1 pick — the
  -- refusals above end every other path).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_undo', 'draft_undo', 'draft',
    p_draft_id::text, p_reason, v_before,
    jsonb_build_object(
      'last_live_pick',   v_to,
      'on_clock_team_id', v_draft.on_clock_team_id,
      'picks',            '[]'::jsonb),
    jsonb_build_object(
      'draft_id', p_draft_id, 'undone_count', v_undone,
      'rewound_to_pick', v_first, 'voided_bids', v_void_live + v_void_past,
      'affected_team_ids', (SELECT COALESCE(jsonb_agg(DISTINCT x->'team_id'), '[]'::jsonb)
                            FROM jsonb_array_elements(v_before->'picks') x)));
$r$, $o$          END || v_nom_note,
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_undo
  s := replace(s, $r$  -- 168/L.E1.29 (F40): the picks about to be reverted, for the receipt.
  SELECT jsonb_build_object(
           'last_live_pick',   v_max_live,
           'on_clock_team_id', v_draft.on_clock_team_id,
           'picks', COALESCE(jsonb_agg(jsonb_build_object(
                      'pick_number', p.pick_number, 'team_id', p.team_id,
                      'player_id', p.player_id, 'price', p.price)
                      ORDER BY p.pick_number), '[]'::jsonb))
    INTO v_before
  FROM public.draft_picks p
  WHERE p.draft_id = p_draft_id AND p.is_undone = FALSE AND p.pick_number > v_to;

  -- E4: soft-undo everything after pick v_to. Pool return is the partial
$r$, $o$  -- E4: soft-undo everything after pick v_to. Pool return is the partial
$o$);  -- draft_undo
  s := replace(s, $r$  v_nom_note   TEXT := '';
  v_before     JSONB;  -- 168/L.E1.29: the picks this undo reverts
BEGIN$r$, $o$  v_nom_note   TEXT := '';
BEGIN$o$);  -- draft_undo
  s := replace(s, $r$          ' (applies to upcoming picks).',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT; the same timer again is a no-op
  -- (detected by value in the seam — the post above stands, as before).
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_set_clock', 'draft_set_clock', 'draft',
    p_draft_id::text, p_reason, v_before, jsonb_build_object(
    'pick_timer_seconds',         v_draft.config->'pick_timer_seconds',
    'auction_nomination_seconds', v_draft.config->'auction_nomination_seconds',
    'auction_bid_seconds',        v_draft.config->'auction_bid_seconds',
    'auction_anti_snipe_seconds', v_draft.config->'auction_anti_snipe_seconds'),
    jsonb_build_object('draft_id', p_draft_id));
$r$, $o$          ' (applies to upcoming picks).',
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_set_clock
  s := replace(s, $r$            || ' (applies to upcoming nominations).',
            'draft:' || p_draft_id::text, TRUE);

    -- 168/L.E1.29 (F40) — THE RECEIPT; the same timers again is a no-op
    -- (detected by value in the seam — the post above stands, as before).
    PERFORM public.draft_commish_receipt_internal(
      v_draft.league_id, v_draft.is_mock, 'draft_set_clock', 'draft_set_clock', 'draft',
      p_draft_id::text, p_reason, v_before, jsonb_build_object(
      'pick_timer_seconds',         v_draft.config->'pick_timer_seconds',
      'auction_nomination_seconds', v_draft.config->'auction_nomination_seconds',
      'auction_bid_seconds',        v_draft.config->'auction_bid_seconds',
      'auction_anti_snipe_seconds', v_draft.config->'auction_anti_snipe_seconds'),
      jsonb_build_object('draft_id', p_draft_id));
$r$, $o$            || ' (applies to upcoming nominations).',
            'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_set_clock
  s := replace(s, $r$  PERFORM public.draft_auction_pause_gate_internal(v_draft, 'draft_set_clock');

  -- 168/L.E1.29 (F40): the timers as they stand, for the receipt's before.
  v_before := jsonb_build_object(
    'pick_timer_seconds',         v_draft.config->'pick_timer_seconds',
    'auction_nomination_seconds', v_draft.config->'auction_nomination_seconds',
    'auction_bid_seconds',        v_draft.config->'auction_bid_seconds',
    'auction_anti_snipe_seconds', v_draft.config->'auction_anti_snipe_seconds');
$r$, $o$  PERFORM public.draft_auction_pause_gate_internal(v_draft, 'draft_set_clock');
$o$);  -- draft_set_clock
  s := replace(s, $r$  v_parts TEXT[] := ARRAY[]::TEXT[];
  v_before JSONB;  -- 168/L.E1.29: the four timers before the edit
BEGIN$r$, $o$  v_parts TEXT[] := ARRAY[]::TEXT[];
BEGIN$o$);  -- draft_set_clock
  s := replace(s, $r$          'Draft resumed by ' || public.draft_actor_name() || '.',
          'draft:' || p_draft_id::text, TRUE);

  -- 168/L.E1.29 (F40) — THE RECEIPT. `before` is 'paused' because the gate
  -- above admits nothing else; the resume-of-a-live-draft no-op returned above.
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_resume', 'draft_resume', 'draft',
    p_draft_id::text, p_reason,
    jsonb_build_object('status', 'paused'),
    jsonb_build_object('status', v_draft.status),
    jsonb_build_object('draft_id', p_draft_id));
$r$, $o$          'Draft resumed by ' || public.draft_actor_name() || '.',
          'draft:' || p_draft_id::text, TRUE);
$o$);  -- draft_resume
  s := replace(s, $r$  v_result := public.draft_pause_internal(
    p_draft_id, auth.uid(),
    'Draft paused by ' || public.draft_actor_name() || '.');

  -- 168/L.E1.29 (F40) — THE RECEIPT, after the state write and the post; a
  -- mock writes none (the seam's own arm). The double-tap no-op returned above.
  PERFORM public.draft_commish_receipt_internal(
    v_draft.league_id, v_draft.is_mock, 'draft_pause', 'draft_pause', 'draft',
    p_draft_id::text, p_reason,
    jsonb_build_object('status', v_draft.status),
    jsonb_build_object('status', v_result->'draft'->>'status'),
    jsonb_build_object('draft_id', p_draft_id));

  RETURN v_result;
END;$r$, $o$  RETURN public.draft_pause_internal(
    p_draft_id, auth.uid(),
    'Draft paused by ' || public.draft_actor_name() || '.');
END;$o$);  -- draft_pause
  s := replace(s, $r$DECLARE
  v_draft public.drafts;
  v_result JSONB;  -- 168/L.E1.29: the pause's result, held for the receipt
BEGIN$r$, $o$DECLARE
  v_draft public.drafts;
BEGIN$o$);  -- draft_pause
  return s;
end
$un$;

-- ---------------------------------------------------------------------------
-- A. Form, and D137 in the database
-- ---------------------------------------------------------------------------
select is(
  (select format('%s:%s:%s:%s:%s', p.prosecdef, array_to_string(p.proconfig, ','),
                 has_function_privilege('anon', p.oid, 'EXECUTE'),
                 has_function_privilege('authenticated', p.oid, 'EXECUTE'),
                 exists (select 1 from aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
                         where a.privilege_type = 'EXECUTE' and a.grantee = 0))
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'draft_commish_receipt_internal'),
  'f:search_path="":f:f:f',
  'A1 the one receipt seam is PLAIN, search_path empty, and closed to anon, authenticated and PUBLIC (a seam, not a door)');
select is(
  (select string_agg(format('%s:%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE'),
                            has_function_privilege('authenticated', p.oid, 'EXECUTE')), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'draft_pause', 'draft_resume', 'draft_set_clock', 'draft_undo', 'draft_reassign_pick',
     'draft_move_player', 'draft_force_pick', 'draft_set_order', 'draft_reverse_won_bid',
     'draft_adjust_budget', 'draft_cancel_nomination', 'draft_end', 'draft_reset',
     'draft_start_internal', 'draft_create_internal', 'set_team_autodraft')),
  'draft_adjust_budget:t:search_path="":f:t draft_cancel_nomination:t:search_path="":f:t '
  || 'draft_create_internal:f:search_path="":f:f draft_end:t:search_path="":f:t '
  || 'draft_force_pick:t:search_path="":f:t draft_move_player:t:search_path="":f:t '
  || 'draft_pause:t:search_path="":f:t draft_reassign_pick:t:search_path="":f:t '
  || 'draft_reset:t:search_path="":f:t draft_resume:t:search_path="":f:t '
  || 'draft_reverse_won_bid:t:search_path="":f:t draft_set_clock:t:search_path="":f:t '
  || 'draft_set_order:t:search_path="":f:t draft_start_internal:f:search_path="":f:f '
  || 'draft_undo:t:search_path="":f:t set_team_autodraft:t:search_path="":f:t',
  'A2 the sixteen replaced bodies keep one overload each, their DEFINER / plain posture, search_path empty, anon closed, and authenticated only on the fourteen doors');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un168(p.prosrc)), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'draft_pause', 'draft_resume', 'draft_set_clock', 'draft_undo', 'draft_reassign_pick',
     'draft_move_player', 'draft_force_pick', 'draft_set_order', 'draft_reverse_won_bid',
     'draft_adjust_budget', 'draft_cancel_nomination', 'draft_end', 'draft_reset',
     'draft_start_internal', 'draft_create_internal', 'set_team_autodraft')),
  'draft_adjust_budget=0383a75e15c240555fe70b82ae6a38e2 draft_cancel_nomination=7ef2d6336fe95a300839162aa09e233a '
  || 'draft_create_internal=b5ec26b4dfc48da34e63e1c3a0649575 draft_end=473709c3829a1e1af47089b2257b0b71 '
  || 'draft_force_pick=882946e885beb2c4ab839ddad1654da6 draft_move_player=a602b5d54a4c6372aac68b082483ab40 '
  || 'draft_pause=df4069d2370efb2b8828900db9394023 draft_reassign_pick=b2facabe18fee16b1b55ea71bc25bb29 '
  || 'draft_reset=9e6f5c24595a2c0eeab59709157770bc draft_resume=3537c6a8085db3257c71db6c85d527c5 '
  || 'draft_reverse_won_bid=9dca39fd55c4ceba4db0dcfbac464529 draft_set_clock=798d32ad4f201c20defae4cb50e0ac41 '
  || 'draft_set_order=638ed3cadc1dfab2abe45b395e81119f draft_start_internal=0c0d84890a31ab00897db9eeddcc7fb4 '
  || 'draft_undo=f8d28d3a005e6fa373d2c35f9a201ac3 set_team_autodraft=123c4e97f88ce7d4a472b33a96379d08',
  'A3 D137: each live body with 168 reversed is its NEWEST definer FILE TEXT (095 / 101 / 100 / 150 / 110 / 066 / 072 — stored md5 literals measured on the 167 chain)');
select is(
  (select string_agg(p.proname || '=' || md5(p.prosrc), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'draft_pause', 'draft_resume', 'draft_set_clock', 'draft_undo', 'draft_reassign_pick',
     'draft_move_player', 'draft_force_pick', 'draft_set_order', 'draft_reverse_won_bid',
     'draft_adjust_budget', 'draft_cancel_nomination', 'draft_end', 'draft_reset',
     'draft_start_internal', 'draft_create_internal', 'set_team_autodraft')),
  'draft_adjust_budget=be8715235b40a0fda968f480a595a499 draft_cancel_nomination=3cea8921c9417e2e0f9ff9b0f05657bc '
  || 'draft_create_internal=b15c88568c7a71eab981cc59b9ff5215 draft_end=e0e1e8c3ac4fc41c51821fb9ef90147e '
  || 'draft_force_pick=de1d78043f51dbde6c15065e5c2704ec draft_move_player=7d8847316f466b551b2f8298811f2339 '
  || 'draft_pause=c64c91f581bce6f67fecafbb48cfa5e9 draft_reassign_pick=83f63daff807cb55e1a695fb1e2496da '
  || 'draft_reset=b5826016cb5d0d033d696091f2c40278 draft_resume=c4a7f571918f368d6602668d222b733e '
  || 'draft_reverse_won_bid=c7712085192f0607f3141050e363a522 draft_set_clock=765ff3d98965980c5cec07d685cfdc6b '
  || 'draft_set_order=df63bfda77e6a047ad1d14a084df3502 draft_start_internal=239381a3e06523caa464e01f3aea9aa1 '
  || 'draft_undo=8a7dd05897b012a730a210021c192a6d set_team_autodraft=247f56f0ffc076d66afbabf036a01478',
  'A4 the sixteen live prosrc md5s — 168 as written (stored literals)');
select is(
  (select string_agg(p.proname || ':' || (length(p.prosrc) - length(replace(p.prosrc, 'public.draft_commish_receipt_internal(', '')))
                                           / length('public.draft_commish_receipt_internal('), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'draft_pause', 'draft_resume', 'draft_set_clock', 'draft_undo', 'draft_reassign_pick',
     'draft_move_player', 'draft_force_pick', 'draft_set_order', 'draft_reverse_won_bid',
     'draft_adjust_budget', 'draft_cancel_nomination', 'draft_end', 'draft_reset',
     'draft_start_internal', 'draft_create_internal', 'set_team_autodraft', 'draft_pause_internal')),
  'draft_adjust_budget:1 draft_cancel_nomination:1 draft_create_internal:1 draft_end:1 draft_force_pick:2 '
  || 'draft_move_player:1 draft_pause:1 draft_pause_internal:0 draft_reassign_pick:1 draft_reset:1 draft_resume:1 '
  || 'draft_reverse_won_bid:1 draft_set_clock:2 draft_set_order:2 draft_start_internal:1 draft_undo:1 set_team_autodraft:1',
  'A5 every change path reaches the seam (two arms each for force-pick, clock and order), and the tick shared pause internal does not');

-- ---------------------------------------------------------------------------
-- B. Fixtures (privileged, before any JWT claims — D49(7))
-- ---------------------------------------------------------------------------
-- The calendar this fixture starts on (the 023 / 036 110-forced shift): the
-- season-2026 weeks far in the future, so a real start and a draft end fit
-- at any wall clock.
update nfl_weeks
set starts_at = starts_at + interval '73 years',
    correction_window_ends_at = correction_window_ends_at + interval '73 years'
where season = 2026;

insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000',
       ('96116000-0000-4000-8000-00000000000' || i)::uuid,
       'authenticated', 'authenticated', 'pgtap-rc-u' || i || '@fieldscout.local', 'x', now(),
       '{"provider": "email", "providers": ["email"]}',
       ('{"username": "rc_user_' || i || '"}')::jsonb, now(), now()
from generate_series(1, 4) i;

insert into players (id, full_name, position, adp)
select 'rc-p' || lpad(i::text, 2, '0'), 'RC Player ' || lpad(i::text, 2, '0'), 'RB', i
from generate_series(1, 40) i;

insert into leagues (id, owner_id, name, season, status, team_count, scoring_system_id, settings) values
  ('b1160000-0000-4000-8000-000000000001', '96116000-0000-4000-8000-000000000001',
   'pgtap-rc-LS-snake', 2026, 'scheduled', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "snake", "snake_reversal": false, "draft_order_mode": "manual",
     "draft_order": ["c1160001-0000-4000-8000-000000000001","c1160001-0000-4000-8000-000000000002",
                     "c1160001-0000-4000-8000-000000000003","c1160001-0000-4000-8000-000000000004",
                     "c1160001-0000-4000-8000-000000000005","c1160001-0000-4000-8000-000000000006",
                     "c1160001-0000-4000-8000-000000000007","c1160001-0000-4000-8000-000000000008"],
     "pick_timer_seconds": 30, "disconnect_grace_seconds": 30}}'),
  ('b1160000-0000-4000-8000-000000000003', '96116000-0000-4000-8000-000000000001',
   'pgtap-rc-LT-tick', 2026, 'scheduled', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "snake", "pick_timer_seconds": 30}}');
insert into leagues (id, owner_id, name, season, status, team_count,
                     scoring_system_id, settings, scoring_rules_snapshot) values
  ('b1160000-0000-4000-8000-000000000002', '96116000-0000-4000-8000-000000000001',
   'pgtap-rc-LA-auction', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "auction", "auction_budget": 200, "auction_zero_dollar_nominations": false,
     "auction_nomination_seconds": 45, "auction_bid_seconds": 30,
     "auction_anti_snipe_seconds": 10, "disconnect_grace_seconds": 30, "pick_timer_seconds": 90}}',
   '{}'),
  ('b1160000-0000-4000-8000-000000000004', '96116000-0000-4000-8000-000000000001',
   'pgtap-rc-LH-held-lock', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "snake", "pick_timer_seconds": 30}}', '{}');
-- 3 draftable slots everywhere (D91: rounds = starters + bench).
update leagues
set roster_settings = '{"starting_slots": [{"key": "rb", "label": "RB", "eligible": ["RB"], "count": 1}],
                        "bench": 2, "ir_slots": [], "swap_spots": 0}'::jsonb
where name like 'pgtap-rc-%';

insert into teams (id, owner_id, name, league_id)
select ('c116000' || l || '-0000-4000-8000-0000000000' || lpad(i::text, 2, '0'))::uuid,
       '96116000-0000-4000-8000-000000000001',
       'rc-L' || l || '-t' || i,
       ('b1160000-0000-4000-8000-00000000000' || l)::uuid
from generate_series(1, 4) l, generate_series(1, 8) i;

-- LS: u1 commissioner (t1), u2 manager (t2), t3–t7 placeholder rows with no
-- user, t8 with NO member row at all (both are "no manager" — D339).
insert into league_members (league_id, user_id, team_id, role, is_placeholder)
select 'b1160000-0000-4000-8000-000000000001',
       case i when 1 then '96116000-0000-4000-8000-000000000001'::uuid
              when 2 then '96116000-0000-4000-8000-000000000002'::uuid end,
       ('c1160001-0000-4000-8000-0000000000' || lpad(i::text, 2, '0'))::uuid,
       case i when 1 then 'commissioner' else 'manager' end,
       i > 2
from generate_series(1, 7) i;
-- LA / LT / LH: u1 commissioner (t1), u2 manager (t2) on LA and LT.
insert into league_members (league_id, user_id, team_id, role) values
  ('b1160000-0000-4000-8000-000000000002', '96116000-0000-4000-8000-000000000001', 'c1160002-0000-4000-8000-000000000001', 'commissioner'),
  ('b1160000-0000-4000-8000-000000000002', '96116000-0000-4000-8000-000000000002', 'c1160002-0000-4000-8000-000000000002', 'manager'),
  ('b1160000-0000-4000-8000-000000000003', '96116000-0000-4000-8000-000000000001', 'c1160003-0000-4000-8000-000000000001', 'commissioner'),
  ('b1160000-0000-4000-8000-000000000003', '96116000-0000-4000-8000-000000000002', 'c1160003-0000-4000-8000-000000000002', 'manager'),
  ('b1160000-0000-4000-8000-000000000004', '96116000-0000-4000-8000-000000000001', 'c1160004-0000-4000-8000-000000000001', 'commissioner');

-- LA: a live auction in the NOMINATING phase at nomination 2, t1 on the
-- clock; nomination 1 was won by t3 at $7 (its opening bid row — F62).
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    draft_order, nomination_order, total_rounds, current_round,
                    current_pick_number, on_clock_team_id, current_deadline, started_at)
values ('e1160000-0000-4000-8000-000000000002', 'b1160000-0000-4000-8000-000000000002',
        'auction', 'live', false,
        '{"auction_budget": 200, "auction_zero_dollar_nominations": false,
          "auction_nomination_seconds": 45, "auction_bid_seconds": 30,
          "auction_anti_snipe_seconds": 10, "disconnect_grace_seconds": 30,
          "pick_timer_seconds": 90}',
        (select jsonb_agg(t.id order by t.name) from teams t where t.league_id = 'b1160000-0000-4000-8000-000000000002'),
        (select jsonb_agg(t.id order by t.name) from teams t where t.league_id = 'b1160000-0000-4000-8000-000000000002'),
        3, 1, 2, 'c1160002-0000-4000-8000-000000000001', now() + interval '1 hour', now() - interval '1 minute');
insert into draft_bids (draft_id, league_id, nomination_seq, player_id, team_id, amount, action_id)
values ('e1160000-0000-4000-8000-000000000002', 'b1160000-0000-4000-8000-000000000002',
        1, 'rc-p31', 'c1160002-0000-4000-8000-000000000003', 7, 'a1160000-0000-4000-8000-0000000000f1');
insert into draft_picks (id, draft_id, league_id, pick_number, round, team_id, player_id, price, is_auto, made_via)
values ('d1160000-0000-4000-8000-000000000001', 'e1160000-0000-4000-8000-000000000002',
        'b1160000-0000-4000-8000-000000000002', 1, null,
        'c1160002-0000-4000-8000-000000000003', 'rc-p31', 7, false, 'manager');

-- LH: a live snake draft at pick 1, t1 on the clock.
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    draft_order, total_rounds, current_round, current_pick_number,
                    on_clock_team_id, current_deadline, started_at)
values ('e1160000-0000-4000-8000-000000000004', 'b1160000-0000-4000-8000-000000000004',
        'snake', 'live', false, '{"pick_timer_seconds": 30}',
        (select jsonb_agg(t.id order by t.name) from teams t where t.league_id = 'b1160000-0000-4000-8000-000000000004'),
        3, 1, 1, 'c1160004-0000-4000-8000-000000000001', now() + interval '1 hour', now());

-- M: a live snake MOCK inside LS, launched by u1 (the commissioner) — the
-- launcher holds the commissioner tools on it (§8.8), and a mock has no
-- commissioner, so nothing on it is receipted.
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    draft_order, total_rounds, current_round, current_pick_number,
                    on_clock_team_id, current_deadline, started_at)
values ('e1160000-0000-4000-8000-000000000005', 'b1160000-0000-4000-8000-000000000001',
        'snake', 'live', true,
        '{"pick_timer_seconds": 30, "mock": {"launched_by": "96116000-0000-4000-8000-000000000001"}}',
        (select jsonb_agg(t.id order by t.name) from teams t where t.league_id = 'b1160000-0000-4000-8000-000000000001'),
        3, 1, 1, 'c1160001-0000-4000-8000-000000000001', now() + interval '1 hour', now());
-- S: a live STANDALONE mock (no league), launched by u4.
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    total_rounds, current_round, current_pick_number, current_deadline, started_at)
values ('e1160000-0000-4000-8000-000000000006', null, 'snake', 'live', true,
        '{"pick_timer_seconds": 30, "mock": {"launched_by": "96116000-0000-4000-8000-000000000004"}}',
        3, 1, 1, now() + interval '1 hour', now());

select is((select count(*)::int from commissioner_actions where league_id::text like 'b1160000-%'), 0,
  'B1 premise: no receipt exists in any fixture league before the first call');
select is(
  (select string_agg(t.name || ':' || coalesce(m.role, 'none') || ':' || (m.user_id is not null), ' ' order by t.name)
   from teams t left join league_members m on m.team_id = t.id
   where t.league_id = 'b1160000-0000-4000-8000-000000000001'),
  'rc-L1-t1:commissioner:true rc-L1-t2:manager:true rc-L1-t3:manager:false rc-L1-t4:manager:false '
  || 'rc-L1-t5:manager:false rc-L1-t6:manager:false rc-L1-t7:manager:false rc-L1-t8:none:false',
  'B2 premise: LS seats one commissioner and one manager; t3 to t7 are placeholder rows and t8 has no member row');

-- ---------------------------------------------------------------------------
-- C. LS — create and start (the commissioner; F45)
-- ---------------------------------------------------------------------------
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000001", "role": "authenticated"}', true);

select is((public.draft_create('b1160000-0000-4000-8000-000000000001')->>'created')::boolean, true,
  'C1 the commissioner creates the LS draft');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 1,
  'C2 change: the create writes exactly ONE receipt');
select is(
  (select format('%s|%s|%s|%s|%s|%s|%s', actor_id, action_type, target_type,
                 target_id = (select d.id::text from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                 before is null, after ->> 'status', after ->> 'draft_type')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_create'),
  '96116000-0000-4000-8000-000000000001|draft_create|draft|t|t|scheduled|snake',
  'C3 the create receipt: the actor, draft_create on the draft row, no before, a scheduled snake draft after');
select is((public.draft_create('b1160000-0000-4000-8000-000000000001')->>'created')::boolean, false,
  'C4 a second create returns the existing draft');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 1,
  'C5 no-op: the second create writes no receipt');

select is((public.draft_start('b1160000-0000-4000-8000-000000000001')->>'started')::boolean, true,
  'C6 the commissioner starts the LS draft');
select is(
  (select string_agg(action_type, ' ' order by action_type) from commissioner_actions
   where league_id = 'b1160000-0000-4000-8000-000000000001'),
  'draft_create draft_start',
  'C7 change: the start writes exactly ONE receipt (draft_start) and no second create');
select is(
  (select after -> 'placeholder_team_ids' from commissioner_actions
   where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_start'),
  '["c1160001-0000-4000-8000-000000000003", "c1160001-0000-4000-8000-000000000004", "c1160001-0000-4000-8000-000000000005", "c1160001-0000-4000-8000-000000000006", "c1160001-0000-4000-8000-000000000007", "c1160001-0000-4000-8000-000000000008"]'::jsonb,
  'C8 F45: the start NAMES the six seats with no manager — the five placeholder rows AND t8, which has no member row (the D339 predicate)');
select is(
  (select format('%s|%s|%s|%s', before, after ->> 'status', after -> 'draft_order' -> 0, metadata -> 'affected_team_ids' = after -> 'placeholder_team_ids')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_start'),
  '{"status": "scheduled"}|live|"c1160001-0000-4000-8000-000000000001"|t',
  'C9 the start receipt: scheduled to live, the resolved order, and the placeholder seats as its affected teams');
select is((public.draft_start('b1160000-0000-4000-8000-000000000001')->>'started')::boolean, false,
  'C10 a second start is the double-click no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 2,
  'C11 no-op: the second start writes no receipt');

-- ---------------------------------------------------------------------------
-- D. LS — the snake controls, change and no-op
-- ---------------------------------------------------------------------------
select is((public.draft_force_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                   'rc-p01', 'a1160000-0000-4000-8000-000000000001') -> 'pick' ->> 'player_id'), 'rc-p01',
  'D1 the commissioner picks rc-p01 for t1 (pick 1)');
select is(
  (select format('%s|%s|%s|%s|%s|%s', action_type, target_type, acting_as_team_id is null, metadata ->> 'for_team_id', before, after)
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_force_pick'),
  'draft_force_pick|draft_pick|t|c1160001-0000-4000-8000-000000000001|{"team_id": "c1160001-0000-4000-8000-000000000001", "player_id": null, "pick_number": 1}|{"team_id": "c1160001-0000-4000-8000-000000000001", "player_id": "rc-p01", "pick_number": 1}',
  'D2 change: ONE force-pick receipt naming the team on the clock in metadata (a draft control, not acting_as — D449(3)), the pick before and after');
select is((public.draft_force_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                   'rc-p01', 'a1160000-0000-4000-8000-000000000001') -> 'pick' ->> 'pick_number')::int, 1,
  'D3 the same action id replays the historical pick');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_force_pick'), 1,
  'D4 no-op: the replay writes no receipt');

select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select is((public.draft_make_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                  'rc-p02', 'a1160000-0000-4000-8000-000000000002') -> 'pick' ->> 'pick_number')::int, 2,
  'D5 the manager makes his own pick 2');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 3,
  'D6 a manager pick is not a commissioner action: still three receipts');

select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select is((public.draft_force_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                   'rc-p03', null) -> 'pick' ->> 'team_id'), 'c1160001-0000-4000-8000-000000000003',
  'D7 the commissioner picks rc-p03 for the placeholder t3 (pick 3, no action id)');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_force_pick'), 2,
  'D8 change: a second force pick is a second receipt');

-- pause (reason whitespace-only ⇒ NULL, never refused)
select is((public.draft_pause((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                              E'  \t\n ') ->> 'paused')::boolean, true,
  'D9 the commissioner pauses (with a whitespace-only reason)');
select is(
  (select format('%s|%s|%s|%s', before, after, reason is null, metadata ->> 'verb')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_pause'),
  '{"status": "live"}|{"status": "paused"}|t|draft_pause',
  'D10 change: ONE pause receipt, live to paused; the whitespace-only reason is stored as NULL');
select is((public.draft_pause((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) ->> 'paused')::boolean, false,
  'D11 a second pause is the double-tap no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_pause'), 1,
  'D12 no-op: the double pause writes no receipt');

-- clock (a 600-character reason is cut to 500, never refused)
select is((public.draft_set_clock((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                  45, false, 'r' || repeat('x', 599)) -> 'draft' -> 'config' ->> 'pick_timer_seconds')::int, 45,
  'D13 the commissioner sets the pick clock to 45s (with a 600-character reason)');
select is(
  (select format('%s|%s|%s|%s', before ->> 'pick_timer_seconds', after ->> 'pick_timer_seconds', length(reason), left(reason, 2))
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_set_clock'),
  '30|45|500|rx',
  'D14 change: ONE clock receipt, 30 to 45; the over-long reason is cut to the 500-character bound, not refused');
select is((select count(*)::int from league_chat where context = 'draft:' || (select d.id::text from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)), 4,
  'D15 premise for D17: four draft-room posts so far (the two commissioner picks, the pause, the clock — a start and a manager pick post nothing)');
select is((public.draft_set_clock((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                  45) -> 'draft' -> 'config' ->> 'pick_timer_seconds')::int, 45,
  'D16 the same clock again is accepted, as before');
select is(
  format('%s|%s',
    (select count(*) from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_set_clock'),
    (select count(*) from league_chat where context = 'draft:' || (select d.id::text from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock))),
  '1|5',
  'D17 no-op DETECTED by value: the same clock writes no receipt, while its chat post still lands (the posts are unchanged)');

-- undo (single — pick 3)
select is((public.draft_undo((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) ->> 'undone_count')::int, 1,
  'D18 the commissioner undoes the last pick');
select is(
  (select format('%s|%s|%s', before, after, metadata -> 'affected_team_ids')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_undo'),
  '{"picks": [{"price": null, "team_id": "c1160001-0000-4000-8000-000000000003", "player_id": "rc-p03", "pick_number": 3}], "last_live_pick": 3, "on_clock_team_id": "c1160001-0000-4000-8000-000000000004"}'
  || '|{"picks": [], "last_live_pick": 2, "on_clock_team_id": "c1160001-0000-4000-8000-000000000003"}'
  || '|["c1160001-0000-4000-8000-000000000003"]',
  'D19 change: ONE undo receipt naming the reverted pick (t3, rc-p03, pick 3) and the clock rewound to t3');

-- reassign pick 1's player; then the same team again (a no-op edit)
select is((public.draft_reassign_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                      (select p.id from draft_picks p join drafts d on d.id = p.draft_id where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock and p.pick_number = 1 and not p.is_undone),
                                      null, 'rc-p05') -> 'pick' ->> 'player_id'), 'rc-p05',
  'D20 the commissioner swaps pick 1 to rc-p05');
select is(
  (select format('%s|%s|%s|%s', target_type, before, after, metadata -> 'affected_team_ids')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_reassign'),
  'draft_pick|{"price": null, "team_id": "c1160001-0000-4000-8000-000000000001", "player_id": "rc-p01", "pick_number": 1}'
  || '|{"price": null, "team_id": "c1160001-0000-4000-8000-000000000001", "player_id": "rc-p05", "pick_number": 1}'
  || '|["c1160001-0000-4000-8000-000000000001"]',
  'D21 change: ONE reassign receipt, the player rc-p01 to rc-p05 on the same pick');
select is((public.draft_reassign_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                      (select p.id from draft_picks p join drafts d on d.id = p.draft_id where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock and p.pick_number = 1 and not p.is_undone),
                                      'c1160001-0000-4000-8000-000000000001') -> 'pick' ->> 'team_id'), 'c1160001-0000-4000-8000-000000000001',
  'D22 naming the team the pick already has is accepted, as before');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_reassign'), 1,
  'D23 no-op DETECTED by value: an edit that leaves team, player and price as they were writes no receipt');

-- move rc-p05 from t1 to t4 (reason kept)
select is((public.draft_move_player((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
                                    'rc-p05', 'c1160001-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000004',
                                    'wrong team') -> 'pick' ->> 'team_id'), 'c1160001-0000-4000-8000-000000000004',
  'D24 the commissioner moves rc-p05 from t1 to t4');
select is(
  (select format('%s|%s|%s|%s', before ->> 'team_id', after ->> 'team_id', reason, metadata -> 'affected_team_ids')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_move_player'),
  'c1160001-0000-4000-8000-000000000001|c1160001-0000-4000-8000-000000000004|wrong team|["c1160001-0000-4000-8000-000000000001", "c1160001-0000-4000-8000-000000000004"]',
  'D25 change: ONE move receipt, t1 to t4, the reason stored as given');

-- order: t2 and t1 swap; then the same order again
select is((public.draft_set_order((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
            array['c1160001-0000-4000-8000-000000000002','c1160001-0000-4000-8000-000000000001','c1160001-0000-4000-8000-000000000003',
                  'c1160001-0000-4000-8000-000000000004','c1160001-0000-4000-8000-000000000005','c1160001-0000-4000-8000-000000000006',
                  'c1160001-0000-4000-8000-000000000007','c1160001-0000-4000-8000-000000000008']::uuid[]) -> 'draft' -> 'draft_order' ->> 0),
  'c1160001-0000-4000-8000-000000000002',
  'D26 the commissioner edits the order mid-draft (t2 first)');
select is(
  (select format('%s|%s|%s|%s', before -> 'draft_order' ->> 0, after -> 'draft_order' ->> 0, before ->> 'on_clock_team_id', after ->> 'on_clock_team_id')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_set_order'),
  'c1160001-0000-4000-8000-000000000001|c1160001-0000-4000-8000-000000000002|c1160001-0000-4000-8000-000000000003|c1160001-0000-4000-8000-000000000003',
  'D27 change: ONE order receipt, t1-first to t2-first (pick 3 stays with t3)');
select is((public.draft_set_order((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock),
            array['c1160001-0000-4000-8000-000000000002','c1160001-0000-4000-8000-000000000001','c1160001-0000-4000-8000-000000000003',
                  'c1160001-0000-4000-8000-000000000004','c1160001-0000-4000-8000-000000000005','c1160001-0000-4000-8000-000000000006',
                  'c1160001-0000-4000-8000-000000000007','c1160001-0000-4000-8000-000000000008']::uuid[]) -> 'draft' -> 'draft_order' ->> 0),
  'c1160001-0000-4000-8000-000000000002',
  'D28 the same order again is accepted, as before');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_set_order'), 1,
  'D29 no-op DETECTED by value: the same order writes no receipt');

-- ---------------------------------------------------------------------------
-- E. The manager is refused everywhere — 42501, unchanged — and nothing is
--    written (u2 manages t2 in LS and LA)
-- ---------------------------------------------------------------------------
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select throws_ok($$ select public.draft_pause((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) $$,
  '42501', null, 'E1 manager: draft_pause refused 42501');
select throws_ok($$ select public.draft_resume((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) $$,
  '42501', null, 'E2 manager: draft_resume refused 42501');
select throws_ok($$ select public.draft_set_clock((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock), 20) $$,
  '42501', null, 'E3 manager: draft_set_clock refused 42501');
select throws_ok($$ select public.draft_undo((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) $$,
  '42501', null, 'E4 manager: draft_undo refused 42501');
select throws_ok($$ select public.draft_reassign_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock), 'd1160000-0000-4000-8000-000000000001', null, 'rc-p09') $$,
  '42501', null, 'E5 manager: draft_reassign_pick refused 42501');
select throws_ok($$ select public.draft_move_player((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock), 'rc-p05', 'c1160001-0000-4000-8000-000000000004', 'c1160001-0000-4000-8000-000000000002') $$,
  '42501', null, 'E6 manager: draft_move_player refused 42501');
select throws_ok($$ select public.draft_force_pick((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock), 'rc-p09') $$,
  '42501', null, 'E7 manager: draft_force_pick refused 42501');
select throws_ok($$ select public.draft_set_order((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock), array['c1160001-0000-4000-8000-000000000001']::uuid[]) $$,
  '42501', null, 'E8 manager: draft_set_order refused 42501');
select throws_ok($$ select public.draft_reset((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) $$,
  '42501', null, 'E9 manager: draft_reset refused 42501');
select throws_ok($$ select public.draft_create('b1160000-0000-4000-8000-000000000003') $$,
  '42501', null, 'E10 manager: draft_create refused 42501');
select throws_ok($$ select public.draft_start('b1160000-0000-4000-8000-000000000003') $$,
  '42501', null, 'E11 manager: draft_start refused 42501');
select throws_ok($$ select public.set_team_autodraft('b1160000-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000003', true) $$,
  '42501', null, 'E12 manager: set_team_autodraft on another team refused 42501');
select throws_ok($$ select public.draft_reverse_won_bid('e1160000-0000-4000-8000-000000000002', 'd1160000-0000-4000-8000-000000000001') $$,
  '42501', null, 'E13 manager: draft_reverse_won_bid refused 42501');
select throws_ok($$ select public.draft_adjust_budget('e1160000-0000-4000-8000-000000000002', 'c1160002-0000-4000-8000-000000000002', 50) $$,
  '42501', null, 'E14 manager: draft_adjust_budget refused 42501');
select throws_ok($$ select public.draft_cancel_nomination('e1160000-0000-4000-8000-000000000002') $$,
  '42501', null, 'E15 manager: draft_cancel_nomination refused 42501');
select throws_ok($$ select public.draft_end('e1160000-0000-4000-8000-000000000002') $$,
  '42501', null, 'E16 manager: draft_end refused 42501');
select is((select count(*)::int from commissioner_actions where league_id::text like 'b1160000-%'), 10,
  'E17 the sixteen refusals wrote nothing: still the ten LS receipts, none in LA or LT');
select is((public.set_team_autodraft('b1160000-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000002', true) ->> 'changed')::boolean, true,
  'E18 the manager toggles autodraft on his OWN seat');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 10,
  'E19 a manager on his own seat is not an override: no receipt');

-- ---------------------------------------------------------------------------
-- F. LS — autodraft, resume, reset (the commissioner)
-- ---------------------------------------------------------------------------
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select is((public.set_team_autodraft('b1160000-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000002', false) ->> 'changed')::boolean, true,
  'F1 the commissioner turns autodraft off for t2');
select is(
  (select format('%s|%s|%s|%s|%s', target_type, target_id, acting_as_team_id, before, after)
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'set_autodraft'),
  'team|c1160001-0000-4000-8000-000000000002|c1160001-0000-4000-8000-000000000002|{"autodraft": true}|{"autodraft": false}',
  'F2 change: ONE autodraft receipt for t2, acting for t2, on to off');
select is((public.set_team_autodraft('b1160000-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000002', false) ->> 'changed')::boolean, false,
  'F3 the same value again is the no-op');
select is((public.set_team_autodraft('b1160000-0000-4000-8000-000000000001', 'c1160001-0000-4000-8000-000000000001', true) ->> 'changed')::boolean, true,
  'F4 the commissioner toggles his OWN seat');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'set_autodraft'), 1,
  'F5 no-op and own seat: neither writes a receipt');

select is((public.draft_resume((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) ->> 'resumed')::boolean, true,
  'F6 the commissioner resumes');
select is(
  (select format('%s|%s', before, after) from commissioner_actions
   where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_resume'),
  '{"status": "paused"}|{"status": "live"}',
  'F7 change: ONE resume receipt, paused to live');
select is((public.draft_resume((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) ->> 'resumed')::boolean, false,
  'F8 a second resume is the no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_resume'), 1,
  'F9 no-op: the second resume writes no receipt');

select is((public.draft_reset((select d.id from drafts d where d.league_id = 'b1160000-0000-4000-8000-000000000001' and not d.is_mock)) ->> 'picks_cleared')::int, 2,
  'F10 the commissioner resets the draft (two live picks cleared)');
select is(
  (select format('%s|%s|%s', before, after, metadata ->> 'picks_cleared') from commissioner_actions
   where league_id = 'b1160000-0000-4000-8000-000000000001' and action_type = 'draft_reset'),
  '{"status": "live", "current_pick_number": 3}|{"status": "scheduled", "current_pick_number": 1}|2',
  'F11 change: ONE reset receipt, live at pick 3 to scheduled at pick 1');
select is(
  (select string_agg(action_type || ':' || n, ' ' order by action_type)
   from (select action_type, count(*) n from commissioner_actions
         where league_id = 'b1160000-0000-4000-8000-000000000001' group by action_type) s),
  'draft_create:1 draft_force_pick:2 draft_move_player:1 draft_pause:1 draft_reassign:1 draft_reset:1 '
  || 'draft_resume:1 draft_set_clock:1 draft_set_order:1 draft_start:1 draft_undo:1 set_autodraft:1',
  'F12 GOLDEN: LS holds exactly one receipt per real change — thirteen, by type — and every one is by the commissioner');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'
           and (actor_id <> '96116000-0000-4000-8000-000000000001' or metadata ->> 'draft_id' is null or metadata -> 'bypassed' <> '[]'::jsonb)), 0,
  'F13 every LS receipt names the commissioner as actor, carries its draft id and bypasses no rule');

-- ---------------------------------------------------------------------------
-- G. LA — the auction controls
-- ---------------------------------------------------------------------------
select is((public.draft_force_pick('e1160000-0000-4000-8000-000000000002', 'rc-p10', 'a1160000-0000-4000-8000-000000000010') -> 'bid' ->> 'amount')::int, 1,
  'G1 the commissioner force-nominates rc-p10 for t1 at the 1 dollar floor');
select is(
  (select format('%s|%s|%s|%s|%s|%s', target_type, acting_as_team_id is null, metadata ->> 'for_team_id', before, after, metadata ->> 'uncontested')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_force_pick'),
  'draft|t|c1160002-0000-4000-8000-000000000001|{"nomination": null, "nomination_seq": 2}'
  || '|{"nomination": {"team_id": "c1160002-0000-4000-8000-000000000001", "player_id": "rc-p10", "opening_bid": 1}, "nomination_seq": 2}|false',
  'G2 change: ONE force-nomination receipt for t1 (metadata, not acting_as): no nomination to rc-p10 at 1 dollar');
select is((public.draft_force_pick('e1160000-0000-4000-8000-000000000002', 'rc-p10', 'a1160000-0000-4000-8000-000000000010') -> 'bid' ->> 'player_id'), 'rc-p10',
  'G3 the same action id replays the opening bid');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002'), 1,
  'G4 no-op: the replay writes no receipt');

select is((public.draft_pause('e1160000-0000-4000-8000-000000000002') ->> 'paused')::boolean, true,
  'G5 the commissioner pauses the auction mid-bidding');
select is((public.draft_cancel_nomination('e1160000-0000-4000-8000-000000000002') ->> 'cancelled_player_id'), 'rc-p10',
  'G6 the commissioner cancels the nomination');
select is(
  (select format('%s|%s|%s', before, after, metadata ->> 'voided_bids')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_cancel_nomination'),
  '{"nomination": {"team_id": "c1160002-0000-4000-8000-000000000001", "high_bid": 1, "player_id": "rc-p10"}}|{"nomination": null}|1',
  'G7 change: ONE cancel receipt naming the nomination that came off the block (rc-p10 at 1 dollar, one bid void)');

select is((public.draft_adjust_budget('e1160000-0000-4000-8000-000000000002', 'c1160002-0000-4000-8000-000000000002', 10, null,
                                      'a1160000-0000-4000-8000-000000000011') ->> 'adjustment_after')::int, 10,
  'G8 the commissioner adds 10 dollars to t2');
select is(
  (select format('%s|%s|%s|%s', target_id, before, after, metadata ->> 'remaining')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_adjust_budget'),
  'c1160002-0000-4000-8000-000000000002|{"budget_adjustment": 0}|{"budget_adjustment": 10}|210',
  'G9 change: ONE budget receipt for t2, adjustment 0 to 10 (210 dollars remaining)');
select is((public.draft_adjust_budget('e1160000-0000-4000-8000-000000000002', 'c1160002-0000-4000-8000-000000000002', 10, null,
                                      'a1160000-0000-4000-8000-000000000011') ->> 'adjustment_after')::int, 10,
  'G10 the same action id replays the stored adjustment');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_adjust_budget'), 1,
  'G11 no-op: the replay writes no receipt');

select is((public.draft_reverse_won_bid('e1160000-0000-4000-8000-000000000002', 'd1160000-0000-4000-8000-000000000001') ->> 'refunded')::int, 7,
  'G12 the commissioner reverses t3 won bid (7 dollars refunded)');
select is(
  (select format('%s|%s|%s|%s', target_id, before, after, metadata ->> 'refunded')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_reverse_bid'),
  'd1160000-0000-4000-8000-000000000001'
  || '|{"price": 7, "undone": false, "team_id": "c1160002-0000-4000-8000-000000000003", "player_id": "rc-p31", "pick_number": 1}'
  || '|{"price": 7, "undone": true, "team_id": "c1160002-0000-4000-8000-000000000003", "player_id": "rc-p31", "pick_number": 1}|7',
  'G13 change: ONE reversal receipt, the won pick and its price live before and reversed after');

select is((public.draft_set_clock('e1160000-0000-4000-8000-000000000002', null, false, null, null, 40) -> 'draft' -> 'config' ->> 'auction_bid_seconds')::int, 40,
  'G14 the commissioner sets the bid clock to 40s');
select is(
  (select format('%s|%s|%s', before ->> 'auction_bid_seconds', after ->> 'auction_bid_seconds', after ->> 'auction_nomination_seconds')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_set_clock'),
  '30|40|45',
  'G15 change: ONE auction-clock receipt, bid clock 30 to 40, nomination clock unchanged at 45');
select is((public.draft_set_clock('e1160000-0000-4000-8000-000000000002', null, false, null, null, 40) -> 'draft' -> 'config' ->> 'auction_bid_seconds')::int, 40,
  'G16 the same bid clock again is accepted');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_set_clock'), 1,
  'G17 no-op DETECTED by value: the same auction clock writes no receipt');

select is((public.draft_set_order('e1160000-0000-4000-8000-000000000002',
            array['c1160002-0000-4000-8000-000000000008','c1160002-0000-4000-8000-000000000007','c1160002-0000-4000-8000-000000000006',
                  'c1160002-0000-4000-8000-000000000005','c1160002-0000-4000-8000-000000000004','c1160002-0000-4000-8000-000000000003',
                  'c1160002-0000-4000-8000-000000000002','c1160002-0000-4000-8000-000000000001']::uuid[]) -> 'draft' -> 'nomination_order' ->> 0),
  'c1160002-0000-4000-8000-000000000008',
  'G18 the commissioner reverses the nomination order');
select is(
  (select format('%s|%s|%s', before -> 'nomination_order' ->> 0, after -> 'nomination_order' ->> 0, before -> 'draft_order' = after -> 'draft_order')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_set_order'),
  'c1160002-0000-4000-8000-000000000001|c1160002-0000-4000-8000-000000000008|t',
  'G19 change: ONE nomination-order receipt, t1-first to t8-first, the draft order untouched');
select is((public.draft_set_order('e1160000-0000-4000-8000-000000000002',
            array['c1160002-0000-4000-8000-000000000008','c1160002-0000-4000-8000-000000000007','c1160002-0000-4000-8000-000000000006',
                  'c1160002-0000-4000-8000-000000000005','c1160002-0000-4000-8000-000000000004','c1160002-0000-4000-8000-000000000003',
                  'c1160002-0000-4000-8000-000000000002','c1160002-0000-4000-8000-000000000001']::uuid[]) -> 'draft' -> 'nomination_order' ->> 0),
  'c1160002-0000-4000-8000-000000000008',
  'G20 the same nomination order again is accepted');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_set_order'), 1,
  'G21 no-op DETECTED by value: the same nomination order writes no receipt');

select is((public.draft_end('e1160000-0000-4000-8000-000000000002') ->> 'ended')::boolean, true,
  'G22 the commissioner ends the auction as it stands');
select is(
  (select format('%s|%s|%s|%s', before, after, metadata ->> 'rostered', metadata ->> 'unfilled_slots')
   from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000002' and action_type = 'draft_end'),
  '{"status": "paused"}|{"status": "complete"}|0|24',
  'G23 change: ONE end receipt, paused to complete (nothing rostered, 24 spots left for free agency)');
select is(
  (select string_agg(action_type || ':' || n, ' ' order by action_type)
   from (select action_type, count(*) n from commissioner_actions
         where league_id = 'b1160000-0000-4000-8000-000000000002' group by action_type) s),
  'draft_adjust_budget:1 draft_cancel_nomination:1 draft_end:1 draft_force_pick:1 draft_pause:1 '
  || 'draft_reverse_bid:1 draft_set_clock:1 draft_set_order:1',
  'G24 GOLDEN: LA holds exactly one receipt per real change — eight, by type');

-- ---------------------------------------------------------------------------
-- H. Mocks write none — league-attached (launched by the commissioner) and
--    standalone
-- ---------------------------------------------------------------------------
select is((public.draft_pause('e1160000-0000-4000-8000-000000000005') ->> 'paused')::boolean, true,
  'H1 the launcher pauses his league mock');
select is((public.draft_set_clock('e1160000-0000-4000-8000-000000000005', 20) -> 'draft' -> 'config' ->> 'pick_timer_seconds')::int, 20,
  'H2 the launcher edits the mock clock');
select is((public.draft_set_order('e1160000-0000-4000-8000-000000000005',
            array['c1160001-0000-4000-8000-000000000008','c1160001-0000-4000-8000-000000000007','c1160001-0000-4000-8000-000000000006',
                  'c1160001-0000-4000-8000-000000000005','c1160001-0000-4000-8000-000000000004','c1160001-0000-4000-8000-000000000003',
                  'c1160001-0000-4000-8000-000000000002','c1160001-0000-4000-8000-000000000001']::uuid[]) -> 'draft' -> 'draft_order' ->> 0),
  'c1160001-0000-4000-8000-000000000008',
  'H3 the launcher edits the mock order');
select is((public.draft_resume('e1160000-0000-4000-8000-000000000005') ->> 'resumed')::boolean, true,
  'H4 the launcher resumes his league mock');
select throws_ok($$ select public.draft_undo('e1160000-0000-4000-8000-000000000005') $$,
  'P0001', 'draft_undo: undo is not open in a practice yet (§8.8/E75)',
  'H5 a control still shut on a mock refuses by its own reason, unchanged');
select is((select count(*)::int from commissioner_actions where metadata ->> 'draft_id' = 'e1160000-0000-4000-8000-000000000005'), 0,
  'H6 mock: four real changes to a league mock and a refusal wrote NO receipt');

reset role;
select set_config('request.jwt.claims', '', true);
select is((select count(*)::int from commissioner_actions where league_id::text like 'b1160000-%'), 21,
  'H7 premise for H9: the fixture leagues hold the thirteen LS and eight LA receipts');
-- The whole table's count BEFORE the standalone pause (the local stack may
-- hold committed rows from other suites — H9 compares against this, never a
-- literal of rows this file does not own).
create temp table rc_total on commit drop as select count(*)::int as n from commissioner_actions;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000004", "role": "authenticated"}', true);
select is((public.draft_pause('e1160000-0000-4000-8000-000000000006') ->> 'paused')::boolean, true,
  'H8 the launcher pauses his standalone mock');
reset role;
select set_config('request.jwt.claims', '', true);
select is((select count(*)::int from commissioner_actions), (select n from rc_total),
  'H9 mock: the standalone pause (no league) wrote no receipt anywhere in the table');

-- ---------------------------------------------------------------------------
-- I. The system paths write none (the tick has no actor — §10.3)
-- ---------------------------------------------------------------------------
select is((public.draft_create_internal('b1160000-0000-4000-8000-000000000003', false) ->> 'created')::boolean, true,
  'I1 the system path creates the LT draft');
select is((public.draft_start_internal('b1160000-0000-4000-8000-000000000003', false) ->> 'started')::boolean, true,
  'I2 the system path starts the LT draft (the auto-start)');
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000003'), 0,
  'I3 system: the tick create and start write no receipt');

-- ---------------------------------------------------------------------------
-- J. The receipts cannot be edited, and members read them (§10.3 / §12.12)
-- ---------------------------------------------------------------------------
select throws_ok($$ update commissioner_actions set reason = 'edited' where league_id = 'b1160000-0000-4000-8000-000000000001' $$,
  'P0001', null, 'J1 even the owner cannot edit a draft receipt (the 123 immutability trigger)');
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000001'), 13,
  'J2 a manager reads all thirteen LS receipts (the log is member-visible)');
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000003", "role": "authenticated"}', true);
select is((select count(*)::int from commissioner_actions where league_id::text like 'b1160000-%'), 0,
  'J3 a non-member reads none');

-- ---------------------------------------------------------------------------
-- K. Held lock re-measured (§8.3 < 50 ms; min RTT of three — the 060 K shape)
-- ---------------------------------------------------------------------------
reset role;
select set_config('request.jwt.claims', '', true);
create temp table rc_rtt (verb text, secs double precision) on commit drop;
grant select, insert on rc_rtt to authenticated;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "96116000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
do $$
declare v_t0 timestamptz; v_i int; begin
  for v_i in 1..3 loop
    v_t0 := clock_timestamp();
    perform public.draft_force_pick('e1160000-0000-4000-8000-000000000004', 'rc-p2' || v_i, null);
    insert into rc_rtt values ('draft_force_pick', extract(epoch from clock_timestamp() - v_t0));
  end loop;
  perform public.draft_pause('e1160000-0000-4000-8000-000000000004');
  for v_i in 1..3 loop
    v_t0 := clock_timestamp();
    perform public.draft_undo('e1160000-0000-4000-8000-000000000004');
    insert into rc_rtt values ('draft_undo', extract(epoch from clock_timestamp() - v_t0));
  end loop;
end $$;
select is((select count(*)::int from commissioner_actions where league_id = 'b1160000-0000-4000-8000-000000000004'), 7,
  'K1 premise: the timed calls each wrote their receipt (three picks, the pause, three undos)');
select cmp_ok((select min(secs) from rc_rtt where verb = 'draft_force_pick'), '<', 0.05::double precision,
  'K2 held-lock discipline: the min RTT of three draft_force_pick calls, receipt included, is under 50 ms');
select cmp_ok((select min(secs) from rc_rtt where verb = 'draft_undo'), '<', 0.05::double precision,
  'K3 held-lock discipline: the min RTT of three draft_undo calls, receipt included, is under 50 ms');
select diag(format('K measured (min of three): draft_force_pick %s ms, draft_undo %s ms',
  (select round((min(secs) * 1000)::numeric, 2) from rc_rtt where verb = 'draft_force_pick'),
  (select round((min(secs) * 1000)::numeric, 2) from rc_rtt where verb = 'draft_undo')));

select * from finish();
rollback;
