-- ============================================================================
-- 117 — receipts for membership, invites and league setup (migration 169;
--       M6 L.E1.30; F32, F514; spec §10.3, §12.12, §15.1; PROGRESS D441,
--       D336, D449, D450)
-- ============================================================================
-- What this file proves, per function, over REAL calls:
--   change   ⇒ exactly ONE commissioner_actions row (actor, type, target,
--              before / after pinned as stored literals);
--   no-op    ⇒ none (the function's own early return, a replay, or the
--              seam's by-value detection — the same role / slug / name /
--              settings / rules / lineup again);
--   manager  ⇒ 42501, unchanged, and nothing written.
-- Plus: remove_manager's three outcomes NAMED; the role changes and the
-- placeholder seat named; a settings save and a scoring save recorded per
-- CHANGED key; THE PRIVACY NEGATIVE (by value, over every row written: no
-- before / after / metadata / reason holds an invite token, an invited_email,
-- an invited_username or an invite code); members read the new rows and an
-- outsider reads none; F514 (a commissioner setting a team he does not
-- manage writes one receipt acting for it; a no-op, a replay, a manager's
-- own save and the commissioner's own team write none); D137 in the
-- database (pg_temp.un169 reverses 169 to each newest definer's file text).
--
-- Worlds (all fabricated inside this rolled-back transaction):
--   LM b117…01  setup — u1 commissioner (t1), u2 manager (t2), u3 manager (t3)
--   LI b117…02  in_season, week 6 live — u1 (t1), u2 (t2), u3 (t3)
--   LD b117…03  setup — u1 commissioner (t1), u2 manager (t2): the transfer
--               and the soft delete
--   u4 / u5 hold no seat (assign / takeover); u6 is an outsider; u7 is the
--   username invite's account.
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(99);

-- pg_temp.un169 — 169's substitutions reversed (generated by derive_169.py
-- with the migration; each replacement text is unique to its body, so the
-- order does not matter). Applied to a live prosrc it yields the source.
create function pg_temp.un169(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$    (p_league_id, NULL, v_team_id, 'manager', TRUE, v_league.faab_budget)
  RETURNING id INTO v_member_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: the seat just added, named. A new seat
  -- is always a change (every refusal above writes nothing).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'add_placeholder_seat', 'add_seat', 'team',
    v_team_id::text, NULL,
    NULL,
    jsonb_build_object('team_id', v_team_id, 'team_name', v_name, 'placeholder', TRUE),
    jsonb_build_object('member_id', v_member_id, 'seats_filled', v_seated + 1,
                       'team_count', v_league.team_count,
                       'affected_team_ids', jsonb_build_array(v_team_id)));
$r$, $o$    (p_league_id, NULL, v_team_id, 'manager', TRUE, v_league.faab_budget)
  RETURNING id INTO v_member_id;
$o$);  -- add_placeholder_seat
  s := replace(s, $r$    UPDATE public.league_members
    SET role = 'commissioner'
    WHERE id = p_member_id;
    -- 169/L.E1.30 (F32) — THE RECEIPT: the commissioner role handed over
    -- (the replay of a completed transfer returned above).
    PERFORM public.draft_commish_receipt_internal(
      p_league_id, FALSE, 'set_member_role', 'transfer_commissioner', 'member',
      p_member_id::text, NULL,
      jsonb_build_object('role', v_target.role, 'commissioner_user_id', v_uid),
      jsonb_build_object('role', 'commissioner', 'commissioner_user_id', v_target.user_id),
      jsonb_build_object('user_id', v_target.user_id,
                         'previous_commissioner_user_id', v_uid,
                         'previous_commissioner_role', 'co_commissioner'));
$r$, $o$    UPDATE public.league_members
    SET role = 'commissioner'
    WHERE id = p_member_id;
$o$);  -- set_member_role
  s := replace(s, $r$  UPDATE public.league_members
  SET role = p_role
  WHERE id = p_member_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: the role change, named (manager ↔
  -- co-commissioner; the same-role no-op returned above).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'set_member_role',
    CASE WHEN p_role = 'co_commissioner' THEN 'promote_member' ELSE 'demote_member' END,
    'member', p_member_id::text, NULL,
    jsonb_build_object('role', v_target.role),
    jsonb_build_object('role', p_role),
    jsonb_build_object('user_id', v_target.user_id));
$r$, $o$  UPDATE public.league_members
  SET role = p_role
  WHERE id = p_member_id;
$o$);  -- set_member_role
  s := replace(s, $r$  SELECT lm.id INTO v_member_id
  FROM public.league_members lm
  WHERE lm.league_id = p_league_id AND lm.user_id = p_user_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: who now manages the franchise. `before`
  -- is the seat as the checks above proved it (no open stint — no manager).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'assign_manager', 'assign_manager', 'team',
    p_team_id::text, NULL,
    jsonb_build_object('manager_user_id', NULL, 'team_status', v_team.status),
    jsonb_build_object('manager_user_id', p_user_id,
                       'team_status', (SELECT t.status FROM public.teams t WHERE t.id = p_team_id)),
    jsonb_build_object('member_id', v_member_id,
                       'team_name', (SELECT t.name FROM public.teams t WHERE t.id = p_team_id),
                       'affected_team_ids', jsonb_build_array(p_team_id)));
$r$, $o$  SELECT lm.id INTO v_member_id
  FROM public.league_members lm
  WHERE lm.league_id = p_league_id AND lm.user_id = p_user_id;
$o$);  -- assign_manager
  s := replace(s, $r$  UPDATE public.teams
  SET owner_id = v_uid,
      updated_at = now()
  WHERE league_id = p_league_id
    AND owner_id = v_removed_user
    AND id <> v_team.id;

  -- 169/L.E1.30 (F32) — THE RECEIPT, one per removal, the outcome NAMED
  -- (§7.2.1: takeover / retire / vacate). before / after are the seat as
  -- it stood and as it stands now (read back, never inferred).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'remove_manager',
    CASE p_mode WHEN 'takeover' THEN 'replace_manager'
                WHEN 'retire'   THEN 'retire_franchise'
                ELSE 'vacate_seat' END,
    'team', v_team.id::text, p_reason,
    jsonb_build_object('manager_user_id', v_removed_user, 'team_status', v_team.status),
    jsonb_build_object(
      'manager_user_id', (SELECT lm.user_id FROM public.league_members lm WHERE lm.id = v_target.id),
      'team_status',     (SELECT t.status FROM public.teams t WHERE t.id = v_team.id))
    || CASE WHEN p_mode = 'retire' THEN jsonb_build_object(
         'successor_team_id', v_successor_id, 'successor_team_name', v_successor_name,
         'retired_at_week', v_week) ELSE '{}'::jsonb END,
    jsonb_build_object('mode', p_mode, 'member_id', v_target.id, 'team_name', v_team_name,
                       'affected_team_ids', CASE WHEN p_mode = 'retire'
                                                 THEN jsonb_build_array(v_team.id, v_successor_id)
                                                 ELSE jsonb_build_array(v_team.id) END)
    || CASE WHEN p_mode = 'retire' THEN jsonb_build_object(
         'action_id', p_action_id, 'repointed', v_result -> 'repointed') ELSE '{}'::jsonb END);
$r$, $o$  UPDATE public.teams
  SET owner_id = v_uid,
      updated_at = now()
  WHERE league_id = p_league_id
    AND owner_id = v_removed_user
    AND id <> v_team.id;
$o$);  -- remove_manager
  s := replace(s, $r$  v_existing RECORD;
  v_invite RECORD;
  v_prev_sent TIMESTAMPTZ;  -- 169/L.E1.30: the re-sent invite's last send, for the receipt
BEGIN
$r$, $o$  v_existing RECORD;
  v_invite RECORD;
BEGIN
$o$);  -- create_league_invite
  s := replace(s, $r$    IF FOUND THEN
      v_prev_sent := (SELECT i.last_sent_at FROM public.league_invites i WHERE i.id = v_existing.id);  -- 169/L.E1.30
      UPDATE public.league_invites
      SET last_sent_at = now()
      WHERE id = v_existing.id;
      -- 169/L.E1.30 (F32) — THE RECEIPT for a re-send (D46): the invite and
      -- its seat, never the token or who it was sent to (TD9).
      PERFORM public.draft_commish_receipt_internal(
        p_league_id, FALSE, 'create_league_invite', 'resend_invite', 'invite',
        v_existing.id::text, NULL,
        jsonb_build_object('last_sent_at', v_prev_sent),
        jsonb_build_object('last_sent_at', now()),
        jsonb_build_object('target_team_id', p_target_team_id, 'team_name', v_team_name,
                           'kind', CASE WHEN p_invited_email IS NOT NULL THEN 'email' ELSE 'username' END,
                           'affected_team_ids', CASE WHEN p_target_team_id IS NULL THEN '[]'::jsonb
                                                     ELSE jsonb_build_array(p_target_team_id) END));
$r$, $o$    IF FOUND THEN
      UPDATE public.league_invites
      SET last_sent_at = now()
      WHERE id = v_existing.id;
$o$);  -- create_league_invite
  s := replace(s, $r$  RETURNING id, token, expires_at INTO v_invite;

  -- 169/L.E1.30 (F32) — THE RECEIPT: "an invite for <team>" (or a league
  -- invite), its kind and its limits — never the token, the email or the
  -- username (TD9; the log is member-readable, §10.3).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'create_league_invite', 'create_invite', 'invite',
    v_invite.id::text, NULL,
    NULL,
    jsonb_build_object('target_team_id', p_target_team_id, 'team_name', v_team_name,
                       'kind', CASE WHEN p_invited_email IS NOT NULL THEN 'email'
                                    WHEN p_invited_username IS NOT NULL THEN 'username'
                                    ELSE 'link' END,
                       'max_uses', p_max_uses, 'expires_at', v_invite.expires_at),
    jsonb_build_object('affected_team_ids', CASE WHEN p_target_team_id IS NULL THEN '[]'::jsonb
                                                 ELSE jsonb_build_array(p_target_team_id) END));
$r$, $o$  RETURNING id, token, expires_at INTO v_invite;
$o$);  -- create_league_invite
  s := replace(s, $r$  UPDATE public.league_invites
  SET revoked_at = now()
  WHERE id = p_invite_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: the invite and its seat, never the
  -- token or who it was for (TD9).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'revoke_league_invite', 'revoke_invite', 'invite',
    p_invite_id::text, NULL,
    jsonb_build_object('revoked', FALSE),
    jsonb_build_object('revoked', TRUE),
    (SELECT jsonb_build_object(
       'target_team_id', i.target_team_id,
       'team_name', (SELECT t.name FROM public.teams t WHERE t.id = i.target_team_id),
       'affected_team_ids', CASE WHEN i.target_team_id IS NULL THEN '[]'::jsonb
                                 ELSE jsonb_build_array(i.target_team_id) END)
     FROM public.league_invites i WHERE i.id = p_invite_id));
$r$, $o$  UPDATE public.league_invites
  SET revoked_at = now()
  WHERE id = p_invite_id;
$o$);  -- revoke_league_invite
  s := replace(s, $r$  -- 169/L.E1.30 (F32) — THE RECEIPT: the code was replaced. Neither code is
  -- recorded (a join credential — TD9).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'rotate_invite_code', 'rotate_invite_code', 'league',
    p_league_id::text, NULL,
    NULL,
    jsonb_build_object('invite_code_rotated', TRUE),
    NULL);

  RETURN jsonb_build_object('invite_code', v_code);
$r$, $o$  RETURN jsonb_build_object('invite_code', v_code);
$o$);  -- rotate_invite_code
  s := replace(s, $r$DECLARE
  v_slug TEXT;
  v_old_slug TEXT;  -- 169/L.E1.30: the slug as it stood, for the receipt
BEGIN
$r$, $o$DECLARE
  v_slug TEXT;
BEGIN
$o$);  -- set_league_invite_slug
  s := replace(s, $r$  v_old_slug := (SELECT l.invite_slug::text FROM public.leagues l WHERE l.id = p_league_id);  -- 169/L.E1.30

  -- NULL clears the slug (§15.1 "set/clear"): joins fall back to the code.
  IF p_slug IS NULL THEN
    UPDATE public.leagues
    SET invite_slug = NULL,
        updated_at = now()
    WHERE id = p_league_id;
    -- 169/L.E1.30 (F32) — THE RECEIPT (none when there was no slug to clear).
    PERFORM public.draft_commish_receipt_internal(
      p_league_id, FALSE, 'set_league_invite_slug', 'set_invite_slug', 'league',
      p_league_id::text, NULL,
      jsonb_build_object('invite_slug', v_old_slug),
      jsonb_build_object('invite_slug', NULL),
      NULL);
$r$, $o$  -- NULL clears the slug (§15.1 "set/clear"): joins fall back to the code.
  IF p_slug IS NULL THEN
    UPDATE public.leagues
    SET invite_slug = NULL,
        updated_at = now()
    WHERE id = p_league_id;
$o$);  -- set_league_invite_slug
  s := replace(s, $r$  -- 169/L.E1.30 (F32) — THE RECEIPT (none when the slug is the one it had).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'set_league_invite_slug', 'set_invite_slug', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('invite_slug', v_old_slug),
    jsonb_build_object('invite_slug', v_slug),
    NULL);

  RETURN jsonb_build_object('invite_slug', v_slug);
$r$, $o$  RETURN jsonb_build_object('invite_slug', v_slug);
$o$);  -- set_league_invite_slug
  s := replace(s, $r$  v_attach_rules JSONB;   -- D169 arm (b)
  v_prior JSONB;          -- 169/L.E1.30: the settings as they stood, for the receipt
  v_diff JSONB;           -- 169/L.E1.30: the keys that changed
BEGIN
$r$, $o$  v_attach_rules JSONB;   -- D169 arm (b)
BEGIN
$o$);  -- update_league_settings
  s := replace(s, $r$  v_prior := public.league_settings_doc_internal(p_league_id);  -- 169/L.E1.30

  -- 7. The atomic write: every §12.1 typed column + blob as passed, and
$r$, $o$  -- 7. The atomic write: every §12.1 typed column + blob as passed, and
$o$);  -- update_league_settings
  s := replace(s, $r$    UPDATE public.league_members
    SET faab_balance = p_faab_budget
    WHERE league_id = p_league_id;
  END IF;

  -- 169/L.E1.30 (F32) — THE RECEIPT: ONE row for the save, carrying exactly
  -- the settings that changed, each by its §7.3 key (the typed columns by
  -- name, each settings key, roster_settings whole — commish_change_setting's
  -- key space); a save that changes nothing writes nothing (by value).
  v_diff := public.league_receipt_diff_internal(
    v_prior, public.league_settings_doc_internal(p_league_id), 1);
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'update_league_settings', 'change_settings', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('settings', v_diff -> 'before'),
    jsonb_build_object('settings', v_diff -> 'after'),
    jsonb_build_object('keys', (SELECT COALESCE(jsonb_agg(k ORDER BY k), '[]'::jsonb)
                                FROM jsonb_object_keys(v_diff -> 'after') k),
                       'league_status', v_status));
$r$, $o$    UPDATE public.league_members
    SET faab_balance = p_faab_budget
    WHERE league_id = p_league_id;
  END IF;
$o$);  -- update_league_settings
  s := replace(s, $r$DECLARE
  v_name TEXT;
  v_prior JSONB;  -- 169/L.E1.30: the profile as it stood, for the receipt
  v_diff JSONB;   -- 169/L.E1.30
BEGIN
$r$, $o$DECLARE
  v_name TEXT;
BEGIN
$o$);  -- update_league_profile
  s := replace(s, $r$  SELECT jsonb_build_object('name', l.name, 'avatar_url', l.avatar_url) INTO v_prior
  FROM public.leagues l WHERE l.id = p_league_id FOR UPDATE;  -- 169/L.E1.30

  IF p_name IS NOT NULL THEN
    v_name := btrim(p_name);
$r$, $o$  IF p_name IS NOT NULL THEN
    v_name := btrim(p_name);
$o$);  -- update_league_profile
  s := replace(s, $r$    SET avatar_url = p_avatar_url, updated_at = now()
    WHERE id = p_league_id;
  END IF;

  -- 169/L.E1.30 (F32) — THE RECEIPT: exactly what changed (name, avatar).
  v_diff := public.league_receipt_diff_internal(
    v_prior,
    (SELECT jsonb_build_object('name', l.name, 'avatar_url', l.avatar_url)
     FROM public.leagues l WHERE l.id = p_league_id));
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'update_league_profile', 'edit_league_profile', 'league',
    p_league_id::text, NULL,
    v_diff -> 'before', v_diff -> 'after', NULL);
$r$, $o$    SET avatar_url = p_avatar_url, updated_at = now()
    WHERE id = p_league_id;
  END IF;
$o$);  -- update_league_profile
  s := replace(s, $r$  UPDATE public.leagues
  SET status = p_status,
      updated_at = NOW()
  WHERE id = p_league_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: the lifecycle move.
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'set_league_status', 'lifecycle_change', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('status', v_status),
    jsonb_build_object('status', p_status),
    NULL);
$r$, $o$  UPDATE public.leagues
  SET status = p_status,
      updated_at = NOW()
  WHERE id = p_league_id;
$o$);  -- set_league_status
  s := replace(s, $r$  UPDATE public.leagues
  SET deleted_at = NOW(),
      updated_at = NOW()
  WHERE id = p_league_id;

  -- 169/L.E1.30 (F32) — THE RECEIPT: the league was deleted (soft — rule 8).
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'soft_delete_league', 'delete_league', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('deleted', FALSE),
    jsonb_build_object('deleted', TRUE),
    NULL);
$r$, $o$  UPDATE public.leagues
  SET deleted_at = NOW(),
      updated_at = NOW()
  WHERE id = p_league_id;
$o$);  -- soft_delete_league
  s := replace(s, $r$  -- 169/L.E1.30 (F32) — THE RECEIPT: the league now scores by its own
  -- custom copy of the template.
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'scoring_fork_template', 'fork_scoring', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('scoring_system_id', v_current),
    jsonb_build_object('scoring_system_id', v_new_id),
    jsonb_build_object('template_id', p_template_id, 'scoring_system_name', v_name || ' Custom'));

  RETURN v_new_id;
$r$, $o$  RETURN v_new_id;
$o$);  -- scoring_fork_template
  s := replace(s, $r$  v_owner       UUID;
  v_rows        INT;
  v_prior_rules JSONB;  -- 169/L.E1.30: the document as it stood, for the receipt
  v_diff        JSONB;  -- 169/L.E1.30
BEGIN
$r$, $o$  v_owner       UUID;
  v_rows        INT;
BEGIN
$o$);  -- scoring_update_rules
  s := replace(s, $r$  PERFORM public.scoring_rules_validate(p_rules);

  v_prior_rules := (SELECT s.rules FROM public.scoring_systems s WHERE s.id = v_current);  -- 169/L.E1.30
  UPDATE public.scoring_systems
$r$, $o$  PERFORM public.scoring_rules_validate(p_rules);

  UPDATE public.scoring_systems
$o$);  -- scoring_update_rules
  s := replace(s, $r$  -- 169/L.E1.30 (F32) — THE RECEIPT: ONE row for the save, carrying exactly
  -- the rules that changed, each by its path in the document
  -- ("base.receptions", "positions.TE.receptions"); an unchanged save writes
  -- nothing (by value).
  v_diff := public.league_receipt_diff_internal(v_prior_rules, p_rules);
  PERFORM public.draft_commish_receipt_internal(
    p_league_id, FALSE, 'scoring_update_rules', 'edit_scoring', 'league',
    p_league_id::text, NULL,
    jsonb_build_object('scoring_rules', v_diff -> 'before'),
    jsonb_build_object('scoring_rules', v_diff -> 'after'),
    jsonb_build_object('scoring_system_id', v_current,
                       'keys', (SELECT COALESCE(jsonb_agg(k ORDER BY k), '[]'::jsonb)
                                FROM jsonb_object_keys(v_diff -> 'after') k)));

  RETURN v_current;
$r$, $o$  RETURN v_current;
$o$);  -- scoring_update_rules
  s := replace(s, $r$      INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)
      VALUES (p_league_id, auth.uid(), v_message, 'league', TRUE);
      -- 169/L.E1.30 (F514) — THE RECEIPT: a commissioner setting a team he
      -- does not manage is a commissioner action (D363(2)) — one row per
      -- changed lineup, the team acted for in acting_as_team_id (§10.3). The
      -- no-op re-save wrote nothing above; a manager's own save (the
      -- commissioner's own team included) is not this arm.
      PERFORM public.draft_commish_receipt_internal(
        p_league_id, FALSE, 'set_lineup', 'edit_lineup', 'team', p_team_id::text, v_reason,
        jsonb_build_object('slot_map', v_stored),
        jsonb_build_object('slot_map', v_canon)
          || CASE WHEN jsonb_array_length(v_ir_placed) + jsonb_array_length(v_ir_removed) > 0
                  THEN jsonb_build_object('ir_moves', jsonb_build_object('placed', v_ir_placed, 'removed', v_ir_removed))
                  ELSE '{}'::jsonb END,
        jsonb_build_object('week', p_week, 'current_week', v_current, 'season', v_league.season,
                           'week_status', v_lw.status, 'team_name', v_team.name, 'action_id', p_action_id),
        p_team_id);
    END IF;
$r$, $o$      INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)
      VALUES (p_league_id, auth.uid(), v_message, 'league', TRUE);
    END IF;
$o$);  -- set_lineup_internal
  return s;
end
$un$;

-- L.E1.40 (migration 173 — additive, the R992 shape): pg_temp.un173 reverses
-- 173's three remove_manager hunks (verbatim from pgTAP 121). Applied
-- INNERMOST, so A3 / A4 keep the literals 169 stored.
create function pg_temp.un173(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$    -- (b) The audit stamp and the reason (E49 "audited override"; D290's
    --     interim posture: reason REQUIRED, stored on the ledger row).
    --     173 / F363(a) — Q66 (v2.16.41, C82): the reason is OPTIONAL. Blank
    --     or whitespace-only (the explicit class, 123:295 — R1328: the same
    --     class the receipt seam trims) is NULL; past 500 characters the
    --     receipt seam refuses it BY NAME (168:196) and the whole retirement
    --     rolls back. The action_id stays REQUIRED (the replay stamp).
$r$, $o$    -- (b) The audit stamp and the reason (E49 "audited override"; D290's
    --     interim posture: reason REQUIRED, stored on the ledger row).
$o$);
  s := replace(s, $r$    v_reason := NULLIF(btrim(COALESCE(p_reason, ''), E' \t\r\n'), '');
$r$, $o$    v_reason := NULLIF(btrim(COALESCE(p_reason, '')), '');
    IF v_reason IS NULL THEN
      RAISE EXCEPTION 'remove_manager: retiring a franchise is an audited override — a reason is required (E49 / D290)'
        USING ERRCODE = '22023';
    END IF;
$o$);
  s := replace(s, $r$      || ' (roster and record carry over for seeding only; head-to-head history does not — §7.2.1(b))'
      -- 173 / Q66: no reason, no "— reason:" tail (league_chat.message is
      -- NOT NULL — `|| NULL` would null the whole post).
      || CASE WHEN v_reason IS NOT NULL THEN ' — reason: ' || v_reason ELSE '' END;
$r$, $o$      || ' (roster and record carry over for seeding only; head-to-head history does not — §7.2.1(b)) — reason: ' || v_reason;
$o$);
  return s;
end
$un$;

-- L.E1.42 (migration 176 — additive, the R992 shape): pg_temp.un176 reverses
-- 176's three remove_manager hunks (verbatim from pgTAP 124). Applied
-- INNERMOST, so A3 / A4 keep the literals 169 / 173 stored.
create function pg_temp.un176(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$    RAISE EXCEPTION 'remove_manager: mode must be takeover or vacate (§7.2.1)'
$r$, $o$    RAISE EXCEPTION 'remove_manager: mode must be takeover, retire, or vacate (§7.2.1)'
$o$);
  s := replace(s, $r$  -- 176 (L.E1.42 — Chris 2026-10-01): a team is NEVER retired. "you can't
  -- simply retire a Team, you can change the manager but the Team lives."
  -- When a manager goes there are two outcomes: takeover (a new manager
  -- inherits the team whole) or vacate (the team stays; the commissioner
  -- runs it). 'retire' stays a NAMED mode so it is refused in plain words,
  -- in every league state. The refusal sits AFTER the replay (L.D3.16's
  -- shape): a retry of a retirement committed before 176 still returns its
  -- stored payload byte-identical (none exist in production — measured
  -- 2026-10-01). Nothing below this block can see p_mode = 'retire'.
  IF p_mode = 'retire' THEN
    IF p_action_id IS NOT NULL THEN
      SELECT t.type, t.payload INTO v_replay
      FROM public.transactions t
      WHERE t.league_id = p_league_id AND t.action_id = p_action_id;
      IF FOUND
         AND v_replay.type = 'commissioner_move'
         AND v_replay.payload ->> 'verb' = 'retire_franchise'
         AND (v_replay.payload ->> 'member_id')::uuid = p_member_id THEN
        RETURN v_replay.payload;
      END IF;
    END IF;
    RAISE EXCEPTION 'remove_manager: a team can''t be retired — seat a new manager or leave it vacant (§7.2.1)'
      USING ERRCODE = 'P0001';
  END IF;
$r$, $o$  -- 120 (L.D1.10): retire-and-succeed is REAL now (§7.2.1(b) / D301 / F31).
  IF p_mode = 'retire' THEN
    -- (a) The status gate. Before the draft D42's refusal stands byte for
    --     byte (017 J pins it; a franchise has no roster or record to
    --     inherit). `in_season` (the LAW's "mid-season … audited override")
    --     and `complete` ("primarily an offseason action") proceed.
    --     `playoffs` REFUSES BY NAME: §7.2.1(b) / §11.5 print nothing about
    --     a retired franchise's bracket line (does the successor play it,
    --     or is it forfeited?) and 118's sync derives later rounds from the
    --     played rows' team ids — PROGRESS Q41 carries the question; this
    --     arm is a refusal, never a fold (R801).
    IF v_league.status IN ('setup', 'scheduled', 'drafting') THEN
      RAISE EXCEPTION 'remove_manager: retiring a franchise isn''t available before the draft — use takeover or vacate (§7.2.1; retire-and-succeed arrives with the in-season milestone)'
        USING ERRCODE = 'P0001';
    ELSIF v_league.status = 'playoffs' THEN
      RAISE EXCEPTION 'remove_manager: retiring a franchise during the playoffs is not defined yet — what the bracket does with a retired franchise''s line is PROGRESS Q41; use takeover or vacate now, or retire the franchise after the season (§7.2.1(b))'
        USING ERRCODE = 'P0001';
    ELSIF v_league.status NOT IN ('in_season', 'complete') THEN
      RAISE EXCEPTION 'remove_manager: league status % admits no retirement (§7.1)', v_league.status
        USING ERRCODE = 'P0001';
    END IF;
    -- (a′) R858: the actor's OWN seat. §7.2.1 gives the leaver no choice of
    --      outcome — leave_league is the voluntary path — and the route's
    --      self-DELETE dispatches there; a co-commissioner calling the RPC
    --      directly must not get the choice back. (A plain manager never
    --      reaches here: not a commissioner, 42501 above.)
    IF v_target.user_id = v_uid THEN
      RAISE EXCEPTION 'remove_manager: you cannot retire your own franchise — a leaver has no choice of outcome (§7.2.1); leave the league, or have the commissioner act on your seat'
        USING ERRCODE = '42501';
    END IF;
    -- (b) The audit stamp and the reason (E49 "audited override"; D290's
    --     interim posture: reason REQUIRED, stored on the ledger row).
    --     173 / F363(a) — Q66 (v2.16.41, C82): the reason is OPTIONAL. Blank
    --     or whitespace-only (the explicit class, 123:295 — R1328: the same
    --     class the receipt seam trims) is NULL; past 500 characters the
    --     receipt seam refuses it BY NAME (168:196) and the whole retirement
    --     rolls back. The action_id stays REQUIRED (the replay stamp).
    IF p_action_id IS NULL THEN
      RAISE EXCEPTION 'remove_manager: retire requires action_id (idempotency key — one UUID per retirement, reused on retry; 113''s contract)'
        USING ERRCODE = '22023';
    END IF;
    v_reason := NULLIF(btrim(COALESCE(p_reason, ''), E' \t\r\n'), '');
    -- (c) REPLAY by (league_id, action_id) — 113's contract (R732): the
    --     stored payload byte-identical; the same stamp on another verb or
    --     another member is a shape violation. Checked BEFORE the seat
    --     checks below: after a committed retirement the seat is an open
    --     placeholder and would otherwise refuse the retry by name.
    SELECT t.type, t.payload INTO v_replay
    FROM public.transactions t
    WHERE t.league_id = p_league_id AND t.action_id = p_action_id;
    IF FOUND THEN
      IF v_replay.type <> 'commissioner_move'
         OR v_replay.payload ->> 'verb' IS DISTINCT FROM 'retire_franchise'
         OR (v_replay.payload ->> 'member_id')::uuid IS DISTINCT FROM p_member_id THEN
        RAISE EXCEPTION 'remove_manager: action_id % already names another action in this league — an action_id identifies ONE submit of ONE verb (R732)', p_action_id
          USING ERRCODE = '22023';
      END IF;
      RETURN v_replay.payload;
    END IF;
  END IF;
$o$);
  s := replace(s, $r$  ELSE
    -- vacate (§7.2.1(c)) — the stint closes with no successor.
$r$, $o$  ELSIF p_mode = 'retire' THEN
    -- (d) F1: the lineage this franchise sits in must be ACYCLIC before it
    --     is extended. The successor minted below is a NEW row (it cannot
    --     close a cycle by construction — said, D267), so the walk is over
    --     the PREDECESSOR chain as STORED: only privileged writes can
    --     corrupt it (D53: the column has no client writer), and a corrupt
    --     chain is refused BY NAME rather than misreported as "already
    --     sealed" (068 F; the DoD probe drops this block).
    WITH RECURSIVE lineage AS (
      SELECT t.id, 0 AS depth FROM public.teams t WHERE t.id = v_team.id
      UNION ALL
      SELECT p.id, l.depth + 1
      FROM lineage l JOIN public.teams p ON p.successor_team_id = l.id
      WHERE l.depth < 64
    ) CYCLE id SET is_cycle USING path
    SELECT l.is_cycle, array_length(l.path, 1) - 1 AS len INTO v_cycle
    FROM lineage l WHERE l.is_cycle
    ORDER BY array_length(l.path, 1) LIMIT 1;
    IF FOUND THEN
      RAISE EXCEPTION 'remove_manager: % sits in a succession CYCLE of length % (the successor_team_id chain revisits a franchise) — refused; repair the lineage before extending it (§12.22 / F1)', v_team_name, v_cycle.len
        USING ERRCODE = 'P0001';
    END IF;
    IF v_team.status = 'retired' OR v_team.successor_team_id IS NOT NULL THEN
      RAISE EXCEPTION 'remove_manager: % is already sealed (status %, successor %) — a retired franchise cannot be retired again (§7.2.1(b))', v_team_name, v_team.status, v_team.successor_team_id
        USING ERRCODE = 'P0001';
    END IF;
    -- (d′) R855: an UNMANAGED seat (vacated / left — 'orphaned', §7.2.1(c))
    --      is admitted when the franchise has a CLOSED stint: the seal
    --      names the LAST manager (History Mode reads the stints; nothing
    --      else is written under a name), no stint is open to close (the
    --      (h) UPDATE matches nothing — D63), no one is notified,
    --      removed_user_id is NULL in the payload. A franchise that has
    --      NEVER had a manager — 120's own successor until it is claimed,
    --      or a placeholder seat autopick-drafted and never claimed — has
    --      no name to seal under and refuses BY NAME.
    IF v_removed_user IS NULL THEN
      PERFORM 1 FROM public.team_managers tm
      WHERE tm.team_id = v_team.id AND tm.ended_at IS NOT NULL;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'remove_manager: % has never had a manager — there is no one to seal it under; use assign-manager to seat someone on it first (§7.2.1(b))', v_team_name
          USING ERRCODE = 'P0001';
      END IF;
    END IF;

    -- (e) The founding week of the successor's book — the first week the
    --     league has NOT yet played: 1 + its last correction_window/final
    --     week (a reopened earlier week stays the predecessor's), else the
    --     first league week. NULL when that week does not exist (the
    --     season is over — `complete`, or every week played): nothing is
    --     re-pointed and History reads the whole book as the retired
    --     franchise's; retired_at_week / ended_week are NULL (§12.22's
    --     "NULL preseason" reading, extended to "outside the season").
    SELECT w.week INTO v_week
    FROM public.league_weeks w
    WHERE w.league_id = p_league_id AND w.season = v_league.season
      AND w.week = COALESCE(
        (SELECT max(x.week) + 1 FROM public.league_weeks x
         WHERE x.league_id = p_league_id AND x.season = v_league.season
           AND x.status IN ('correction_window', 'final')),
        (SELECT min(x.week) FROM public.league_weeks x
         WHERE x.league_id = p_league_id AND x.season = v_league.season));

    -- (f) The successor: a NEW franchise in the same slot (§7.2.1(b)),
    --     named by D74(5)'s series over the league's WHOLE franchise count
    --     (retired included — a retired franchise keeps its number, so the
    --     name cannot collide with a seat's default), owned by the acting
    --     commissioner like every placeholder (add_placeholder_seat),
    --     'orphaned': no manager until a takeover (§7.2.1(c)'s holding
    --     state; assign_manager / a seat claim return it to 'active' —
    --     D74(2)). It counts as seated in every capacity count.
    SELECT count(*)::int INTO v_franchises FROM public.teams t WHERE t.league_id = p_league_id;
    v_successor_name := 'Team ' || (v_franchises + 1)::text;
    INSERT INTO public.teams (owner_id, name, league_id, list_id, status)
    VALUES (v_uid, v_successor_name, p_league_id, NULL, 'orphaned')
    RETURNING id INTO v_successor_id;

    -- (g) SEAL the franchise: status, the partition week, the link. owner_id
    --     moves to the acting commissioner for the vacate arm's reason (the
    --     removed user's profile deletion would CASCADE the sealed franchise
    --     away — 001:495); name and record are frozen by the absence of any
    --     writer (§7.2.1(b)).
    UPDATE public.teams
    SET status = 'retired',
        retired_at_week = v_week,
        successor_team_id = v_successor_id,
        owner_id = v_uid,
        updated_at = now()
    WHERE id = v_team.id;

    -- (h) The stint closes `seat_retired` — the one §12.22 value M1 never
    --     wrote (D74(9)); the F3 close shape; a missing open stint is a
    --     no-op (D63). No stint opens: the successor has no manager yet.
    UPDATE public.team_managers
    SET ended_at = now(),
        ended_week = v_week,
        end_reason = 'seat_retired',
        ended_by = v_uid
    WHERE team_id = v_team.id AND ended_at IS NULL;

    -- (i) The seat: ONE league_members row per seat, always (§12.2) — the
    --     cache row is re-pointed at the successor as an OPEN placeholder
    --     (assign_manager / a seat-targeted invite fill it). faab_balance is
    --     deliberately NOT re-seeded: (b)'s "inherits FAAB" is the seat's
    --     balance carrying, which the in-place UPDATE does for free (D301:
    --     vacuous until M5 makes the balance live; the transfer line M5 need
    --     not write is this one).
    UPDATE public.league_members
    SET user_id = NULL,
        is_placeholder = TRUE,
        role = 'manager',
        team_id = v_successor_id
    WHERE id = v_target.id;

    -- (j) THE INHERITANCE, every re-point COUNTED (rule 10). The roster
    --     whole (072's per-row trigger broadcasts each row on league:<id>);
    --     the CURRENT and future weeks' lineups, matchups and results — the
    --     successor's book opens at v_week; past weeks stay the
    --     predecessor's (History partitions at retired_at_week — E49).
    --     league_player_pool carries no team reference (109); transactions,
    --     lineup_actions and the draft rows are history under the
    --     predecessor. A game-day lock is per PLAYER, evaluated from
    --     nfl_games at call time (115/Q34(B)) — a re-point unlocks no one.
    UPDATE public.league_rosters SET team_id = v_successor_id
    WHERE league_id = p_league_id AND team_id = v_team.id;
    GET DIAGNOSTICS v_n_rosters = ROW_COUNT;
    IF v_week IS NOT NULL THEN
      UPDATE public.team_lineups SET team_id = v_successor_id
      WHERE team_id = v_team.id AND season = v_league.season AND week >= v_week;
      GET DIAGNOSTICS v_n_lineups = ROW_COUNT;
      UPDATE public.matchups SET home_team_id = v_successor_id, updated_at = now()
      WHERE league_id = p_league_id AND season = v_league.season AND week >= v_week AND home_team_id = v_team.id;
      GET DIAGNOSTICS v_n_matchups = ROW_COUNT;
      UPDATE public.matchups SET away_team_id = v_successor_id, updated_at = now()
      WHERE league_id = p_league_id AND season = v_league.season AND week >= v_week AND away_team_id = v_team.id;
      GET DIAGNOSTICS v_n = ROW_COUNT;
      v_n_matchups := v_n_matchups + v_n;
      UPDATE public.team_week_results SET team_id = v_successor_id
      WHERE league_id = p_league_id AND season = v_league.season AND week >= v_week AND team_id = v_team.id;
      GET DIAGNOSTICS v_n_results = ROW_COUNT;
      UPDATE public.team_week_results SET opponent_team_id = v_successor_id
      WHERE league_id = p_league_id AND season = v_league.season AND week >= v_week AND opponent_team_id = v_team.id;
      GET DIAGNOSTICS v_n = ROW_COUNT;
      v_n_results := v_n_results + v_n;
      UPDATE public.team_week_results SET second_opponent_team_id = v_successor_id
      WHERE league_id = p_league_id AND season = v_league.season AND week >= v_week AND second_opponent_team_id = v_team.id;
      GET DIAGNOSTICS v_n = ROW_COUNT;
      v_n_results := v_n_results + v_n;
    END IF;

    -- (k) The payload — also the LEDGER row's, so a replay is byte-identical.
    v_result := jsonb_build_object(
      'ok', true, 'mode', p_mode, 'verb', 'retire_franchise', 'action_id', p_action_id,
      'member_id', v_target.id, 'team_id', v_team.id,
      'removed_user_id', v_removed_user, 'successor_user_id', NULL, 'already_vacant', false,
      'retired_team_id', v_team.id, 'retired_team_name', v_team_name,
      'successor_team_id', v_successor_id, 'successor_team_name', v_successor_name,
      'season', v_league.season, 'retired_at_week', v_week, 'reason', v_reason,
      'repointed', jsonb_build_object(
        'rosters', v_n_rosters, 'lineups', v_n_lineups, 'matchups', v_n_matchups, 'results', v_n_results),
      'inherits', jsonb_build_object(
        'roster', true, 'record', 'seeding_only', 'h2h_history', false, 'faab', 'seat_balance_kept'));
    -- (l) The ledger (D290 interim; 113's shape): ONE transactions row of
    --     type commissioner_move, commissioner-initiated (no initiator team),
    --     stamped with p_action_id; 119's trigger carries it to the feed.
    INSERT INTO public.transactions
      (league_id, type, status, initiator_team_id, initiated_by, payload, week, action_id)
    VALUES (p_league_id, 'commissioner_move', 'complete', NULL, v_uid, v_result, v_week, p_action_id);
    -- (m) The D97 in-transaction system post (111/113's shape).
    v_message := v_team_name || ' was retired by ' || public.draft_actor_name()
      || CASE WHEN v_removed_user IS NULL
           THEN ' — the vacant franchise is sealed under its last manager (§7.2.1(c)); '
           ELSE ' — the franchise is sealed under its final manager; ' END
      || v_successor_name
      || ' takes its slot' || CASE WHEN v_week IS NULL THEN ' after the season' ELSE ' from Week ' || v_week::text END
      || ' (roster and record carry over for seeding only; head-to-head history does not — §7.2.1(b))'
      -- 173 / Q66: no reason, no "— reason:" tail (league_chat.message is
      -- NOT NULL — `|| NULL` would null the whole post).
      || CASE WHEN v_reason IS NOT NULL THEN ' — reason: ' || v_reason ELSE '' END;
    INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)
    VALUES (p_league_id, v_uid, v_message, 'league', TRUE);
  ELSE
    -- vacate (§7.2.1(c)) — the stint closes with no successor.
$o$);
  return s;
end
$un$;

-- ---------------------------------------------------------------------------
-- A. Form, and D137 in the database
-- ---------------------------------------------------------------------------
select is(
  (select string_agg(format('%s:%s:%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE'),
                            has_function_privilege('authenticated', p.oid, 'EXECUTE'),
                            exists (select 1 from aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
                                    where a.privilege_type = 'EXECUTE' and a.grantee = 0)), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in ('league_receipt_diff_internal', 'league_settings_doc_internal')),
  'league_receipt_diff_internal:f:search_path="":f:f:f league_settings_doc_internal:f:search_path="":f:f:f',
  'A1 the two new helpers are PLAIN, search_path empty, and closed to anon, authenticated and PUBLIC (seams, not doors)');
select is(
  (select string_agg(format('%s:%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE'),
                            has_function_privilege('authenticated', p.oid, 'EXECUTE')), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'add_placeholder_seat', 'set_member_role', 'assign_manager', 'remove_manager',
     'create_league_invite', 'revoke_league_invite', 'rotate_invite_code', 'set_league_invite_slug',
     'update_league_settings', 'update_league_profile', 'set_league_status', 'soft_delete_league',
     'scoring_fork_template', 'scoring_update_rules', 'set_lineup_internal')),
  'add_placeholder_seat:t:search_path="":f:t assign_manager:t:search_path="":f:t '
  || 'create_league_invite:t:search_path="":f:t remove_manager:t:search_path="":f:t '
  || 'revoke_league_invite:t:search_path="":f:t rotate_invite_code:t:search_path="":f:t '
  || 'scoring_fork_template:t:search_path="":f:t scoring_update_rules:t:search_path="":f:t '
  || 'set_league_invite_slug:t:search_path="":f:t set_league_status:t:search_path="":f:t '
  || 'set_lineup_internal:f:search_path="":f:f set_member_role:t:search_path="":f:t '
  || 'soft_delete_league:t:search_path="":f:t update_league_profile:t:search_path="":f:t '
  || 'update_league_settings:t:search_path="":f:t',
  'A2 the fifteen replaced bodies keep one overload each, their DEFINER / plain posture, search_path empty, anon closed, and authenticated on the fourteen doors only');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un169(pg_temp.un173(pg_temp.un176(p.prosrc)))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'add_placeholder_seat', 'set_member_role', 'assign_manager', 'remove_manager',
     'create_league_invite', 'revoke_league_invite', 'rotate_invite_code', 'set_league_invite_slug',
     'update_league_settings', 'update_league_profile', 'set_league_status', 'soft_delete_league',
     'scoring_fork_template', 'scoring_update_rules', 'set_lineup_internal')),
  'add_placeholder_seat=7a276be79c6fa58a9e615ea156a8c8e5 assign_manager=58aa952eacc44a5859797014649a1b34 '
  || 'create_league_invite=0285e16f0ef02c6e353a0fe4c64aa926 remove_manager=df2ab5c77f0b5936ac0b1e30dd9fa33c '
  || 'revoke_league_invite=2cb43e5ad0d4a9425b7a97ed80516abc rotate_invite_code=0f88dc74d977be12b79497cc1f9b87f3 '
  || 'scoring_fork_template=1626ee041457cc40617ace01a43bc380 scoring_update_rules=0ebe670e11eceb1386e6f1e11f23623b '
  || 'set_league_invite_slug=fa7789b109a0e4e5aaf6da233ced2815 set_league_status=d2943892e3f96868678216a2280191cf '
  || 'set_lineup_internal=ca3307414057469da7ed5c0af0b29fe6 set_member_role=a97a6e5edf6ff08ae440447d76e513fa '
  || 'soft_delete_league=cb7b208f1856cea83f3ecf8a83722a83 update_league_profile=a00e4578603e579b1018c3382d4b1978 '
  || 'update_league_settings=fa301876833c5cba5fe27ae4455e7a2e',
  'A3 D137: each live body with 169 reversed is its NEWEST definer FILE TEXT (063 / 150 / 062 / 118 / 064 / 059 / 060 / 105 / 157 — stored md5 literals measured on the 168 chain)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un173(pg_temp.un176(p.prosrc))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'add_placeholder_seat', 'set_member_role', 'assign_manager', 'remove_manager',
     'create_league_invite', 'revoke_league_invite', 'rotate_invite_code', 'set_league_invite_slug',
     'update_league_settings', 'update_league_profile', 'set_league_status', 'soft_delete_league',
     'scoring_fork_template', 'scoring_update_rules', 'set_lineup_internal')),
  'add_placeholder_seat=c2c3b4df5f685c1c7c1d66c9e5d5d16d assign_manager=ddb16f4993b36011d348ce001a94705a '
  || 'create_league_invite=082f56743aaecc386b0110d81de2f19f remove_manager=06921fe6b49594376fdf7f521ba41c36 '
  || 'revoke_league_invite=cbc5db97b88ded7ca47662c7ef493bd3 rotate_invite_code=fc11ceb285f9f8e0565d4f33e463fa3f '
  || 'scoring_fork_template=76fbb4d2aa54a77b0f867d4f7c7f5efe scoring_update_rules=2a737dd7a75692e7bcae370618e6083f '
  || 'set_league_invite_slug=406d50399ee5a5b93c363dc3a10d265a set_league_status=b94ac2112a7b1aeeba50c8e7b4852f33 '
  || 'set_lineup_internal=36a62aed801182faf52dcd3f58f1a723 set_member_role=516483c5b214da865a808d26afceff50 '
  || 'soft_delete_league=cdcd56355f0cfc7404436753056729c0 update_league_profile=034aff016a77968b1b4eb4e17bf73098 '
  || 'update_league_settings=0afb6fffbfc688dc96a0fcc5bb4ad9d1',
  'A4 the fifteen live prosrc md5s — 169 as written (stored literals; remove_manager through pg_temp.un173(pg_temp.un176(…)) since 176, additive)');
select is(
  (select count(*)::int from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname not in (
     'add_placeholder_seat', 'set_member_role', 'assign_manager', 'remove_manager',
     'create_league_invite', 'revoke_league_invite', 'rotate_invite_code', 'set_league_invite_slug',
     'update_league_settings', 'update_league_profile', 'set_league_status', 'soft_delete_league',
     'scoring_fork_template', 'scoring_update_rules', 'set_lineup_internal')
     and pg_temp.un169(p.prosrc) <> p.prosrc),
  0,
  'A5 un169 is an identity on every other body in the schema — so the older suites that apply it innermost pin exactly what they pinned (additive, R992)');
select is(
  (select string_agg(p.proname || ':' || (length(p.prosrc) - length(replace(p.prosrc, 'public.draft_commish_receipt_internal(', '')))
                                           / length('public.draft_commish_receipt_internal('), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname in (
     'add_placeholder_seat', 'set_member_role', 'assign_manager', 'remove_manager',
     'create_league_invite', 'revoke_league_invite', 'rotate_invite_code', 'set_league_invite_slug',
     'update_league_settings', 'update_league_profile', 'set_league_status', 'soft_delete_league',
     'scoring_fork_template', 'scoring_update_rules', 'set_lineup_internal', 'set_lineup', 'leave_league')),
  'add_placeholder_seat:1 assign_manager:1 create_league_invite:2 leave_league:0 remove_manager:1 '
  || 'revoke_league_invite:1 rotate_invite_code:1 scoring_fork_template:1 scoring_update_rules:1 '
  || 'set_league_invite_slug:2 set_league_status:1 set_lineup:0 set_lineup_internal:1 set_member_role:2 '
  || 'soft_delete_league:1 update_league_profile:1 update_league_settings:1',
  'A6 every change path reaches the one seam (two arms each for the role, the invite and the slug), and neither the leave nor the set_lineup door does');
select is(
  public.league_receipt_diff_internal(
    '{"a": 1, "b": {"c": 2, "d": [1, 2]}, "e": {"f": 1}, "g": null}'::jsonb,
    '{"a": 1, "b": {"c": 3, "d": [1, 2]}, "e": {"f": 1}, "h": {"i": 4}}'::jsonb),
  '{"before": {"b.c": 2, "h": null}, "after": {"b.c": 3, "h": {"i": 4}}}'::jsonb,
  'A7 the diff helper: only the changed leaves, by path; an absent key reads as null; arrays are leaves; an added object is one leaf');
select is(
  public.league_receipt_diff_internal('{"a": {"x": 1}, "b": 2}'::jsonb, '{"a": {"x": 2}, "b": 2}'::jsonb, 1),
  '{"before": {"a": {"x": 1}}, "after": {"a": {"x": 2}}}'::jsonb,
  'A8 depth 1 compares the top-level keys only — a changed object is reported whole under its key');
select throws_ok(
  $$ select public.league_receipt_diff_internal('[]'::jsonb, '{}'::jsonb) $$,
  '22023', NULL,
  'A9 loud, never no change: a document that is not an object is refused by name');

-- ---------------------------------------------------------------------------
-- B. Fixtures (privileged, before any JWT claims — D49(7))
-- ---------------------------------------------------------------------------
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000',
       ('97117000-0000-4000-8000-00000000000' || i)::uuid,
       'authenticated', 'authenticated', 'pgtap-e117-u' || i || '@fieldscout.local', 'x', now(),
       '{"provider": "email", "providers": ["email"]}',
       ('{"username": "e117_user_' || i || '"}')::jsonb, now(), now()
from generate_series(1, 7) i;

insert into leagues (id, owner_id, name, season, status, team_count, regular_season_weeks, playoff_teams,
                     playoff_start_week, scoring_system_id, faab_budget, settings) values
  ('b1170000-0000-4000-8000-000000000001', '97117000-0000-4000-8000-000000000001', 'pgtap-e117-LM', 2026, 'setup', 8, 14, 4, 15,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'), 100,
   '{"median_game": false, "draft": {"draft_type": "snake", "draft_scheduled_at": "2099-09-01T18:00:00+00:00"}}'),
  ('b1170000-0000-4000-8000-000000000003', '97117000-0000-4000-8000-000000000001', 'pgtap-e117-LD', 2026, 'setup', 8, 14, 4, 15,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'), 100, '{}');
insert into leagues (id, owner_id, name, season, status, team_count, regular_season_weeks, playoff_teams, playoff_start_week,
                     scoring_system_id, scoring_rules_snapshot, lineup_lock, waiver_type, faab_budget, trade_review,
                     settings, roster_settings)
values ('b1170000-0000-4000-8000-000000000002', '97117000-0000-4000-8000-000000000001', 'pgtap-e117-LI', 2026, 'in_season', 8, 14, 0, 15,
        (select id from scoring_systems where is_template and name = 'ESPN Standard'),
        (select rules from scoring_systems where is_template and name = 'ESPN Standard'),
        'per_player_kickoff', 'none_fcfs', 100, 'none', '{}'::jsonb,
        '{"starting_slots": [{"key": "rb", "label": "RB", "eligible": ["RB"], "count": 2}], "bench": 4, "ir_slots": [], "swap_spots": 0}'::jsonb);

insert into teams (id, owner_id, name, league_id)
select ('c117000' || l || '-0000-4000-8000-00000000000' || i)::uuid,
       ('97117000-0000-4000-8000-00000000000' || i)::uuid,
       'e117-L' || l || '-t' || i,
       ('b1170000-0000-4000-8000-00000000000' || l)::uuid
from generate_series(1, 3) l, generate_series(1, 3) i
where not (l = 3 and i = 3);
insert into league_members (league_id, user_id, team_id, role, is_placeholder, faab_balance)
select t.league_id, t.owner_id, t.id,
       case when t.owner_id = '97117000-0000-4000-8000-000000000001' then 'commissioner' else 'manager' end, false, 100
from teams t where t.id::text like 'c117000%';
insert into team_managers (league_id, team_id, user_id, role)
select t.league_id, t.id, t.owner_id, 'manager' from teams t where t.id::text like 'c117000%';

-- LI: week 6 live (weeks 1–5 final); every player on an NFL team with no game
-- this week (no lock anywhere — F514 is about the receipt, not the lock).
insert into league_weeks (league_id, season, week)
select 'b1170000-0000-4000-8000-000000000002', 2026, w from generate_series(1, 14) w;
update league_weeks set status = 'live'  where league_id = 'b1170000-0000-4000-8000-000000000002' and week <= 6;
update league_weeks set status = 'correction_window' where league_id = 'b1170000-0000-4000-8000-000000000002' and week <= 5;
update league_weeks set status = 'final'             where league_id = 'b1170000-0000-4000-8000-000000000002' and week <= 5;
insert into players (id, full_name, position, team, status)
select 'e117-p' || i, 'E117 Player ' || i, 'RB', 'ZZ', 'Active' from generate_series(1, 6) i;
-- ZZ plays late in week 6 — after the instant every lineup call below uses.
insert into nfl_games (id, season, week, home_team, away_team, kickoff_at, status) values
  ('e117-g6', 2026, 6, 'ZZ', 'ZY', '2026-10-19 00:20:00+00', 'scheduled');
insert into league_rosters (league_id, team_id, player_id, slot_key)
select 'b1170000-0000-4000-8000-000000000002',
       case when i <= 4 then 'c1170002-0000-4000-8000-000000000002'::uuid else 'c1170002-0000-4000-8000-000000000001'::uuid end,
       'e117-p' || i, 'bn'
from generate_series(1, 6) i;
insert into league_player_pool (league_id, player_id, state)
select r.league_id, r.player_id, 'rostered' from league_rosters r where r.league_id = 'b1170000-0000-4000-8000-000000000002';

-- What must never reach the log (filled as the invites are made — §D).
create temp table e117_secrets (kind text, v text);
insert into e117_secrets select 'code', invite_code from leagues where id = 'b1170000-0000-4000-8000-000000000001';

-- ---------------------------------------------------------------------------
-- C. Membership (LM, setup) — seats, roles, managers
-- ---------------------------------------------------------------------------
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);

select is(public.add_placeholder_seat('b1170000-0000-4000-8000-000000000001', '') ->> 'team_name', 'Team 4',
  'C1 the commissioner adds a placeholder seat (Team 4)');
select is(
  (select format('%s|%s|%s|%s|%s|%s|%s', actor_id, action_type, target_type,
                 target_id = after ->> 'team_id', before is null, reason is null, acting_as_team_id is null)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'),
  '97117000-0000-4000-8000-000000000001|add_seat|team|t|t|t|t',
  'C2 change: exactly ONE receipt — add_seat on the new team, no before, no reason, not acting as a team');
select is(
  (select jsonb_build_array(after - 'team_id', metadata - 'member_id' - 'affected_team_ids')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat'),
  '[{"team_name": "Team 4", "placeholder": true}, {"verb": "add_placeholder_seat", "bypassed": [], "team_count": 8, "seats_filled": 4}]'::jsonb,
  'C3 the seat receipt NAMES the placeholder seat (Team 4) and the count it fills');

select is(
  (public.set_member_role('b1170000-0000-4000-8000-000000000001',
    (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000003'),
    'co_commissioner') ->> 'role'), 'co_commissioner',
  'C4 the commissioner promotes u3 to co-commissioner');
select is(
  (select jsonb_build_array(action_type, target_type, before, after, metadata ->> 'user_id',
                            target_id = (select id::text from league_members where league_id = 'b1170000-0000-4000-8000-000000000001'
                                                                               and user_id = '97117000-0000-4000-8000-000000000003'))
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'promote_member'),
  '["promote_member", "member", {"role": "manager"}, {"role": "co_commissioner"}, "97117000-0000-4000-8000-000000000003", true]'::jsonb,
  'C5 change: ONE promote_member receipt on the member, manager to co-commissioner');
select public.set_member_role('b1170000-0000-4000-8000-000000000001',
  (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000003'),
  'co_commissioner');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 2,
  'C6 no-op: the same role again writes no receipt');
select public.set_member_role('b1170000-0000-4000-8000-000000000001',
  (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000003'),
  'manager');
select is(
  (select jsonb_build_array(action_type, before, after)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'demote_member'),
  '["demote_member", {"role": "co_commissioner"}, {"role": "manager"}]'::jsonb,
  'C7 change: ONE demote_member receipt, co-commissioner back to manager');

select is(
  (public.assign_manager('b1170000-0000-4000-8000-000000000001',
    (select after ->> 'team_id' from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat')::uuid,
    '97117000-0000-4000-8000-000000000004') ->> 'already_seated')::boolean, false,
  'C8 the commissioner seats u4 on Team 4');
select is(
  (select jsonb_build_array(action_type, target_type, before, after, metadata ->> 'team_name',
                            target_id = (select after ->> 'team_id' from commissioner_actions
                                         where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat'))
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'assign_manager'),
  '["assign_manager", "team", {"team_status": "active", "manager_user_id": null}, {"team_status": "active", "manager_user_id": "97117000-0000-4000-8000-000000000004"}, "Team 4", true]'::jsonb,
  'C9 change: ONE assign_manager receipt — the seat had no manager and now has u4');
select is(
  (public.assign_manager('b1170000-0000-4000-8000-000000000001',
    (select after ->> 'team_id' from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat')::uuid,
    '97117000-0000-4000-8000-000000000004') ->> 'already_seated')::boolean, true,
  'C10 assigning the same manager again is the already-seated no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 4,
  'C11 no-op: the second assign writes no receipt');

-- remove_manager: vacate (with a padded reason), then takeover (no reason)
select is(
  (public.remove_manager('b1170000-0000-4000-8000-000000000001',
    (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000004'),
    'vacate', NULL, E'  seat abandoned \n') ->> 'already_vacant')::boolean, false,
  'C12 the commissioner vacates Team 4');
select is(
  (select jsonb_build_array(action_type, target_type, reason, before, after, metadata ->> 'mode', metadata ->> 'team_name')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'vacate_seat'),
  '["vacate_seat", "team", "seat abandoned", {"team_status": "active", "manager_user_id": "97117000-0000-4000-8000-000000000004"}, {"team_status": "orphaned", "manager_user_id": null}, "vacate", "Team 4"]'::jsonb,
  'C13 change: ONE vacate_seat receipt — the outcome named, the seat before and after, the reason trimmed');
select is(
  (public.remove_manager('b1170000-0000-4000-8000-000000000001',
    (select m.id from league_members m join teams t on t.id = m.team_id
     where m.league_id = 'b1170000-0000-4000-8000-000000000001' and t.name = 'Team 4'),
    'vacate') ->> 'already_vacant')::boolean, true,
  'C14 vacating the open seat again is the already-vacant no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 5,
  'C15 no-op: the second vacate writes no receipt');
select public.remove_manager('b1170000-0000-4000-8000-000000000001',
  (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000003'),
  'takeover', '97117000-0000-4000-8000-000000000005');
select is(
  (select jsonb_build_array(action_type, target_id, reason, before, after, metadata ->> 'mode')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'replace_manager'),
  '["replace_manager", "c1170001-0000-4000-8000-000000000003", null, {"team_status": "active", "manager_user_id": "97117000-0000-4000-8000-000000000003"}, {"team_status": "active", "manager_user_id": "97117000-0000-4000-8000-000000000005"}, "takeover"]'::jsonb,
  'C16 change: ONE replace_manager receipt — the takeover named, u3 out and u5 in, no reason');
select throws_ok(
  format($$ select public.remove_manager('b1170000-0000-4000-8000-000000000001', %L, 'vacate', NULL, %L) $$,
         (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000002'),
         repeat('x', 501)),
  '22023', 'remove_manager: the reason is 501 characters — at most 500 (the league_chat bound; §12.13)',
  'C17 a reason over 500 characters is refused by name (the seam rule, D449(8))');
select is(
  (select format('%s|%s', (select count(*) from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'),
                 (select user_id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and team_id = 'c1170001-0000-4000-8000-000000000002'))),
  '6|97117000-0000-4000-8000-000000000002',
  'C18 and the refusal rolled the vacate back with it — u2 still holds the seat, nothing written');

select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select throws_ok($$ select public.add_placeholder_seat('b1170000-0000-4000-8000-000000000001', '') $$, '42501', NULL,
  'C19 a manager cannot add a seat (42501 unchanged)');
select throws_ok(
  format($$ select public.set_member_role('b1170000-0000-4000-8000-000000000001', %L, 'co_commissioner') $$,
         (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000002')),
  '42501', NULL, 'C20 a manager cannot change a role');
select throws_ok(
  $$ select public.assign_manager('b1170000-0000-4000-8000-000000000001', 'c1170001-0000-4000-8000-000000000003', '97117000-0000-4000-8000-000000000006') $$,
  '42501', NULL, 'C21 a manager cannot assign a manager');
select throws_ok(
  format($$ select public.remove_manager('b1170000-0000-4000-8000-000000000001', %L, 'vacate') $$,
         (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000001' and user_id = '97117000-0000-4000-8000-000000000005')),
  '42501', NULL, 'C22 a manager cannot remove a manager');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 6,
  'C23 the refused manager calls wrote nothing');

-- The transfer (LD): u1 hands the commissioner role to u2, then replays it.
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select is(
  (public.set_member_role('b1170000-0000-4000-8000-000000000003',
    (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000003' and user_id = '97117000-0000-4000-8000-000000000002'),
    'commissioner') ->> 'transferred')::boolean, true,
  'C24 the commissioner transfers the role to u2 (LD)');
select is(
  (select jsonb_build_array(action_type, before, after, metadata)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000003'),
  '["transfer_commissioner", {"role": "manager", "commissioner_user_id": "97117000-0000-4000-8000-000000000001"}, {"role": "commissioner", "commissioner_user_id": "97117000-0000-4000-8000-000000000002"}, {"verb": "set_member_role", "user_id": "97117000-0000-4000-8000-000000000002", "bypassed": [], "previous_commissioner_role": "co_commissioner", "previous_commissioner_user_id": "97117000-0000-4000-8000-000000000001"}]'::jsonb,
  'C25 change: ONE transfer_commissioner receipt — the role and who holds the commissioner seat, before and after');
select is(
  (public.set_member_role('b1170000-0000-4000-8000-000000000003',
    (select id from league_members where league_id = 'b1170000-0000-4000-8000-000000000003' and user_id = '97117000-0000-4000-8000-000000000002'),
    'commissioner') ->> 'transferred')::boolean, false,
  'C26 the replayed transfer is the D63 no-op');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000003'), 1,
  'C27 no-op: the replay writes no receipt');

-- ---------------------------------------------------------------------------
-- D. Invites (LM) — and TD9 privacy
-- ---------------------------------------------------------------------------
select is((public.create_league_invite('b1170000-0000-4000-8000-000000000001', NULL, NULL, NULL, 5) ->> 'resent')::boolean, false,
  'D1 the commissioner makes a league link invite (5 uses)');
select is(
  (select jsonb_build_array(action_type, target_type, before, after - 'expires_at',
                            (after ->> 'expires_at')::timestamptz = (select i.expires_at from league_invites i where i.id::text = a.target_id))
   from commissioner_actions a where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'create_invite'),
  '["create_invite", "invite", null, {"kind": "link", "max_uses": 5, "team_name": null, "target_team_id": null}, true]'::jsonb,
  'D2 change: ONE create_invite receipt — a link invite, its limits, no seat');
select public.create_league_invite('b1170000-0000-4000-8000-000000000001',
  (select after ->> 'team_id' from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat')::uuid,
  'Secret.Invitee@Example.com', NULL, 1);
select is(
  (select jsonb_build_array(after - 'expires_at' - 'target_team_id', after ->> 'target_team_id' = (select after ->> 'team_id' from commissioner_actions
                             where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat'))
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'create_invite'
     and after ->> 'kind' = 'email'),
  '[{"kind": "email", "max_uses": 1, "team_name": "Team 4"}, true]'::jsonb,
  'D3 TD9: the seat invite receipt says an invite for Team 4, by email — and names no one');
select is((public.create_league_invite('b1170000-0000-4000-8000-000000000001',
  (select after ->> 'team_id' from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'add_seat')::uuid,
  'secret.invitee@example.com', NULL, 1) ->> 'resent')::boolean, true,
  'D4 the same live email invite again is a re-send (D46)');
select is(
  (select jsonb_build_array(action_type, before, (after ->> 'last_sent_at')::timestamptz = now(), metadata ->> 'kind', metadata ->> 'team_name')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'resend_invite'),
  '["resend_invite", {"last_sent_at": null}, true, "email", "Team 4"]'::jsonb,
  'D5 change: ONE resend_invite receipt — the send stamped, the seat named, no one named');
select public.create_league_invite('b1170000-0000-4000-8000-000000000001', NULL, NULL, 'E117_User_7', 1);
select is(
  (select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'
     and action_type = 'create_invite' and after ->> 'kind' = 'username' and after ->> 'team_name' is null),
  1, 'D6 change: ONE create_invite receipt for the username invite — kind username');

select public.revoke_league_invite('b1170000-0000-4000-8000-000000000001',
  (select target_id::uuid from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'
     and action_type = 'create_invite' and after ->> 'kind' = 'link'));
select is(
  (select jsonb_build_array(action_type, before, after, metadata ->> 'target_team_id')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'revoke_invite'),
  '["revoke_invite", {"revoked": false}, {"revoked": true}, null]'::jsonb,
  'D7 change: ONE revoke_invite receipt');
select public.revoke_league_invite('b1170000-0000-4000-8000-000000000001',
  (select target_id::uuid from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'
     and action_type = 'create_invite' and after ->> 'kind' = 'link'));
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'revoke_invite'), 1,
  'D8 no-op: revoking the revoked invite again writes no receipt');

select ok(public.rotate_invite_code('b1170000-0000-4000-8000-000000000001') ? 'invite_code', 'D9 the commissioner rotates the invite code');
select is(
  (select jsonb_build_array(action_type, target_type, before, after)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'rotate_invite_code'),
  '["rotate_invite_code", "league", null, {"invite_code_rotated": true}]'::jsonb,
  'D10 change: ONE rotate_invite_code receipt — and neither code in it');

select is(public.set_league_invite_slug('b1170000-0000-4000-8000-000000000001', 'Pgtap-E117-Slug') ->> 'invite_slug', 'pgtap-e117-slug',
  'D11 the commissioner sets the invite slug');
select public.set_league_invite_slug('b1170000-0000-4000-8000-000000000001', 'pgtap-e117-slug');
select public.set_league_invite_slug('b1170000-0000-4000-8000-000000000001', NULL);
select public.set_league_invite_slug('b1170000-0000-4000-8000-000000000001', NULL);
select is(
  (select jsonb_agg(jsonb_build_array(before, after) order by created_at, (before ->> 'invite_slug') nulls first)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'set_invite_slug'),
  '[[{"invite_slug": null}, {"invite_slug": "pgtap-e117-slug"}], [{"invite_slug": "pgtap-e117-slug"}, {"invite_slug": null}]]'::jsonb,
  'D12 set, same again, clear, clear again: TWO set_invite_slug receipts — the repeats are by-value no-ops');

select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select throws_ok($$ select public.create_league_invite('b1170000-0000-4000-8000-000000000001', NULL, NULL, NULL, 1) $$, '42501', NULL,
  'D13 a manager cannot make an invite');
select throws_ok(
  format($$ select public.revoke_league_invite('b1170000-0000-4000-8000-000000000001', %L) $$,
         (select target_id from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'
            and action_type = 'create_invite' and after ->> 'kind' = 'username')),
  '42501', NULL, 'D14 a manager cannot revoke an invite');
select throws_ok($$ select public.rotate_invite_code('b1170000-0000-4000-8000-000000000001') $$, '42501', NULL,
  'D15 a manager cannot rotate the code');
select throws_ok($$ select public.set_league_invite_slug('b1170000-0000-4000-8000-000000000001', 'mgr-slug') $$, '42501', NULL,
  'D16 a manager cannot set the slug');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 14,
  'D17 the refused manager calls wrote nothing');

-- ---------------------------------------------------------------------------
-- E. League setup (LM) — settings, scoring, profile, lifecycle; LD deleted
-- ---------------------------------------------------------------------------
-- pg_temp.save: update_league_settings with the stored values, overridden by
-- a patch (typed keys at the top, blob keys under "settings").
reset role;
create function pg_temp.save(p_league uuid, p_patch jsonb) returns void language plpgsql as $f$
declare l public.leagues;
begin
  select * into l from public.leagues where id = p_league;
  perform public.update_league_settings(
    p_league, coalesce((p_patch ->> 'team_count')::int, l.team_count),
    l.settings || coalesce(p_patch -> 'settings', '{}'::jsonb), l.roster_settings, null,
    l.format, l.regular_season_weeks, l.playoff_teams, l.playoff_start_week, l.waiver_type,
    coalesce((p_patch ->> 'faab_budget')::int, l.faab_budget), l.trade_review, l.trade_deadline_week, l.lineup_lock);
end
$f$;
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);

select pg_temp.save('b1170000-0000-4000-8000-000000000001', '{"faab_budget": 150, "settings": {"median_game": true}}');
select is(
  (select jsonb_build_array(action_type, target_type, before, after, metadata)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'change_settings'),
  '["change_settings", "league", {"settings": {"faab_budget": 100, "median_game": false}}, {"settings": {"faab_budget": 150, "median_game": true}}, {"keys": ["faab_budget", "median_game"], "verb": "update_league_settings", "bypassed": [], "league_status": "setup"}]'::jsonb,
  'E1 change: ONE change_settings receipt for the save, carrying EXACTLY the two keys that changed (a typed column and a settings key)');
select pg_temp.save('b1170000-0000-4000-8000-000000000001', '{}');
select pg_temp.save('b1170000-0000-4000-8000-000000000001', '{"faab_budget": 150, "settings": {"median_game": true}}');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'change_settings'), 1,
  'E2 no-op: two saves that change nothing write nothing');
select pg_temp.save('b1170000-0000-4000-8000-000000000001', '{"team_count": 10}');
select is(
  (select jsonb_build_array(before, after) from commissioner_actions
   where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'change_settings' and metadata -> 'keys' = '["team_count"]'),
  '[{"settings": {"team_count": 8}}, {"settings": {"team_count": 10}}]'::jsonb,
  'E3 change: the next save that moves only the team count records only it');

select isnt(public.scoring_fork_template('b1170000-0000-4000-8000-000000000001',
              (select id from scoring_systems where is_template and name = 'ESPN Standard')),
            (select id from scoring_systems where is_template and name = 'ESPN Standard'),
  'E4 the commissioner forks the template into the league custom scoring');
select is(
  (select jsonb_build_array(action_type, before -> 'scoring_system_id' = to_jsonb((select id from scoring_systems where is_template and name = 'ESPN Standard')),
                            after -> 'scoring_system_id' = to_jsonb((select scoring_system_id from leagues where id = 'b1170000-0000-4000-8000-000000000001')),
                            metadata ->> 'scoring_system_name')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'fork_scoring'),
  '["fork_scoring", true, true, "pgtap-e117-LM Custom"]'::jsonb,
  'E5 change: ONE fork_scoring receipt — the template before, the fork after');
select public.scoring_fork_template('b1170000-0000-4000-8000-000000000001',
  (select id from scoring_systems where is_template and name = 'ESPN Standard'));
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'fork_scoring'), 1,
  'E6 no-op: the idempotent re-fork writes no receipt');

select public.scoring_update_rules('b1170000-0000-4000-8000-000000000001',
  (select jsonb_set(s.rules, '{base,receptions}', '1') from scoring_systems s
   where s.id = (select scoring_system_id from leagues where id = 'b1170000-0000-4000-8000-000000000001')));
select is(
  (select jsonb_build_array(action_type, before, after, metadata -> 'keys')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_scoring'),
  '["edit_scoring", {"scoring_rules": {"base.receptions": 0}}, {"scoring_rules": {"base.receptions": 1}}, ["base.receptions"]]'::jsonb,
  'E7 change: ONE edit_scoring receipt carrying EXACTLY the one rule that changed, by its path');
select public.scoring_update_rules('b1170000-0000-4000-8000-000000000001',
  (select s.rules from scoring_systems s where s.id = (select scoring_system_id from leagues where id = 'b1170000-0000-4000-8000-000000000001')));
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_scoring'), 1,
  'E8 no-op: saving the same document again writes no receipt');
select public.scoring_update_rules('b1170000-0000-4000-8000-000000000001',
  (select jsonb_set(s.rules, '{positions}', '{"TE": {"receptions": 1.5}}') from scoring_systems s
   where s.id = (select scoring_system_id from leagues where id = 'b1170000-0000-4000-8000-000000000001')));
select is(
  (select jsonb_build_array(before, after) from commissioner_actions
   where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_scoring' and metadata -> 'keys' = '["positions.TE"]'),
  '[{"scoring_rules": {"positions.TE": null}}, {"scoring_rules": {"positions.TE": {"receptions": 1.5}}}]'::jsonb,
  'E9 change: a new position override is recorded as the one path it adds');

select public.update_league_profile('b1170000-0000-4000-8000-000000000001', '  pgtap-e117-LM renamed  ');
select is(
  (select jsonb_build_array(action_type, before, after)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_league_profile'),
  '["edit_league_profile", {"name": "pgtap-e117-LM"}, {"name": "pgtap-e117-LM renamed"}]'::jsonb,
  'E10 change: ONE edit_league_profile receipt — the name before and after, and nothing that did not change');
select public.update_league_profile('b1170000-0000-4000-8000-000000000001', 'pgtap-e117-LM renamed');
select public.update_league_profile('b1170000-0000-4000-8000-000000000001');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_league_profile'), 1,
  'E11 no-op: the same name again, and a call that changes nothing, write no receipt');
select public.update_league_profile('b1170000-0000-4000-8000-000000000001', NULL, 'https://example.com/e117.png');
select is(
  (select jsonb_build_array(before, after) from commissioner_actions
   where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'edit_league_profile' and after ? 'avatar_url'),
  '[{"avatar_url": null}, {"avatar_url": "https://example.com/e117.png"}]'::jsonb,
  'E12 change: the avatar receipt carries only the avatar');

select public.set_league_status('b1170000-0000-4000-8000-000000000001', 'scheduled');
select public.set_league_status('b1170000-0000-4000-8000-000000000001', 'scheduled');
select public.set_league_status('b1170000-0000-4000-8000-000000000001', 'setup');
select is(
  (select jsonb_agg(jsonb_build_array(before, after) order by before ->> 'status')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' and action_type = 'lifecycle_change'),
  '[[{"status": "scheduled"}, {"status": "setup"}], [{"status": "setup"}, {"status": "scheduled"}]]'::jsonb,
  'E13 setup to scheduled, the same again, back to setup: TWO lifecycle_change receipts — the repeat is the no-op');

select public.soft_delete_league('b1170000-0000-4000-8000-000000000003');
select public.soft_delete_league('b1170000-0000-4000-8000-000000000003');
select is(
  (select jsonb_agg(jsonb_build_array(action_type, before, after) order by action_type)
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000003'),
  '[["delete_league", {"deleted": false}, {"deleted": true}], ["transfer_commissioner", {"role": "manager", "commissioner_user_id": "97117000-0000-4000-8000-000000000001"}, {"role": "commissioner", "commissioner_user_id": "97117000-0000-4000-8000-000000000002"}]]'::jsonb,
  'E14 the co-commissioner deletes LD: ONE delete_league receipt; the second delete is the no-op');

select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select throws_ok($$ select pg_temp.save('b1170000-0000-4000-8000-000000000001', '{"faab_budget": 1}') $$, '42501', NULL,
  'E15 a manager cannot save settings');
select throws_ok($$ select public.scoring_fork_template('b1170000-0000-4000-8000-000000000001', (select id from scoring_systems where is_template and name = 'ESPN Standard')) $$,
  '42501', NULL, 'E16 a manager cannot fork scoring');
select throws_ok($$ select public.scoring_update_rules('b1170000-0000-4000-8000-000000000001', '{}') $$, '42501', NULL,
  'E17 a manager cannot edit scoring');
select throws_ok($$ select public.update_league_profile('b1170000-0000-4000-8000-000000000001', 'mgr name') $$, '42501', NULL,
  'E18 a manager cannot rename the league');
select throws_ok($$ select public.set_league_status('b1170000-0000-4000-8000-000000000001', 'scheduled') $$, '42501', NULL,
  'E19 a manager cannot move the lifecycle');
select throws_ok($$ select public.soft_delete_league('b1170000-0000-4000-8000-000000000001') $$, '42501', NULL,
  'E20 a manager cannot delete the league');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 23,
  'E21 the refused manager calls wrote nothing (23 receipts in LM)');

-- ---------------------------------------------------------------------------
-- F. F514 — set_lineup, the commissioner arm (LI, week 6)
-- ---------------------------------------------------------------------------
-- The instant seam (set_lineup_internal is postgres-only — 060 / 062), with
-- the caller JWT claims set: auth.uid() is the commissioner.
reset role;
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select is(
  (public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
     '{"rb:0": "e117-p1", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000001', '2026-10-18 16:00:00+00', E' \t ')
   ->> 'edited_by_commish')::boolean, true,
  'F1 the commissioner sets the lineup of a team he does not manage');
select is(
  (select jsonb_build_array(actor_id, action_type, target_type, target_id, acting_as_team_id, reason, before, after,
                            metadata - 'action_id')
   from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'),
  '["97117000-0000-4000-8000-000000000001", "edit_lineup", "team", "c1170002-0000-4000-8000-000000000002", "c1170002-0000-4000-8000-000000000002", null, {"slot_map": {}}, {"slot_map": {"rb:0": "e117-p1", "rb:1": "e117-p2"}}, {"verb": "set_lineup", "week": 6, "season": 2026, "bypassed": [], "team_name": "e117-L2-t2", "week_status": "live", "current_week": 6}]'::jsonb,
  'F2 change: ONE edit_lineup receipt acting for the team — the lineup before and after, a whitespace reason stored as none');
select is(
  (select count(*)::int from league_chat where league_id = 'b1170000-0000-4000-8000-000000000002' and is_system
     and message = 'Week 6 lineup for e117-L2-t2 set by e117_user_1 (commissioner)'),
  1, 'F3 the chat post is unchanged (one system post, no reason clause)');
select public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
  '{"rb:0": "e117-p1", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000001', '2026-10-18 16:00:00+00', NULL);
select is((public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
  '{"rb:0": "e117-p1", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000002', '2026-10-18 16:00:00+00', NULL) ->> 'no_changes')::boolean, true,
  'F4 the same lineup again under a new action id is the no-op re-save');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'), 1,
  'F5 no-op: the replay and the unchanged re-save write no receipt');
select public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
  '{"rb:0": "e117-p3", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000003', '2026-10-18 16:00:00+00', 'injury swap');
select is(
  (select jsonb_build_array(reason, before, after) from commissioner_actions
   where league_id = 'b1170000-0000-4000-8000-000000000002' and metadata ->> 'action_id' = 'a1170000-0000-4000-8000-000000000003'),
  '["injury swap", {"slot_map": {"rb:0": "e117-p1", "rb:1": "e117-p2"}}, {"slot_map": {"rb:0": "e117-p3", "rb:1": "e117-p2"}}]'::jsonb,
  'F6 change: the next real edit writes its own receipt, with its reason');
select public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000001', 6,
  '{"rb:0": "e117-p5"}', 'a1170000-0000-4000-8000-000000000004', '2026-10-18 16:00:00+00', NULL);
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'), 2,
  'F7 the commissioner setting HIS OWN team is a manager save — no receipt');
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select is((public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
  '{"rb:0": "e117-p4", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000005', '2026-10-18 16:00:00+00', NULL) ->> 'edited_by_commish')::boolean, false,
  'F8 the manager sets his own lineup');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'), 2,
  'F9 a manager own save writes no receipt');
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select throws_ok(
  format($$ select public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
           '{"rb:0": "e117-p1", "rb:1": "e117-p2"}', 'a1170000-0000-4000-8000-000000000006', '2026-10-18 16:00:00+00', %L) $$, repeat('r', 501)),
  '22023', 'set_lineup: the reason is 501 characters — at most 500 (the league_chat bound; §12.13)',
  'F10 a reason over 500 characters meets set_lineup own refusal first (131, unchanged — no new refusal)');
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000006", "role": "authenticated"}', true);
select throws_ok(
  $$ select public.set_lineup_internal('b1170000-0000-4000-8000-000000000002', 'c1170002-0000-4000-8000-000000000002', 6,
       '{"rb:0": "e117-p1"}', 'a1170000-0000-4000-8000-000000000007', '2026-10-18 16:00:00+00', NULL) $$,
  '42501', NULL, 'F11 an outsider is refused (42501 unchanged)');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'), 2,
  'F12 the refusals wrote nothing');

-- ---------------------------------------------------------------------------
-- G. remove_manager — retire (LI, in season). RE-CUT BY 176 (M6 L.E1.42 —
--    Chris 2026-10-01: a team is never retired). G1–G4 pinned the retirement
--    receipt; retire is now refused by name and writes nothing.
-- ---------------------------------------------------------------------------
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000001", "role": "authenticated"}', true);
select throws_ok(
  $$ select public.remove_manager('b1170000-0000-4000-8000-000000000002',
       (select id from public.league_members where league_id = 'b1170000-0000-4000-8000-000000000002' and user_id = '97117000-0000-4000-8000-000000000003'),
       'retire', NULL, 'moving away', 'a1170000-0000-4000-8000-0000000000aa') $$,
  'P0001', 'remove_manager: a team can''t be retired — seat a new manager or leave it vacant (§7.2.1)',
  'G1 RE-CUT (176): retiring u3 team mid-season is refused BY NAME (was: retired, successor Team 4)');
select is(
  (select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002' and action_type = 'retire_franchise'),
  0,
  'G2 RE-CUT (176): …and no retire_franchise receipt is written (was: ONE receipt naming the seal and the successor)');
select is(
  (select t.status || '|' || (t.successor_team_id is null)::text || '|' ||
          (select count(*) from teams x where x.league_id = 'b1170000-0000-4000-8000-000000000002')::text
   from teams t where t.id = 'c1170002-0000-4000-8000-000000000003'),
  'active|true|3',
  'G3 RE-CUT (176): u3 team is still active, has no successor, and no team was minted (was: the replay returned the stored retirement)');
select throws_ok(
  $$ select public.remove_manager('b1170000-0000-4000-8000-000000000002',
       (select id from public.league_members where league_id = 'b1170000-0000-4000-8000-000000000002' and user_id = '97117000-0000-4000-8000-000000000003'),
       'retire', NULL, 'moving away', 'a1170000-0000-4000-8000-0000000000aa') $$,
  'P0001', 'remove_manager: a team can''t be retired — seat a new manager or leave it vacant (§7.2.1)',
  'G4 RE-CUT (176): the retry with the same action id is refused the same way — nothing was stored to replay (was: the replay wrote no receipt)');

-- ---------------------------------------------------------------------------
-- H. TD9 — the privacy negative, BY VALUE over every row written
-- ---------------------------------------------------------------------------
reset role;
insert into e117_secrets
  select 'token', token from league_invites where league_id = 'b1170000-0000-4000-8000-000000000001'
  union all select 'email', invited_email::text from league_invites where league_id = 'b1170000-0000-4000-8000-000000000001' and invited_email is not null
  union all select 'username', invited_username::text from league_invites where league_id = 'b1170000-0000-4000-8000-000000000001' and invited_username is not null
  union all select 'code', invite_code from leagues where id = 'b1170000-0000-4000-8000-000000000001';
insert into e117_secrets values ('email', 'Secret.Invitee@Example.com'), ('username', 'E117_User_7');
select is(
  (select string_agg(kind || ':' || n, ' ' order by kind) from (select kind, count(*) n from e117_secrets group by kind) x),
  'code:2 email:2 token:3 username:2',
  'H1 not vacuous: three tokens, the email and the username as stored and as typed, and both invite codes are checked');
select is(
  (select count(*)::int from commissioner_actions a
   where a.league_id in ('b1170000-0000-4000-8000-000000000001', 'b1170000-0000-4000-8000-000000000002', 'b1170000-0000-4000-8000-000000000003')
     and a.action_type in ('create_invite', 'resend_invite', 'revoke_invite', 'rotate_invite_code')),
  6, 'H2 not vacuous: six invite receipts are among the rows checked');
select is(
  (select count(*)::int from commissioner_actions a, e117_secrets s
   where a.league_id in ('b1170000-0000-4000-8000-000000000001', 'b1170000-0000-4000-8000-000000000002', 'b1170000-0000-4000-8000-000000000003')
     and strpos(lower(coalesce(a.before::text, '') || ' ' || coalesce(a.after::text, '') || ' ' || coalesce(a.metadata::text, '')
                      || ' ' || coalesce(a.reason, '') || ' ' || coalesce(a.target_id, '')), lower(s.v)) > 0),
  0,
  'H3 TD9: no receipt before, after, metadata, reason or target holds an invite token, an invited email, an invited username or an invite code');

-- ---------------------------------------------------------------------------
-- I. Members read the rows; nobody edits one
-- ---------------------------------------------------------------------------
select is((select count(*)::int from league_chat where league_id = 'b1170000-0000-4000-8000-000000000001'), 0,
  'I1 the membership, invite and setup receipts post nothing to chat (none of them posted before)');
set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000002", "role": "authenticated"}', true);
select is(
  (select string_agg(action_type || ':' || n, ' ' order by action_type)
   from (select action_type, count(*) n from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001' group by action_type) x),
  'add_seat:1 assign_manager:1 change_settings:2 create_invite:3 demote_member:1 edit_league_profile:2 edit_scoring:2 '
  || 'fork_scoring:1 lifecycle_change:2 promote_member:1 replace_manager:1 resend_invite:1 revoke_invite:1 '
  || 'rotate_invite_code:1 set_invite_slug:2 vacate_seat:1',
  'I2 a manager reads every one of the 23 new LM rows (§10.3: the log is league-visible)');
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000002'), 2,
  'I3 a manager reads the LI rows too — the lineup receipts (RE-CUT 176: 3 → 2, no retirement receipt)');
select set_config('request.jwt.claims', '{"sub": "97117000-0000-4000-8000-000000000006", "role": "authenticated"}', true);
select is((select count(*)::int from commissioner_actions where league_id in (
  'b1170000-0000-4000-8000-000000000001', 'b1170000-0000-4000-8000-000000000002', 'b1170000-0000-4000-8000-000000000003')), 0,
  'I4 an outsider reads none');
reset role;
set local role anon;
select is((select count(*)::int from commissioner_actions where league_id = 'b1170000-0000-4000-8000-000000000001'), 0,
  'I5 anon reads none');
reset role;
select throws_ok(
  $$ update commissioner_actions set reason = 'edited' where league_id = 'b1170000-0000-4000-8000-000000000001' $$,
  'P0001', NULL, 'I6 even the owner cannot edit a receipt (the 123 backstop)');

select * from finish();
rollback;
