-- ============================================================================
-- 119 — the commissioner's doors on draft_place_bid and draft_queue_replace
--       (migration 171; M6 L.E1.38; F521; spec §8.4, §8.6.3, §8.7, §10.3,
--       §12.12; tasks-M6 TD9, TD16; PROGRESS D449, D451, D452; standing
--       rules (a), (b), (i))
-- ============================================================================
-- What this file proves, over REAL calls in one rolled-back transaction:
--   §A  form and D137 in the database — the one draft_place_bid (six
--       arguments, the last defaulted), both DEFINER with search_path '',
--       the ACLs as they stood on 170, pg_temp.un171 reverses each live body
--       to its newest definer's file text, the one validator untouched.
--   §C  THE BID DOOR — the commissioner bids for a placeholder team in a
--       live auction: the bid is that team's, one receipt acting for it (its
--       before / after / metadata as stored literals), one room post, the
--       anti-snipe floor applied as for any bid; a replay writes none; a
--       co-commissioner has the door too.
--   §V  VALIDITY BINDS HIM (standing rule (i)) — the self-raise, the $1
--       increment, the max bid (E5), the complete roster (E27), the stale
--       nomination (R330), the paused draft, a retired or foreign team: each
--       refused with the manager's own message and nothing written.
--   §Z  WHOSE TEAM — a manager naming another team is refused (42501) with
--       nothing written; a manager's own bid (no team, or his own named) and
--       the commissioner's bid for his own seat write no receipt and no post
--       (his manager act); an outsider is refused; a mock names only the
--       launcher's seat.
--   §Q  THE QUEUE DOOR — the commissioner replaces another team's Targets:
--       one receipt acting for it that never carries a player, one post; the
--       same queue again ⇒ none; a re-order, an add / remove, a clear ⇒ one
--       each with its counts; a placeholder he owns ⇒ his act for it; his
--       own seat ⇒ none; the shape rules bind him; a manager on another
--       team, a foreign or retired team, a mock seat ⇒ 42501 with nothing
--       written; the queue's own manager reads what was set.
--   §K  the held lock re-measured on both bid paths (§8.3 < 50 ms).
-- Worlds: LA b1190000…01 — a live auction in its BIDDING phase (nomination
-- 4, x119-p01 at $1 by t1; t5 bought three players — a complete roster);
-- u1 commissioner (seat t1), u2 manager (t2), u3 co-commissioner (no seat),
-- t3–t6 placeholder seats (owned by u1, as 169's add_placeholder_seat
-- stamps), t7 retired; LO b1190000…02 another league (u5 commissioner, o1);
-- M e1190000…03 a live mock auction in LA launched by u1 from t2.
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(70);

-- pg_temp.un171 — 171's prosrc substitutions reversed (generated by
-- derive_171.py with the migration; each replacement text is unique to its
-- body). Applied to a live prosrc it yields the source file text's prosrc.
create function pg_temp.un171(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$  v_stale_name    TEXT;
  v_acting        BOOLEAN := FALSE;  -- 171: the commissioner bids for a team he does not manage
  v_team_name     TEXT;
  v_before        JSONB;
  v_result        JSONB;
BEGIN$r$, $o$  v_stale_name    TEXT;
BEGIN$o$);  -- draft_place_bid
  s := replace(s, $r$  IF v_draft.is_mock THEN
    v_my_team := (v_draft.config->'mock'->>'human_team_id')::uuid;
    -- 171/L.E1.38 (F521): a mock has no commissioner (§8.8) — the launcher
    -- bids only for the seat he practises from, so naming any other team is
    -- refused and nothing is written.
    IF p_team_id IS NOT NULL AND p_team_id IS DISTINCT FROM v_my_team THEN
      RAISE EXCEPTION
        'draft_place_bid: in a practice draft you bid only for your own seat (§8.8)'
        USING ERRCODE = 'P0001';
    END IF;
  ELSE$r$, $o$  IF v_draft.is_mock THEN
    v_my_team := (v_draft.config->'mock'->>'human_team_id')::uuid;
  ELSE$o$);  -- draft_place_bid
  s := replace(s, $r$    WHERE m.league_id = v_draft.league_id AND m.user_id = auth.uid();
    -- 171/L.E1.38 (F521; standing rule (a); spec §8.7, §10.3) — THE
    -- COMMISSIONER'S DOOR. A named team that is not the caller's own seat is
    -- a bid FOR that team, and only a commissioner or co-commissioner may
    -- make it. He stands outside nothing but "whose team": every check above
    -- (the phase, the nomination identity, the status) has run, and every
    -- validity rule below — the self-raise, the complete roster, the $1
    -- increment, the max bid, the anti-snipe floor — binds him exactly as
    -- it binds the team's manager, because the named team is the one the
    -- one validator reads. The caller's own seat named (or no team named)
    -- is the manager's own bid, unchanged, and writes no receipt.
    IF p_team_id IS NOT NULL AND p_team_id IS DISTINCT FROM v_my_team THEN
      IF NOT public.is_league_commish(v_draft.league_id) THEN
        RAISE EXCEPTION
          'draft_place_bid: only a commissioner can bid for another team (§8.7)'
          USING ERRCODE = '42501';
      END IF;
      SELECT t.name INTO v_team_name
      FROM public.teams t
      WHERE t.id = p_team_id AND t.league_id = v_draft.league_id
        AND t.status <> 'retired';
      IF NOT FOUND THEN
        RAISE EXCEPTION 'draft_place_bid: team % is not an active franchise of this league', p_team_id
          USING ERRCODE = 'P0002';
      END IF;
      v_my_team := p_team_id;
      v_acting  := TRUE;
      v_before  := jsonb_build_object(
                     'player_id', v_player_id,
                     'high_bid', v_high_bid,
                     'high_bidder_team_id', v_draft.current_nomination->>'high_bidder_team_id');
    END IF;
    IF v_my_team IS NULL THEN$r$, $o$    WHERE m.league_id = v_draft.league_id AND m.user_id = auth.uid();
    IF v_my_team IS NULL THEN$o$);  -- draft_place_bid
  s := replace(s, $r$  v_result := public.draft_place_bid_internal(
    p_draft_id, v_my_team, p_amount, p_action_id, 'draft_place_bid');

  -- 171/L.E1.38 (F521) — THE RECEIPT AND THE POST, on the commissioner arm
  -- only (§8.7 "every one writes a commissioner_actions audit entry"; §10.3
  -- the post cannot be disabled). A bid that lands always moves the high
  -- bid, so it is always a real change; a replay returned above and writes
  -- none; a refusal raised inside the validator and wrote nothing. The
  -- after-image is the stored bid row the validator returned.
  IF v_acting THEN
    INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)
    VALUES (v_draft.league_id, auth.uid(),
            'Bid of $' || (v_result->'bid'->>'amount') || ' on '
            || COALESCE((SELECT pl.full_name FROM public.players pl WHERE pl.id = v_player_id), 'the player up for bid')
            || ' placed by commissioner ' || public.draft_actor_name()
            || ' for ' || COALESCE(v_team_name, 'a team') || '.',
            'draft:' || p_draft_id::text, TRUE);
    PERFORM public.draft_commish_receipt_internal(
      v_draft.league_id, v_draft.is_mock, 'draft_place_bid', 'draft_bid', 'draft',
      p_draft_id::text, NULL,
      v_before,
      jsonb_build_object(
        'player_id', v_result->'bid'->>'player_id',
        'high_bid', (v_result->'bid'->>'amount')::int,
        'high_bidder_team_id', v_result->'bid'->>'team_id'),
      jsonb_build_object(
        'draft_id', p_draft_id,
        'nomination_seq', (v_result->'bid'->>'nomination_seq')::int,
        'bid_id', v_result->'bid'->>'id',
        'for_team_id', p_team_id,
        'affected_team_ids', jsonb_build_array(p_team_id)),
      p_team_id);  -- acting_as: the team he bid for (§10.3, D451)
  END IF;

  RETURN v_result;
END;$r$, $o$  RETURN public.draft_place_bid_internal(
    p_draft_id, v_my_team, p_amount, p_action_id, 'draft_place_bid');
END;$o$);  -- draft_place_bid
  s := replace(s, $r$  v_result JSONB;
  v_draft     public.drafts;       -- 171
  v_commish   BOOLEAN := FALSE;    -- 171: the commissioner edits a team he does not manage
  v_old       TEXT[];              -- 171: the queue before, for the no-op test (never recorded)
  v_team_name TEXT;                -- 171
BEGIN$r$, $o$  v_result JSONB;
BEGIN$o$);  -- draft_queue_replace
  s := replace(s, $r$  -- DELETE/INSERT below (SECURITY INVOKER).
  --
  -- 171/L.E1.38 (F521; standing rule (a); spec §8.4, §8.7, §10.3) — THE
  -- COMMISSIONER'S ARM, and the posture it forces. A commissioner or
  -- co-commissioner may replace the queue of any active franchise of the
  -- draft's league that is not his own seat — the act §8.4 gives its
  -- manager, done for the team (an absent manager's Targets are what his
  -- timeouts draft from). A real draft only: a mock has no commissioner
  -- (§8.8), so its one admit stays the launcher's. The arm writes a receipt
  -- and a room post, and the receipt seam is not a client's to call, so the
  -- function now runs SECURITY DEFINER: THIS guard is the whole auth law.
  -- The two arms below are 065's two policies re-derived exactly (the owner
  -- arm here is stricter — the league-consistency conjunct, 031), so a
  -- manager or a mock launcher is admitted precisely as before, and the
  -- comments below that say "invoker" / "RLS-checked" describe the pre-171
  -- posture; 065's policies still govern every direct table read and write.
  -- Validity is unchanged for him: the same shape rules (500 players, no
  -- duplicate, known ids) run before anything is touched.
  SELECT d.* INTO v_draft FROM public.drafts d WHERE d.id = p_draft_id;
  v_commish := COALESCE(
    v_draft.id IS NOT NULL
    AND NOT v_draft.is_mock
    AND public.is_league_commish(v_draft.league_id)
    AND EXISTS (
      SELECT 1 FROM public.teams t
      WHERE t.id = p_team_id AND t.league_id = v_draft.league_id
        AND t.status <> 'retired'
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.league_members m
      WHERE m.league_id = v_draft.league_id AND m.user_id = v_uid
        AND m.team_id = p_team_id
    ), FALSE);
  IF NOT v_commish AND NOT ($r$, $o$  -- DELETE/INSERT below (SECURITY INVOKER).
  IF NOT ($o$);  -- draft_queue_replace
  s := replace(s, $r$  -- 171: the commissioner arm reads the queue it replaces, under the seat
  -- lock, to tell a real change from the same queue again (D336 part 3).
  IF v_commish THEN
    SELECT COALESCE(array_agg(q.player_id ORDER BY q.rank, q.id), '{}'::text[])
    INTO v_old
    FROM public.draft_queues q
    WHERE q.draft_id = p_draft_id AND q.team_id = p_team_id;
  END IF;

  DELETE FROM public.draft_queues
  WHERE draft_id = p_draft_id AND team_id = p_team_id;$r$, $o$  DELETE FROM public.draft_queues
  WHERE draft_id = p_draft_id AND team_id = p_team_id;$o$);  -- draft_queue_replace
  s := replace(s, $r$  WHERE q.draft_id = p_draft_id AND q.team_id = p_team_id;

  -- 171/L.E1.38 (F521) — THE RECEIPT AND THE POST, on the commissioner arm
  -- only, and only when the queue changed (the same players in the same
  -- order is a no-op: nothing posted, nothing receipted — standing rule
  -- (b)). The log is member-readable, so a receipt NEVER carries the queue
  -- (TD9): only how many Targets there were and are, how many were added
  -- and removed, and whether the kept ones were re-ordered.
  IF v_commish AND v_old IS DISTINCT FROM p_players THEN
    SELECT t.name INTO v_team_name FROM public.teams t WHERE t.id = p_team_id;
    INSERT INTO public.league_chat (league_id, user_id, message, context, is_system)
    VALUES (v_draft.league_id, v_uid,
            'Targets for ' || COALESCE(v_team_name, 'a team') || ' updated by commissioner '
            || public.draft_actor_name() || '.',
            'draft:' || p_draft_id::text, TRUE);
    PERFORM public.draft_commish_receipt_internal(
      v_draft.league_id, v_draft.is_mock, 'draft_queue_replace', 'draft_set_queue', 'team',
      p_team_id::text, NULL,
      jsonb_build_object('targets', COALESCE(array_length(v_old, 1), 0)),
      jsonb_build_object(
        'targets', COALESCE(array_length(p_players, 1), 0),
        'added', (SELECT count(*)::int FROM unnest(p_players) AS n(id) WHERE NOT (n.id = ANY (v_old))),
        'removed', (SELECT count(*)::int FROM unnest(v_old) AS o(id) WHERE NOT (o.id = ANY (p_players))),
        'reordered',
          (SELECT COALESCE(array_agg(n.id ORDER BY n.ord), '{}'::text[])
           FROM unnest(p_players) WITH ORDINALITY AS n(id, ord) WHERE n.id = ANY (v_old))
          IS DISTINCT FROM
          (SELECT COALESCE(array_agg(o.id ORDER BY o.ord), '{}'::text[])
           FROM unnest(v_old) WITH ORDINALITY AS o(id, ord) WHERE o.id = ANY (p_players))),
      jsonb_build_object(
        'draft_id', p_draft_id,
        'team_name', v_team_name,
        'affected_team_ids', jsonb_build_array(p_team_id)),
      p_team_id);  -- acting_as: the team whose Targets he set (§10.3, D451)
  END IF;

  RETURN v_result;$r$, $o$  WHERE q.draft_id = p_draft_id AND q.team_id = p_team_id;

  RETURN v_result;$o$);  -- draft_queue_replace
  return s;
end
$un$;

-- pg_temp.as_user: the JWT subject every verb reads through auth.uid(). The
-- suite runs as the owner with claims set (the 118 shape) — the doors are
-- DEFINER, so the in-body gates are what is exercised; the one RLS read
-- (Q24 / Q25) switches role explicitly.
create function pg_temp.as_user(p_uid uuid) returns void language sql as $f$
  select set_config('request.jwt.claims',
    case when p_uid is null then '' else json_build_object('sub', p_uid, 'role', 'authenticated')::text end, true)::text;
  select null::void;
$f$;
create function pg_temp.rc() returns int language sql stable as $f$
  select count(*)::int from public.commissioner_actions where league_id = 'b1190000-0000-4000-8000-000000000001'
$f$;
create function pg_temp.posts() returns int language sql stable as $f$
  select count(*)::int from public.league_chat
  where context in ('draft:e1190000-0000-4000-8000-000000000001', 'draft:e1190000-0000-4000-8000-000000000003') and is_system
$f$;
create function pg_temp.bids() returns int language sql stable as $f$
  select count(*)::int from public.draft_bids where draft_id in ('e1190000-0000-4000-8000-000000000001', 'e1190000-0000-4000-8000-000000000003')
$f$;
create function pg_temp.nom() returns jsonb language sql stable as $f$
  select d.current_nomination from public.drafts d where d.id = 'e1190000-0000-4000-8000-000000000001'
$f$;
create function pg_temp.q(p_draft uuid, p_team uuid) returns text[] language sql stable as $f$
  select coalesce(array_agg(q.player_id order by q.rank), '{}'::text[]) from public.draft_queues q
  where q.draft_id = p_draft and q.team_id = p_team
$f$;
-- the newest receipt of the league (receipts in this file are written one
-- per statement, so the newest by created_at is ambiguous; seq by id order
-- of insertion is not stored — each cell below reads the rows it expects by
-- what is new since a snapshot).
create temp table _seen (id uuid primary key);
create function pg_temp.fresh() returns setof public.commissioner_actions language sql as $f$
  select c.* from public.commissioner_actions c
  where c.league_id = 'b1190000-0000-4000-8000-000000000001' and not exists (select 1 from _seen s where s.id = c.id)
$f$;
create function pg_temp.seen() returns void language sql as $f$
  insert into _seen select c.id from public.commissioner_actions c
  where c.league_id = 'b1190000-0000-4000-8000-000000000001' on conflict do nothing;
  select null::void;
$f$;
create function pg_temp.row_doc(c public.commissioner_actions) returns jsonb language sql immutable as $f$
  select jsonb_build_object('actor', c.actor_id, 'type', c.action_type, 'target_type', c.target_type,
    'target_id', c.target_id, 'reason', c.reason, 'acting', c.acting_as_team_id,
    'before', c.before, 'after', c.after, 'metadata', c.metadata - 'bid_id')
$f$;

-- ---------------------------------------------------------------------------
-- A. Form, and D137 in the database
-- ---------------------------------------------------------------------------
select is(
  (select string_agg(pg_get_function_identity_arguments(p.oid), ' / ')
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'draft_place_bid'),
  'p_draft_id uuid, p_amount integer, p_action_id uuid, p_nomination_seq integer, p_player_id text, p_team_id uuid',
  'A1 ONE draft_place_bid, and it takes the team to bid for as a sixth, defaulted argument (the five-argument form is gone — no overload)');
select is(
  (select pg_get_expr(p.proargdefaults, 0) from pg_proc p
   where p.oid = 'public.draft_place_bid(uuid, integer, uuid, integer, text, uuid)'::regprocedure),
  'NULL::integer, NULL::text, NULL::uuid',
  'A2 the three trailing arguments default to NULL — a manager call that names no team is the call it always was');
select is(
  (select string_agg(p.proname || ':' || p.prosecdef || ':' || array_to_string(p.proconfig, ','), ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_place_bid', 'draft_queue_replace')),
  'draft_place_bid:true:search_path="" draft_queue_replace:true:search_path=""',
  'A3 both doors are SECURITY DEFINER with search_path empty (draft_queue_replace was INVOKER until 171 — its guard is now the whole auth law)');
select is(
  (select string_agg(p.proname || '=' || p.proacl::text, ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_place_bid', 'draft_queue_replace')),
  'draft_place_bid={postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres} '
  || 'draft_queue_replace={postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}',
  'A4 the ACLs are exactly as they stood on 170 — authenticated and service_role execute, PUBLIC and anon do not');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un171(p.prosrc)), ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_place_bid', 'draft_queue_replace')),
  'draft_place_bid=2190079221e849405383fa1acec22cf7 draft_queue_replace=c844590b468080cda8858600fcc6f19a',
  'A5 D137 in the database: each live body with 171 reversed is its newest definer file text (095:2892, 082:64) byte for byte');
select is(
  (select string_agg(p.proname || '=' || md5(p.prosrc), ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_place_bid', 'draft_queue_replace')),
  'draft_place_bid=7e95f5ec6e0f9301b0c89577684909fe draft_queue_replace=d219e8994bc4be0b2e4319e22262243c',
  'A6 the live bodies are the derived ones (golden md5)');
select is(
  (select md5(p.prosrc) from pg_proc p where p.oid = 'public.draft_place_bid_internal(uuid, uuid, integer, uuid, text)'::regprocedure),
  '7ec9b09b73c71d01cb4680aa40e98f7b',
  'A7 the one bid validator (092:1982, shared with the mock CPU arm) is untouched');
select is(
  (select format('%s|%s|%s',
     (length(p.prosrc) - length(replace(p.prosrc, 'public.draft_place_bid_internal(', ''))) / length('public.draft_place_bid_internal('),
     (length(p.prosrc) - length(replace(p.prosrc, 'public.draft_commish_receipt_internal(', ''))) / length('public.draft_commish_receipt_internal('),
     (select (length(q.prosrc) - length(replace(q.prosrc, 'public.draft_commish_receipt_internal(', ''))) / length('public.draft_commish_receipt_internal(')
      from pg_proc q where q.oid = 'public.draft_queue_replace(uuid, uuid, text[])'::regprocedure))
   from pg_proc p where p.oid = 'public.draft_place_bid(uuid, integer, uuid, integer, text, uuid)'::regprocedure),
  '1|1|1',
  'A8 draft_place_bid calls the one validator once and the draft receipt seam once; draft_queue_replace calls the seam once (D449 — one seam)');

-- ---------------------------------------------------------------------------
-- B. The worlds (the owner, before any claims)
-- ---------------------------------------------------------------------------
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000',
       ('99119000-0000-4000-8000-00000000000' || i)::uuid,
       'authenticated', 'authenticated', 'pgtap-x119-u' || i || '@fieldscout.local', 'x', now(),
       '{"provider": "email", "providers": ["email"]}',
       ('{"username": "x119_user_' || i || '"}')::jsonb, now(), now()
from generate_series(1, 5) i;

select is((select count(*)::int from leagues where id::text like 'b1190000-%'), 0,
  'B1 PREMISE: no fixture league exists before this file makes it — every receipt and post counted below is a delta this file caused');

insert into players (id, full_name, position, adp)
select 'x119-p' || lpad(i::text, 2, '0'), 'X119 Player ' || lpad(i::text, 2, '0'), 'RB', i
from generate_series(1, 40) i;

insert into leagues (id, owner_id, name, season, status, team_count, scoring_system_id, settings, scoring_rules_snapshot) values
  ('b1190000-0000-4000-8000-000000000001', '99119000-0000-4000-8000-000000000001', 'pgtap-x119-LA', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "auction", "auction_budget": 200, "auction_zero_dollar_nominations": false,
     "auction_nomination_seconds": 45, "auction_bid_seconds": 30,
     "auction_anti_snipe_seconds": 10, "disconnect_grace_seconds": 30, "pick_timer_seconds": 90}}', '{}'),
  ('b1190000-0000-4000-8000-000000000002', '99119000-0000-4000-8000-000000000005', 'pgtap-x119-LO', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'),
   '{"draft": {"draft_type": "auction"}}', '{}');
update leagues
set roster_settings = '{"starting_slots": [{"key": "rb", "label": "RB", "eligible": ["RB"], "count": 1}],
                        "bench": 2, "ir_slots": [], "swap_spots": 0}'::jsonb
where id::text like 'b1190000-0000-4000-8000-00000000000%';

-- LA: t1 u1's seat, t2 u2's franchise, t3–t6 placeholders owned by u1 (169's
-- add_placeholder_seat stamps the commissioner as owner), t7 retired (owned
-- by the outsider u4, so no owner arm reaches it for u1).
insert into teams (id, owner_id, name, league_id)
select ('c1190001-0000-4000-8000-00000000000' || i)::uuid, '99119000-0000-4000-8000-000000000001',
       'x119-t' || i, 'b1190000-0000-4000-8000-000000000001'
from generate_series(1, 7) i;
update teams set owner_id = '99119000-0000-4000-8000-000000000002' where id = 'c1190001-0000-4000-8000-000000000002';
update teams set owner_id = '99119000-0000-4000-8000-000000000004', status = 'retired' where id = 'c1190001-0000-4000-8000-000000000007';
insert into teams (id, owner_id, name, league_id) values
  ('c1190002-0000-4000-8000-000000000001', '99119000-0000-4000-8000-000000000005', 'x119-o1', 'b1190000-0000-4000-8000-000000000002');
insert into league_members (league_id, user_id, team_id, role, is_placeholder)
select 'b1190000-0000-4000-8000-000000000001',
       case i when 1 then '99119000-0000-4000-8000-000000000001'::uuid when 2 then '99119000-0000-4000-8000-000000000002'::uuid end,
       ('c1190001-0000-4000-8000-00000000000' || i)::uuid,
       case i when 1 then 'commissioner' else 'manager' end, i > 2
from generate_series(1, 6) i;
insert into league_members (league_id, user_id, team_id, role) values
  ('b1190000-0000-4000-8000-000000000001', '99119000-0000-4000-8000-000000000003', null, 'co_commissioner'),
  ('b1190000-0000-4000-8000-000000000002', '99119000-0000-4000-8000-000000000005', 'c1190002-0000-4000-8000-000000000001', 'commissioner');

-- D: the live auction in its BIDDING phase — nomination 4, x119-p01 opened
-- at $1 by t1, the clock 2 seconds from zero (the anti-snipe floor bites);
-- t5 bought three players in nominations 1–3 (a complete roster, E27).
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    draft_order, nomination_order, total_rounds, current_round,
                    current_pick_number, on_clock_team_id, current_deadline, started_at, current_nomination)
select 'e1190000-0000-4000-8000-000000000001', 'b1190000-0000-4000-8000-000000000001',
       'auction', 'live', false,
       '{"auction_budget": 200, "auction_zero_dollar_nominations": false,
         "auction_nomination_seconds": 45, "auction_bid_seconds": 30,
         "auction_anti_snipe_seconds": 10, "disconnect_grace_seconds": 30,
         "pick_timer_seconds": 90}',
       o.ord, o.ord, 3, 2, 4, 'c1190001-0000-4000-8000-000000000001',
       now() + interval '2 seconds', now() - interval '5 minutes',
       '{"player_id": "x119-p01", "high_bid": 1, "high_bidder_team_id": "c1190001-0000-4000-8000-000000000001"}'
from (select jsonb_agg(t.id order by t.name) as ord from teams t
      where t.league_id = 'b1190000-0000-4000-8000-000000000001' and t.status <> 'retired') o;
insert into draft_picks (draft_id, league_id, pick_number, round, team_id, player_id, price, is_auto, made_via)
select 'e1190000-0000-4000-8000-000000000001', 'b1190000-0000-4000-8000-000000000001', i, null,
       'c1190001-0000-4000-8000-000000000005', 'x119-p3' || i, 1, false, 'manager'
from generate_series(1, 3) i;
insert into draft_bids (draft_id, league_id, nomination_seq, player_id, team_id, amount, action_id) values
  ('e1190000-0000-4000-8000-000000000001', 'b1190000-0000-4000-8000-000000000001', 4, 'x119-p01',
   'c1190001-0000-4000-8000-000000000001', 1, 'a1190000-0000-4000-8000-0000000000f0');

-- M: a live MOCK auction in LA launched by u1, practising from t2.
insert into drafts (id, league_id, draft_type, status, is_mock, config,
                    draft_order, nomination_order, total_rounds, current_round,
                    current_pick_number, on_clock_team_id, current_deadline, started_at, current_nomination)
select 'e1190000-0000-4000-8000-000000000003', 'b1190000-0000-4000-8000-000000000001',
       'auction', 'live', true,
       '{"auction_budget": 200, "auction_zero_dollar_nominations": false,
         "auction_nomination_seconds": 45, "auction_bid_seconds": 30, "auction_anti_snipe_seconds": 10,
         "mock": {"launched_by": "99119000-0000-4000-8000-000000000001",
                  "human_team_id": "c1190001-0000-4000-8000-000000000002", "cpu_speed": "realistic"}}',
       o.ord, o.ord, 3, 1, 1, 'c1190001-0000-4000-8000-000000000003',
       now() + interval '30 seconds', now() - interval '1 minute',
       '{"player_id": "x119-p02", "high_bid": 1, "high_bidder_team_id": "c1190001-0000-4000-8000-000000000003"}'
from (select jsonb_agg(t.id order by t.name) as ord from teams t
      where t.league_id = 'b1190000-0000-4000-8000-000000000001' and t.status <> 'retired') o;

select is(format('%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.bids()), '0|0|1',
  'B2 PREMISE: before any call — no receipt, no room post, one bid (the opening)');

-- ---------------------------------------------------------------------------
-- C. THE BID DOOR — u1 bids $2 for the placeholder t3 (a team he does not
--    manage) on the live nomination.
-- ---------------------------------------------------------------------------
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
create temp table _c1 as
select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 2, 'a1190000-0000-4000-8000-000000000001',
                              4, 'x119-p01', 'c1190001-0000-4000-8000-000000000003') as r;
select is((select format('%s|%s|%s|%s', r->'bid'->>'team_id', r->'bid'->>'amount', r->'bid'->>'nomination_seq', r->'bid'->>'player_id') from _c1),
  'c1190001-0000-4000-8000-000000000003|2|4|x119-p01',
  'C1 the commissioner bid lands AS t3 — the stored bid row names the team he bid for, on the nomination he named');
select is(pg_temp.nom(),
  '{"player_id": "x119-p01", "high_bid": 2, "high_bidder_team_id": "c1190001-0000-4000-8000-000000000003"}'::jsonb,
  'C2 t3 holds the high bid at $2 (the live nomination as stored)');
select is((select d.current_deadline from drafts d where d.id = 'e1190000-0000-4000-8000-000000000001'),
  now() + interval '10 seconds',
  'C3 the anti-snipe floor applied exactly as for any bid — the clock two seconds from zero re-floored to ten (D128)');
select is(pg_temp.rc(), 1, 'C4 exactly ONE receipt');
select is((select pg_temp.row_doc(c) from pg_temp.fresh() c),
  '{"actor": "99119000-0000-4000-8000-000000000001", "type": "draft_bid", "target_type": "draft",
    "target_id": "e1190000-0000-4000-8000-000000000001", "reason": null, "acting": "c1190001-0000-4000-8000-000000000003",
    "before": {"player_id": "x119-p01", "high_bid": 1, "high_bidder_team_id": "c1190001-0000-4000-8000-000000000001"},
    "after": {"player_id": "x119-p01", "high_bid": 2, "high_bidder_team_id": "c1190001-0000-4000-8000-000000000003"},
    "metadata": {"verb": "draft_place_bid", "bypassed": [], "draft_id": "e1190000-0000-4000-8000-000000000001",
                 "nomination_seq": 4, "for_team_id": "c1190001-0000-4000-8000-000000000003",
                 "affected_team_ids": ["c1190001-0000-4000-8000-000000000003"]}}'::jsonb,
  'C5 the receipt (stored literal): draft_bid on the draft, acting for t3, the high bid before and after, no reason');
select is((select c.metadata->>'bid_id' from pg_temp.fresh() c), (select r->'bid'->>'id' from _c1),
  'C6 the receipt names the stored bid row');
select pg_temp.seen();
select is(
  (select string_agg(m.message, ' | ') from league_chat m
   where m.context = 'draft:e1190000-0000-4000-8000-000000000001' and m.is_system),
  'Bid of $2 on X119 Player 01 placed by commissioner x119_user_1 for x119-t3.',
  'C7 ONE room post names the bid, the commissioner and the team (the post cannot be disabled, spec 10.3)');
-- the replay of the same action id
select is(
  (select r->'bid'->>'id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 2,
     'a1190000-0000-4000-8000-000000000001', 4, 'x119-p01', 'c1190001-0000-4000-8000-000000000003') as r) x),
  (select r->'bid'->>'id' from _c1),
  'C8 the replay of the same action id returns the original bid');
select is(format('%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.bids()), '1|1|2',
  'C9 …and writes no second receipt, post or bid');

-- ---------------------------------------------------------------------------
-- V. VALIDITY BINDS HIM (standing rule (i)) — the manager messages, verbatim
-- ---------------------------------------------------------------------------
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a1',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000003') $$,
  'P0001', 'draft_place_bid: you are already the high bidder at $2 — wait for someone to raise you (§8.6.3)',
  'V1 the self-raise refusal binds him on the team that holds the bid');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 2, 'a1190000-0000-4000-8000-0000000000a2',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: outbid at $2 — x119-t3 holds the high bid; bid $3 or more',
  'V2 the $1 increment binds him');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 199, 'a1190000-0000-4000-8000-0000000000a3',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: $199 is over your max bid of $198 — you have $200 for 3 open roster spots at a $1 per-slot reserve (§8.6.1/E5)',
  'V3 the named team max bid binds him (E5 — the team budget, not his)');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a4',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000005') $$,
  'P0001', 'draft_place_bid: your roster is complete — a complete roster cannot bid (§8.6.7(c)/E27)',
  'V4 a complete roster cannot bid, whoever bids for it (E27)');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a5',
       4, 'x119-p09', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: X119 Player 09 just went off the board — X119 Player 01 is up for bid now at $2 (§16.3)',
  'V5 the nomination identity binds him — a stale player (R330)');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a6',
       3, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: that nomination just went off the board — X119 Player 01 is up for bid now at $2 (§16.3)',
  'V6 …and a stale nomination sequence (R330)');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a7',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000007') $$,
  'P0002', 'draft_place_bid: team c1190001-0000-4000-8000-000000000007 is not an active franchise of this league',
  'V7 a retired franchise has no seat in the auction — refused by name');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a8',
       4, 'x119-p01', 'c1190002-0000-4000-8000-000000000001') $$,
  'P0002', 'draft_place_bid: team c1190002-0000-4000-8000-000000000001 is not an active franchise of this league',
  'V8 another league team is refused by name');
update drafts set status = 'paused' where id = 'e1190000-0000-4000-8000-000000000001';
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000a9',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: the draft is paused',
  'V9 a paused draft takes no bid from him either (the status rule runs before his door)');
update drafts set status = 'live' where id = 'e1190000-0000-4000-8000-000000000001';
select is(format('%s|%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.bids(), pg_temp.nom()->>'high_bid'), '1|1|2|2',
  'V10 every refusal above wrote nothing — no receipt, no post, no bid, the high bid unmoved');

-- ---------------------------------------------------------------------------
-- Z. WHOSE TEAM — the door is the commissioner alone; his own seat, and the
--    manager own bid, are the manager act (no receipt, no post)
-- ---------------------------------------------------------------------------
select pg_temp.as_user('99119000-0000-4000-8000-000000000002');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3, 'a1190000-0000-4000-8000-0000000000b1',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  '42501', 'draft_place_bid: only a commissioner can bid for another team (§8.7)',
  'Z1 a manager naming another team is refused 42501 by name');
select is((select r->'bid'->>'team_id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 3,
            'a1190000-0000-4000-8000-0000000000b2', 4, 'x119-p01', 'c1190001-0000-4000-8000-000000000002') as r) x),
  'c1190001-0000-4000-8000-000000000002',
  'Z2 a manager naming his OWN team bids for it — the same bid as naming none');
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
select is((select r->'bid'->>'team_id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 4,
            'a1190000-0000-4000-8000-0000000000b3', 4, 'x119-p01', 'c1190001-0000-4000-8000-000000000001') as r) x),
  'c1190001-0000-4000-8000-000000000001',
  'Z3 the commissioner naming his own seat t1 bids for it (his manager act)');
select pg_temp.as_user('99119000-0000-4000-8000-000000000002');
select is((select r->'bid'->>'team_id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 5,
            'a1190000-0000-4000-8000-0000000000b4', 4, 'x119-p01') as r) x),
  'c1190001-0000-4000-8000-000000000002',
  'Z4 the manager own bid, naming no team, is his seat as always');
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
select is((select r->'bid'->>'team_id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 6,
            'a1190000-0000-4000-8000-0000000000b5', 4, 'x119-p01') as r) x),
  'c1190001-0000-4000-8000-000000000001',
  'Z5 the commissioner naming no team bids for his own seat as always');
select is(format('%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.bids()), '1|1|6',
  'Z6 Z2–Z5 are manager bids — four bids landed, and not one receipt or room post among them');
-- a co-commissioner (no seat of his own) has the door too
select pg_temp.as_user('99119000-0000-4000-8000-000000000003');
select is((select r->'bid'->>'team_id' from (select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 7,
            'a1190000-0000-4000-8000-0000000000b6', 4, 'x119-p01', 'c1190001-0000-4000-8000-000000000006') as r) x),
  'c1190001-0000-4000-8000-000000000006',
  'Z7 a co-commissioner with no seat bids for t6');
select is((select format('%s|%s|%s|%s', c.actor_id, c.action_type, c.acting_as_team_id, c.after->>'high_bid') from pg_temp.fresh() c),
  '99119000-0000-4000-8000-000000000003|draft_bid|c1190001-0000-4000-8000-000000000006|7',
  'Z8 …with ONE receipt, his, acting for t6');
select pg_temp.seen();
select is(
  (select count(*)::int from league_chat m
   where m.context = 'draft:e1190000-0000-4000-8000-000000000001' and m.is_system
     and m.message = 'Bid of $7 on X119 Player 01 placed by commissioner x119_user_3 for x119-t6.'),
  1, 'Z9 …and ONE room post naming him');
select pg_temp.as_user('99119000-0000-4000-8000-000000000004');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 8, 'a1190000-0000-4000-8000-0000000000b7',
       4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004') $$,
  '42501', 'draft_place_bid: not a member of this draft''s league',
  'Z10 an outsider is refused at the member floor, as before');
-- a mock has no commissioner (§8.8): the launcher names only his seat
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
select throws_ok(
  $$ select public.draft_place_bid('e1190000-0000-4000-8000-000000000003', 2, 'a1190000-0000-4000-8000-0000000000b8',
       1, 'x119-p02', 'c1190001-0000-4000-8000-000000000004') $$,
  'P0001', 'draft_place_bid: in a practice draft you bid only for your own seat (§8.8)',
  'Z11 in a mock the launcher — the league commissioner too — cannot bid for another seat');
select is(format('%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.bids()), '2|2|7',
  'Z12 the refusals Z1 / Z10 / Z11 wrote nothing (the receipt, post and bid counted are Z7 only)');

-- ---------------------------------------------------------------------------
-- Q. THE QUEUE DOOR — u1 sets the Targets of u2 team t2 on the real draft
-- ---------------------------------------------------------------------------
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
select is(
  public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                             array['x119-p11', 'x119-p12']),
  '[{"player_id": "x119-p11", "rank": 1}, {"player_id": "x119-p12", "rank": 2}]'::jsonb,
  'Q1 the commissioner replaces another team queue — the settled queue returned, dense ranks');
select is((select pg_temp.row_doc(c) from pg_temp.fresh() c),
  '{"actor": "99119000-0000-4000-8000-000000000001", "type": "draft_set_queue", "target_type": "team",
    "target_id": "c1190001-0000-4000-8000-000000000002", "reason": null, "acting": "c1190001-0000-4000-8000-000000000002",
    "before": {"targets": 0},
    "after": {"targets": 2, "added": 2, "removed": 0, "reordered": false},
    "metadata": {"verb": "draft_queue_replace", "bypassed": [], "draft_id": "e1190000-0000-4000-8000-000000000001",
                 "team_name": "x119-t2", "affected_team_ids": ["c1190001-0000-4000-8000-000000000002"]}}'::jsonb,
  'Q2 ONE receipt (stored literal): draft_set_queue on t2, acting for t2 — counts only, never a player');
select pg_temp.seen();
select is(
  (select count(*)::int from league_chat m
   where m.context = 'draft:e1190000-0000-4000-8000-000000000001' and m.is_system
     and m.message = 'Targets for x119-t2 updated by commissioner x119_user_1.'),
  1, 'Q3 ONE room post — who set whose Targets, and nothing of what is in them');
select is(
  public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                             array['x119-p11', 'x119-p12']),
  '[{"player_id": "x119-p11", "rank": 1}, {"player_id": "x119-p12", "rank": 2}]'::jsonb,
  'Q4 the same queue again lands');
select is(format('%s|%s', pg_temp.rc(), pg_temp.posts()), '3|3',
  'Q5 …and is a NO-OP — no receipt, no post (detected by value, D336 part 3)');
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                                  array['x119-p12', 'x119-p11']);
select is((select format('%s|%s|%s', c.before, c.after, c.acting_as_team_id) from pg_temp.fresh() c),
  '{"targets": 2}|{"added": 0, "removed": 0, "targets": 2, "reordered": true}|c1190001-0000-4000-8000-000000000002',
  'Q6 a re-order of the same players is a change — one receipt, reordered');
select pg_temp.seen();
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                                  array['x119-p12', 'x119-p13']);
select is((select format('%s|%s', c.before, c.after) from pg_temp.fresh() c),
  '{"targets": 2}|{"added": 1, "removed": 1, "targets": 2, "reordered": false}',
  'Q7 one player swapped for another — one receipt, one added and one removed');
select pg_temp.seen();
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                                  array[]::text[]);
select is((select format('%s|%s', c.before, c.after) from pg_temp.fresh() c),
  '{"targets": 2}|{"added": 0, "removed": 2, "targets": 0, "reordered": false}',
  'Q8 a clear is a change — one receipt, two removed');
select pg_temp.seen();
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                                  array[]::text[]);
select is(format('%s|%s', pg_temp.rc(), pg_temp.posts()), '6|6',
  'Q9 clearing an empty queue is a no-op — none (three changes since Q5, three receipts, three posts)');
-- a placeholder he owns but does not manage: his act FOR it
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003',
                                  array['x119-p14']);
select is((select format('%s|%s|%s', c.acting_as_team_id, c.before, c.after) from pg_temp.fresh() c),
  'c1190001-0000-4000-8000-000000000003|{"targets": 0}|{"added": 1, "removed": 0, "targets": 1, "reordered": false}',
  'Q10 a placeholder seat whose team row he owns is still an act FOR that team — one receipt acting for t3');
select pg_temp.seen();
-- his own seat: his manager act
select is(jsonb_array_length(public.draft_queue_replace('e1190000-0000-4000-8000-000000000001',
            'c1190001-0000-4000-8000-000000000001', array['x119-p15'])), 1,
  'Q11 his own seat t1 queue lands (the owner arm, as before)');
select is(format('%s|%s', pg_temp.rc(), pg_temp.posts()), '7|7',
  'Q12 …and writes no receipt or post — his own act (only Q10 counted since Q9)');
-- the shape rules bind him
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003',
       array['x119-p16', 'x119-p16']) $$,
  '22023', 'A player can appear in the queue only once.', 'Q13 a duplicate is refused for him as for the manager');
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003',
       array['x119-p16', 'x119-ghost']) $$,
  '22023', 'Unknown player id(s): x119-ghost', 'Q14 an unknown player is refused for him, named');
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003',
       (select array_agg('x119-z' || g::text) from generate_series(1, 501) g)) $$,
  '22023', 'A queue can hold at most 500 players.', 'Q15 the 500-player bound binds him');
-- who may not
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000007',
       array['x119-p16']) $$,
  '42501', 'You do not manage this queue.', 'Q16 a retired franchise is outside his door (no-leak 42501)');
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190002-0000-4000-8000-000000000001',
       array['x119-p16']) $$,
  '42501', 'You do not manage this queue.', 'Q17 another league team on this draft is refused (no-leak 42501)');
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000003', 'c1190001-0000-4000-8000-000000000004',
       array['x119-p16']) $$,
  '42501', 'You do not manage this queue.', 'Q18 a mock has no commissioner — another seat of his own practice is refused');
select is(jsonb_array_length(public.draft_queue_replace('e1190000-0000-4000-8000-000000000003',
            'c1190001-0000-4000-8000-000000000002', array['x119-p16', 'x119-p17'])), 2,
  'Q19 the launcher still writes the seat he practises from (D103(3)), as before');
select pg_temp.as_user('99119000-0000-4000-8000-000000000002');
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003',
       array['x119-p16']) $$,
  '42501', 'You do not manage this queue.', 'Q20 a manager on another team is refused as before');
select pg_temp.as_user(null);
select throws_ok(
  $$ select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
       array['x119-p16']) $$,
  '42501', 'You do not manage this queue.', 'Q21 no signed-in user (the service role path) is refused in-body, as before');
select is(format('%s|%s|%s', pg_temp.rc(), pg_temp.posts(), pg_temp.q('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000003')),
  '7|7|{x119-p14}',
  'Q22 the refusals Q13–Q21 and the mock write wrote no receipt and no post, and t3 queue is as Q10 left it');
-- a co-commissioner has the door too
select pg_temp.as_user('99119000-0000-4000-8000-000000000003');
select public.draft_queue_replace('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002',
                                  array['x119-p18']);
select is((select format('%s|%s|%s', c.actor_id, c.action_type, c.acting_as_team_id) from pg_temp.fresh() c),
  '99119000-0000-4000-8000-000000000003|draft_set_queue|c1190001-0000-4000-8000-000000000002',
  'Q23 a co-commissioner sets t2 Targets — one receipt, his, acting for t2');
select pg_temp.seen();
select is(
  (select count(*)::int from commissioner_actions c
   where c.league_id = 'b1190000-0000-4000-8000-000000000001' and c.action_type = 'draft_set_queue'
     and (coalesce(c.before::text, '') || coalesce(c.after::text, '') || coalesce(c.metadata::text, '')) ~ 'x119-p'),
  0, 'Q24 no queue receipt carries a player id (TD9 — the log is member-readable)');
-- what the RLS reads see: the queue owner reads what was set; the
-- commissioner still reads no other team queue straight from the table (F48).
set local role authenticated;
select pg_temp.as_user('99119000-0000-4000-8000-000000000002');
select is(pg_temp.q('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002'), array['x119-p18'],
  'Q25 the manager of t2 reads the Targets his co-commissioner set (the 065 read policy)');
select pg_temp.as_user('99119000-0000-4000-8000-000000000001');
select is(pg_temp.q('e1190000-0000-4000-8000-000000000001', 'c1190001-0000-4000-8000-000000000002'), '{}'::text[],
  'Q26 the commissioner reads no other team queue straight from the table — the read-all policy is F48, not built here');
reset role;

-- ---------------------------------------------------------------------------
-- K. Held lock re-measured (§8.3 < 50 ms; min RTT of three — the 060 K shape)
-- ---------------------------------------------------------------------------
create temp table rc_rtt (path text, secs double precision);
do $$
declare v_t0 timestamptz; v_i int; begin
  for v_i in 1..3 loop
    perform pg_temp.as_user('99119000-0000-4000-8000-000000000001');
    v_t0 := clock_timestamp();
    perform public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 10 * v_i,
      ('a1190000-0000-4000-8000-0000000000c' || v_i)::uuid, 4, 'x119-p01', 'c1190001-0000-4000-8000-000000000004');
    insert into rc_rtt values ('commissioner', extract(epoch from clock_timestamp() - v_t0));
    perform pg_temp.as_user('99119000-0000-4000-8000-000000000002');
    v_t0 := clock_timestamp();
    perform public.draft_place_bid('e1190000-0000-4000-8000-000000000001', 10 * v_i + 5,
      ('a1190000-0000-4000-8000-0000000000d' || v_i)::uuid, 4, 'x119-p01');
    insert into rc_rtt values ('manager', extract(epoch from clock_timestamp() - v_t0));
  end loop;
end $$;
select is(format('%s|%s', pg_temp.rc(), pg_temp.nom()->>'high_bid'), '11|35',
  'K1 premise: the six timed bids landed — three commissioner bids for t4 with a receipt each, three manager bids with none');
select cmp_ok((select min(secs) from rc_rtt where path = 'commissioner'), '<', 0.05::double precision,
  'K2 held-lock discipline: the min RTT of three commissioner bids, receipt and post included, is under 50 ms');
select cmp_ok((select min(secs) from rc_rtt where path = 'manager'), '<', 0.05::double precision,
  'K3 held-lock discipline: the min RTT of three manager bids is under 50 ms');
select diag(format('K measured (min of three): commissioner bid %s ms, manager bid %s ms',
  (select round((min(secs) * 1000)::numeric, 2) from rc_rtt where path = 'commissioner'),
  (select round((min(secs) * 1000)::numeric, 2) from rc_rtt where path = 'manager')));

select * from finish();
rollback;
