-- ============================================================================
-- 126 — "whose queue" is the SEAT, and the commissioner reads another team's
--       Targets through a door (migration 178; M6 follow-ups F525 + F524;
--       spec §8.4, §8.7, §10.3, §12.6, §12.12; PROGRESS D452, D474)
-- ============================================================================
-- What this file proves, over REAL table writes and calls in one rolled-back
-- transaction:
--   §A  FORM and D137 — draft_queue_replace's live prosrc a stored-literal
--       md5, pg_temp.un178 reverses 178's two substitutions to 171's derived
--       body (119 A6's old literal 5b54fe07…); the new read door DEFINER,
--       search_path '', its ACL; both policies key on league_members, never
--       teams.owner_id, and keep the mock-launcher arm.
--   §T  THE TABLE PATH (F525 / R1339) — the commissioner who is teams.owner_id
--       of a placeholder team can no longer INSERT / UPDATE / DELETE / SELECT
--       its draft_queues rows through the table (RETURNING counts 0, the
--       INSERT 42501); a demoted ex-commissioner who still owns a team row is
--       refused on the table AND by draft_queue_replace; the seated manager
--       still reads and writes his own queue (counts 1); the mock-launcher
--       arm is unchanged and the F51 guard still keeps a real owner off a
--       mock seat.
--   §R  THE RECEIPTED DOOR — the commissioner sets the placeholder's Targets
--       through draft_queue_replace: one receipt acting for it per real
--       change, none for the same queue again, none for his own seat.
--   §D  THE COMMISSIONER'S READ (F48 / F524) — draft_queue_for_team returns
--       the team's queue as a stored literal for the commissioner and a
--       seatless co-commissioner; a manager (another team, or his own), an
--       outsider, no user, a mock, a foreign team ⇒ 42501 with one message;
--       a read writes no receipt.
-- World: league L b1260000…01 (snake, drafting) — u1 commissioner (seat t1),
-- u2 manager (seat t2), u3 a DEMOTED ex-commissioner (manager, seat t5) who
-- still holds teams.owner_id of t4, u5 co-commissioner (no seat), u4 an
-- outsider; t3 a placeholder seat owned by u1 (169's stamp); t4 a vacated
-- seat (no user) owned by u3. D e1260000…01 the real draft, M …02 a mock in
-- L launched by u1 practising from t2. LO …02 a foreign league (team o1).
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(42);

-- pg_temp.un178 — 178's two substitutions reversed (generated by
-- derive_178.py with the migration). Applied to the live prosrc it yields
-- 171's derived body.
create function pg_temp.un178(s text) returns text language plpgsql as $un$
begin
  s := replace(s, $r$  -- 178 (F525): the manager arm is the SEAT (league_members.user_id on the
  -- team), never teams.owner_id: a placeholder or vacated team's owner_id is
  -- the commissioner who made or vacated it (169 / 150), so the owner arm
  -- admitted him (and, once demoted, kept admitting him) with no receipt.
  -- Another team's queue is reached only through v_commish above, which
  -- writes the receipt.
$r$, '');
  s := replace(s, $r$      FROM public.league_members m   -- 178 (F525): the seat, never teams.owner_id
      JOIN public.drafts d ON d.id = p_draft_id
      WHERE m.team_id = p_team_id
        AND m.league_id = d.league_id
        AND m.user_id = v_uid
$r$, $o$      FROM public.teams t
      JOIN public.drafts d ON d.id = p_draft_id
      WHERE t.id = p_team_id
        AND t.league_id = d.league_id
        AND t.owner_id = v_uid
$o$);
  return s;
end
$un$;

create function pg_temp.as_user(p_uid uuid) returns void language sql as $f$
  select set_config('request.jwt.claims',
    case when p_uid is null then '' else json_build_object('sub', p_uid, 'role', 'authenticated')::text end, true)::text;
  select null::void;
$f$;
-- n(sql): run one DML as the CURRENT role (RLS applies) and return its row
-- count — the RETURNING-count face of the no-write-policy pattern (§4.2).
create function pg_temp.n(p_sql text) returns int language plpgsql as $f$
declare v int;
begin
  execute p_sql;
  get diagnostics v = row_count;
  return v;
end
$f$;
grant execute on function pg_temp.n(text) to authenticated;
create function pg_temp.rc() returns int language sql stable as $f$
  select count(*)::int from public.commissioner_actions where league_id = 'b1260000-0000-4000-8000-000000000001'
$f$;
create function pg_temp.q(p_draft uuid, p_team uuid) returns text[] language sql stable as $f$
  select coalesce(array_agg(q.player_id order by q.rank), '{}'::text[]) from public.draft_queues q
  where q.draft_id = p_draft and q.team_id = p_team
$f$;

-- ---------------------------------------------------------------------------
-- A. Form and D137
-- ---------------------------------------------------------------------------
select is(
  (select format('%s:%s', p.prosecdef, array_to_string(p.proconfig, ','))
   from pg_proc p where p.oid = 'public.draft_queue_for_team(uuid, uuid)'::regprocedure),
  't:search_path=""',
  'A1 draft_queue_for_team is SECURITY DEFINER with search_path empty');
select is(
  (select string_agg(p.proname || '=' || md5(p.prosrc), ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_queue_replace', 'draft_queue_for_team')),
  'draft_queue_for_team=ceba0b5ec0d9e5bedaa0ab22f1a77099 draft_queue_replace=69d64cbdfb4e9cbbab15f6a46fead4a7',
  'A2 the live bodies are the derived ones (golden md5)');
select is(
  (select md5(pg_temp.un178(p.prosrc)) from pg_proc p where p.oid = 'public.draft_queue_replace(uuid, uuid, text[])'::regprocedure),
  '5b54fe07ad99a494d3052e376c1e47a7',
  'A3 D137 in the database: the live draft_queue_replace with 178 reversed is 171''s body (its newest definer, 171:432-634) byte for byte');
select is(
  (select string_agg(p.proname || '=' || p.proacl::text, ' ' order by p.proname)
   from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('draft_queue_replace', 'draft_queue_for_team')),
  'draft_queue_for_team={postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres} '
  || 'draft_queue_replace={postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}',
  'A4 the ACLs: authenticated and service_role execute, PUBLIC and anon do not');
select is(
  (select string_agg(format('%s:%s:%s:%s', p.policyname, p.cmd,
            p.qual like '%league_members m%' and p.qual like '%(m.user_id = auth.uid())%',
            p.qual not like '%owner_id%' and p.qual like '%launched_by%' and p.qual like '%(NOT d.is_mock)%'),
          ' ' order by p.policyname)
   from pg_policies p where p.schemaname = 'public' and p.tablename = 'draft_queues'),
  'Own queue read:SELECT:t:t Own queue write:ALL:t:t',
  'A5 both draft_queues policies key the real-draft arm on the seat (league_members.user_id), name no teams.owner_id, keep F51''s NOT is_mock and the mock-launcher arm — and there are exactly two');

-- ---------------------------------------------------------------------------
-- B. The world (the owner, before any claims)
-- ---------------------------------------------------------------------------
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000',
       ('99126000-0000-4000-8000-00000000000' || i)::uuid,
       'authenticated', 'authenticated', 'pgtap-x126-u' || i || '@fieldscout.local', 'x', now(),
       '{"provider": "email", "providers": ["email"]}',
       ('{"username": "x126_user_' || i || '"}')::jsonb, now(), now()
from generate_series(1, 5) i;

insert into players (id, full_name, position, adp)
select 'x126-p' || lpad(i::text, 2, '0'), 'X126 Player ' || lpad(i::text, 2, '0'), 'RB', i
from generate_series(1, 6) i;

insert into leagues (id, owner_id, name, season, status, team_count, scoring_system_id, settings, scoring_rules_snapshot) values
  ('b1260000-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000001', 'pgtap-x126-L', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'), '{}', '{}'),
  ('b1260000-0000-4000-8000-000000000002', '99126000-0000-4000-8000-000000000004', 'pgtap-x126-LO', 2026, 'drafting', 8,
   (select id from scoring_systems where is_template and name = 'ESPN Standard'), '{}', '{}');

insert into teams (id, owner_id, name, league_id) values
  ('c1260001-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000001', 'x126-t1', 'b1260000-0000-4000-8000-000000000001'),
  ('c1260001-0000-4000-8000-000000000002', '99126000-0000-4000-8000-000000000002', 'x126-t2', 'b1260000-0000-4000-8000-000000000001'),
  ('c1260001-0000-4000-8000-000000000003', '99126000-0000-4000-8000-000000000001', 'x126-t3', 'b1260000-0000-4000-8000-000000000001'),
  ('c1260001-0000-4000-8000-000000000004', '99126000-0000-4000-8000-000000000003', 'x126-t4', 'b1260000-0000-4000-8000-000000000001'),
  ('c1260001-0000-4000-8000-000000000005', '99126000-0000-4000-8000-000000000003', 'x126-t5', 'b1260000-0000-4000-8000-000000000001'),
  ('c1260002-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000004', 'x126-o1', 'b1260000-0000-4000-8000-000000000002');
insert into league_members (league_id, user_id, team_id, role, is_placeholder) values
  ('b1260000-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000001', 'commissioner', false),
  ('b1260000-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000002', 'c1260001-0000-4000-8000-000000000002', 'manager', false),
  ('b1260000-0000-4000-8000-000000000001', null, 'c1260001-0000-4000-8000-000000000003', 'manager', true),
  ('b1260000-0000-4000-8000-000000000001', null, 'c1260001-0000-4000-8000-000000000004', 'manager', true),
  ('b1260000-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000003', 'c1260001-0000-4000-8000-000000000005', 'manager', false),
  ('b1260000-0000-4000-8000-000000000001', '99126000-0000-4000-8000-000000000005', null, 'co_commissioner', false),
  ('b1260000-0000-4000-8000-000000000002', '99126000-0000-4000-8000-000000000004', 'c1260002-0000-4000-8000-000000000001', 'commissioner', false);

insert into drafts (id, league_id, draft_type, status, is_mock, config, total_rounds, current_pick_number) values
  ('e1260000-0000-4000-8000-000000000001', 'b1260000-0000-4000-8000-000000000001', 'snake', 'scheduled', false, '{}', 3, 1),
  ('e1260000-0000-4000-8000-000000000002', 'b1260000-0000-4000-8000-000000000001', 'snake', 'scheduled', true,
   '{"mock": {"launched_by": "99126000-0000-4000-8000-000000000001",
              "human_team_id": "c1260001-0000-4000-8000-000000000002", "cpu_speed": "realistic"}}', 3, 1),
  ('e1260000-0000-4000-8000-000000000003', 'b1260000-0000-4000-8000-000000000002', 'snake', 'scheduled', false, '{}', 3, 1);

-- Rows written before 178 through the owner arm (they stay — D38 waiver):
-- t3's (owner u1) and t4's (owner u3), plus t2's own.
insert into draft_queues (draft_id, team_id, player_id, rank) values
  ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003', 'x126-p01', 1),
  ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000004', 'x126-p02', 1),
  ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002', 'x126-p03', 1);

select is(pg_temp.rc(), 0, 'B1 PREMISE: no receipt in L before any call');

-- ---------------------------------------------------------------------------
-- T. The table path (F525)
-- ---------------------------------------------------------------------------
set local role authenticated;
select pg_temp.as_user('99126000-0000-4000-8000-000000000001');

select throws_ok(
  $$insert into public.draft_queues (draft_id, team_id, player_id, rank)
    values ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003', 'x126-p04', 2)$$,
  '42501', null,
  'T1 THE BYPASS CLOSED: the commissioner who owns placeholder t3''s team row cannot INSERT its queue through the table');
select is(pg_temp.n($$update public.draft_queues set rank = 9
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000003'$$), 0,
  'T2 …nor UPDATE it (0 rows)');
select is(pg_temp.n($$delete from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000003'$$), 0,
  'T3 …nor DELETE it (0 rows)');
select is((select count(*)::int from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000003'), 0,
  'T4 …nor SELECT it from the table (his read is the door — §D)');
select is(pg_temp.n($$delete from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000002'$$), 0,
  'T5 the commissioner cannot DELETE a seated manager''s queue through the table either (0 rows)');

-- the demoted ex-commissioner u3 still owns t4's row
select pg_temp.as_user('99126000-0000-4000-8000-000000000003');
select throws_ok(
  $$insert into public.draft_queues (draft_id, team_id, player_id, rank)
    values ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000004', 'x126-p05', 2)$$,
  '42501', null,
  'T6 a demoted ex-commissioner who still holds teams.owner_id of vacated t4 cannot INSERT its queue');
select is(pg_temp.n($$delete from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000004'$$), 0,
  'T7 …nor DELETE it (0 rows)');
select throws_ok(
  $$select public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000004', array['x126-p05'])$$,
  '42501', 'You do not manage this queue.',
  'T8 …and draft_queue_replace''s manager arm refuses him too (it keys on the seat now)');
select is(pg_temp.q('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000005'), '{}'::text[],
  'T9 PREMISE: u3''s own seat t5 has no Targets yet');
select is(public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000005', array['x126-p05']),
  '[{"rank": 1, "player_id": "x126-p05"}]'::jsonb,
  'T10 the seated manager u3 still sets his own seat''s Targets through the door');

-- the seated manager u2 on the table
select pg_temp.as_user('99126000-0000-4000-8000-000000000002');
select is(pg_temp.n($$insert into public.draft_queues (draft_id, team_id, player_id, rank)
    values ('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002', 'x126-p04', 2)$$), 1,
  'T11 the seated manager INSERTs his own queue row (1 row)');
select is((select array_agg(q.player_id order by q.rank) from public.draft_queues q
    where q.draft_id = 'e1260000-0000-4000-8000-000000000001' and q.team_id = 'c1260001-0000-4000-8000-000000000002'),
  array['x126-p03', 'x126-p04'],
  'T12 …and reads his queue from the table');
select is(pg_temp.n($$update public.draft_queues set rank = 3
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000002' and player_id = 'x126-p04'$$), 1,
  'T13 …UPDATEs it (1 row)');
select is(pg_temp.n($$delete from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id = 'c1260001-0000-4000-8000-000000000002' and player_id = 'x126-p04'$$), 1,
  'T14 …DELETEs it (1 row)');
select is((select count(*)::int from public.draft_queues
    where draft_id = 'e1260000-0000-4000-8000-000000000001' and team_id <> 'c1260001-0000-4000-8000-000000000002'), 0,
  'T15 …and sees no other team''s queue');
select throws_ok(
  $$insert into public.draft_queues (draft_id, team_id, player_id, rank)
    values ('e1260000-0000-4000-8000-000000000002', 'c1260001-0000-4000-8000-000000000002', 'x126-p06', 1)$$,
  '42501', null,
  'T16 F51 kept: t2''s real manager cannot write the mock''s human-seat queue (the launcher''s practice prep)');

-- the mock launcher arm, unchanged
select pg_temp.as_user('99126000-0000-4000-8000-000000000001');
select is(pg_temp.n($$insert into public.draft_queues (draft_id, team_id, player_id, rank)
    values ('e1260000-0000-4000-8000-000000000002', 'c1260001-0000-4000-8000-000000000002', 'x126-p06', 1)$$), 1,
  'T17 the D103(3) launcher arm is unchanged: u1 writes his mock''s human-seat queue (1 row)');
reset role;

select is(format('%s|%s|%s', pg_temp.rc(),
    array_to_string(pg_temp.q('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003'), ','),
    array_to_string(pg_temp.q('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000004'), ',')),
  '0|x126-p01|x126-p02',
  'T18 nothing the table path refused was written: no receipt, t3 and t4 hold what they held');

-- ---------------------------------------------------------------------------
-- R. The receipted door — u1 sets placeholder t3's Targets
-- ---------------------------------------------------------------------------
select pg_temp.as_user('99126000-0000-4000-8000-000000000001');
select is(public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003', array['x126-p01', 'x126-p02']),
  '[{"rank": 1, "player_id": "x126-p01"}, {"rank": 2, "player_id": "x126-p02"}]'::jsonb,
  'R1 the commissioner sets placeholder t3''s Targets through draft_queue_replace');
select is(
  (select format('%s|%s|%s|%s|%s|%s', count(*), max(c.action_type), max(c.target_type), max(c.acting_as_team_id::text),
                 max(c.before::text), max(c.after::text))
   from public.commissioner_actions c where c.league_id = 'b1260000-0000-4000-8000-000000000001'),
  '1|draft_set_queue|team|c1260001-0000-4000-8000-000000000003|{"targets": 1}|{"added": 1, "removed": 0, "targets": 2, "reordered": false}',
  'R2 ONE receipt acting for t3 (stored literal — counts only, never the players)');
select is(public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003', array['x126-p01', 'x126-p02']),
  '[{"rank": 1, "player_id": "x126-p01"}, {"rank": 2, "player_id": "x126-p02"}]'::jsonb,
  'R3 the same Targets again');
select is(pg_temp.rc(), 1, 'R4 …write NO receipt (a no-op)');
select lives_ok(
  $$select public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003', array['x126-p02', 'x126-p01'])$$,
  'R5 a re-order of t3''s Targets');
select is(pg_temp.rc(), 2, 'R6 …writes one more receipt (a real change)');
select lives_ok(
  $$select public.draft_queue_replace('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000001', array['x126-p06'])$$,
  'R7 the commissioner sets his OWN seat''s Targets');
select is(pg_temp.rc(), 2, 'R8 …his manager act: no receipt');

-- ---------------------------------------------------------------------------
-- D. The commissioner's read (F48 / F524)
-- ---------------------------------------------------------------------------
select is(public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003'),
  '[{"rank": 1, "player_id": "x126-p02"}, {"rank": 2, "player_id": "x126-p01"}]'::jsonb,
  'D1 the commissioner reads placeholder t3''s Targets in rank order (stored literal)');
select is(public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002'),
  '[{"rank": 1, "player_id": "x126-p03"}]'::jsonb,
  'D2 …and a seated manager''s Targets (t2)');
select pg_temp.as_user('99126000-0000-4000-8000-000000000005');
select is(public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000005'),
  '[{"rank": 1, "player_id": "x126-p05"}]'::jsonb,
  'D3 a co-commissioner with no seat reads t5''s Targets');
select is(pg_temp.rc(), 2, 'D4 reads write no receipt');

select pg_temp.as_user('99126000-0000-4000-8000-000000000002');
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000003')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D5 NO LEAK: a manager cannot read another team''s Targets through the door');
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D6 …nor his own through it (he reads his own from the table)');
select pg_temp.as_user('99126000-0000-4000-8000-000000000004');
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D7 an outsider (another league''s commissioner) is refused');
select pg_temp.as_user(null);
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260001-0000-4000-8000-000000000002')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D8 no user is refused');
select pg_temp.as_user('99126000-0000-4000-8000-000000000001');
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000002', 'c1260001-0000-4000-8000-000000000002')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D9 a mock has no commissioner (§8.8) — the launcher reads his practice seat from the table');
select throws_ok(
  $$select public.draft_queue_for_team('e1260000-0000-4000-8000-000000000001', 'c1260002-0000-4000-8000-000000000001')$$,
  '42501', 'draft_queue_for_team: only a commissioner can read another team''s Targets (§12.6)',
  'D10 a team of another league is refused');

select * from finish();
rollback;
