-- ============================================================================
-- 128 — league posts and notices in plain English (migration 180; F569
--       part 2, F573; PROGRESS D490)
-- ============================================================================
-- What this file proves, in one rolled-back transaction:
--   §A  FORM and D137 — each of the five bodies keeps its security, its
--       search_path '' and its client EXECUTE as before; the live prosrc md5s
--       are stored literals; with 180's 26 hunks reversed (pg_temp.un180)
--       each md5 is its newest definer's FILE TEXT (149:1924-1987,
--       118:1945-2218, 155:190-257, 155:551-724, 156:205-668 — stored
--       literals; 103 A7 and 105 A6 already held two of them).
--   §B  THE SETTINGS PANEL'S WORDS (F573) — every refused key's refused_why
--       is pinned character for character, partners share their sentence,
--       and no reason in the catalog carries a spec mark, a ledger code, a
--       line reference or a snake_case setting name.
-- The stored / sent sentences of finalize_matchups, trade_vote_veto_internal,
-- trade_tick and trade_execute_internal are pinned where they are produced
-- over real fixtures: 064 E11c, 099 D4 / G7 / F12 / I4 / I5, 103 D7 / D16 /
-- E4 / E7, 104 F3 / F4b, 122 X12 / X13 / Y7 (moved by 180).
-- Break probe (§4.3): put a code back into one refused_why (team_count's)
-- ⇒ A2, A3, B1, B13 and 077 E2 red (shown in the PR, reverted).
-- ============================================================================
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(18);

-- pg_temp.un180 — migration 180's 26 wording hunks reversed (generated by
-- gen_un180.py from derive_180.py's pairs); an identity on every body
-- 180 did not touch. Applied INNERMOST.
-- pg_temp.un183 — migration 183's two inserted lines per job body removed
-- (each marked `183 / L.G1.3 (TD4)`); an identity on every other body.
create function pg_temp.un183(p_src text) returns text language sql as $un183$
  select regexp_replace(
           regexp_replace(p_src,
             E'\n\n  PERFORM public\\.job_pause_note_internal\\(''[a-z-]+'', p_league_id, p_now\\);   -- 183 / L\\.G1\\.3 \\(TD4\\)', '', 'g'),
           E'        AND NOT public\\.job_paused_internal\\(''[a-z-]+'', l\\.id\\)   -- 183 / L\\.G1\\.3 \\(TD4\\)\n', '', 'g')
$un183$;
create function pg_temp.un180(p_src text) returns text language sql as $un180$
  select replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(p_src,
    E'\'The playoff bracket has already been set from this, so it can\'\'t change once the playoffs start.\')\n    WHEN p_key IN (\'playoff_weeks_per_round\'',
    E'\'once the league is in playoffs (or complete) the bracket has been SEEDED from this key (118:1075-1077, :1338-1340); no verb re-seeds a bracket under played rounds\')\n    WHEN p_key IN (\'playoff_weeks_per_round\''),
    E'\'The playoff bracket has already been set from this, so it can\'\'t change once the playoffs start.\')\n    -- REFUSED',
    E'\'once the league is in playoffs (or complete) the bracket has been SEEDED from this key (118:1075-1077, :1338-1340); no verb re-seeds a bracket under played rounds\')\n    -- REFUSED'),
    E'\'The season\'\'s weeks and matchups are already set, so the length of the regular season and when the playoffs start can only change before the draft.\'',
    E'\'this key defines the SEASON WINDOW: league_weeks and matchups were generated for the stored plan (111:346, :422) and the standings cutoff reads it (D288), so moving it under rows that already exist re-plans nothing and re-cuts the standings; it is also coupled to its partner by Q10 (playoff_start_week = regular_season_weeks + 1), which one key at a time cannot keep. Pre-draft the route is update_league_settings, which validates the pair; post-draft no verb re-plans a season\''),
    E'\'The number of teams can only change before the draft — every team already has its place and its schedule.\'',
    E'\'team_count is PRE-DRAFT ONLY (§7.3, erratum v2.16.40 — Q65 ruled (b) by Chris 2026-09-15): seats (teams / league_members) and a schedule already exist for the stored count; pre-draft the route is update_league_settings (F28\'\'s seat floor lives there, 118:2499-2510); post-draft there is NO route — no verb raises this number in-season, and a placeholder seat cannot be added past the stored ceiling\''),
    E'\'The schedule has already been made from this, so it can only change before the draft.\'',
    E'\'this key defines the SCHEDULE SHAPE: primary, secondary and median rows are generated by the schedule engine (110/111) from it, and flipping it under rows that already exist leaves rows nothing reads or removes. Pre-draft the route is update_league_settings; post-draft no verb re-plans a schedule\''),
    E'\'Leagues are redraft only for now — there\'\'s nothing else to switch to.\'',
    E'\'pinned to redraft in v1 (§7.3.1) — there is no other value to change it to\''),
    E'\'Each player\'\'s lineup spot always locks when his own game kicks off — this can\'\'t be changed.\'',
    E'\'pinned to per_player_kickoff by 114\'\'s CHECK (Q34(A)) — any other value is a constraint violation\''),
    E'\'Divisions aren\'\'t available yet — the whole league plays as one group.\'',
    E'\'pinned to 1 (Q30 (d), v2.16.12) — the engine ignores the value\''),
    E'\'Playoff byes come from the number of playoff teams — change that instead.\'',
    E'\'derived from the bracket size (§7.3.1: the literal \'\'auto\'\') — not independently settable\''),
    E'\'This is set automatically when the schedule is made or reshuffled.\'',
    E'\'minted by the schedule engine and re-minted by a remix (F246) — never set by hand\''),
    E'\'This setting has been replaced: pick the days and time waivers run, and when free agency opens, instead. A dropped player stays on waivers until the next waiver run.\'',
    E'\'RETIRED by the waiver schedule (Q70, ruled 2026-09-27; spec §7.3.4 v2.16.59): when waivers run is waiver_run_days + waiver_run_time in waiver_time_zone, and when free agency is open is free_agency_opens (+ free_agency_open_day / free_agency_open_time); a dropped player is on waivers until the next run, so there is no waiver period to set\''),
    E'\'This setting has been retired: a waiver claim always fails if the player you\'\'d drop has already played this week, just like a regular drop.\'',
    E'\'RETIRED (Q73, ruled 2026-09-27; spec §7.3.4 v2.16.59): a waiver claim whose drop has already played this week always fails at the waiver run — the same rule as a manual drop — so there is nothing to switch\''),
    E'\'The draft is over, so its settings can\'\'t change now.\'',
    E'\'the §7.3.8 draft block: pre-draft it belongs to the wizard / update_league_settings; post-draft the draft has happened and the block has no subject\''),
    E'\' is final without the postponed game\' ||',
    E'\' was finalized without the postponed game\' ||'),
    E'\' — players in a game moved out of the week score 0 for the week. The commissioner can change a result.\',',
    E'\' — players in a game postponed out of the week score 0 for the week (§23.3/E43); the commissioner may override.\','),
    E'\' managers who can vote voted to veto, and the league needs \'',
    E'\' managers who can vote voted to veto, and the league\'\'s number is \''),
    E'is more than the managers who can vote)\'\n            ELSE \'\' END;',
    E'is more than the managers who can vote)\'\n            ELSE \'\' END\n    || \' (§13.3 / Q77)\';'),
    E'              || \' began (\' || (v_deadline ->> \'label\') || \')\',',
    E'              || \' began (\' || (v_deadline ->> \'label\') || \'; trade_deadline_week \' || (v_deadline ->> \'deadline_week\') || \', §13.3 / Q76)\','),
    E'          v_reason := \'the league is \' || CASE WHEN v_league.deleted_at IS NOT NULL THEN \'deleted\' WHEN v_league.status = \'complete\' THEN \'over for the season\' ELSE \'not in its season\' END\n                      || \' — trades only go through during the season and the playoffs\';',
    E'          v_reason := \'the league is \' || CASE WHEN v_league.deleted_at IS NOT NULL THEN \'deleted\' ELSE v_league.status END\n                      || \' — a trade goes through only while the league is in season or in the playoffs (§7.1 / §13.3)\';'),
    E'          SELECT tm.name || \' is retired and can\'\'t make trades\' INTO v_reason',
    E'          SELECT tm.name || \' is retired — a sealed franchise makes no trades (§7.2.1)\' INTO v_reason'),
    E'|| COALESCE(\'$\' || m.faab_balance, \'not set\')',
    E'|| COALESCE(\'$\' || m.faab_balance, \'not recorded\') || \' (§13.3)\''),
    E'      RAISE EXCEPTION \'trade_execute: the league is % — trades only go through during the season and the playoffs\',\n        CASE WHEN v_league.deleted_at IS NOT NULL THEN \'deleted\' WHEN v_league.status = \'complete\' THEN \'over for the season\' ELSE \'not in its season\' END',
    E'      RAISE EXCEPTION \'trade_execute: the league is % — a trade goes through only while the league is in season or in the playoffs (§7.1 / §13.3)\',\n        CASE WHEN v_league.deleted_at IS NOT NULL THEN \'deleted\' ELSE v_league.status END'),
    E'\'trade_execute: % is retired and can\'\'t make trades\',',
    E'\'trade_execute: % is retired — a sealed franchise makes no trades (§7.2.1)\','),
    E'\'trade_execute: % has no FAAB budget to receive $% into\',',
    E'\'trade_execute: % has no FAAB balance on record to receive $% into (§12.2)\','),
    E'\' already played this week, and this league cancels a trade like that instead of waiting for the week\'\'s last game to end\',',
    E'\' already kicked off this week and cannot change teams until the week\'\'s last game ends — this league fails such a trade instead of waiting (trade_lock_behavior = reject, E35)\','),
    E'\' already played this week, so the whole trade goes through right after the week\'\'s last game ends. Until then every player stays with his team.\',',
    E'\' already played this week, so the whole trade goes through right after the week\'\'s last game ends (E35); until then every player stays with his team\',')
$un180$;

-- ---------------------------------------------------------------------------
-- A. Form and D137
-- ---------------------------------------------------------------------------
select is(
  (select string_agg(format('%s:%s:%s:%s', p.proname, p.prosecdef, array_to_string(p.proconfig, ','),
                            has_function_privilege('anon', p.oid, 'EXECUTE')), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('commish_setting_policy', 'finalize_matchups', 'trade_execute_internal', 'trade_tick', 'trade_vote_veto_internal')),
  'commish_setting_policy:f:search_path="":f finalize_matchups:t:search_path="":f trade_execute_internal:f:search_path="":f trade_tick:f:search_path="":f trade_vote_veto_internal:f:search_path="":f',
  'A1 form unchanged: finalize_matchups SECURITY DEFINER, the rest not; search_path '''' on all five; anon executes none');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un183(p.prosrc)), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('commish_setting_policy', 'finalize_matchups', 'trade_execute_internal', 'trade_tick', 'trade_vote_veto_internal')),
  'commish_setting_policy=2550d16b263ed670fecf42883931315e finalize_matchups=5239ab311af797a401bb91d00d78f9bd trade_execute_internal=dae3b9d576251356c39932bd7649177f trade_tick=c45ab31cf5c172eadc4e4566d7dd18b0 trade_vote_veto_internal=0e7abc429e88101e59a828c890eb65a0',
  'A2 the five live prosrc md5s — 180 as written (stored literals; 183''s two finalize_matchups pause lines reversed first — L.G1.3)');
select is(
  (select string_agg(p.proname || '=' || md5(pg_temp.un180(pg_temp.un183(p.prosrc))), ' ' order by p.proname)
   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('commish_setting_policy', 'finalize_matchups', 'trade_execute_internal', 'trade_tick', 'trade_vote_veto_internal')),
  'commish_setting_policy=35c597336b625a6896981d3bda1b1fd9 finalize_matchups=023892388a95d6df2dd1cf44f4341928 trade_execute_internal=044fd0a7668adb67c2c81b0e452b8341 trade_tick=8ed5c0706d2fa7da12898deeda721c31 trade_vote_veto_internal=220794d66953336530f746e2d2b62f0e',
  'A3 D137: with 180''s hunks reversed each body is its newest definer''s FILE TEXT (stored literals) — 180 changed wording and nothing else');
select is(
  (select count(*)::int from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('commish_setting_policy', 'finalize_matchups', 'trade_execute_internal', 'trade_tick', 'trade_vote_veto_internal')
     and pg_temp.un180(p.prosrc) <> p.prosrc),
  5,
  'A4 …and every one of the five carries at least one of 180''s hunks');

-- ---------------------------------------------------------------------------
-- B. The settings panel's words (F573)
-- ---------------------------------------------------------------------------
select is(public.commish_setting_policy('team_count') ->> 'refused_why',
  'The number of teams can only change before the draft — every team already has its place and its schedule.',
  'B1 team_count');
select is(public.commish_setting_policy('regular_season_weeks') ->> 'refused_why',
  'The season''s weeks and matchups are already set, so the length of the regular season and when the playoffs start can only change before the draft.',
  'B2 regular_season_weeks');
select is(public.commish_setting_policy('schedule_mode') ->> 'refused_why',
  'The schedule has already been made from this, so it can only change before the draft.',
  'B3 schedule_mode');
select is(public.commish_setting_policy('playoff_teams') ->> 'refused_why',
  'The playoff bracket has already been set from this, so it can''t change once the playoffs start.',
  'B4 playoff_teams (class bracket)');
select is(public.commish_setting_policy('format') ->> 'refused_why',
  'Leagues are redraft only for now — there''s nothing else to switch to.', 'B5 format');
select is(public.commish_setting_policy('lineup_lock') ->> 'refused_why',
  'Each player''s lineup spot always locks when his own game kicks off — this can''t be changed.', 'B6 lineup_lock');
select is(public.commish_setting_policy('divisions') ->> 'refused_why',
  'Divisions aren''t available yet — the whole league plays as one group.', 'B7 divisions');
select is(public.commish_setting_policy('playoff_byes') ->> 'refused_why',
  'Playoff byes come from the number of playoff teams — change that instead.', 'B8 playoff_byes');
select is(public.commish_setting_policy('schedule_seed') ->> 'refused_why',
  'This is set automatically when the schedule is made or reshuffled.', 'B9 schedule_seed');
select is(public.commish_setting_policy('waiver_period_hours') ->> 'refused_why',
  'This setting has been replaced: pick the days and time waivers run, and when free agency opens, instead. A dropped player stays on waivers until the next waiver run.',
  'B10 the retired waiver timing keys');
select is(public.commish_setting_policy('bench_lock') ->> 'refused_why',
  'This setting has been retired: a waiver claim always fails if the player you''d drop has already played this week, just like a regular drop.',
  'B11 bench_lock');
select is(public.commish_setting_policy('draft') ->> 'refused_why',
  'The draft is over, so its settings can''t change now.', 'B12 draft');
select is(
  (select count(*)::int from unnest(array[
     'waiver_type', 'faab_budget', 'trade_review', 'trade_deadline_week', 'roster_settings', 'faab_min_bid', 'faab_tiebreaker',
     'waiver_run_days', 'waiver_run_time', 'waiver_time_zone', 'free_agency_opens', 'free_agency_open_day', 'free_agency_open_time',
     'acquisitions_per_week', 'acquisitions_per_season', 'fa_hold_hours', 'trade_veto_votes', 'trade_review_period_hours',
     'allow_faab_in_trades', 'allow_future_considerations', 'trade_lock_behavior', 'allow_illegal_lineups', 'auto_sub_inactives',
     'stat_correction_window', 'tiebreakers', 'playoff_reseed', 'scoring_system_id', 'playoff_teams', 'playoff_weeks_per_round',
     'consolation_bracket', 'third_place_game', 'regular_season_weeks', 'playoff_start_week', 'team_count', 'schedule_mode',
     'median_game', 'second_opponent', 'format', 'lineup_lock', 'divisions', 'playoff_byes', 'schedule_seed', 'waiver_process_day',
     'waiver_process_time', 'waiver_period_hours', 'free_agency', 'bench_lock', 'draft']) k
   where public.commish_setting_policy(k) ->> 'refused_why' ~ '§|[A-Z][0-9]|[a-z]_[a-z]|[0-9]:[0-9]|\(|\)|[A-Z]{3,}'),
  0,
  'B13 no refused_why in the catalog carries a spec mark, a ledger code, a line reference, brackets, SHOUTING or a snake_case setting name');
select is(
  (select string_agg(k || '=' || md5(public.commish_setting_policy(k) ->> 'refused_why'), ' ' order by k)
   from unnest(array['playoff_start_week', 'median_game', 'second_opponent', 'playoff_weeks_per_round', 'consolation_bracket',
                     'third_place_game', 'waiver_process_day', 'waiver_process_time', 'free_agency']) k)
  = (select string_agg(k || '=' || md5(public.commish_setting_policy(p) ->> 'refused_why'), ' ' order by k)
     from (values ('playoff_start_week', 'regular_season_weeks'), ('median_game', 'schedule_mode'), ('second_opponent', 'schedule_mode'),
                  ('playoff_weeks_per_round', 'playoff_teams'), ('consolation_bracket', 'playoff_teams'), ('third_place_game', 'playoff_teams'),
                  ('waiver_process_day', 'waiver_period_hours'), ('waiver_process_time', 'waiver_period_hours'), ('free_agency', 'waiver_period_hours')) v(k, p)),
  true,
  'B14 partners share their sentence (the season window, the schedule shape, the bracket, the retired waiver timing keys)');

select * from finish();
rollback;
