/**
 * playoffs-api-db.test.ts — L.D5.5's stack half for `GET /api/leagues/[id]/playoffs`
 * at the SERVICE layer (`readPlayoffBracket`) and the standings route's
 * projected arm (`readStandings(…, { view: 'projected' })`) against the
 * LOCAL Supabase stack through PostgREST — the production wire path — with
 * real signed-in clients (the `inseason-reads-api-db.test.ts` shape).
 *
 * pgTAP 066 proves 118's engine DB-side (the pairing rule, the rollover,
 * the rebuild, the verdicts). What THIS suite proves is the layer it does
 * not touch:
 *   - the auth matrix on the member read: a NON-MEMBER gets the family's
 *     no-leak 403 (118's in-body 42501), a nonexistent league the same 403
 *     for a member, a SOFT-DELETED league the ONE 404 copy (R812);
 *   - the PROJECTED document over 118's REAL rows: a league whose season
 *     was generated by `league_generate_schedule` (110 — 14 regular + 3
 *     playoff `league_weeks`, the 8-team defaults: `playoff_teams` 6,
 *     bracket 8, 3 rounds) reads `view: projected` with round 1 seeded
 *     from the projected table (2 byes, 2 games), the basis named, and
 *     the rollover NULL on the wire (the synthetic calendar records no
 *     `last_game_ends_at` — F238's posture reaches the client as `null`);
 *   - **F247(b) on the bracket**: playoff rows PLANTED with seeds (the
 *     engine's shape — a row with seeds is the engine's, D318(5)) render
 *     `home_total` as `101.25` and a bye's as `0` on the wire, and the
 *     service hands the UI ONE kind of number; a NULL week score stays
 *     NULL (E61); `decided_by` is 118's verdict;
 *   - a playoff row WITHOUT seeds is counted as `foreign_rows` and never
 *     read as a game;
 *   - the projected standings arm: `projected: true` / `weeks_projected`
 *     through the route's query, the final read `projected: false`, and a
 *     `?view=` outside the enum a 400.
 *
 * Requires the local stack — D59(5) precedent; FAILS loudly when the
 * stack is down, never skips (§4.3).
 *
 * CALENDAR (F215/F226): the league lives on `SYNTHETIC_SEASON` (2099); NO
 * `nfl_games` rows are placed and NO `nfl_weeks` instant is written —
 * nothing here evaluates a kickoff or drives a job. The planted playoff
 * rows are `scheduled` rows with scores, exactly what the read model
 * reads (066 I-series' shape).
 *
 * Determinism: FIXED emails/usernames/action_ids + cleanup-first. Action-id
 * prefix `b01` — this suite owns it (the D108(14) registry: af0–aff and
 * b00 taken, b01 measured free 2026-09-08).
 */
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import type { Database } from '@/types/database'

import { defaultsForTeamCount, splitSettings } from '../settings/league-settings'
import { SYNTHETIC_SEASON, seedSyntheticSeason } from '../sim/synthetic-season'
import { INSEASON_LEAGUE_GONE_MESSAGE, INSEASON_READ_FORBIDDEN_MESSAGE } from './inseason-reads'
import { readPlayoffBracket, type PlayoffBracketDoc } from './playoffs-service'
import { readStandings, type LeagueStandings } from './standings-service'

const LOCAL_URL = process.env.SUPABASE_LOCAL_URL ?? 'http://127.0.0.1:54321'
const LOCAL_ANON_KEY =
  process.env.SUPABASE_LOCAL_ANON_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'
const LOCAL_SERVICE_ROLE_KEY =
  process.env.SUPABASE_LOCAL_SERVICE_ROLE_KEY ??
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU'

const LEAGUE_NAME = 'vitest-playoffs-api-league'
const NO_SUCH_LEAGUE = '00000000-0000-4000-8000-0000000beef5'

const COMMISH = { email: 'playoffs-api-commish@fieldscout.test', password: 'pgtap-playoffs-api-pass-1', username: 'po_commish_one' }
const MANAGER = { email: 'playoffs-api-manager@fieldscout.test', password: 'pgtap-playoffs-api-pass-2', username: 'po_manager_two' }
const OUTSIDER = { email: 'playoffs-api-outsider@fieldscout.test', password: 'pgtap-playoffs-api-pass-3', username: 'po_outsider_three' }

const ACTION = { league: 'b0100000-0000-4000-8000-000000000001' } as const

const service = createClient<Database>(LOCAL_URL, LOCAL_SERVICE_ROLE_KEY, { auth: { persistSession: false } })

let commishClient: SupabaseClient<Database>
let managerClient: SupabaseClient<Database>
let outsiderClient: SupabaseClient<Database>
let leagueId: string
let teamIds: string[] = []

async function deleteUserByUsername(username: string): Promise<void> {
  const { data } = await service.from('profiles').select('id').eq('username', username)
  for (const row of data ?? []) await service.auth.admin.deleteUser(row.id)
}

async function cleanup(): Promise<void> {
  const { data: stale } = await service.from('leagues').select('id').like('name', `${LEAGUE_NAME}%`)
  const ids = (stale ?? []).map((row) => row.id)
  if (ids.length > 0) {
    for (const table of ['team_week_results', 'matchups', 'league_weeks', 'league_player_pool', 'league_rosters', 'league_members', 'league_chat', 'schedule_actions'] as const) {
      const { error } = await service.from(table).delete().in('league_id', ids)
      if (error) throw new Error(`cleanup ${table}: ${error.message}`)
    }
    const { error: teamsError } = await service.from('teams').delete().in('league_id', ids)
    if (teamsError) throw new Error(`cleanup teams: ${teamsError.message}`)
    const { error: leaguesError } = await service.from('leagues').delete().in('id', ids)
    if (leaguesError) throw new Error(`cleanup leagues: ${leaguesError.message}`)
  }
  for (const u of [COMMISH, MANAGER, OUTSIDER]) await deleteUserByUsername(u.username)
}

async function createUser(user: { email: string; password: string; username: string }): Promise<string> {
  const { data, error } = await service.auth.admin.createUser({ email: user.email, password: user.password, email_confirm: true, user_metadata: { username: user.username } })
  if (error) throw new Error(`createUser failed for ${user.email}: ${error.message}`)
  return data.user.id
}

async function signIn(user: { email: string; password: string }): Promise<SupabaseClient<Database>> {
  const client = createClient<Database>(LOCAL_URL, LOCAL_ANON_KEY, { auth: { persistSession: false } })
  const { error } = await client.auth.signInWithPassword(user)
  if (error) throw new Error(`sign-in failed for ${user.email}: ${error.message}`)
  return client
}

function errorText(result: { body: unknown }): string {
  const err = (result.body as { error?: unknown }).error
  return typeof err === 'string' ? err : JSON.stringify(err)
}

beforeAll(async () => {
  await cleanup()
  await seedSyntheticSeason(service)

  const commishId = await createUser(COMMISH)
  const managerId = await createUser(MANAGER)
  await createUser(OUTSIDER)
  commishClient = await signIn(COMMISH)
  managerClient = await signIn(MANAGER)
  outsiderClient = await signIn(OUTSIDER)

  // The 8-team defaults: playoff_teams 6, one week per round, reseed on.
  const settings = defaultsForTeamCount(8)
  const { columns, blob } = splitSettings(settings)
  const columnArgs = Object.fromEntries(Object.entries(columns).map(([key, value]) => [`p_${key}`, value]))
  const { data: template } = await commishClient.from('scoring_systems').select('id, rules').eq('is_template', true).eq('name', 'ESPN Standard').single()
  const { data: created, error: createError } = await commishClient.rpc('create_league', {
    p_name: LEAGUE_NAME,
    p_season: SYNTHETIC_SEASON,
    p_scoring_system_id: template?.id,
    p_team_name: 'Commish Team',
    p_action_id: ACTION.league,
    p_settings: blob,
    ...columnArgs,
  } as unknown as Database['public']['Functions']['create_league']['Args'])
  if (createError) throw new Error(`create_league failed: ${createError.message}`)
  leagueId = (created as { league_id: string }).league_id

  // Eight seats (110 refuses a half-seated league): the manager's + six
  // unmanaged franchises owned by the commissioner.
  const { data: mt, error: mtError } = await service.from('teams').insert({ owner_id: managerId, name: 'Manager Team', league_id: leagueId }).select('id').single()
  if (mtError) throw new Error(`teams insert: ${mtError.message}`)
  const { error: seatsError } = await service
    .from('teams')
    .insert(Array.from({ length: 6 }, (_, i) => ({ owner_id: commishId, name: `Seat ${i + 3}`, league_id: leagueId })))
  if (seatsError) throw new Error(`teams insert (seats): ${seatsError.message}`)
  const { error: memberError } = await service.from('league_members').insert({ league_id: leagueId, user_id: managerId, team_id: mt.id, role: 'manager' })
  if (memberError) throw new Error(`league_members insert: ${memberError.message}`)
  const { error: seasonError } = await service.from('leagues').update({ status: 'in_season', scoring_rules_snapshot: template?.rules ?? null }).eq('id', leagueId)
  if (seasonError) throw new Error(`leagues → in_season: ${seasonError.message}`)

  // The REAL season (110): 14 regular + 3 playoff league_weeks, 56 matchups.
  const { error: genError } = await service.rpc('league_generate_schedule', { p_league_id: leagueId })
  if (genError) throw new Error(`league_generate_schedule: ${genError.message}`)
  const { data: teams } = await service.from('teams').select('id').eq('league_id', leagueId).order('id')
  teamIds = (teams ?? []).map((t) => t.id)
  expect(teamIds).toHaveLength(8)
}, 60_000)

afterAll(async () => {
  await cleanup()
})

describe('GET …/playoffs — the auth matrix (118 in-body; the family’s posture)', () => {
  it('a NON-MEMBER is refused by 118 in-body (42501) and the service answers the family’s no-leak 403', async () => {
    expect(await readPlayoffBracket(outsiderClient, leagueId)).toStrictEqual({ status: 403, body: { error: INSEASON_READ_FORBIDDEN_MESSAGE } })
  })

  it('a nonexistent league answers a member the same 403 — the membership check precedes the lookup', async () => {
    expect(await readPlayoffBracket(managerClient, NO_SUCH_LEAGUE)).toStrictEqual({ status: 403, body: { error: INSEASON_READ_FORBIDDEN_MESSAGE } })
  })
})

describe('GET …/playoffs — the PROJECTED document over 118’s real rows (Q39 (E): "if the playoffs started today")', () => {
  it('a member reads view: projected — round 1 seeded from the projected table (2 byes, 2 games), the basis named, the rollover NULL on the wire (F238), three unbuilt rounds', async () => {
    const result = await readPlayoffBracket(managerClient, leagueId)
    expect(result.status, errorText(result)).toBe(200)
    const doc = result.body as unknown as PlayoffBracketDoc
    expect(doc.kind).toBe('bracket')
    expect(doc.view).toBe('projected')
    expect(doc.status).toBe('in_season')
    expect(doc.playoff_teams).toBe(6)
    expect(doc.bracket_size).toBe(8)
    expect(doc.rounds).toBe(3)
    expect(doc.weeks_per_round).toBe(1)
    expect(doc.reseed).toBe(true)
    expect(doc.regular_season).toEqual({ first_week: 1, last_week: 14 })
    expect(doc.playoff_start_week).toBe(15)
    expect(doc.regular_season_rolled).toBe(false)
    expect(doc.regular_season_final).toBe(false)
    // The ONE instant: the synthetic calendar records no last game end —
    // the wire carries `null`, and the UI names the event (never a clock).
    expect(doc.rollover_week).toBe(14)
    expect(doc.rollover_at).toBeNull()
    expect(typeof doc.corrections_close_at).toBe('string')
    expect(doc.next_round).toBe(1)
    expect(doc.champion_team_id).toBeNull()
    expect(doc.bracket_champion_team_id).toBeNull()

    // Round 1 from the projected table: 8 seated teams → 6 seeds; byes to
    // seeds 1–2, then 3v6 and 4v5 (rider (i)) — the ENGINE's pairing.
    expect(doc.projection_basis).toEqual({ projected: true, weeks_final: 0, weeks_projected: 0, seeded: 6, reason: 'no_final_weeks' })
    expect(doc.projected_round_1).not.toBeNull()
    const pairs = doc.projected_round_1!
    expect(pairs).toHaveLength(4)
    expect(pairs.map((p) => [p.home.seed, p.away?.seed ?? null])).toEqual([
      [1, null],
      [2, null],
      [3, 6],
      [4, 5],
    ])
    for (const p of pairs) {
      expect(teamIds).toContain(p.home.team_id)
      if (p.away) expect(teamIds).toContain(p.away.team_id)
    }
    expect(new Set(pairs.flatMap((p) => [p.home.team_id, p.away?.team_id]).filter(Boolean)).size).toBe(6)

    expect(doc.round_list.map((r) => [r.round, r.built, r.expected_games, r.foreign_rows, r.weeks.map((w) => w.week)])).toEqual([
      [1, false, 4, 0, [15]],
      [2, false, 2, 0, [16]],
      [3, false, 1, 0, [17]],
    ])
  })

  it('the projected STANDINGS arm through the route’s query: projected: true; the final read projected: false; a view outside the enum is a 400', async () => {
    const projected = await readStandings(managerClient, leagueId, { view: 'projected' })
    expect(projected.status, errorText(projected)).toBe(200)
    const pdoc = projected.body as unknown as LeagueStandings
    expect(pdoc.projected).toBe(true)
    expect(pdoc.weeks_projected).toBe(0) // no OPEN week: every league_week is `upcoming`
    expect(pdoc.standings).toHaveLength(8)
    expect(pdoc.reason).toBe('no_final_weeks')

    const final = await readStandings(managerClient, leagueId)
    expect(final.status).toBe(200)
    const fdoc = final.body as unknown as LeagueStandings
    expect(fdoc.projected).toBe(false)
    expect(fdoc.weeks_projected).toBe(0)
    // The two tables agree with no open week — the projection adds nothing.
    expect(pdoc.standings.map((r) => r.team_id)).toEqual(fdoc.standings.map((r) => r.team_id))

    const bogus = await readStandings(managerClient, leagueId, { view: 'live' })
    expect(bogus.status).toBe(400)
    // The outsider is refused on the projected arm too (118's wrapper carries 117's member check).
    expect(await readStandings(outsiderClient, leagueId, { view: 'projected' })).toStrictEqual({ status: 403, body: { error: INSEASON_READ_FORBIDDEN_MESSAGE } })
  })
})

describe('GET …/playoffs — a BUILT round over planted engine rows (F247(b) on the bracket; E61; D318(5))', () => {
  const planted: string[] = []

  afterAll(async () => {
    if (planted.length > 0) await service.from('matchups').delete().in('id', planted)
  })

  it('rows WITH seeds are the engine’s: the totals arrive as ONE kind of number, a NULL score stays NULL, decided_by is 118’s; a row WITHOUT seeds is a foreign row, counted and never read', async () => {
    const [a, b, c, d, e, f, g, h] = teamIds
    // Round 1 in week 15 (the plan's first playoff week): A bye (seed 1), B
    // bye (seed 2), C(3) v F(6) 101.25–98.10, D(4) v E(5) 90.00–NULL (E's
    // score pending). Plus a FOREIGN row (no seeds) in the same week.
    const { data: rows, error } = await service
      .from('matchups')
      .insert([
        { league_id: leagueId, season: SYNTHETIC_SEASON, week: 15, round_type: 'playoff', home_team_id: a, away_team_id: null, home_seed: 1, away_seed: null, status: 'scheduled' },
        { league_id: leagueId, season: SYNTHETIC_SEASON, week: 15, round_type: 'playoff', home_team_id: b, away_team_id: null, home_seed: 2, away_seed: null, status: 'scheduled' },
        { league_id: leagueId, season: SYNTHETIC_SEASON, week: 15, round_type: 'playoff', home_team_id: c, away_team_id: f, home_seed: 3, away_seed: 6, home_score: 101.25, away_score: 98.1, status: 'scheduled' },
        { league_id: leagueId, season: SYNTHETIC_SEASON, week: 15, round_type: 'playoff', home_team_id: d, away_team_id: e, home_seed: 4, away_seed: 5, home_score: 90, away_score: null, status: 'scheduled' },
        { league_id: leagueId, season: SYNTHETIC_SEASON, week: 15, round_type: 'playoff', home_team_id: g, away_team_id: h, status: 'scheduled' },
      ])
      .select('id')
    expect(error?.message ?? null).toBeNull()
    planted.push(...(rows ?? []).map((r) => r.id))
    expect(planted).toHaveLength(5)

    const result = await readPlayoffBracket(managerClient, leagueId)
    expect(result.status, errorText(result)).toBe(200)
    const doc = result.body as unknown as PlayoffBracketDoc
    expect(doc.view).toBe('bracket') // round 1 exists ⇒ no projection (118 §9)
    expect(doc.projected_round_1).toBeNull()
    expect(doc.next_round).toBe(2)
    const r1 = doc.round_list[0]
    expect(r1.built).toBe(true)
    expect(r1.foreign_rows).toBe(1)
    expect(r1.games).toHaveLength(4)
    expect(r1.games.map((x) => [x.home_seed, x.away_seed, x.decided_by, x.final])).toEqual([
      [1, null, 'bye', false],
      [2, null, 'bye', false],
      [3, 6, 'points', false],
      [4, 5, 'points', false],
    ])
    // F247(b): the numeric scale collapses to ONE JS kind through the service.
    const game = r1.games[2]
    expect(game.home_total).toBe(101.25)
    expect(game.away_total).toBe(98.1)
    expect(typeof game.home_total).toBe('number')
    expect(r1.games[0].home_total).toBe(0)
    expect(typeof r1.games[0].home_total).toBe('number')
    expect(game.weeks).toHaveLength(1)
    expect(game.weeks[0].home_score).toBe(101.25)
    // E61: E's pending score is NULL on the wire and NULL after the service — never 0.00.
    const pending = r1.games[3]
    expect(pending.weeks[0].away_score).toBeNull()
    expect(pending.away_total).toBe(0) // 118's sum COALESCEs a NULL to 0 for the verdict; the CELL stays null
    expect(pending.winner_team_id).toBe(d)
    // The foreign pair never appears as a game.
    for (const x of r1.games) {
      expect([g, h]).not.toContain(x.home_team_id)
      expect([g, h]).not.toContain(x.away_team_id)
    }
    expect(r1.survivors.map((s) => s.seed)).toEqual([1, 2, 3, 4])
    expect(doc.entrants_next?.map((s) => s.seed)).toEqual([1, 2, 3, 4])
  })

  it('the raw RPC really does render the two scales differently on the WIRE (R601: raw bytes) — which is why the service normalises', async () => {
    const { data: session } = await managerClient.auth.getSession()
    const response = await fetch(`${LOCAL_URL}/rest/v1/rpc/league_playoff_bracket`, {
      method: 'POST',
      headers: { apikey: LOCAL_ANON_KEY, Authorization: `Bearer ${session.session?.access_token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ p_league_id: leagueId }),
    })
    expect(response.status).toBe(200)
    const raw = await response.text()
    // The SUMMED figure carries the `round(…, 2)` scale (`90.00`, `0.00`)
    // while the raw column renders as stored (`90`, `101.25`, `98.1`) — two
    // renderings of one score, which is why the service normalises rather
    // than trusts; and a NULL cell is `null`, never `0`.
    expect(raw).toMatch(/"home_total":\s*90\.00\b/)
    expect(raw).toMatch(/"home_total":\s*0\.00\b/)
    expect(raw).toMatch(/"home_score":\s*90[,}]/)
    expect(raw).toMatch(/"away_score":\s*98\.1[,}]/)
    expect(raw).toMatch(/"away_score":\s*null/)
  })
})

describe('a SOFT-DELETED league answers a MEMBER the ONE 404 copy after the membership check, and a NON-MEMBER the same 403 (R812)', () => {
  it('playoffs + the projected standings arm', async () => {
    const { error: deleteError } = await service.from('leagues').update({ deleted_at: '2099-01-01T00:00:00+00:00' }).eq('id', leagueId)
    expect(deleteError).toBeNull()
    try {
      const gone = { status: 404, body: { error: INSEASON_LEAGUE_GONE_MESSAGE } }
      const playoffs = await readPlayoffBracket(managerClient, leagueId)
      expect(playoffs).toStrictEqual(gone)
      expect(errorText(playoffs)).not.toContain('not found')
      expect(await readStandings(managerClient, leagueId, { view: 'projected' })).toStrictEqual(gone)
      const forbidden = { status: 403, body: { error: INSEASON_READ_FORBIDDEN_MESSAGE } }
      expect(await readPlayoffBracket(outsiderClient, leagueId)).toStrictEqual(forbidden)
    } finally {
      const { error: restoreError } = await service.from('leagues').update({ deleted_at: null }).eq('id', leagueId)
      expect(restoreError).toBeNull()
    }
    expect((await readPlayoffBracket(managerClient, leagueId)).status).toBe(200)
  })
})
