import Link from 'next/link'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'

import { CommentsThread } from '@/components/lists/comments-thread'
import { GuestShell } from '@/components/layout/guest-shell'
import { PersonaBadge } from '@/components/personas/persona-badge'
import { PublicListView } from '@/components/lists/public-list-view'
import { featureFlags } from '@/lib/feature-flags'
import { createServerClient } from '@/lib/supabase/server'


interface PageProps {
  params: Promise<{ username: string; listSlug: string }>
}

async function loadList(username: string, slug: string) {
  const supabase = await createServerClient()

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, username, avatar_url, cred_score, is_pro')
    .eq('username', username)
    .maybeSingle()

  if (!profile) return null

  const { data: list } = await supabase
    .from('lists')
    .select(
      'id, owner_id, title, description, slug, position_filter, hide_order, tiers_enabled, is_big_board, is_private, comments_enabled, like_count, view_count, player_count, updated_at, deleted_at, ai_persona_id',
    )
    .eq('owner_id', profile.id)
    .eq('slug', slug)
    .is('deleted_at', null)
    .maybeSingle()

  if (!list || list.is_private) return null

  interface PlayerJoin {
    player_id: string
    position: number
    // Whatever the column holds. `list_players_tier_check` accepts round and
    // cost keys as well as S–F since migration 081 (LV.1.5), so narrowing this
    // to `ListTier` here would be a type that lies to a server component.
    tier: string | null
    player: {
      id: string
      full_name: string
      position: string
      team: string | null
      headshot_url: string | null
      status: string | null
    }
  }
  interface TagJoin {
    tag: { id: string; name: string; slug: string } | null
  }

  const [{ data: players }, { data: tagRows }] = await Promise.all([
    supabase
      .from('list_players')
      .select(
        'player_id, position, tier, player:players(id, full_name, position, team, headshot_url, status)',
      )
      .eq('list_id', list.id)
      .order('position', { ascending: true }),
    supabase
      .from('list_tags')
      .select('tag:tags(id, name, slug)')
      .eq('list_id', list.id),
  ])

  const flatTags = ((tagRows ?? []) as unknown as TagJoin[])
    .map((r) => r.tag)
    .filter((t): t is NonNullable<typeof t> => Boolean(t))

  // Persona attribution: persona-owned lists carry the "Generated by
  // FieldScout AI" footer + disclaimer (spec-ai-expert-personas.md).
  let persona: { username: string; display_name: string } | null = null
  if (list.ai_persona_id) {
    const { data: personaRow } = await supabase
      .from('ai_personas')
      .select('username, display_name')
      .eq('id', list.ai_persona_id)
      .eq('is_active', true)
      .is('deleted_at', null)
      .maybeSingle()
    persona = personaRow ?? null
  }

  return {
    list,
    persona,
    owner: profile,
    players: ((players ?? []) as unknown as PlayerJoin[]).map((p) => ({
      player_id: p.player_id,
      position: p.position,
      tier: p.tier,
      player: p.player,
    })),
    tags: flatTags,
  }
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { username, listSlug } = await params
  const data = await loadList(username, listSlug)
  if (!data) return { title: 'List not found' }
  const { list, owner } = data
  const handle = `@${owner.username}`
  return {
    title: `${list.title} by ${handle} · FieldScout`,
    description:
      list.description ??
      `${handle}'s ${list.title} — ${list.player_count} player${list.player_count === 1 ? '' : 's'}`,
    openGraph: {
      title: `${list.title} by ${handle}`,
      description: list.description ?? undefined,
    },
  }
}

export default async function PublicListPage({ params }: PageProps) {
  const { username, listSlug } = await params
  const data = await loadList(username, listSlug)
  if (!data) notFound()

  const { list, owner, players, tags, persona } = data

  // Viewer context for the Pin button: anyone who isn't the owner can pin;
  // signed-out viewers get a sign-in CTA.
  const supabase = await createServerClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  const signedIn = Boolean(user)
  const isOwner = Boolean(user && user.id === list.owner_id)
  let initialPinned = false
  if (user && !isOwner) {
    const { data: fav } = await supabase
      .from('list_favorites')
      .select('list_id')
      .eq('user_id', user.id)
      .eq('list_id', list.id)
      .maybeSingle()
    initialPinned = Boolean(fav)
  }

  return (
    <GuestShell>
      <div className="mx-auto max-w-3xl space-y-10">
        <PublicListView
          list={list}
          owner={owner}
          players={players}
          tags={tags}
          canPin={!isOwner}
          signedIn={signedIn}
          initialPinned={initialPinned}
        />
        {persona && (
          <div className="flex flex-wrap items-center justify-center gap-2 text-[11px] font-medium text-n-3">
            <PersonaBadge />
            <span>
              Generated by FieldScout AI as{' '}
              {/* The persona profile is release-gated out of the 2026 go-live
                  scope; the AI disclosure itself always stays — only the link
                  to the (hidden) profile drops. */}
              {featureFlags.personas ? (
                <Link
                  href={`/personas/${persona.username}`}
                  className="font-bold text-ink hover:underline"
                >
                  {persona.display_name}
                </Link>
              ) : (
                <span className="font-bold text-ink">{persona.display_name}</span>
              )}{' '}
              — a fictional, parody analyst persona not affiliated with any real person.
            </span>
          </div>
        )}
        <CommentsThread
          listId={list.id}
          ownerId={owner.id}
          commentsEnabled={list.comments_enabled}
        />
      </div>
    </GuestShell>
  )
}
