-- ============================================================================
-- AI WRITE GUARDS (review follow-up to 020/024)
-- ============================================================================
-- Two column-level protections that RLS alone cannot express:
--
-- 1. profiles billing fields: "Users can manage own profiles" (001) allows a
--    signed-in user to UPDATE their own row — including is_pro — which would
--    let anyone self-grant Pro and defeat requireProUser(). Guard the billing
--    columns so only the service role (Stripe webhooks, scripts) can change
--    them.
--
-- 2. lists.ai_persona_id: "Users can manage own lists" allows any owner to
--    set ai_persona_id on their own list (ai_personas ids are publicly
--    readable), spoofing "Generated by FieldScout AI" attribution. Only the
--    service role may set or change it.
--
-- auth.role() is 'authenticated'/'anon' for client requests and
-- 'service_role' for service-key requests; direct connections (migrations,
-- superuser) return NULL and are allowed.

CREATE OR REPLACE FUNCTION guard_profile_billing_columns()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.role() IN ('authenticated', 'anon') THEN
    IF NEW.is_pro IS DISTINCT FROM OLD.is_pro
       OR NEW.subscription_status IS DISTINCT FROM OLD.subscription_status
       OR NEW.stripe_customer_id IS DISTINCT FROM OLD.stripe_customer_id THEN
      RAISE EXCEPTION 'Subscription fields are managed by the system.'
        USING errcode = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_profile_billing
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION guard_profile_billing_columns();

CREATE OR REPLACE FUNCTION guard_lists_ai_persona()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.role() IN ('authenticated', 'anon') THEN
    IF (TG_OP = 'INSERT' AND NEW.ai_persona_id IS NOT NULL)
       OR (TG_OP = 'UPDATE' AND NEW.ai_persona_id IS DISTINCT FROM OLD.ai_persona_id) THEN
      RAISE EXCEPTION 'ai_persona_id is managed by the system.'
        USING errcode = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_lists_ai_persona
  BEFORE INSERT OR UPDATE ON lists
  FOR EACH ROW
  EXECUTE FUNCTION guard_lists_ai_persona();
