/**
 * The FORMAT-2 rules envelope, its pure resolver, its normal form, and the
 * fork (SE.2; spec §7.3.3.1's rules-document / All-Positions / D/ST(b)
 * bullets; D167's engine-home rule; D59(4) explicit-0 score-inert).
 *
 * ## What this module is
 *
 * `scoring_systems.rules` — and therefore `leagues.scoring_rules_snapshot`,
 * which freezes it VERBATIM at draft start — may now be one of two things:
 *
 *  - **format 1**: a flat `{ stat_key: coefficient }` map. Every one of the
 *    six shipped templates is one, and stays one, byte-identical. A format-1
 *    doc carries **no `format` member**, and `format` is not a registry key
 *    (`STAT_KEYS`), so the discriminator is unambiguous — pinned by test.
 *  - **format 2**: the base + per-position-override envelope §7.3.3.1 prints:
 *    `{ format: 2, base, positions: { QB … DST }, tier_cuts: { def_pa, def_ya } }`.
 *
 * `resolveRules(doc, position)` turns either one into the flat map the D33/D57
 * calculator already eats, so `scorePlayerWeek` never learns that format 2
 * exists. The production composition is
 * `scorePlayerWeek(resolveRules(doc, player.position), deriveTierIndicators(line))`.
 *
 * ## THE IDENTITY PROPERTY — this module's centre of gravity
 *
 * For a format-1 document the resolver is the **identity for every position**,
 * and that is not a convenience: it is the entire backward-compatibility
 * guarantee of the SE track. §7.3.3.1's own words — *"no existing template
 * league's scored outcome changes by even a cent."* The pin in
 * `rules-doc.test.ts` is therefore a PROPERTY (all six positions, positions
 * outside the six, `__proto__`/`constructor`, all six templates, every parity
 * fixture line — totals AND perKey AND pending), not an example, and it is
 * reference-exact: a format-1 doc resolves to THE SAME OBJECT, so there is no
 * copy in which a value could drift.
 *
 * The same property is what makes the F133 fix at
 * `auction-player-table-ops.ts` → `scoringFamilyFromRules` a strict no-op for
 * every league that exists today (tasks-SE §0(A)): resolving first cannot
 * change what a template league classifies as, because for a template league
 * resolving changes nothing at all.
 *
 * ## What this module deliberately does NOT check (one owner per check)
 *
 * `resolveRules` validates exactly what it READS — the `format` version, and
 * that `base` / `positions` / `positions[P]` are objects — and it fails LOUDLY
 * when they are not (CLAUDE.md: never let a bad input produce a plausible
 * empty result; an unknown future `format: 3` silently read as flat would
 * score a whole league wrong). It does **not** validate coefficients and it
 * does **not** validate `tier_cuts`:
 *
 *  - **coefficients** are `scorePlayerWeek`'s trust boundary (R59/D58 — a
 *    non-finite coefficient is a corrupt snapshot and throws there);
 *  - the **document guardrails** (scorable allowlist, tier exclusivity,
 *    position scope, normal form, bounds, `tier_cuts` residuals) are
 *    §7.3.3.1(5)'s validator — SE.3 in TS, SE.4/SE.4b in SQL. Re-implementing
 *    any of them here would be the second mirror D168 exists to prevent.
 */

import {
  DEF_PA_PREFIX,
  DEF_YA_PREFIX,
  ESPN_PA_CUTS,
  SHARED_PA_CUTS,
  YA_CUTS,
  type EnvelopeTierCuts,
  tierKeysFromCuts,
} from './tier-cuts'

// ---------------------------------------------------------------------------
// 1. The document types
// ---------------------------------------------------------------------------

/**
 * The six positions §7.3.3.1 scopes overrides to (guardrail 3), in the
 * editor's own stepper order: QB → RB → WR → TE → K → D/ST.
 *
 * Spelled `DST` to match `ROSTER_POSITIONS` in
 * `src/lib/leagues/settings/league-settings.ts` — one spelling of a position
 * across the league engine, the D33 one-namespace argument applied to
 * position codes.
 */
export const SCORING_POSITIONS = ['QB', 'RB', 'WR', 'TE', 'K', 'DST'] as const

/** A position an override may be scoped to. */
export type ScoringPosition = (typeof SCORING_POSITIONS)[number]

/** A flat coefficient map over canonical registry keys — a format-1
 *  document, and also what `resolveRules` hands the calculator. */
export type FlatScoringRules = Record<string, number>

/**
 * The format-2 envelope, exactly the shape §7.3.3.1 prints.
 *
 * `tier_cuts` is `EnvelopeTierCuts` — **both tables required** (SE.1/R577).
 * A document may not omit one: "this league pays no yards-allowed table" is
 * expressed by paying no `def_ya_*` keys, never by dropping its cut list,
 * because guardrail 2 ("`def_ya_*` keys ⊆ the set generated by
 * `tier_cuts.def_ya`") would otherwise be unevaluable.
 */
export interface ScoringRulesDocV2 {
  format: 2
  base: FlatScoringRules
  /** Per-position overrides; a position absent here resolves to `base`
   *  alone. Normal form (below) keeps this free of no-op and empty entries. */
  positions: Partial<Record<ScoringPosition, FlatScoringRules>>
  tier_cuts: EnvelopeTierCuts
}

/** Either version of the document. Format 1 has no `format` member; that
 *  absence IS the discriminator (§7.3.3.1). */
export type ScoringRulesDoc = FlatScoringRules | ScoringRulesDocV2

/** The envelope's version number, as a value — so the discriminator is
 *  written once and every comparison points at it. */
export const SCORING_DOC_FORMAT_2 = 2

/** The discriminator key. Named here because the argument for it is a
 *  registry fact (`format` is not a `STAT_KEYS` key), pinned in the test. */
export const SCORING_DOC_FORMAT_KEY = 'format'

const hasOwn = (object: object, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(object, key)

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

/**
 * A format-1 document: an object carrying no OWN `format` member.
 *
 * `hasOwn` rather than `in` on purpose — a JSON document parsed from the
 * database has no interesting prototype, but `'format' in doc` would also
 * answer true for an inherited member, and "is this a versioned envelope"
 * must be a fact about the document itself.
 */
export function isFormat1Doc(doc: unknown): doc is FlatScoringRules {
  return isPlainObject(doc) && !hasOwn(doc, SCORING_DOC_FORMAT_KEY)
}

/**
 * Refuse to resolve anything that is not a resolvable format-2 envelope,
 * loudly. The version check is the load-bearing one: a `format: 3` document
 * this code has never heard of must NOT fall through to any reading — the
 * one silently-plausible outcome (treat it as flat, or as base-only) scores
 * an entire league wrong with no error anywhere.
 */
function assertResolvableV2(doc: unknown): asserts doc is ScoringRulesDocV2 {
  if (!isPlainObject(doc)) {
    throw new TypeError(
      `scoring rules document is not an object (§7.3.3.1 — refusing to resolve)`,
    )
  }
  const format = doc[SCORING_DOC_FORMAT_KEY]
  if (format !== SCORING_DOC_FORMAT_2) {
    throw new TypeError(
      `scoring rules document declares format ${JSON.stringify(format)}, which this build cannot resolve (§7.3.3.1 knows format 1 — no "format" member — and format 2)`,
    )
  }
  if (!isPlainObject(doc.base)) {
    throw new TypeError(
      `format-2 scoring document has no "base" object (§7.3.3.1's printed shape — refusing to resolve)`,
    )
  }
  if (!isPlainObject(doc.positions)) {
    throw new TypeError(
      `format-2 scoring document has no "positions" object (§7.3.3.1's printed shape — refusing to resolve)`,
    )
  }
}

// ---------------------------------------------------------------------------
// 2. resolveRules — the pure resolver in front of the untouched calculator
// ---------------------------------------------------------------------------

/**
 * Effective rules for a player of `position` (§7.3.3.1):
 *
 *  - **format 1 → THE DOCUMENT ITSELF, for every position.** The identity
 *    property; reference-exact by design.
 *  - **format 2 → `{ ...base, ...positions[P] }`** — the override wins, and an
 *    explicit `0` override switches that category off for that position
 *    (D59(4): a delivered stat against a 0 coefficient is a real `perKey: 0`,
 *    which is NOT the same as dropping the key, whose stat would then be
 *    ignored entirely).
 *  - **a position absent from `positions` — including any position outside
 *    the six, and any string at all → `base` alone.**
 *
 * `position` is typed `string`, not `ScoringPosition`, because the caller is
 * `players.position` from the database and the spec rules on exactly that
 * case ("*a position absent from `positions`, including any position outside
 * the six, resolves to `base` alone*"). Own-property lookup keeps `'__proto__'`
 * and `'constructor'` on that same path instead of reaching the prototype.
 *
 * Pure: never mutates `doc`. The returned map is READ-ONLY by contract —
 * format 1 hands back the document itself so the identity is exact, and every
 * consumer today (the calculator, `scoringFamilyFromRules`) only reads.
 */
export function resolveRules(
  doc: ScoringRulesDoc,
  position: string,
): FlatScoringRules {
  if (isFormat1Doc(doc)) return doc

  assertResolvableV2(doc)

  if (!hasOwn(doc.positions, position)) return { ...doc.base }

  const override = (doc.positions as Record<string, unknown>)[position]
  if (!isPlainObject(override)) {
    throw new TypeError(
      `format-2 scoring document has a non-object override at positions.${position} (§7.3.3.1's printed shape — refusing to resolve)`,
    )
  }

  return { ...doc.base, ...(override as FlatScoringRules) }
}

// ---------------------------------------------------------------------------
// 3. normalizeScoringDoc — the normal form the All-Positions switch rides on
// ---------------------------------------------------------------------------

/**
 * §7.3.3.1's normal form: **overrides equal to the base value and empty
 * override objects are stripped.**
 *
 * Why it exists at all: the "All Positions" switch is DERIVED state, never
 * stored — a section shows All-Positions ON iff none of its keys carry a
 * position override. Without the strip, editing a value to X for one position
 * and then back to the base value would leave a no-op override behind, and the
 * switch would read OFF for a section whose values are in fact uniform. The
 * switch state has to round-trip from the document alone, so the document has
 * to be free of overrides that change nothing.
 *
 * Two boundaries this gets right on purpose, both pinned:
 *
 *  - **An override of a key the base does not carry is NEVER a no-op**, not
 *    even at `0`. Absent means "this league does not score this category at
 *    all"; `0` means "scored, worth nothing" — a delivered stat then produces
 *    a real `perKey: 0`, and an undelivered one lands in `pending` (§23.5/E61).
 *    So the strip requires the key to EXIST in `base` and match it.
 *  - **A position key outside the six is preserved, not dropped.** Normal form
 *    is a strip, not a validator: silently deleting an illegal `positions.FB`
 *    would let an invalid document launder itself into validity by being
 *    normalized first. Guardrail 3 (SE.3/SE.4) is what rejects it.
 *
 * Format 1 has no overrides, so it is already in normal form and comes back
 * unchanged — the same object, the identity again.
 *
 * `===` rather than `Object.is` for the equality: `-0` and `0` score
 * identically and `JSON.stringify(-0)` is `"0"`, so a `-0` override over a `0`
 * base is exactly the no-op the normal form exists to remove.
 */
export function normalizeScoringDoc(doc: ScoringRulesDoc): ScoringRulesDoc {
  if (isFormat1Doc(doc)) return doc

  assertResolvableV2(doc)

  const source = doc.positions as Record<string, FlatScoringRules>
  const positions: Record<string, FlatScoringRules> = {}

  for (const position of Object.keys(source)) {
    const override = source[position]
    if (!isPlainObject(override)) {
      throw new TypeError(
        `format-2 scoring document has a non-object override at positions.${position} (§7.3.3.1's printed shape — refusing to normalize)`,
      )
    }

    const kept: FlatScoringRules = {}
    for (const key of Object.keys(override)) {
      if (hasOwn(doc.base, key) && doc.base[key] === override[key]) continue
      kept[key] = override[key]
    }

    if (Object.keys(kept).length > 0) positions[position] = kept
  }

  return {
    format: SCORING_DOC_FORMAT_2,
    base: { ...doc.base },
    // The accumulator is keyed by `string` because an illegal position key is
    // preserved rather than dropped (above); the declared type stays the
    // spec's six so every WRITER of a document is held to guardrail 3.
    positions: positions as ScoringRulesDocV2['positions'],
    tier_cuts: doc.tier_cuts,
  }
}

// ---------------------------------------------------------------------------
// 4. forkTemplateDoc — a template becomes the league's own custom document
// ---------------------------------------------------------------------------

/** The two published points-allowed families, as their GENERATED key sets —
 *  never as name lists, so the fork and the tier-key generator can never
 *  disagree about what a family contains. */
const PA_FAMILIES: ReadonlyArray<{
  cuts: readonly number[]
  keys: ReadonlySet<string>
}> = [
  { cuts: SHARED_PA_CUTS, keys: new Set(tierKeysFromCuts(DEF_PA_PREFIX, SHARED_PA_CUTS)) },
  { cuts: ESPN_PA_CUTS, keys: new Set(tierKeysFromCuts(DEF_PA_PREFIX, ESPN_PA_CUTS)) },
]

const YA_FAMILY_KEYS: ReadonlySet<string> = new Set(
  tierKeysFromCuts(DEF_YA_PREFIX, YA_CUTS),
)

const keysWithPrefix = (rules: FlatScoringRules, prefix: string): string[] =>
  Object.keys(rules).filter((key) => key.startsWith(`${prefix}_`))

/**
 * Which cut lists a flat document's own tier keys were cut on — **detected
 * from the key set, never from a template's name.**
 *
 * §7.3.3.1(b): the fork writes the STARTING TEMPLATE's cut lists, so that the
 * generated key set is identical to the template's literal keys and the
 * document scores the same whether the engine derives from cuts or from
 * `derive-stats.ts`'s literals. Matching on the string "ESPN" would make that
 * guarantee depend on a display name a commissioner can rename; matching on
 * the keys makes it depend on the only thing that actually scores.
 *
 * The two PA families share four key names (`def_pa_0`, `def_pa_1_6`,
 * `def_pa_7_13`, `def_pa_28_34`), so a subset match can be AMBIGUOUS — a
 * document naming only those four is a member of both. That case throws
 * rather than picking one: guessing would silently re-cut a defense's tiers.
 * All six shipped templates carry at least one divergent key and match
 * exactly one family (pinned).
 *
 * The YA slot is ALWAYS written (SE.2(4)) — a single-model document simply
 * pays no `def_ya_*` keys. A document whose `def_ya_*` keys are NOT generated
 * by `YA_CUTS` would be re-cut by writing them, so that throws too; adding a
 * YA table to a single-model document is F59's follow-up, not this fork.
 */
export function detectTierCuts(rules: FlatScoringRules): EnvelopeTierCuts {
  const paKeys = keysWithPrefix(rules, DEF_PA_PREFIX)
  if (paKeys.length === 0) {
    throw new TypeError(
      `cannot fork a scoring document with no ${DEF_PA_PREFIX}_* keys: its points-allowed cut list is undetectable, and guessing one would re-cut the defense's tiers (§7.3.3.1(b))`,
    )
  }

  const matches = PA_FAMILIES.filter(({ keys }) =>
    paKeys.every((key) => keys.has(key)),
  )
  if (matches.length !== 1) {
    throw new TypeError(
      `${DEF_PA_PREFIX}_* keys [${paKeys.join(', ')}] match ${matches.length} published families — a fork must inherit exactly one cut list (§7.3.3.1(b); F21 guardrail 2)`,
    )
  }

  const yaKeys = keysWithPrefix(rules, DEF_YA_PREFIX)
  const strayYa = yaKeys.filter((key) => !YA_FAMILY_KEYS.has(key))
  if (strayYa.length > 0) {
    throw new TypeError(
      `${DEF_YA_PREFIX}_* keys [${strayYa.join(', ')}] are not generated by the published yards-allowed cut list — forking would re-cut them (§7.3.3.1(b))`,
    )
  }

  return { def_pa: matches[0].cuts, def_ya: YA_CUTS }
}

/**
 * Fork a template into the league's own format-2 document (§7.3.3.1's entry
 * point; the row SE.5's RPC inserts and `leagues.scoring_system_id` repoints
 * to in the same transaction).
 *
 * `base` is the template's flat map verbatim — a COPY, so that editing a fork
 * can never reach back into `SCORING_TEMPLATES` or into the row it was read
 * from. `positions` starts empty: a fresh fork overrides nothing, which is why
 * it scores identically to its template for every position (the
 * fork-equivalence property). `tier_cuts` is the inherited family per
 * `detectTierCuts`.
 *
 * Refuses a format-2 input: re-picking a template is a fresh fork FROM a
 * template, and folding a fork into a fork would quietly discard its
 * overrides.
 */
export function forkTemplateDoc(templateRules: FlatScoringRules): ScoringRulesDocV2 {
  if (!isFormat1Doc(templateRules)) {
    throw new TypeError(
      `forkTemplateDoc takes a format-1 template document; got one carrying a "${SCORING_DOC_FORMAT_KEY}" member (§7.3.3.1 — a fork always starts from a template)`,
    )
  }

  return {
    format: SCORING_DOC_FORMAT_2,
    base: { ...templateRules },
    positions: {},
    tier_cuts: detectTierCuts(templateRules),
  }
}
