/**
 * The §7.3.3.1 guardrail validator, TS side (SE.3 — F21's validator half;
 * spec §7.3.3.1's "F21 guardrails (validation LAW, not UI hope)" bullet;
 * D168's one-validator-per-language rule; D167's engine-home rule).
 *
 * ## What this module is
 *
 * §7.3.3.1 states the guardrails as a list of things a scoring document
 * **structurally cannot express** — not a list of things the editor tries not
 * to offer. This is the TS half of that law: the client's UX pre-check and the
 * service-layer pre-check, mirrored family-for-family in SQL by
 * `scoring_rules_validate(jsonb)` (SE.4), which is the wall every server write
 * path actually stands behind (SE.4b's two triggers — D175/D168). **Client Zod
 * is UX only** (§7.3.3.1(5)); nothing here is a substitute for the SQL mirror,
 * and the TS≡SQL parity fixture (D168(1)) is what stops the two drifting.
 *
 * ## The five families, in the spec's own numbering
 *
 *  1. **Scorable allowlist** — every coefficient key ∈ the registry's
 *     `scoring_surface: 'scorable'` set (§23.5 v2.11 / SE.1). Raw sources and
 *     aggregates are `context`: a document paying `def_points_allowed` *and*
 *     its derived tier buckets is the original F21 double-pay, one layer up.
 *  2. **Tier exclusivity — the F21 double-pay itself.** Format 2: the doc's
 *     `def_pa_*` keys ⊆ the set generated by its OWN `tier_cuts.def_pa`, and
 *     `def_ya_*` ⊆ the set generated by its own `tier_cuts.def_ya`. Format 1
 *     (the templates and any flat league doc): `def_pa_*` ⊆ a single published
 *     family (shared 7-key / ESPN 8-key), `def_ya_*` ⊆ the 9-key YA set.
 *     `def_pa_14_20` + `def_pa_18_27` in one document one-hot together at
 *     PA 18–20 and double-pay it — that pair is the row F21 was filed for.
 *  3. **Position scope** — `positions` keys ⊆ {QB, RB, WR, TE, K, DST}, and an
 *     override under P may name only P's own section keys (K keys only under
 *     K, D/ST keys only under DST, offense keys never under K/DST).
 *  4. **Normal form** — no no-op overrides, no empty override objects.
 *  5. **Bounds** — finite, |coef| ≤ 100, multiples of 0.01.
 *
 * Plus §7.3.3.1(c)'s **`tier_cuts` residuals** (ascending, integers, ≥ 2 cuts,
 * per table, the two tables independent) — the spec's (c) bullet, not one of
 * the five, so it is reported last.
 *
 * ## Three things this module owns on purpose, stated so they don't read as
 * accidents
 *
 * **(a) It never throws.** Its input is a JSONB blob from a route body or a
 * database column, so "this document is nonsense" is an ordinary answer, not
 * an exception. `resolveRules` and `tierKeysFromCuts` DO throw (a corrupt doc
 * reaching the engine is a programming error there), so this module checks the
 * preconditions before it composes them — which is why `tier_cuts` residuals
 * are evaluated before guardrail 2 uses them to generate a key set.
 *
 * **(b) Guardrail 4 composes `normalizeScoringDoc` — it does not re-implement
 * the strip.** The question "is this document in normal form?" is exactly "does
 * normalizing change it?", so the normal form has ONE definition
 * (`rules-doc.ts`) and this module only reports WHERE the two differ. A second
 * strip here would be the mirror D168 exists to prevent, one module over.
 *
 * **(c) Violations are ordered by the spec's own family numbering** (shape
 * first, `tier_cuts` residuals last), so `violations[0].code` is stable and
 * SE.4's SQL — which RAISEs on the FIRST violation — names the same family for
 * any document that breaks exactly one. The TS≡SQL parity fixture (SE.4(4)) is
 * built from documents that each break exactly one family for that reason.
 */

import { z } from 'zod'

import { STAT_KEYS } from '../stats/stat-keys'
import {
  DEF_PA_PREFIX,
  DEF_YA_PREFIX,
  ESPN_PA_CUTS,
  SHARED_PA_CUTS,
  YA_CUTS,
  tierKeysFromCuts,
} from './tier-cuts'
import {
  SCORING_DOC_FORMAT_2,
  SCORING_DOC_FORMAT_KEY,
  SCORING_POSITIONS,
  normalizeScoringDoc,
  type FlatScoringRules,
  type ScoringPosition,
  type ScoringRulesDoc,
  type ScoringRulesDocV2,
} from './rules-doc'

// ---------------------------------------------------------------------------
// 1. The result shape (the settings-contract error shape, plus a family code)
// ---------------------------------------------------------------------------

/**
 * The guardrail family a violation belongs to — §7.3.3.1's own numbering.
 *
 * `document_shape` and `tier_cuts` are not among the five: the first is the
 * front door (an input that is not a resolvable document at all), the second is
 * §7.3.3.1(c)'s residual validation, which exists because cut points make
 * overlaps and gaps unconstructible rather than validation-caught.
 */
export const SCORING_GUARDRAILS = [
  'document_shape',
  'scorable_allowlist',
  'tier_exclusivity',
  'position_scope',
  'normal_form',
  'bounds',
  'tier_cuts',
] as const

/**
 * SE.6 needed these seven **at runtime**, not only in the type system: 103
 * puts the family code in the refusal's `HINT` (its own banner: *"HINT the
 * guardrail family code, the same seven strings the TS…"*), and the route
 * layer decides "is this a document rejection I can key to a field, or a state
 * refusal?" by reading that hint. A second hand-written list in the service
 * could drift from this one silently, so the union is DERIVED from the array
 * rather than written twice — the seven strings exist once in TypeScript.
 * (Byte-identical union to the hand-written one it replaces; the TS≡SQL side
 * of the same seven is measured by `scoring-parity-db.test.ts`, unchanged.)
 */
export type ScoringGuardrail = (typeof SCORING_GUARDRAILS)[number]

/**
 * One violation — `src/lib/leagues/settings/`'s `FieldIssue` shape (dot path +
 * human-readable message) plus the family `code`.
 *
 * The `code` is what the TS≡SQL parity fixture and the route layer compare on;
 * the `message` is what a commissioner reads. **Every message names its own
 * guardrail family** (the E75 shape: a refusal names its own reason) — a
 * rejection that says only "invalid scoring rules" is the failure mode this
 * whole section exists to prevent.
 */
export interface ScoringViolation {
  code: ScoringGuardrail
  /** Dot path of the offending member — `base.def_points_allowed`,
   *  `positions.QB.fg_0_39`, `tier_cuts.def_pa`, or `''` for the document. */
  path: string
  message: string
}

/** The validator's answer. `valid` ⟺ `violations.length === 0`. */
export interface ScoringValidationResult {
  valid: boolean
  violations: ScoringViolation[]
}

// ---------------------------------------------------------------------------
// 2. The allowlists — composed from SE.1's registry and generator, never
//    re-listed
// ---------------------------------------------------------------------------

/** §23.5 v2.11: exactly the keys a format-2 document may pay (SE.1 classified
 *  all 61 registry entries; the scorable 48 are proved ≡ the section catalog ∪
 *  the cut-generated tier keys in `stat-keys.test.ts`). */
export const SCORABLE_KEYS: ReadonlySet<string> = new Set(
  STAT_KEYS.filter((def) => def.scoring_surface === 'scorable').map((def) => def.key),
)

/** Registry surface by key — used only to say WHY a key is refused (a
 *  `context` raw source reads differently from a `reserved` bonus, and the
 *  commissioner deserves the difference). */
const SURFACE_BY_KEY: ReadonlyMap<string, string> = new Map(
  STAT_KEYS.map((def) => [def.key, def.scoring_surface]),
)

/**
 * §7.3.3.1's section catalog, transcribed from the spec sentence and grouped
 * by the position whose page renders it — **the position-scope law of
 * guardrail 3**.
 *
 * *Why this lives in the engine and not in the editor.* D167 puts the editor's
 * own catalog (sections, labels, ordering, D173's `gated` flag) in
 * `scoring-editor-ops.ts` — that is rendering. Which keys are LEGAL under which
 * position is validation law: SE.4 mirrors this exact mapping in SQL, and
 * SE.4b's trigger enforces it on every write. **SE.7 must COMPOSE this map
 * rather than re-transcribe the catalog** (ledger F136) — two copies of the
 * catalog would let the editor offer a key the validator refuses, which is the
 * silent-drop shape §7.3.3.1 is written against.
 *
 * The transcription is not trusted: `validate-rules-doc.test.ts` proves the six
 * position sets are pairwise disjoint and that their union ≡ the registry's
 * scorable set, so a drift on either side reds.
 */
export const POSITION_SCORABLE_KEYS: Readonly<
  Record<ScoringPosition, readonly string[]>
> = (() => {
  // The five sections every position except K and D/ST carries (§7.3.3.1's
  // product-shape bullet (3)): Passing · Rushing · Receiving · Special Teams ·
  // Turnovers. `return_yards` is deliberately absent — Q13/D173 ship Special
  // Teams with `return_td` only, and the registry entry does not exist until
  // the data task lands (F71).
  const offense: readonly string[] = [
    // Passing
    'pass_yards',
    'pass_tds',
    'pass_2pt',
    'qb_sack_taken',
    // Rushing
    'rush_yards',
    'rush_tds',
    'rush_2pt',
    // Receiving
    'receptions',
    'receiving_yards',
    'receiving_tds',
    'rec_2pt',
    // Special Teams
    'return_td',
    // Turnovers
    'interceptions',
    'fumbles_lost',
    'fumble_recovery_td',
  ]

  return {
    QB: offense,
    RB: offense,
    WR: offense,
    TE: offense,
    // The K page — one single-section page (Q12, ruled 2026-08-16).
    K: ['fg_0_39', 'fg_40_49', 'fg_50_plus', 'pat_made', 'fg_missed', 'pat_missed'],
    // The D/ST page — the event categories PLUS the doc's tier tables. The
    // tier half is the GENERATED names (§23.5(b) cut lists), never a second
    // literal list: a family the generator can produce is a family the D/ST
    // page can pay.
    DST: [
      'def_sack',
      'def_int',
      'def_fumble_rec',
      'def_td',
      'def_safety',
      'def_block',
      'def_return_td',
      ...new Set([
        ...tierKeysFromCuts(DEF_PA_PREFIX, SHARED_PA_CUTS),
        ...tierKeysFromCuts(DEF_PA_PREFIX, ESPN_PA_CUTS),
        ...tierKeysFromCuts(DEF_YA_PREFIX, YA_CUTS),
      ]),
    ],
  }
})()

const POSITION_KEY_SETS: Readonly<Record<ScoringPosition, ReadonlySet<string>>> = {
  QB: new Set(POSITION_SCORABLE_KEYS.QB),
  RB: new Set(POSITION_SCORABLE_KEYS.RB),
  WR: new Set(POSITION_SCORABLE_KEYS.WR),
  TE: new Set(POSITION_SCORABLE_KEYS.TE),
  K: new Set(POSITION_SCORABLE_KEYS.K),
  DST: new Set(POSITION_SCORABLE_KEYS.DST),
}

/**
 * The two published points-allowed families as their GENERATED key sets, and
 * the one yards-allowed family — the format-1 arm of guardrail 2.
 *
 * Generated, never listed, so this check and `tierKeysFromCuts` can never
 * disagree about what a family contains (the same argument `detectTierCuts`
 * makes for the fork).
 */
const PA_FAMILY_KEY_SETS: ReadonlyArray<{ label: string; keys: ReadonlySet<string> }> = [
  {
    label: 'shared (Yahoo/Sleeper)',
    keys: new Set(tierKeysFromCuts(DEF_PA_PREFIX, SHARED_PA_CUTS)),
  },
  { label: 'ESPN', keys: new Set(tierKeysFromCuts(DEF_PA_PREFIX, ESPN_PA_CUTS)) },
]

const YA_FAMILY_KEYS: ReadonlySet<string> = new Set(
  tierKeysFromCuts(DEF_YA_PREFIX, YA_CUTS),
)

// ---------------------------------------------------------------------------
// 3. Bounds (§7.3.3.1's per-field bounds bullet)
// ---------------------------------------------------------------------------

/** §7.3.3.1: `|coef| ≤ 100`. */
export const MAX_ABS_COEFFICIENT = 100

/** §7.3.3.1: "max 2 decimal places (multiples of 0.01)". */
export const COEFFICIENT_STEP = 0.01

/**
 * How many violations a single answer prints before it stops enumerating
 * (R595). The verdict never changes — only how much of it is printed — and the
 * truncation says so out loud rather than trailing off.
 *
 * Why a cap exists at all: guardrails 1 and 5 emit one violation per key, so a
 * document is free to choose the size of the answer. A 200,000-key flat map
 * produced **200,000 violations / 25.3 MB** of message text from a body a
 * fraction of that size, and `scoringRulesDocSchema` republished every one as
 * a Zod issue. That is a service-layer amplifier, and the caller only ever
 * shows the first few. *(The related question — whether §7.3.3.1(c) should
 * also cap a cut LIST's length — is a spec amendment, not this validator's
 * call: a 20,000-cut ascending integer list satisfies every residual the
 * section states. Routed to F59, which owns cut-point entry.)*
 */
export const MAX_REPORTED_VIOLATIONS = 50

/** Enumerate a key/cut list in a message without letting the document choose
 *  the message's length (R595). */
function summarize(items: readonly (string | number)[], max = 8): string {
  if (items.length <= max) return items.join(', ')
  return `${items.slice(0, max).join(', ')}, … (${items.length} total)`
}

/**
 * Does `value` carry at most 2 decimal places?
 *
 * **This is the DECIMAL rule, and it is deliberately the exact mirror of the
 * SQL side's `scale(p) <= 2` (R589).** `jsonb` preserves a numeric literal
 * byte-exactly and `scale()` counts the digits after its decimal point, so
 * testing the JS number's own decimal rendering asks Postgres's question in
 * JavaScript — the two layers accept and refuse the same documents, and SE.4's
 * parity fixture measures agreement instead of documenting a divergence.
 *
 * The first cut of this module snapped the scaled value (`Number((value *
 * 100).toPrecision(12))`) to dodge `0.07 * 100 === 7.000000000000001`. That
 * dodges the float artefact, but it enforces a ~5e-13 RELATIVE TOLERANCE
 * rather than the spec's rule: it accepted `0.1 + 0.2` (scale 17), accepted
 * `99.99999999999` (11 dp) while refusing `99.9999999999` (10 dp) — not even
 * monotone in decimal places — and accepted `1.000000000001` as an "override"
 * of a base `1`, which scores identically yet survives `normalizeScoringDoc`'s
 * exact `===` strip and so defeats guardrail 4. Measured against the exact
 * rule: **0 false rejections across all 20,001 legal 2dp values in [-100, 100]
 * and across all 218 coefficients of the six shipped templates** (both pinned).
 *
 * `String(value)` is the shortest round-tripping decimal rendering, so a
 * literal that WAS 2dp stays 2dp. Exponential renderings (`1e-7`, `1e+21`)
 * fail the pattern, which is correct: they are not 2dp decimals. Magnitude is
 * checked first, so nothing large enough to render exponentially reaches here.
 */
function isTwoDecimalMultiple(value: number): boolean {
  return /^-?\d+(\.\d{1,2})?$/.test(String(value))
}

// ---------------------------------------------------------------------------
// 4. Small helpers
// ---------------------------------------------------------------------------

/** The four members §7.3.3.1's printed shape defines, and the two tables its
 *  `tier_cuts` defines — the closed sets R588's member check tests against. */
const ENVELOPE_MEMBERS: ReadonlySet<string> = new Set([
  SCORING_DOC_FORMAT_KEY,
  'base',
  'positions',
  'tier_cuts',
])
const TIER_CUT_TABLES: readonly ['def_pa', 'def_ya'] = ['def_pa', 'def_ya']

const hasOwn = (object: object, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(object, key)

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const isScoringPosition = (key: string): key is ScoringPosition =>
  (SCORING_POSITIONS as readonly string[]).includes(key)

/** A coefficient entry to check, with the dot path it lives at. */
interface CoefficientEntry {
  path: string
  key: string
  value: unknown
}

/**
 * Every coefficient in the document, base first then overrides in document
 * order — the order guardrails 1 and 5 report in.
 *
 * `basePath` is `'base'` for the envelope and `''` for a flat format-1
 * document, whose coefficients live at the top level: reporting a flat map's
 * problem at `base.pass_yardz` would name a member the document does not have,
 * and SE.6's route surfaces these paths as form fields.
 */
function coefficientEntries(
  base: Record<string, unknown>,
  overrides: ReadonlyArray<{ position: string; map: Record<string, unknown> }>,
  basePath: string,
): CoefficientEntry[] {
  const entries: CoefficientEntry[] = Object.keys(base).map((key) => ({
    path: basePath === '' ? key : `${basePath}.${key}`,
    key,
    value: base[key],
  }))
  for (const { position, map } of overrides) {
    for (const key of Object.keys(map)) {
      entries.push({ path: `positions.${position}.${key}`, key, value: map[key] })
    }
  }
  return entries
}

// ---------------------------------------------------------------------------
// 5. validateScoringRulesDoc — the five families + the residuals
// ---------------------------------------------------------------------------

/**
 * Validate a scoring rules document against §7.3.3.1's guardrails.
 *
 * Takes `unknown`: the caller is a route body or a `jsonb` column, and this
 * function's whole job is to be the thing that finds out. Never throws.
 *
 * A **format-1** document (a flat map with no `format` member — every shipped
 * template) is checked against the families that mean anything for a flat map:
 * the allowlist (1), the format-1 arm of tier exclusivity (2), and the bounds
 * (5). Position scope and normal form have no subject there. **That the flat
 * arm is checked at all is a deliberate reading**: §7.3.3.1's guardrail bullet
 * heads its list with "what a format-2 doc structurally cannot express", but
 * guardrail 2 spells out its own format-1 arm, D175's wall validates format-1
 * rows (`is_template = TRUE`, and any live-league-referenced row), and F21's
 * raw-source ban would be hollow if a flat document could still pay
 * `def_points_allowed` next to its derived buckets. All six templates pass
 * (pinned — the acceptance floor, SE.3(3)).
 */
export function validateScoringRulesDoc(doc: unknown): ScoringValidationResult {
  const shape: ScoringViolation[] = []
  const allowlist: ScoringViolation[] = []
  const exclusivity: ScoringViolation[] = []
  const positionScope: ScoringViolation[] = []
  const normalForm: ScoringViolation[] = []
  const bounds: ScoringViolation[] = []
  const cuts: ScoringViolation[] = []

  const collect = (): ScoringValidationResult => {
    const violations = [
      ...shape,
      ...allowlist,
      ...exclusivity,
      ...positionScope,
      ...normalForm,
      ...bounds,
      ...cuts,
    ]
    if (violations.length > MAX_REPORTED_VIOLATIONS) {
      return {
        valid: false,
        violations: [
          ...violations.slice(0, MAX_REPORTED_VIOLATIONS),
          {
            code: 'document_shape',
            path: '',
            message: `Document shape (§7.3.3.1): this document has ${violations.length} problems; the first ${MAX_REPORTED_VIOLATIONS} are listed above (R595 — the answer is capped, the verdict is not).`,
          },
        ],
      }
    }
    return { valid: violations.length === 0, violations }
  }

  // ── The front door ──────────────────────────────────────────────────────
  if (!isPlainObject(doc)) {
    shape.push({
      code: 'document_shape',
      path: '',
      message: `Document shape (§7.3.3.1): a scoring rules document must be a JSON object; got ${describeType(doc)}.`,
    })
    return collect()
  }

  const isFormat2 = hasOwn(doc, SCORING_DOC_FORMAT_KEY)

  // ── Format 1: the flat map ──────────────────────────────────────────────
  if (!isFormat2) {
    // An envelope whose `format` member was dropped reads as a flat map whose
    // keys happen to be "base", "positions" and "tier_cuts" — and the answer
    // was six allowlist violations naming nothing a commissioner could act on
    // (R597). The document says what it is; the refusal should too.
    const envelopeMembers = Object.keys(doc).filter(
      (key) => key !== SCORING_DOC_FORMAT_KEY && ENVELOPE_MEMBERS.has(key),
    )
    if (envelopeMembers.length > 0) {
      shape.push({
        code: 'document_shape',
        path: '',
        message: `Document shape (§7.3.3.1): this document carries no "format" member, so it reads as a flat format-1 map — but it holds ${summarize(envelopeMembers)}, which are format-2 envelope members. Add "format": ${SCORING_DOC_FORMAT_2}, or make it a genuine flat map of coefficients.`,
      })
    }

    const entries = coefficientEntries(doc, [], '')
    checkAllowlist(entries, allowlist)
    checkBounds(entries, bounds)
    checkFormat1TierFamilies(Object.keys(doc), exclusivity)
    return collect()
  }

  // ── Format 2: the envelope ──────────────────────────────────────────────
  const format = doc[SCORING_DOC_FORMAT_KEY]
  if (format !== SCORING_DOC_FORMAT_2) {
    // Never fall through to a plausible reading of an unknown version: a
    // `format: 3` document read as flat, or as base-only, scores an entire
    // league wrong with no error anywhere (CLAUDE.md's never-let-"nothing
    // happened"-mean-"it worked" rule; the same refusal `resolveRules` makes,
    // here as a violation rather than a throw).
    shape.push({
      code: 'document_shape',
      path: SCORING_DOC_FORMAT_KEY,
      message:
        format === 1
          ? // The one version number that needs its own sentence (R597): the
            // first cut of this message refused a document "for declaring
            // format 1" while saying in the same breath that it validates
            // format 1. Both halves are true and the combination is nonsense —
            // format 1 IS the flat map, identified by carrying NO version
            // member at all (§7.3.3.1: "no `format` member — the discriminator
            // is unambiguous"), so a document that names version 1 is not one.
            `Document shape (§7.3.3.1): this document declares format 1 — but format 1 IS the flat map, identified by carrying NO "format" member at all, so a document that names the version is not one. Drop the "format" member for a flat map, or use format ${SCORING_DOC_FORMAT_2}'s envelope.`
          : `Document shape (§7.3.3.1): this document declares format ${JSON.stringify(format)}, which this build cannot validate — it knows the flat map (no "format" member) and format ${SCORING_DOC_FORMAT_2}. A future format is a future validator, never a silent pass.`,
    })
    return collect()
  }

  // §7.3.3.1's printed shape has exactly four members, and a document that
  // carries a FIFTH is not a document with a harmless extra — it is almost
  // always a member the writer believed was load-bearing (R588). Nothing else
  // in this module would ever look at it: every family reads `base` and
  // `positions`, so `postions: {…}` — one transposed letter — used to validate
  // clean while `resolveRules` returned the base values and the commissioner's
  // entire override map evaporated on save. That is CLAUDE.md's
  // never-let-"nothing happened"-mean-"it worked" and §7.3.3.1(5)'s "never a
  // silently-ignored key", so an unenumerated member is refused BY NAME.
  for (const member of Object.keys(doc)) {
    if (ENVELOPE_MEMBERS.has(member)) continue
    shape.push({
      code: 'document_shape',
      path: member,
      message: `Document shape (§7.3.3.1's printed shape): "${member}" is not a member of a format-2 scoring document, which carries exactly ${summarize([...ENVELOPE_MEMBERS])}. A member nothing reads is a value silently discarded on save — coefficients belong in "base" or under a position.`,
    })
  }

  const base = doc.base
  if (!isPlainObject(base)) {
    shape.push({
      code: 'document_shape',
      path: 'base',
      message: `Document shape (§7.3.3.1's printed shape): a format-2 scoring document needs a "base" object; got ${describeType(base)}.`,
    })
  }
  const positions = doc.positions
  if (!isPlainObject(positions)) {
    shape.push({
      code: 'document_shape',
      path: 'positions',
      message: `Document shape (§7.3.3.1's printed shape): a format-2 scoring document needs a "positions" object; got ${describeType(positions)}.`,
    })
  }

  // §7.3.3.1(c) residuals, evaluated HERE because guardrail 2 generates its
  // key sets from them — a malformed cut list must produce a violation, never
  // a throw out of `tierKeysFromCuts`, and never a generated key set nobody
  // should trust.
  const validCuts = checkTierCuts(doc.tier_cuts, cuts)

  if (!isPlainObject(base) || !isPlainObject(positions)) return collect()

  // Overrides, in document order. A non-object override is a shape violation
  // (and stops guardrail 4, which would throw on it).
  const overrides: Array<{ position: string; map: Record<string, unknown> }> = []
  let everyOverrideIsAnObject = true
  for (const position of Object.keys(positions)) {
    const override = positions[position]
    if (!isPlainObject(override)) {
      everyOverrideIsAnObject = false
      shape.push({
        code: 'document_shape',
        path: `positions.${position}`,
        message: `Document shape (§7.3.3.1's printed shape): a position override must be an object of coefficients; positions.${position} is ${describeType(override)}.`,
      })
      continue
    }
    overrides.push({ position, map: override })
  }

  const entries = coefficientEntries(base, overrides, 'base')

  // (1) Scorable allowlist.
  checkAllowlist(entries, allowlist)

  // (2) Tier exclusivity — the format-2 arm: against the document's OWN cuts.
  checkFormat2TierFamilies(entries, validCuts, exclusivity)

  // (3) Position scope.
  for (const { position, map } of overrides) {
    if (!isScoringPosition(position)) {
      positionScope.push({
        code: 'position_scope',
        path: `positions.${position}`,
        message: `Position scope (§7.3.3.1 guardrail 3): "${position}" is not one of the six scored positions ${SCORING_POSITIONS.join(', ')}.`,
      })
      continue
    }
    const legal = POSITION_KEY_SETS[position]
    for (const key of Object.keys(map)) {
      if (legal.has(key)) continue
      // A key that is not scorable at all is already guardrail 1's rejection;
      // saying it twice would make the parity fixture's first-violation
      // contract ambiguous for no gain.
      if (!SCORABLE_KEYS.has(key)) continue
      positionScope.push({
        code: 'position_scope',
        path: `positions.${position}.${key}`,
        message: `Position scope (§7.3.3.1 guardrail 3): "${key}" is not scored for ${position} — it belongs to ${whereKeyBelongs(key)}. An override may only name its own position's section keys.`,
      })
    }
  }

  // (4) Normal form — asked of `normalizeScoringDoc`, never re-implemented.
  if (everyOverrideIsAnObject) {
    checkNormalForm(doc as unknown as ScoringRulesDocV2, overrides, normalForm)
  }

  // (5) Bounds.
  checkBounds(entries, bounds)

  return collect()
}

/** `typeof`, but useful in a message: arrays and null read as themselves. */
function describeType(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) return 'an array'
  if (value === undefined) return 'nothing'
  return `a ${typeof value}`
}

/** Which position pages DO carry `key` — for guardrail 3's message. */
function whereKeyBelongs(key: string): string {
  const homes = SCORING_POSITIONS.filter((position) =>
    POSITION_KEY_SETS[position].has(key),
  )
  if (homes.length === 0) return 'no position page'
  if (homes.length === SCORING_POSITIONS.length) return 'every position'
  return homes.join('/')
}

// ---------------------------------------------------------------------------
// 6. The families
// ---------------------------------------------------------------------------

/** (1) Scorable allowlist — §7.3.3.1 guardrail 1 / §23.5's `scoring_surface`. */
function checkAllowlist(
  entries: readonly CoefficientEntry[],
  out: ScoringViolation[],
): void {
  for (const { path, key } of entries) {
    if (SCORABLE_KEYS.has(key)) continue
    const surface = SURFACE_BY_KEY.get(key)
    const why =
      surface === 'context'
        ? 'it is a context key — a raw source or an aggregate (§23.5), and paying it beside the keys derived from it is the double-count this guardrail exists to make inexpressible'
        : surface === 'reserved'
          ? 'it is a reserved key (§23.5) — deferred bonuses, placeholders and IDP are not exposed by the cohort editor'
          : 'it is not a canonical stat key at all (§23.5 STAT_KEYS)'
    out.push({
      code: 'scorable_allowlist',
      path,
      message: `Scorable allowlist (§7.3.3.1 guardrail 1): "${key}" cannot be scored — ${why}.`,
    })
  }
}

/** (5) Bounds — §7.3.3.1's per-field bounds bullet. */
function checkBounds(
  entries: readonly CoefficientEntry[],
  out: ScoringViolation[],
): void {
  for (const { path, key, value } of entries) {
    if (typeof value !== 'number' || !Number.isFinite(value)) {
      out.push({
        code: 'bounds',
        path,
        message: `Bounds (§7.3.3.1 guardrail 5): "${key}" must be a finite number; got ${describeValue(value)}.`,
      })
      continue
    }
    if (Math.abs(value) > MAX_ABS_COEFFICIENT) {
      out.push({
        code: 'bounds',
        path,
        message: `Bounds (§7.3.3.1 guardrail 5): "${key}" is ${value}; a coefficient must satisfy |coef| ≤ ${MAX_ABS_COEFFICIENT}.`,
      })
      continue
    }
    if (!isTwoDecimalMultiple(value)) {
      out.push({
        code: 'bounds',
        path,
        message: `Bounds (§7.3.3.1 guardrail 5): "${key}" is ${value}; a coefficient carries at most 2 decimal places (a multiple of ${COEFFICIENT_STEP}).`,
      })
    }
  }
}

function describeValue(value: unknown): string {
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)
  return describeType(value)
}

/**
 * (2) Tier exclusivity, format-1 arm — §7.3.3.1 guardrail 2's parenthetical.
 *
 * **The reading, recorded because the spec sentence admits two.** The text is
 * *"`def_pa_*` ⊆ exactly one named platform family, shared 7-key XOR ESPN
 * 8-key, the families sharing 4 key names"*. Read literally as "a subset of
 * exactly one of the two sets", a document naming only shared key names —
 * `def_pa_0`, `def_pa_1_6`, `def_pa_7_13`, `def_pa_28_34` — would be refused
 * for being a subset of *both*, though it cannot double-pay anything: within
 * one family the tiers are non-overlapping by construction, so at most one
 * indicator is ever hot. The controlling clause is the guardrail's own stated
 * purpose two sentences earlier — *mixing* families is what must be
 * inexpressible — and the "families sharing 4 key names" parenthetical is the
 * spec telling the implementer that a key can belong to both. So the check is
 * **"some published family contains every `def_pa_*` key this document
 * names"**, which refuses exactly the mixed documents and nothing else.
 *
 * Measured, not argued: the two readings agree on every document that exists —
 * all six templates match exactly one family, and the F21 literal
 * (`def_pa_14_20` + `def_pa_18_27`) is refused under both. The divergence is
 * pinned by its own test so a ruling the other way is a one-line change.
 */
function checkFormat1TierFamilies(keys: readonly string[], out: ScoringViolation[]): void {
  const paKeys = keys.filter((key) => key.startsWith(`${DEF_PA_PREFIX}_`))
  if (paKeys.length > 0) {
    const homes = PA_FAMILY_KEY_SETS.filter(({ keys: family }) =>
      paKeys.every((key) => family.has(key)),
    )
    if (homes.length === 0) {
      out.push({
        code: 'tier_exclusivity',
        path: '',
        message: `Tier exclusivity (§7.3.3.1 guardrail 2): the points-allowed keys [${summarize(paKeys)}] are not all cut on one published family (${PA_FAMILY_KEY_SETS.map((f) => f.label).join(' or ')}). Mixing families double-pays every week that lands in the overlap — the F21 defect.`,
      })
    }
  }

  const stray = keys
    .filter((key) => key.startsWith(`${DEF_YA_PREFIX}_`))
    .filter((key) => !YA_FAMILY_KEYS.has(key))
  if (stray.length > 0) {
    out.push({
      code: 'tier_exclusivity',
      path: '',
      message: `Tier exclusivity (§7.3.3.1 guardrail 2): the yards-allowed keys [${summarize(stray)}] are not generated by the published yards-allowed cut list.`,
    })
  }
}

/**
 * (2) Tier exclusivity, format-2 arm — a document's tier keys ⊆ the set
 * generated by its OWN `tier_cuts`.
 *
 * This is the version the spec calls *inexpressible*: a format-2 document
 * carries one cut list per table, one cut list generates one non-overlapping
 * tier set, so a key the document's own cuts do not generate has no tier to
 * pay. Checked doc-wide (base AND every override, whatever position it sits
 * under), because the double-pay is a property of the document, not of one map
 * — the changelog's own words, "PA/YA **bucketization-set exclusivity**
 * doc-wide".
 *
 * A table whose cut list failed §7.3.3.1(c)'s residuals is skipped: there is no
 * trustworthy key set to compare against, and the residual violation is already
 * the document's answer.
 */
function checkFormat2TierFamilies(
  entries: readonly CoefficientEntry[],
  validCuts: { def_pa: readonly number[] | null; def_ya: readonly number[] | null },
  out: ScoringViolation[],
): void {
  for (const [prefix, cutList, table] of [
    [DEF_PA_PREFIX, validCuts.def_pa, 'points-allowed'],
    [DEF_YA_PREFIX, validCuts.def_ya, 'yards-allowed'],
  ] as const) {
    if (cutList === null) continue
    // Nothing to compare against if the document names no key in this family —
    // and generating a key set the document cannot violate is the one place a
    // long-but-legal cut list would cost real work (R595).
    if (!entries.some(({ key }) => key.startsWith(`${prefix}_`))) continue
    const generated = new Set(tierKeysFromCuts(prefix, cutList))
    for (const { path, key } of entries) {
      if (!key.startsWith(`${prefix}_`)) continue
      if (generated.has(key)) continue
      out.push({
        code: 'tier_exclusivity',
        path,
        message: `Tier exclusivity (§7.3.3.1 guardrail 2): "${key}" is not a tier this document's own ${table} cut list [${summarize(cutList)}] generates (${summarize([...generated])}). A document cannot name a tier its own cuts do not cut — that is how the F21 double-pay is made inexpressible.`,
      })
    }
  }
}

/**
 * (4) Normal form — §7.3.3.1's normal-form bullet, asked of the one
 * implementation that defines it.
 *
 * `normalizeScoringDoc` strips overrides equal to the base value and empty
 * override objects; a document is in normal form iff normalizing changes
 * nothing. Everything below is a DIFF against its output — the strip rule
 * itself (including its two designed boundaries: an override of a key absent
 * from `base` is never a no-op even at 0, and a position key outside the six is
 * preserved rather than dropped — D268(5)) lives in `rules-doc.ts` alone.
 */
function checkNormalForm(
  doc: ScoringRulesDocV2,
  overrides: ReadonlyArray<{ position: string; map: Record<string, unknown> }>,
  out: ScoringViolation[],
): void {
  const normalized = normalizeScoringDoc(doc as ScoringRulesDoc) as ScoringRulesDocV2
  const normalizedPositions = normalized.positions as Record<string, FlatScoringRules>

  for (const { position, map } of overrides) {
    const keys = Object.keys(map)

    // An override object the normal form strips ENTIRELY is reported at the
    // object path only when it is empty; when it holds keys, every one of them
    // is a no-op and each is named — a commissioner (and SE.6's route) gets
    // the same per-key message whether one key repeats the base or all of them
    // do. (`normalizeScoringDoc` keeps a key unless it exists in `base` and
    // matches it, so "did not survive" and "is a no-op" are the same fact.)
    if (!hasOwn(normalizedPositions, position) && keys.length === 0) {
      out.push({
        code: 'normal_form',
        path: `positions.${position}`,
        message: `Normal form (§7.3.3.1 guardrail 4): positions.${position} is an empty override object — the normal form carries no empty overrides, because the All-Positions switch state is derived from the document alone.`,
      })
      continue
    }

    const kept = hasOwn(normalizedPositions, position) ? normalizedPositions[position] : {}
    for (const key of keys) {
      if (hasOwn(kept, key)) continue
      out.push({
        code: 'normal_form',
        path: `positions.${position}.${key}`,
        message: `Normal form (§7.3.3.1 guardrail 4): positions.${position}.${key} repeats the base value (${JSON.stringify(doc.base[key])}), so it overrides nothing — the All-Positions switch would read OFF for a section whose values are in fact uniform.`,
      })
    }
  }
}

/**
 * §7.3.3.1(c)'s residual validation: **ascending, integers, ≥ 2 cuts, per
 * table, the two tables independent.**
 *
 * Both tables are required — `EnvelopeTierCuts`, R577/SE.1: "this league pays
 * no yards-allowed table" is expressed by paying no `def_ya_*` keys, never by
 * dropping its cut list, because guardrail 2's format-2 arm would otherwise be
 * unevaluable for that table.
 *
 * Returns each table's cut list when it is sound and `null` when it is not, so
 * guardrail 2 knows which key sets it may generate. The same three conditions
 * are `tier-cuts.ts`'s own `assertCutList` precondition, which THROWS — this is
 * the document-level, user-facing arm §7.3.3.1(5) puts here (D267(5)); calling
 * the generator on an unvalidated list is exactly the throw this module must
 * not make.
 */
function checkTierCuts(
  tierCuts: unknown,
  out: ScoringViolation[],
): { def_pa: readonly number[] | null; def_ya: readonly number[] | null } {
  const none = { def_pa: null, def_ya: null }
  if (!isPlainObject(tierCuts)) {
    out.push({
      code: 'tier_cuts',
      path: 'tier_cuts',
      message: `Tier cuts (§7.3.3.1(a)/(c)): a format-2 document carries a "tier_cuts" object with both a "${DEF_PA_PREFIX}" and a "${DEF_YA_PREFIX}" cut list; got ${describeType(tierCuts)}.`,
    })
    return none
  }

  // R588's second half, and the one a normalize-based fix would MISS:
  // `normalizeScoringDoc` passes `tier_cuts` through by REFERENCE, so a stray
  // table inside it is a fixed point of the normal form. It needs its own
  // member check, here.
  for (const table of Object.keys(tierCuts)) {
    if ((TIER_CUT_TABLES as readonly string[]).includes(table)) continue
    out.push({
      code: 'tier_cuts',
      path: `tier_cuts.${table}`,
      message: `Tier cuts (§7.3.3.1(a)/(c)): "${table}" is not a tier table — a format-2 document cuts exactly ${summarize([...TIER_CUT_TABLES])}, which are independent and additively scored. A table nothing reads is a cut list silently discarded.`,
    })
  }

  const checked: Record<string, readonly number[] | null> = { def_pa: null, def_ya: null }
  for (const table of TIER_CUT_TABLES) {
    const path = `tier_cuts.${table}`
    const list = tierCuts[table]
    if (!Array.isArray(list)) {
      out.push({
        code: 'tier_cuts',
        path,
        message: `Tier cuts (§7.3.3.1(a)/(c)): ${path} must be an ascending list of integer cut points; got ${describeType(list)}. Both tables are always written — a league that pays no ${table === 'def_pa' ? 'points-allowed' : 'yards-allowed'} table simply pays none of its keys.`,
      })
      continue
    }
    if (list.length < 2) {
      out.push({
        code: 'tier_cuts',
        path,
        message: `Tier cuts (§7.3.3.1(c)): ${path} needs at least 2 cut points to define a tier boundary; got ${list.length}.`,
      })
      continue
    }
    const badIndex = list.findIndex((cut) => !Number.isInteger(cut))
    if (badIndex >= 0) {
      out.push({
        code: 'tier_cuts',
        path,
        message: `Tier cuts (§7.3.3.1(c)): ${path} must be integers; index ${badIndex} is ${describeValue(list[badIndex])}.`,
      })
      continue
    }
    const flat = list.findIndex((cut, i) => i > 0 && (cut as number) <= (list[i - 1] as number))
    if (flat > 0) {
      out.push({
        code: 'tier_cuts',
        path,
        message: `Tier cuts (§7.3.3.1(c)): ${path} must ascend strictly — ${list[flat - 1]} then ${list[flat]} at index ${flat}. Ascending cut points are what make overlapping tiers and coverage gaps unconstructible.`,
      })
      continue
    }
    // R592 — **the points-allowed table must start at exactly 0**, which is a
    // fourth residual beyond §7.3.3.1(c)'s three, and it is D174 made
    // enforceable rather than a new rule. The PA family FLOORS at its first
    // cut (`tier-cuts.ts`'s `DEF_PA_FIRST_TIER = 'floor'`) because R58/D58
    // rules a negative points-allowed UNMAPPABLE, and §7.3.3.1(a)'s own
    // controlling clause is that the cuts reading must AGREE with today's
    // literals ("no behavior change"). A first cut anywhere but 0 breaks that
    // agreement in one direction or the other, and both directions are a lie
    // about the E61 pending badge — measured, and pinned: a first cut BELOW 0
    // pays a tier for data the derivation refuses to map, and a first cut
    // ABOVE 0 withholds the whole family on an ordinary low-scoring week
    // (PA 0/3/6 → a FALSE "waiting on data" badge on a complete week).
    // Neither moves a total; both move the only signal E61 gives. YA needs no
    // such rule — its first tier is genuinely open below (D174), because a
    // negative-total-yards game is real.
    if (table === 'def_pa' && list[0] !== 0) {
      out.push({
        code: 'tier_cuts',
        path,
        message: `Tier cuts (§7.3.3.1(c) + §7.3.3.1(a)'s derive-agreement clause): ${path} must start at 0 — a points-allowed table covers a shutout upward, and R58/D58 rules a negative points-allowed unmappable. Starting at ${list[0]} moves the E61 pending badge without moving any total. (Yards allowed has no such floor: its first tier is open below.)`,
      })
      continue
    }
    checked[table] = list as readonly number[]
  }

  return { def_pa: checked.def_pa, def_ya: checked.def_ya }
}

// ---------------------------------------------------------------------------
// 7. The route layer's Zod envelope — UX only, and a DELEGATION, not a mirror
// ---------------------------------------------------------------------------

/**
 * The scoring-document schema SE.6's routes parse a request body with.
 *
 * §7.3.3.1(5) is explicit that **client Zod is UX only** — the wall is the
 * server (SE.4's `scoring_rules_validate`, standing behind SE.4b's triggers).
 * So this schema deliberately contains **no rule of its own**: it hands the
 * value to `validateScoringRulesDoc` and republishes each violation as a Zod
 * issue at the same path, carrying the guardrail family in `params.guardrail`.
 *
 * That is the whole point. A hand-written `z.object({ format: z.literal(2),
 * base: z.record(z.number().min(-100).max(100)), … })` would be a second
 * implementation of families 1 and 5 in a third language, free to drift from
 * both the TS validator and the SQL mirror — and the drift would show up as a
 * route accepting a document the database then refuses, or worse, rejecting one
 * it would have accepted. `validate-rules-doc.test.ts` pins the delegation
 * (verdict and issue count identical across the whole fixture corpus), so the
 * schema cannot quietly grow an opinion.
 */
export const scoringRulesDocSchema = z
  .unknown()
  .superRefine((value, ctx) => {
    for (const violation of validateScoringRulesDoc(value).violations) {
      ctx.addIssue({
        code: 'custom',
        // Dot paths only — every segment is a registry key, a position code or
        // a document member, none of which contain a dot (pinned).
        path: violation.path === '' ? [] : violation.path.split('.'),
        message: violation.message,
        params: { guardrail: violation.code },
      })
    }
  })
  .transform((value) => value as ScoringRulesDoc)
